### ISSUE TITLE
OpenAl-Soft uses deprecated feature on OS X 10.11

### ISSUE THREAD

**Issue by mantognini** [SFML/SFML#1000]
From http://en.sfml-dev.org/forums/index.php?topic=19305.0

> ```
[8530:1171230] 23:17:10.816 WARNING:  140: This application, or a library it uses, is using the
deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed
in a future release. Also, this makes the host incompatible with version 3 audio units. Please
transition to the API's in AudioComponent.h.
```

Actually reported here too: https://github.com/kcat/openal-soft/issues/20

This is not the case with OS X default OpenAL implementation, but it remains to see if #541 was solved by Apple or not.

**Comment by kipbits** [comment]
It's come to my attentions, that these settings might be to specific to the mac app store to warrant a change to source. For instance, if you are uploading an iOS app, it will have a different value, and if you are releasing an App on your own website, you can still sign your App without this field.

**Comment by mantognini** [comment]
Superseded by #1057.
