### ISSUE TITLE
sf::Time constexpr constructor and methods

### ISSUE THREAD

**Issue by trid** [SFML/SFML#1003]
It will be just cool to be able to use sf::Time as C++11 constexpr instead of static const.

**Comment by zsbzsb** [comment]
SFML won't support C++11 until v3.

**Comment by eXpl0it3r** [comment]
We are looking forward to using C++11 (and beyond?) in the future as well. As of right now we want SFML 2.x to be fully compatible to C++03/98 and thus can't use constexpr.

For future reports, please make sure to take a look at our [contributions guidelines](http://www.sfml-dev.org/contribute.php). :wink:
