### ISSUE TITLE
Only lowercase keypresses are handled on Linux

### ISSUE THREAD

**Issue by SMemsky** [SFML/SFML#1012]
In [WindowImplX11.cpp](https://github.com/SFML/SFML/blob/master/src/SFML/Window/Unix/WindowImplX11.cpp) function "*keysymToSF(xcb_keysym_t symbol)*" handles only lowercase KeySym's(XK_a, XK_b, e.t.c.). 
This causes SFML to generate sf::Keyboard::Unknown keycodes in button events when CapsLock and/or L/RShift is pressed.
As of [Xlib manual](https://tronche.com/gui/x/xlib/input/keyboard-encoding.html#KeySym) uppercase presses are generated too and they should be handled as XK_A, XK_B, e.t.c.

I'm running Linux 3.19.0-33-generic Ubuntu-14.04.1 i686

**Comment by binary1248** [comment]
@SMemsky can you try out the patch I submitted in #1022?

**Comment by SMemsky** [comment]
Yes, patch seems to fix this problem on Ubuntu 14.04 with qwerty layout.
