### ISSUE TITLE
cmake cannot find package JPEG on linux for android arm64 target

### ISSUE THREAD

**Issue by makoConstruct** [SFML/SFML#1019]
steps to reproduce:
```
cd SFML
mkdir build && cd build
mkdir arm64 && cd arm64
cmake -DANDROID_ABI=arm64-v8a -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/android.toolchain.cmake ../
```
outputs
```
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find JPEG (missing: JPEG_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.0/Modules/FindJPEG.cmake:42 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/toolchains/android.toolchain.cmake:1565 (find_package)
  src/SFML/Graphics/CMakeLists.txt:122 (find_host_package)


-- Configuring incomplete, errors occurred!
See also "/home/mako/programming/res/sfmlw/build/arm64-v8a/CMakeFiles/CMakeOutput.log".
```
CMakeOutput.log contains
```
The target system is: Linux - 1 - aarch64
The host system is: Linux - 3.16.0-4-amd64 - x86_64
```
cmake version is 3.0.2

I'm (pretty much) following the instructions given here https://github.com/SFML/SFML/wiki/Tutorial:-Building-SFML-for-Android

I should note that compiling for armeabi works. Compiling for x86_64 for android fails in the same way, even though a normal compilation (which is taking place on an x86_64 platform) works.

The readme lists the problematic 64-bit ABIs as being for NDK r10 and newer. I am using ndk r10e.

**Comment by MarioLiebisch** [comment]
Simple answer: SFML's repository doesn't bring precompiled dependencies for those platforms so far. Check the contents of `extlibs/libs-android`. You should be able to add your own precompiled headers to get everything working though.
