### ISSUE TITLE
Application signing fails because of frameworks' incomplete plist file

### ISSUE THREAD

**Issue by mantognini** [SFML/SFML#1020]
As reported on [the forum](http://en.sfml-dev.org/forums/index.php?topic=19498.0), external dependencies such as freetype are missing some information in their plist file.

``` plist
    <key>CFBundleSupportedPlatforms</key>
    <array>
        <string>MacOSX</string>
    </array>
```

**Comment by kipbits** [comment]
I've given it some thought, and I don't think this should be a part of the main repository.

I think these settings might be too specific to submitting a mac app to warrant a change to source. For instance, if you are uploading an iOS app, it will have a different value, and if you are releasing an App on your own website, you can still sign your App without this field at all. Also I think there might be a way to set these values automatically in Xcode.

**Comment by mantognini** [comment]
I think there's no downside in adding this since OS X frameworks are not used for iOS, and vice-versa.

**Comment by mantognini** [comment]
@kipbits: Thanks for the PRs. But I think one PR for this issue would be better. Could you squash everything into one commit? Thanks a bunch!

**Comment by kipbits** [comment]
Sorry, I will sent a new PR

**Comment by mantognini** [comment]
See #1036 for further details on potential fix.

**Comment by mantognini** [comment]
Superseded by #1194.
