### ISSUE TITLE
Empty sf::String crash in destructor

### ISSUE THREAD

**Issue by Daeloce** [SFML/SFML#1021]
This code crashing with SIGTRAP signal on second line:

    sf::String *string = new sf::String();
    delete string; <-- crash

If string not empty, destructor work correctly.

System:
Windows 8 x64
MinGW 4.8.3 x64
SFML builded from source, latest Git version of master branch.

On the Linux this trouble don't repeated.

**Comment by fabianf1** [comment]
You should try a different compiler as I can run this perfectly using TDM-GCC 5.1.0 x64.

**Comment by Daeloce** [comment]
This compiler works correctly, thank you.
