### ISSUE TITLE
Create a maintained mapping of <string,sf::Keyboard::Key> for configuration files.

### ISSUE THREAD

**Issue by justjoeyuk** [SFML/SFML#1024]
I've been using SFML to create a project and upon creating custom configurations (using JSON), I discovered the amount of difficulty in extracting an enum value from a string without having a  unordered_map of "string, EnumType".

I initially decided to use integers in the configuration but this is a problem as the sf::Keyboard::Key could change which would require a re-mapping and could cause odd behaviour in applications due to key codes changing position.

I'm confused in how this would be implemented without having a maintainable map of keys which would have a helper function such as "sf::Keyboard::keyWithIdentifier("Up")" or something along those lines. It would add a lot of simplicity to the library when it comes to flexibility and protects the programmers from any problems further down the line.

My current implementation is a class with a map of the key names and the keys. For example:
keyMap["A"] = sf::Keyboard::Key::A
keyMap["B"] = sf::Keyboard::Key::B
keyMap["C"] = ...

This seems future-proof enough but I feel like this should be in the library, not in my own code-base. C++17 will hopefully be introducing a way to extract Enum Values via a string (which is exactly what my requirement would be) using reflection.

Unfortunately, this isn't something that's in C++11 and should have a simple method.

That's my thoughts from using the library for a while. I'm really enjoying it so far, good job!

**Comment by MarioLiebisch** [comment]
> I initially decided to use integers in the configuration but this is a problem as the sf::Keyboard::Key could change which would require a re-mapping and could cause odd behaviour in applications due to key codes changing position.

And if any name in the SFML implementation changes, you've got the very same problem. :)

I don't think providing a mapping is the right way to go here (should still happen in "library user land", but I think there should be a function to retrieve key names (there are typically platform specific API calls for that).

**Comment by Bromeon** [comment]
> [...]  I discovered the amount of difficulty in extracting an enum value from a string [...]

You should have researched a bit, you're not the first one with this problem. This functionality has been in [Thor](http://www.bromeon.ch/libraries/thor/v2.0/doc/_input_names_8hpp.html) for quite a while now :wink: 

> but I think there should be a function to retrieve key names (there are typically platform specific API calls for that).

Why do you need platform-specific key names in portable library like SFML? You can't use them for serialization...

**Comment by mantognini** [comment]
Because this didn't attract much attention and is still flagged as undecided, I'm closing this. But feel free to further make your case (preferably on the forum). Besides, @MarioLiebisch referred to #7, which is more fundamental.
