### ISSUE TITLE
Bug involving seeking multi-channel flac files.

### ISSUE THREAD

**Issue by ief015** [SFML/SFML#1040]
It appears the way SFML is seeking in flac files is not taking into account the number of channels of the flac file when seeking to a specific sample position.

For instance, seeking to 100 seconds of a 200 second 2-channel flac file will bring you to the very end of the audio.

http://en.sfml-dev.org/forums/index.php?topic=18995.msg141271#msg141271

**Comment by Foaly** [comment]
I implemented a fix for this here #1041. It would be nice if you could test it, to verify that it fixes your problem.

**Comment by ief015** [comment]
@Foaly Yep, appears to be working as intended.

**Comment by eXpl0it3r** [comment]
Fixed in c78c8106dad49dd458aa3624df06d2a989f3d0ed
