### ISSUE TITLE
Linking fails when calling setUniform(string, Mat4)

### ISSUE THREAD

**Issue by TankOs** [SFML/SFML#1044]
Reported here, incl. example code: http://en.sfml-dev.org/forums/index.php?topic=19677

The reason for failed linking is that `setUniform(string, Mat4)` is a template and calls the non-exported function `copyMatrix()` in Glsl.inl. Linking works when prepending copyMatrix() by `SFML_GRAPHICS_API`; this also applies to other `copy*` functions in that header.

@Bromeon Mentioning you here because you wrote the code. I'd contribute a patch if you don't have anything else in mind. Also, what's your opinion on moving the `copy*` functions to the .hpp file instead? They are no templates anyway.

**Comment by Bromeon** [comment]
> Also, what's your opinion on moving the  copy*  functions to the .hpp file instead? They are no templates anyway.

I put everything I could in the .inl file to keep the .hpp header as clean as possible (including the `Matrix` and `Vector` class definitions). I'm not sure if it's better when the .hpp begins with a huge block of implementation details (i.e. `namespace detail`), it makes it more difficult to get a quick overview.

Yes, let's add the `SFML_GRAPHICS_API` macros. I don't care who does it, I can also fix it (tomorrow) :)

**Comment by eXpl0it3r** [comment]
Since when are the *.inl files there to "hide" code? :confused:

**Comment by Bromeon** [comment]
> Since when are the *.inl files there to "hide" code? :confused: 

[November 20, 2010](https://github.com/SFML/SFML/blob/master/include/SFML/System/Thread.inl#L25-L63)

**Comment by TankOs** [comment]
I can understand the case in Thread.inl, as 98% of the code are templates (except the base class, which is pure virtual). The `copy` functions are not "closely" related to templates at all, though.

It was just a suggestion anyway. I gonna add the macros and leave the rest as it is. ;)

**Comment by LaurentGomila** [comment]
The copy functions are implementation details, and thus I think they should be hidden as much as possible. There's no benefit to expose them in the header.

**Comment by TankOs** [comment]
I agree that they are not important for the user at all, and if it was possible, they would completely disappear from any public header. But since that doesn't work due to template code, it can't be "hidden" because it's being used by the user, indirectly, and the .inl file is included anyway.

I was confused at first because I found function declarations (!) in an .inl file. The general way of using .hpp/.inl is using .hpp for declarations, and .inl for definitions, just like you'd do with .hpp/.cpp — and you only do that because there's no other way (template code). That's why I wondered that the .inl contains declarations which are defined in a .cpp file.

Personally I think that hiding as much as possible is of course good. But moving away from the widely agreed-on .hpp/.inl behavior can at least lead to some question marks over some people's heads. ;-)

As I stated before, I'm not going to change this, and probably also not going into a debate about it. It's no big deal..

**Comment by LaurentGomila** [comment]
> just like you'd do with .hpp/.cpp

We put all private stuff into .cpp as much as possible (in anonymous namespaces). In this specific case, if the .inl file was a .cpp, I wouldn't change anything. To me, the current code is perfectly consistent with our habits.

**Comment by TankOs** [comment]
If the .inl file was a .cpp, you'd have put the declaration in it.

**Comment by LaurentGomila** [comment]
Which declaration?

**Comment by TankOs** [comment]
`void copyMatrix(...);`. It's declared in .inl, and implemented in .cpp.

**Comment by eXpl0it3r** [comment]
Merged in b61502b69ac0623a5782bd1a6d96d0edeb11695e
