### ISSUE TITLE
Indexed mode for VertexArray ? Or new class VertexArrayIndexed ?

### ISSUE THREAD

**Issue by jokoon** [SFML/SFML#1048]
I noticed there is no way to use indexed vertex arrays in SFML.

(by that I mean have a vertex array and another int array telling which vertices to draw)

I looked at the code a little, and it seems it would involve some big code change in RenderTarget::draw().

So, has it it already been a concern, or should I start looking into trying out some patch?

**Comment by LaurentGomila** [comment]
Before writing an implementation for it, please open a discussion on the forum ("Feature requests"), to see if it is relevant, what design would fit the best, etc.

All this stuff is explained in the contribution guideline.
