### ISSUE TITLE
Bug: iOS orientation change handling re-scales window size by backingScaleFactor

### ISSUE THREAD

**Issue by louis-langholtz** [SFML/SFML#1049]
After creating an `sf::RenderWindow` under iOS `getSize()` returns 640 by 960 (on an iPhone 4S at least running in the simulator). This size matches the pixel unit size of what's expected according to [the technical specs for the iPhone 4S](https://www.apple.com/lae/iphone-4s/specs/).

But after changing the device's orientation (rotating the device left or right) a `Resized` event is generated that gives width and height values that are a factor of two larger than the original size. This factor of two, is the value of the SFML iOS application delegate's `backingScaleFactor` variable (for this device) and it's being re-applied in the `deviceOrientationDidChange` method (in `sfml-window/ios/SFAppDelegate.mm`) to the size returned from `self.sfWindow->getSize()` (which already factors this value in).

**Comment by eXpl0it3r** [comment]
Superseded by #1050
