### ISSUE TITLE
Draw a texture without sprite

### ISSUE THREAD

**Issue by egordorichev** [SFML/SFML#1051]
Hello! Can I draw a texture without using a sprite? If not, can you implemnt this, please!

**Comment by MarioLiebisch** [comment]
In theory you can use any primitive for that (like `sf::RectangleShape`), but there's little to no overhead on `sf::Sprite`.

Besides that, note that this **bug** tracker is meant for confirmed issues and bugs. If you've got some feature request or require help, use the official forums found on http://www.sfml-dev.org/. Also make sure to include as much information as possible (e.g. "Why don't you want to use `sf::Sprite`?").
