### ISSUE TITLE
Allow creation of robust context

### ISSUE THREAD

**Issue by feliwir** [SFML/SFML#1053]
Allow the user to create a robust context for the extension GL_ARB_ROBUSTNESS, which got part of the core profile in OpenGL 4.1. This requires SFML to add the GLX_ARB_create_context_robustness  (X11) and WGL_ARB_create_context_robustness  (Windows) OpenGL extensions. GLFW did already add this feature see here: http://www.glfw.org/docs/latest/window.html (see in chapter "Context related hints"). Since this needs to be done during context creation it should be part of SFML.

**Comment by Bromeon** [comment]
Please use the [feature request subforum](http://en.sfml-dev.org/forums/index.php?board=2.0), as stated in the [contribution guidelines](http://www.sfml-dev.org/contribute.php). This tracker is for confirmed tasks only.

And please add a bit more description than just "GLFW has it too" :)
