### ISSUE TITLE
UB in android sf::Mouse::getMousePosition()

### ISSUE THREAD

**Issue by 1aam2am1** [SFML/SFML#1054]
```
Vector2i Mouse::getPosition()
{
    return priv::InputImpl::getMousePosition();
}
```
```
Vector2i InputImpl::getMousePosition()
{
    ALooper_pollAll(0, NULL, NULL, NULL);

    priv::ActivityStates* states = priv::getActivity(NULL);
    Lock lock(states->mutex);

    return states->mousePosition;
}
```
```
ActivityStates* getActivity(ActivityStates* initializedStates, bool reset) //reset=false
{
    static ActivityStates* states = NULL;

    if (!states || reset)
        states = initializedStates;

    return states; ///returns null
}
```

**Comment by MarioLiebisch** [comment]
Is this a theoretical bug or an actual issue? Can you provide some minimal example where this issue occurs? When writing bug reports, try to explain the situation. Don't just add two tiny comments to source snippets, if it isn't obvious when/how something happens.

**Comment by 1aam2am1** [comment]
I buried something wrong with pointers and debugger showed me wrong position on error in android :(

**Comment by Bromeon** [comment]
Please use the forum next time, we usually like to add a GitHub issue only once a bug is confirmed. See also [Contribution Guidelines](http://www.sfml-dev.org/contribute.php). Thanks!
