### ISSUE TITLE
Vulkan Support

### ISSUE THREAD

**Issue by AustinHaugerud** [SFML/SFML#1061]
I understand this is isn't actually an issue, and to make it a goal would be to take on a very large goal, but I think it'd be neat to at least discuss. 

As many of you have probably already heard, Vulkan 1.0 has finally been released. It seems glfw has actually already added some basic Vulkan support. 
https://github.com/glfw/glfw/commit/9b75bffc88939883d8ae77901b73182dda35e733

Vulkan just like OpenGL would be awesome to have some higher level library wrappers for. It'd certainly be awesome to see SFML at some point support Vulkan.

**Comment by mantognini** [comment]
> I think it'd be neat to at least discuss.

Yes, please. But *please*, follow our >> [contribution guideline](https://github.com/SFML/SFML/blob/master/CONTRIBUTING) <<

> They will help you focus on the important stuff and prevent you from losing (y)our time with requests
that are out of SFML's scope, known issues, and so on.

I'm therefore closing this until it is properly discussed on the forum and that a precise plan is made. Without that, it's just lost energy!

**Comment by Bromeon** [comment]
I think [one closed issue](https://github.com/SFML/SFML/issues/899) is enough. (and its comment 2h before this post is hardly a coincidence...)
