### ISSUE TITLE
Shouldn't there be getters and setters for a lot of the objects

### ISSUE THREAD

**Issue by SirSharpest** [SFML/SFML#1070]
Just something I've noticed in the code, but when I want to give a new value to coords for SF Shape objects, it's done through assignment rather than a sanitizing function?

**Comment by Bromeon** [comment]
For design discussions and general questions about the library, please use the forum. This is outlined in our [Contribution Guidelines](http://www.sfml-dev.org/contribute.php). Issues on the other hand are for tasks that the SFML team has confirmed to work on.
