### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by sharhar** [SFML/SFML#1071]
It would be really nice to have simple way to create a vulkan instance, device, surface, etc. Even though all drivers for it are in beta it would be very helpful to have something like this for the future. Also, it would be very useful on mobile platforms where an api like vulkan would really help performance.

I'm just wondering, would there ever be support for a d3d implementation for windows platforms?

**Comment by eXpl0it3r** [comment]
Please use the search function. [Duplicate 1](https://github.com/SFML/SFML/issues/1061) [duplicate 2](https://github.com/SFML/SFML/issues/899). Use [this thread](http://en.sfml-dev.org/forums/index.php?topic=19822) for discussion.

**Comment by sharhar** [comment]
sorry, i i searched for a duplicate port about vulkan but couldn't find one.
