### ISSUE TITLE
Install FindSFML.cmake to the CMake path on Linux/FreeBSD

### ISSUE THREAD

**Issue by akien-mga** [SFML/SFML#1076]
Most libraries install their `FindFooBar.cmake` in the system-wide path that CMake looks into automatically `/usr/share/cmake/Modules`, e.g. `/usr/share/cmake/Modules/FindZLIB.cmake`.

By default, SFML installs its .cmake file in `/usr/share/SFML/cmake/Modules/FindSFML.cmake`. Due to this it won't be used by downstream projects that rely on SFML and use CMake unless they specify this path in their own CMakeLists.

I think it would be sensible to install SFML's cmake file to `/usr/share/cmake/Modules/FindSFML.cmake`.

**Comment by jcowgill** [comment]
Using config files is a much better solution than doing this (#758, #937).

Also, on some distributions the CMake Modules directory changes with each version of CMake, which makes installing files there a bit annoying (for example the Modules directory on my system is `/usr/share/cmake-3.5/Modules`).

**Comment by eXpl0it3r** [comment]
The question is, is there a reliable way to find the modules path, because as @jcowgill said, it changes from distro to distro.

Also please take a look at the [contribution guidelines](http://www.sfml-dev.org/contribute.php) and start discussions on the forum next time, so we can use this tracker for confirmed issues only.

**Comment by akien-mga** [comment]
> Using config files is a much better solution than doing this.

I agree, though I have little experience with config files myself. At the moment though, there is a .cmake file but it's just being installed in a non-usable path, so that's still something worth changing if there's a better solution.

> Also, on some distributions the CMake Modules directory changes with each version of CMake, which makes installing files there a bit annoying (for example the Modules directory on my system is ``/usr/share/cmake-3.5/Modules``).

That's a good point. I'm not 100% sure how other projects do to get the path right when installing their own .cmake file, but I imagine that CMake has a built-in function that gives you the path for CMake modules configured for this CMake distribution. I'll have a look.

> Also please take a look at the contribution guidelines and start discussions on the forum next time, so we can use this tracker for confirmed issues only.

Sorry about that, I had a quick look over the guidelines but as I'm quite used to contributing to many different projects, and that most of the times the recommendations are to check first for existing issues (which I did), make sure it's reproducible, etc., I missed the part about not reporting issues on GH but on the forums.

**Comment by akien-mga** [comment]
I believe this path could be used for the installation target: ``${CMAKE_ROOT}/Modules``.
(https://cmake.org/pipermail/cmake/2007-January/012520.html)

On my system, this command:
```
message(STATUS "CMake modules path: ${CMAKE_ROOT}/Modules")
```
outputs:
```
-- CMake modules path: /usr/share/cmake/Modules
```

**Comment by MarioLiebisch** [comment]
Bit late to the party, but don't forget `${CMAKE_ROOT}` might not be writable by the user, e.g. on Windows it's typically under `C:\Program Files` and therefore requires elevated access. If there's no fallback, users wouldn't be able to install SFML anywhere without admin credentials, which might be a problem for company or educational use.

**Comment by JonnyPtn** [comment]
I'm very much in support of this, on all platforms.

Could it not install to CMAKE_MODULE_PATH, which can be overriden by the user to install it somewhere not requiring admin if they so choose?

**Comment by MarioLiebisch** [comment]
Well, the right thing to do would actually be CMake moving their Modules directory to the writeable `C:\ProgramData` (i.e. `%ALLUSERSPROFILE%` or `%APPDATA%`). Could actually be a good suggestion and it would follow their path layout compared to Linux (since this is essentially `/usr/share`). With that done I'd see no problem actually hardcoding the path.

Not sure if it's a good idea to reuse `CMAKE_MODULE_PATH`. It might point somewhere else when embedding SFML in another project (I think).
