### ISSUE TITLE
find_package(OpenAL) failing with target armabi and host OSX

### ISSUE THREAD

**Issue by qinqon** [SFML/SFML#1080]
It's preferring always the OSX OpenAL Framework version, I have to force OPENAL_LIBRARY.
#1081

**Comment by eXpl0it3r** [comment]
The preferred way, as stated in the [contribution guidelines](http://www.sfml-dev.org/contribute.php), would have been to discuss this issue on the forum first.

**Comment by qinqon** [comment]
Oops, ok.

**Comment by eXpl0it3r** [comment]
Was setting the environment variable `OPENAL`, as mentioned on the forum, successful?

Can this PR be closed or do we still need to adjust something?

**Comment by qinqon** [comment]
We can close it.
