### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by Quintus** [SFML/SFML#1082]
Hi,

we as the dev team of [TSC](https://github.com/Secretchronicles/TSC) got a request to drop SFML because it doesn’t support "the future" of graphics in Linux, Wayland. Money quote ([source](https://github.com/Secretchronicles/TSC/issues/534#issuecomment-208031577)):

> Please consider SDL2. SFML does not support Wayland. Wayland is more or less "the future" compared to X.

That being said, we have no intentions honouring that request just because of Wayland, but I would like to suggest to include Wayland support into SFML in some more or less distant future.

Valete,
Quintus

**Comment by victorlevasseur** [comment]
You should consider reading this http://en.sfml-dev.org/forums/index.php?topic=10819

**Comment by LaurentGomila** [comment]
I'm closing this issue, please refer use the existing thread on the forum to discuss about Wayland, if you really feel like you have new arguments in favor of this change.

**Comment by Boiethios** [comment]
Ok, I understand now why the game does not work on my Debian…

This is a strange decision to use a library that does not support wayland (and if I well read, Laurent does not want to develop SFML for wayland). The current stable GNOME version (3.20) cannot run anymore on X, and I suppose more and more desktop will drop the support for X. That is not good for the future of tsc, unless SFML get ported on wayland.

**Comment by victorlevasseur** [comment]
You know that X apps can run inside wayland (that's how most old apps still work with it). By the way, I don't think that GNOME 3.20 defaults to Wayland...

**Comment by Boiethios** [comment]
I can no more connect on a pure X session since GNOME 3.20. I know X apps can run inside wayland through Xwayland, but because the game did not work on my computer, I supposed that was the fault of the SFML. If you think that the problem comes from something else, I will open another issue.

**Comment by LaurentGomila** [comment]
> because the game did not work on my computer, I supposed that was the fault of the SFML

Don't suppose. If the game doesn't work on your computer, then post a help request on the game's forum/tracker/whatever. If the cause of the problem is found and related to SFML, then come back with technical details.

**Comment by shriramters** [comment]
I believe this should be reopened as almost all popular DEs run on wayland today

**Comment by Wanye-7300** [comment]
> **GNOME Merge Requests Opened That Would Drop X.Org Session Support.**
> (https://www.phoronix.com/news/GNOME-MR-Drop-X11-Session)

As desktop environments gradually make Wayland their default, it's clear that Wayland is the future. Back in 2016, hesitation about adopting Wayland might have made sense, but sticking with X11 these days makes little sense.

**Comment by permafrozen** [comment]
100% agree, as `wayland` became pretty much the succesor of `x11`.

**Comment by sm-Fifteen** [comment]
> > **GNOME Merge Requests Opened That Would Drop X.Org Session Support.**
> > (https://www.phoronix.com/news/GNOME-MR-Drop-X11-Session)
> 
> As desktop environments gradually make Wayland their default, it's clear that Wayland is the future. Back in 2016, hesitation about adopting Wayland might have made sense, but sticking with X11 these days makes little sense.

Dropping the X11 session mode won't drop X11 compatibility, though. Even if 100% of applications running on your GNOME machine were X11-only, they would still work under the current Wayland session and they would still work after X11 session support got dropped because they are X11 *clients*, which can continue running via XWayland.

There are no plans to drop XWayland in the future because that would render all unmaintained X11 applications unusable.

I'm still pushing for Wayland adoption, but let's not act like there's any sense of urgency, here.

**Comment by Bambo-Borris** [comment]
I agree Wayland support is an important thing for SFML to adopt, but also we need people with the relevant experience/knowledge to come in and contribute that support. Just re-opening this issue is merely an admin step here, if people want to see Wayland we need to see some draft PRs come in.
