### ISSUE TITLE
sf::Vector binary operators do not support type promotion.

### ISSUE THREAD

**Issue by khatharr** [SFML/SFML#1083]
For example,

`sf::Vector2f v(1.0f, 1.0f);
v *= 3; //this fails`

The reason being that the operator*= template specifies arguments `(sf::Vector<T> left, T right)`, so type deduction fails and the right-side argument can't be promoted.

A solution is to change to 
`template<typename T, typename Q>
sf::Vector2<T>& operator*=(sf::Vector2<T>left, Q right)`

Which will match varied types and only fail to compile if the operation itself does not make sense.

**Comment by eXpl0it3r** [comment]
I'm quite certain that this is by design. There's no gain in allowing type mixing other than for the developer to be lazy and not use the matching type. :wink:  
Say you have a `sf::Vector2<int>` and then multiply by a `float` , how should that work out?

Also this issue tracker is for confirmed issues only, use the forum to discuss things like that. See also the [contribution guidelines](http://www.sfml-dev.org/contribute.php).

**Comment by khatharr** [comment]
http://swizec.com/blog/programmers-are-fucking-lazy/swizec/2648

As for the demotion issue, try a short test case.  I'm away from the machine, but I strongly suspect that the compiler is going to talk to you about it, same as it does in any other case.

**Comment by mantognini** [comment]
I'm highly confident this was discussed and rejected in the past. Please have a look at the forums for previous pro/against arguments or open a new thread there to motivate this alternative design if you have new arguments.

**Comment by LaurentGomila** [comment]
Mixing types the right way is a lot more complicated than that.

Take this example, that would use your suggestion:
```cpp
int v1 = 2;
float v2 = v1 * 3.3f;
// v2 equals 6.6 because int * float gets promoted to float

sf::Vector2<int> v1(2, 2);
sf::Vector2<float> v2 = v1 * 3.3f;
// v2 equals (6, 6) because Vector2<int> * float returns a truncated Vector2<int> which is then converted to Vector2<float>
```

With some C++11 template magic you can get the right return type according to the language promotion rules, but I don't think we want to start doing it -- and SFML is still stuck in C++03 for now ;)

**Comment by khatharr** [comment]
Don't know why I bother.

**Comment by louis-langholtz** [comment]
Template magic like the following perhaps?


template <typename LTYPE, typename RTYPE>
constexpr auto operator* (sf::Vector2<LTYPE> lhs, RTYPE rhs)
{
	return sf::Vector2<decltype(lhs.x * rhs)>{ lhs.x * rhs, lhs.y * rhs };
}


I wouldn’t as quickly call that magical as I’d call C++03 the-dark-ages.

**Comment by LaurentGomila** [comment]
Yes, magic like this. Maybe with an explicit trailing return type declaration to make it C++11 compliant.

But as we all know, SFML can't include non-C++03 code for now anyway.
