### ISSUE TITLE
Window icon not showing in some linux destros

### ISSUE THREAD

**Issue by genaside** [SFML/SFML#1087]
So basically the setIcon function does not show up on some Linux destros.
Go here for more information.
http://en.sfml-dev.org/forums/index.php?topic=20229.0

**Comment by binary1248** [comment]
Should be fixed in #1088, care to test?

**Comment by genaside** [comment]
@binary1248 you are a beautiful, beautiful person. The change works on machine now. The icon problem was small problem, but it annoyed me :). Thanks again.

**Comment by eXpl0it3r** [comment]
Superseded and fixed by #1088
