### ISSUE TITLE
Window menu doesn't work on OSX

### ISSUE THREAD

**Issue by thedeadc0der** [SFML/SFML#1091]
The "Window" menu in the menu bar normally contains the options "Minimize", "Zoom" and "Enter Full Screen", as well as a list of windows. In an SFML program, though these menu items exist, they are greyed out, which also has the unfortunate side-effect that the familiar keyboard shortcuts for these actions don't work either.

**Comment by eXpl0it3r** [comment]
[Related forum post](http://en.sfml-dev.org/forums/index.php?topic=20344.0)

Additional comment by @mantognini:

> Regarding the "Enter Full Screen" action, this cannot be implemented ATM because we cannot programmatically change the "style" of a window in SFML. It would be inconsistent with this limitation to have such menu.

**Comment by mantognini** [comment]
If people are motivated to solve this:

> But since I won't have time to look into this soon, it would be very appreciated if you could use `git bisect` to find which commit did introduce the regression. Note that to do this, you'll need to update cmake/Config.cmake this [the attached patch](http://en.sfml-dev.org/forums/index.php?action=dlattach;topic=20344.0;attach=2675) on some git versions if you're using OS X 10.10 or above.

**Comment by JonnyPtn** [comment]
Bisecting leads me to this commit: 7f0f89bac95831c9e6d9d2027525338a6e85fcd1 

Unfortunately I don't know what's going on in that commit so can't help further right now

**Comment by mantognini** [comment]
Superseded by #1193.
