### ISSUE TITLE
Boost doesn't use CMake

### ISSUE THREAD

**Issue by ruslo** [SFML/SFML#1101]
There is a statement in "Introduction" section that Boost use CMake ([link](http://www.sfml-dev.org/tutorials/2.3/compile-with-cmake.php#introduction)):
```
CMake is used by many projects including well-known ones such as Blender, Boost, KDE, and Ogre.
```
It is (unfortunately) not true. Boost uses their own build system. At least if we are talking about [this](http://www.boost.org/) project :)

**Comment by LaurentGomila** [comment]
Wrong repository :)

https://github.com/SFML/SFML-Website

**Comment by ruslo** [comment]
> https://github.com/SFML/SFML-Website

Okay, I see.
