### ISSUE TITLE
Add sf::String::at(), analagous to std::string::at()

### ISSUE THREAD

**Issue by xqbt** [SFML/SFML#1110]
Runtime boundary checking would be nice to have.

**Comment by eXpl0it3r** [comment]
Please have a look at our [contribution guidelines](http://www.sfml-dev.org/contribute.php). We reserve the GitHub tracker for confirmed issues and features only and use the forum (especially the [feature request section](http://en.sfml-dev.org/forums/index.php?board=2.0)), for random ideas and discussions.

**Comment by xqbt** [comment]
OK, gotcha.
