### ISSUE TITLE
Joystick rumble support

### ISSUE THREAD

**Issue by Zuzu-Typ** [SFML/SFML#1112]
Dear developers,

I'm new to GitHub, so expect some stupidity or mistakes of mine.

So I recently found that the ability to use the rumble feature in my game without having to use XInput would be great, as I am rather new to C++ and not skilled enough to write such a function myself, yet I try to make as much of my game with as few additional modules as possible.
A challenge that will probably ruin it, as I have to learn C++ and modern OpenGL while doing other advanced things that I have no idea of.

I know this has been suggested in the forum already, but as I was unsure how this issue tracker worked, I thought suggesting it again can't be bad.

Thank you for your time and support,
--Zuzu_Typ--

**Comment by mantognini** [comment]
You are more than welcome to discuss your issue on the forum first as we try to keep this issue tracker for confirmed issues only. The procedure to open a bug/feature request is explained in [the contribution guidelines](http://www.sfml-dev.org/contribute.php). Thanks.
