### ISSUE TITLE
Workaround for building SFML on VS2015 (Android).

### ISSUE THREAD

**Issue by doside** [SFML/SFML#1115]
I have used VS2015 to build SFML ,and then I succeed to do it, however, when I run the 
android example at music.openFromFile("canary.wav"), the app is stopped.
Finally I found that the key to solve this problem is define ANDROID macro for any 
project use this macro, because the file FileInputStream.cpp  use this macro to determinate  which implement to use.
Although I have fixed this issue, I still worry that if there is any other function about this macro.
If it has no special meaning but just detect the platform, I am afraid that maybe use the `__ANDROID__` would be a better choice.

By the way, I think maybe there was something affected the project settings since I used a special version
of cmake to generate the vs2015 project; the cmake I used is avaliable in this [link](https://blogs.msdn.microsoft.com/vcblog/2015/12/15/support-for-android-cmake-projects-in-visual-studio/) .
 When I used it to generate project I met some problem which said that find_host_package
is an unknown command, I replaced those to find_package in all CmakeList.txt for workaround it.

**Comment by mantognini** [comment]
You are more than welcome to discuss your issue on the forum first as we try to keep this issue tracker for confirmed issues only. The procedure to open a bug/feature request is explained in [the contribution guidelines](http://www.sfml-dev.org/contribute.php). Thanks.

@MarioLiebisch @Sonkun Feel free to re-open & tag appropriately if you know what this is about.
