### ISSUE TITLE
Different signatures in function setTexture (sf::Sprite and sf::Shape classes)

### ISSUE THREAD

**Issue by Dka8** [SFML/SFML#1127]
Hello! This is what we have now:
`void sf::Sprite::setTexture	(const Texture & texture, bool resetRect = false)` — texture as reference
`void sf::Shape::setTexture	(const Texture *  texture, bool resetRect = false)` — pointer on texture

Let us assume we have a pointer on some `sf::Drawable` object and want write a nice function for setting object's texture:
```
template<typename DRAWABLE>
void setTexture(sf::Drawable* l_drawable, const sf::Texture* l_texture) {
			l_drawable = dynamic_cast<DRAWABLE*>(itr->second);
			drawable->setTexture(l_texture);
			return true;
}
```
Unfortunately this function will work only for object type `sf::Shape`.
If we try use it for `sf::Sprite` like this:
`setTexture<sf::Sprite>(l_drawable, &l_texture)` our compiler will thow an error: 

> cannot convert argument 1 from 'const sf::Texture *' to 'const sf::Texture &'

We can solve this by writing an overload version:
`void setTexture(sf::Drawable* l_drawable, const sf::Texture& l_texture)`
But still it would be nice to have a similar interference for sf::Shape and sf::Sprite.
Besides implementation of that function is very similar for both cases:
```
void Sprite::setTexture(const Texture& texture, bool resetRect)
{
    // Recompute the texture area if requested, or if there was no valid texture & rect before
    if (resetRect || (!m_texture && (m_textureRect == sf::IntRect())))
        setTextureRect(IntRect(0, 0, texture.getSize().x, texture.getSize().y));

    // Assign the new texture
    m_texture = &texture;
}
```
and

```
void Shape::setTexture(const Texture* texture, bool resetRect)
{
    if (texture)
    {
        // Recompute the texture area if requested, or if there was no texture & rect before
        if (resetRect || (!m_texture && (m_textureRect == IntRect())))
            setTextureRect(IntRect(0, 0, texture->getSize().x, texture->getSize().y));
    }

    // Assign the new texture
    m_texture = texture;
}
```
Note, that privat member `m_texture` is a pointer to `sf::Texture` in both classes.
Thanks!

**Comment by LaurentGomila** [comment]
The texture in sf::Shape is optional, not in sf::Sprite. That's the reason.

Next time please discuss this on the forum, this tracker is for confirmed bugs and features.
