### ISSUE TITLE
Scalar color operators

### ISSUE THREAD

**Issue by kavika13** [SFML/SFML#1128]
For simplicity and brevity in working with colors, it may be useful to support scalar math operators.

    Color darkGreen = Color::Green - 127;
    Color darkGray = Color::Black + 63;
    Color darkerColor = someComputedColor * 63;

The equivalents are already possible now, but are more verbose:

    Color darkGreen = Color::Green - Color(127, 127, 127, 0);
    Color darkGray = Color::Black + Color(63, 63, 63, 0);
    Color darkerColor = someComputedColor * Color(63, 63, 63, 255);

Problems I see:

- Accidental implicit conversions. I think this is already taken care of by providing `operator uint32_t` as a named member function instead of an overloaded operator. It is also taken care of by making the `Color(uint32_t)` constructor explicit.
- The `operator *` might be confusing, since it scales down, not up. The existing `operator *` already does this, and anyone who is "multiplying" colors already has to understand this difference as it stands today. I'd change my mind if `operator /` was introduced, but I think that's a very confusing construct to begin with for someone who isn't super familiar with color math, so I think it should not go into the library anyway.
- There might be anxiety on the user's side on whether the alpha channel is touched or not. This could be cleared up by documentation of the scalar operators. I think preserving the alpha channel in these operators is the more common case, and is the least surprising.

If there was interest, I'm perfectly happy and able to put in a pull request implementing these features. I'd prefer to ask for comments and/or a rejection before I spend time on it.

**Comment by MarioLiebisch** [comment]
Maybe it's just me, but this sounds reasonable on one hand but misleading on the other. You can do similar operations in shaders, but you'd apply it to all components, i.e. you'd modify alpha as well.

I could imagine scenarios where you'd want to modify alpha and I could imagine scenarios where you don't.

Plus we've got the problem that multiplication might be misleading when using integers vs. foats.

**Comment by nabijaczleweli** [comment]
Neat idea; multiplying by `float`s would be inconsistent with rest of `Color`, though, would it not?

**Comment by kavika13** [comment]
> multiplying by floats would be inconsistent with rest of Color, though, would it not?

It would be inconsistent. It might be confusing to people who were new to have an inconsistent interface. You also can provide both interfaces via overrides, but that might be even more confusing. Another option I can think of is to provide both a float-oriented color class and an integer-oriented color class.

Having overrides that operate differently wouldn't be confusing to me, but I've been programing for a long time.

I also think trying to solve too many use cases is also [against the contrib guidelines](http://www.sfml-dev.org/contribute.php). You always open up this can of worms when you mix higher level classes with operator overloads :) I would argue with consistency with the original integer-based design, unless adding `float: [0.0, 1.0]` oriented math was opening up a bunch of use cases that was in demand.

There are C++ math libraries that provide [shader-style vector interfaces on the CPU](https://github.com/gwiazdorrr/CxxSwizzle), trying to get 100% compatibility with shaders, which to me falls squarely in the "put a feature in an extension when you can" part of the contrib guidelines.

> You can do similar operations in shaders, but you'd apply it to all components, i.e. you'd modify alpha as well.

If the intention was to perfectly mimic shaders, then I think the components would always be floats, and an integer interface wouldn't be provided.

I think this discrepancy opens up the root of the issue, and that is determining exactly what the driving use cases are behind colors in this library.

Right now the Color class seems most useful for applying a color mask on items in the scene graph, like making a green rectangle, or giving a sprite a color overlay when something interesting happens to it (selected, hovered over, actor takes damage, some stat slowly turns from a "good" value to a "bad" value, etc). It can also be used for simple OpenGL style vertex colors, or as input parameters to shaders.

I think anything more complicated than this (full screen effects, mathematical signals as an input, advanced blending, etc) is probably best calculated on the GPU.

> I could imagine scenarios where you'd want to modify alpha and I could imagine scenarios where you don't.

Can you describe the specific use cases? I think being explicit with the use cases we can think of helps in determining the weights of those cases, and helps in prioritizing design tradeoffs. I don't know all the use cases, and I think more eyeballs and voices could help this out.

**Comment by kavika13** [comment]
In case it helps:

Some of my inspiration for this idea comes from working with Arudino and [the FastLED library](https://github.com/FastLED/FastLED/) after having worked with [the NeoPixel library](https://github.com/adafruit/Adafruit_NeoPixel) and trying to implement my own color library on top of it. Totally different set of use cases, but it was helpful to me to see their `CRGB` interface, and see what features might make sense in SFML, and which would obviously be an extension. Multiplying by a scalar turned out to be pretty straight-forward and useful in my programs.

[This article on vector libraries](http://www.reedbeta.com/blog/2013/12/28/on-vector-math-libraries/) (and the comments section) also gave me inspiration for the types of things that would be useful for vectors, showed me that a separate color class is the way to go, and showed me that not everything that applies to vectors works well for colors with unsigned integer components.

**Comment by mantognini** [comment]
> Maybe it's just me, but this sounds reasonable on one hand but misleading on the other. You can do similar operations in shaders, but you'd apply it to all components, i.e. you'd modify alpha as well.

I also think the proposed behaviour is misleading. Please [discuss this on the forum](http://www.sfml-dev.org/contribute.php#requesting-features) to reach a consensus.

**Comment by kavika13** [comment]
Thanks for the feedback so far :)

Thread to be continued here:

http://en.sfml-dev.org/forums/index.php?topic=20718.0

**Comment by kavika13** [comment]
The last post on the discussion was mid-August, and I'm the only one who has spoken about this feature request 100% positively. Should we keep this open and let it sit, add a poll to the forum, or simply close this issue?

**Comment by eXpl0it3r** [comment]
I'm against adding these changes.

**Comment by mantognini** [comment]
So I'm closing this for now. If consensus on the forum changes we can reopen it of course, but I wouldn't put too much hope on that. ;-)
