### ISSUE TITLE
There is no way to retrieve the actual resolution of the screen

### ISSUE THREAD

**Issue by ajweeks** [SFML/SFML#1134]
sf::VideoMode::getDesktopMode() returns the current resolution that the user has their monitor set to, which is not necessarily the actual resolution of their screen. The problem with this is window creation asks for a resolution in terms of actual screen resolution.

For example, I have a 3840x2160 monitor, but I sometimes set the resolution to 1920x1080. When creating a window based on the width and height retrieved from getDesktopMode(), the window is significantly smaller when my screen's resolution set to a smaller value.

I would like to be able to create a window which is a certain percentage of the user's screen size (regardless of their current resolution). Is there a way to do this that I am not seeing?

**Comment by mantognini** [comment]
You are more than welcome to discuss your issue on the forum first as we try to keep this issue tracker for confirmed issues only. The procedure to open a bug/feature request is explained in [the contribution guidelines](http://www.sfml-dev.org/contribute.php). Thanks.

**Comment by Foaly** [comment]
I once wrote a draft for multi monitor support, that also included the actual size of a screen (bounds in vitual screen space). As per usual it got lost over time. You can still find the [branch](https://github.com/Foaly/SFML/tree/multi-monitor) and the [forum thread](http://en.sfml-dev.org/forums/index.php?topic=18950.0).
