### ISSUE TITLE
Optimization of several cycles

### ISSUE THREAD

**Issue by gshep** [SFML/SFML#1139]
Hi everyone!

To tell the truth I was playing with a sample from another library -
[EntityX](https://github.com/alecthomas/entityx) but it ran very slow on my corn AMD A6 so I decided to profile
the sample. It uses SFML.

The main issue was in the sample itself but I found several interesting
places:
    1) Shape::updateFillColors
    2) Shape::updateTexCoords
    3) Shape::updateOutlineColors
    4) VertexArray::getBounds.

They contain for-loops but the condition checks the container's size
on every iteration! See attached screenshot for updateOutlineColors statistics in KCachegrind.
![qcachegrind-loops2](https://cloud.githubusercontent.com/assets/6125411/18053584/3d2cfd36-6e11-11e6-9d17-e32a12f2dc2d.png)

I made up my mind to send an PR.

IMHO this is not so sophisticated optimization to not to merge it.

However SFML may contain other cycles with conditions that check some
object's methods on every iteration and impact performance: size, iterator,
etc. I grepped and got the following results:
[for-loops.txt](https://github.com/SFML/SFML/files/442524/for-loops.txt)

So I propose to review these places and make "optimization" or just
"optimize" them. =)

**Comment by mantognini** [comment]
Please, please, please, have a look at [the contribution guidelines](http://www.sfml-dev.org/contribute.php). If you strongly feel that SFML needs to be optimised in some way, show on the forum a clear and significant performance increase with a SSCCE for us to test. We don't want to increase the complexity of the codebase just to save 1 or 2 CPU cycles -- that's not worth it in term of maintenance costs.
