### ISSUE TITLE
Add swap() to VertexArray

### ISSUE THREAD

**Issue by kevvo1288** [SFML/SFML#1141]
I just had an interesting case where having the ability to call swap() on two vertex array's would have been useful (in this particular case it was a double sided puzzle piece that can be flipped over). Is there a reason why VertexArray can't make use of the built in magic that is std::vector::swap()? Is this something that is worth having and maintaining, or is it a "never will another programmer need this feature" thing? Should it be implemented as a friend function that specializes the std::swap() function in algorithm/utility, or should it be a class function of VertexArray?

**Comment by eXpl0it3r** [comment]
Please take a look at the [contribution guidelines](http://www.sfml-dev.org/contribute.php). We try to keep this track for confirmed bugs, issues and feature requests and use the forum for questions and discussions.

`sf::VertexArray` is just a thin wrapper and should stay that way. If you want to do more advanced vertex manipulations it's adviced to use `std::vector<sf::Vertex>` directly.

**Comment by victorlevasseur** [comment]
The best is to use std::vector<sf::Vertex> directly and give
my_vector.data() to the draw method of sf::RenderTarget.

**Comment by kevvo1288** [comment]
That was fast, friendly, and useful. Thanks.
