### ISSUE TITLE
KeyRepeat event requested

### ISSUE THREAD

**Issue by IntellectualKitty** [SFML/SFML#1144]
Currently there is no way to determine whether or not a KeyPressed event represents the first time a key was pressed or if it is an operating system-generated key repeat event (apart from storing the key state in a boolean and trying to work it out yourself).  This information is typically provided with the event notification that is received from the operating system, and it would be nice if it could be passed on from SFML to the end application.  Sometimes this information is encoded as a boolean repeat value, but using a KeyRepeat event would be easier since the KeyEvent struct would not have to be modified; also, it would be a cleaner approach since a repeat field in the struct would be meaningless for KeyReleased events.

**Comment by LaurentGomila** [comment]
Please take a look at the [contribution guidelines](http://www.sfml-dev.org/contribute.php#contributing). We try to keep this track for confirmed bugs, issues and feature requests and use the forum for questions and discussions.
