### ISSUE TITLE
Can't compile on Linux (Mint 18 'Sarah')

### ISSUE THREAD

**Issue by ramonmeza** [SFML/SFML#1149]
```
Could NOT find LIBXCB_IMAGE (missing:  LIBXCB_IMAGE_LIBRARY) 
CMake Error at cmake/Modules/FindXCB.cmake:93 (message):
  xcb-image not found
Call Stack (most recent call first):
  src/SFML/Window/CMakeLists.txt:209 (find_package)
```

Library is definitely installed.

**Comment by SirSharpest** [comment]
@ramonmeza could you show me the output of this command: `dpkg -l | grep libxcb-image
`

**Comment by eXpl0it3r** [comment]
As stated in the [contribution guidelines](http://www.sfml-dev.org/contribute.php), we're trying to keep this issue tracker for confirmed issues only. Please use the forum instead and make sure to provide more information than "Library is definitely installed.". :wink:
