### ISSUE TITLE
General improvements for sf::Image

### ISSUE THREAD

**Issue by Fytch** [SFML/SFML#1152]
I happen to use `sf::Image` quite a lot in a current project but I am widely dissatisfied with its somewhat meager functionality. Possible improvements:

- Constructor overload that does the same as `sf::Image::create`.
- `sf::Image::create` is poorly implemented. It calls `.resize` on the internal `std::vector` which either leads to every old pixel being copied (even though they are all overwritten shortly after) or to `sf::Image` possessing a lot of memory it doesn't use (because `std::vector::capacity` stays the same regardless). The correct way of implementing this function is to swap the internal vector with a newly created one.
- `sf::Image::create` grants no exception safety. The instance is indeed corrupt after an erroneous `sf::Image::create` invocation because the dimensions and the actual data don't match anymore. However, strong exception safety (no changes in case of an exception being thrown) is easily achievable by just changing the order inside the function. Memory allocation must be done first and only then the actual instance should be modified.
- There should be an overload of `sf::Image::create` that doesn't fill the image with a particular color. This is an optimization when the user intends to overwrite the pixels anyway.
- `sf::Image::swap` should be implemented. The lack thereof forces users to copy the content from one image to another instead of just swapping the vectors' pointers, which leads to significant worse performance.
- `sf::Image::empty` would be nice as `sf::Image.getPixelsPtr() == nullptr` doesn't work and `sf::Image.getSize().x && sf::Image.getSize().y` is verbose. Multiple functions of `sf::Image` contain `if (!m_pixels.empty())`, yet this function isn't available outside the class.

I can implement these by myself and create a pull request, if others also appreciate these improvements.

**Comment by mantognini** [comment]
You are more than welcome to discuss your issue on the forum first as we try to keep this issue tracker for confirmed issues only. The procedure to open a bug/feature request is explained in [the contribution guidelines](http://www.sfml-dev.org/contribute.php). Thanks.

**Comment by MarioLiebisch** [comment]
[In case anyone stumbles over this, the discussion thread is here.](http://en.sfml-dev.org/forums/index.php?topic=20875.0)
