### ISSUE TITLE
Create hidden window?

### ISSUE THREAD

**Issue by volcoma** [SFML/SFML#1155]
It would be nice to be able to create the window and not show it by default.

Currently if i want to create a window and hide it immediately i see a flickering from the transition of the window.

**Comment by jcowgill** [comment]
Perhaps you are looking for this?
```
glfwWindowHint(GLFW_VISIBLE, GL_FALSE);
```

**Comment by volcoma** [comment]
I know how to do it, but there isn't any public api in the current window class to do it

**Comment by jcowgill** [comment]
Woops I think I was looking at totally the wrong repository :)

Please ignore my previous message.

**Comment by eXpl0it3r** [comment]
Please use the [Feature Request](http://en.sfml-dev.org/forums/index.php?board=2.0) forum for feature requests. As mentioned in the [Contribution Guidelines](http://www.sfml-dev.org/contribute.php) we try to use this tracker for confirmed issues and accepted features only.

Also make sure to read the section about feature requests in the contribution guidelines, so you'll include concrete use cases in your forum post. :wink:
