### ISSUE TITLE
Setting a subrect on texture not displaying

### ISSUE THREAD

**Issue by UnFlimFlammable** [SFML/SFML#1159]
Loading and displaying a single spritesheet displays, but loading a subrect of a texture and it won't display. 
![ship](https://cloud.githubusercontent.com/assets/6807831/19217016/7f094302-8d99-11e6-94d4-4e8adee0a60d.png)

```
#include <SFML/Graphics.hpp>
#include <iostream>
int main()
{
	sf::RenderWindow window(sf::VideoMode(200, 200), "Space Game!");
	sf::Texture texture;
	sf::IntRect subrect;
	subrect.left = 0;
	subrect.top = 0;
	subrect.width = 64;
	subrect.height = 64;

	//Load the ship from file
	if (!texture.loadFromFile("Assets/Ship.png")) {
		std::cout << "Error loading ship from file" << std::endl;
	}

	sf::Sprite sprite(texture, sf::IntRect(0,0,64,64));
	sprite.setPosition(sf::Vector2f(0, 0));

	while (window.isOpen())
	{
		sf::Event event;
		while (window.pollEvent(event))
		{
			if (event.type == sf::Event::Closed)
				window.close();
		}

		window.clear();
		window.draw(sprite);
		window.display();
	}

	return 0;
}
```

**Comment by eXpl0it3r** [comment]
It loads fine, but at the position (0, 0) with the size (64, 64) you get a fully transparent image and thus "nothing" gets displayed.

Please use [the forum](http://en.sfml-dev.org/forums/index.php#c3) for such help questions, since we want to keep this tracker for confirmed issues only.
