### ISSUE TITLE
glGetString(GL_EXTENSIONS) gives EXC_BAD_ACCESS on macOS 10.12

### ISSUE THREAD

**Issue by mmajko** [SFML/SFML#1163]
This piece of code terminates with segfault.

```c++
sf::ContextSettings settings(32, 0, 4, 4, 1, sf::ContextSettings::Attribute::Core);
sf::Window win(sf::VideoMode(1366, 768), "OpenGL", sf::Style::Default, settings);

std::cout << glGetString(GL_EXTENSIONS);
```

![screen shot 2016-10-18 at 22 16 28](https://cloud.githubusercontent.com/assets/3010503/19494682/9138d710-9580-11e6-8113-c89c8f8ff3e9.png)

Encountered this problem when trying to create sf::Shader objects.

Adding `window.setActive()` doesn't help. Trying another >3.2 contexts doesn't work either.
Console gives always this output:

```
Error. Unable to create the context. Retrying without shared context.
Warning. New context created without shared context.
```

**Comment by eXpl0it3r** [comment]
Please use the [forum](http://en.sfml-dev.org/forums/index.php) for discussing issues with your code. We like to reserve the issue tracker for confirmed bugs and features only as stated in the mentioned [Contribution Guidelines](http://www.sfml-dev.org/contribute.php).

32bit depth is most likely not supported, given that it's a rather uncommon mode.

**Comment by mmajko** [comment]
This is not a problem with 32bit depth, also tried with 24, there is 32 because I tried every option to make it work and forgot about it.

I've already consulted this on your IRC. If you're closing issues just like that, with no interest in solving problems, then I should stop using SFML and look for other library with helpful community around it. I've spent over an hour on this, I've made myself sure there isn't mistake in my code and I am not interested in registering on some forum. GitHub should be used for issues, not some bulletin boards.

Really disappointed, I liked SFML until this moment.

**Comment by mantognini** [comment]
If you're opening issues just like that, with no interest in helping properly identify problems, then you should stop and consider how many hours we lose with false report, why we decided to have some guidelines to report issues, and follow them to be helpful to our community. Thank you.
