### ISSUE TITLE
Win32 ClockImpl: QueryPerformanceCounter might return negative values

### ISSUE THREAD

**Issue by eggersa** [SFML/SFML#1167]
Microsoft actually points out that the QueryPerfomanceCounter might return a value below 0 and therefore the value should be clamped to ensure this must not happen: 

"When computing deltas, the values should be clamped to ensure that any bugs in the timing values do not cause crashes or unstable time-related computations. The clamp range should be from 0 (to prevent negative delta values) to some reasonable value based on your lowest expected framerate. Clamping is likely to be useful in any debugging of your application, but be sure to keep it in mind if doing performance analysis or running the game in some unoptimized mode." - https://msdn.microsoft.com/en-us/library/windows/desktop/ee417693(v=vs.85).aspx

I propose the following fix:

```
Time Clock::getElapsedTime() const
{
	Time elapsed = priv::ClockImpl::getCurrentTime() - m_startTime;

#if defined(SFML_SYSTEM_WINDOWS)
	// Ensure no negative value on windows
	if (elapsed < Time::Zero)
		elapsed = Time::Zero;
#endif

	return elapsed;
}


////////////////////////////////////////////////////////////
Time Clock::restart()
{
    Time now = priv::ClockImpl::getCurrentTime();
    Time elapsed = now - m_startTime;
    m_startTime = now;

#if defined(SFML_SYSTEM_WINDOWS)
	// Ensure no negative value on windows
	if (elapsed < Time::Zero)
		elapsed = Time::Zero;
#endif

    return elapsed;
}
```

**Comment by LaurentGomila** [comment]
Why did you close the issue just 2 minutes after posting it?

**Comment by eggersa** [comment]
Sorry, had to rework my fix for proposal. If you want I can do a pull request.

**Comment by eXpl0it3r** [comment]
I assume this is just something you came across in that documentation bit and it's not something you actually experienced in your application, right?

The posted quote is part of a document that talks about high performance timing for games and is listed as a recommendation. I may understand this wrong, but to me it seems more that they point out, that one should make sure that one doesn't accidentally end up with a negative delta value. So this doesn't really imply that the underlying API calls could return negative values, but is just an advice for the high-level implementations.

While the API documentation for [QueryPerformanceFrequency](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644905(v=vs.85).aspx) and [QueryPerformanceCounter](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644904(v=vs.85).aspx) only talk about nonzero values and don't say it could never be negative, it doesn't make sense in the context for it to be negative. Additionally [their example](https://msdn.microsoft.com/en-us/library/windows/desktop/dn553408(v=vs.85).aspx) doesn't bother to clamp anything either.
And finally SFML has been using the QueryPerformanceCounter for years now and I've never seen any reports of this being an issue, even with sf::Clock being used in pretty much every SFML application.

As such, I really wonder what they meant exactly with that quoted paragraph.

However if we do go for a fix, I wonder if this should go into the Windows clock implementation or more on a higher level as proposed above.

**Comment by eggersa** [comment]
I actually never came across such an issue. The windows ping command is likely to use the QueryPerformanceCounter internally and there are reports of negative ping values.

If you look inside the .NET Source Code, you actually find the same value clamping: https://referencesource.microsoft.com/#System/services/monitoring/system/diagnosticts/Stopwatch.cs,ceb0ba9cc88de82e

`public void Stop() {
	// ... 
		if (elapsed < 0) {
			// When measuring small time periods the StopWatch.Elapsed* 
			// properties can return negative values.  This is due to 
			// bugs in the basic input/output system (BIOS) or the hardware
			// abstraction layer (HAL) on machines with variable-speed CPUs
			// (e.g. Intel SpeedStep).

			elapsed = 0;
		}
	}
}`

Furthermore the book "Introduction to 3D game programming with DirectX 10 by Frank D. Luna" points out the same issue. However, they all blindly argue with a link to MSDN. But before this turns into a philosophical discussion its probably best to close this issue.

**Comment by MarioLiebisch** [comment]
I'm pretty sure that  clamping/sidenote from .net is really just a leftover from the XP timing bug, where multiple cores could run in different "times".

**Comment by eXpl0it3r** [comment]
As discussed above, I'm gonna close this issue.

**Comment by huangrongfu** [comment]
https://learn.microsoft.com/en-us/troubleshoot/windows-server/performance/programs-queryperformancecounter-function-perform-poorly

QueryPerformanceCounter may return negative value
