### ISSUE TITLE
CSFML 2.3 linked against the wrong version of SFML

### ISSUE THREAD

**Issue by jeannekamikaze** [SFML/SFML#1169]
I have downloaded the precompiled binaries for CSFML 2.3 for 64-bit Linux from [here](http://www.sfml-dev.org/files/CSFML-2.3-linux-gcc-64-bit.tar.bz2). ldd shows the libraries are linked against SFML 2.2, not 2.3:

```
$ ldd libcsfml-audio.so
	linux-vdso.so.1 =>  (0x00007ffd57f03000)
	libsfml-audio.so.2.2 => not found
	libsfml-system.so.2.2 => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fefe0253000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fefe003c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fefdfc75000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fefdf96a000)
	/lib64/ld-linux-x86-64.so.2 (0x000056332407b000)
```

Is this correct? Shouldn't it link against SFML 2.3?

Thanks.

**Comment by binary1248** [comment]
This is the issue tracker for SFML not CSFML. Please re-open this issue here: https://github.com/SFML/CSFML

**Comment by mantognini** [comment]
It was actually already discussed: SFML/CSFML#111
