### ISSUE TITLE
Linux Shift + any key always report -1/Unknown

### ISSUE THREAD

**Issue by stacksmith** [SFML/SFML#1170]
Testing on Ubuntu 16.04, sfml 2.4.1 according to the changelog.  Any keystroke while shift key is held down returns -1, Unknown.
```c
int main()
{
    sf::RenderWindow window(sf::VideoMode(200, 200), "SFML works!");
    sf::CircleShape shape(100.f);
    shape.setFillColor(sf::Color::Green);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
	    if (event.type == sf::Event::KeyPressed)
	      printf ("KEY EVENT ~%d\n", event.key.code);
        }

        window.clear();
        window.draw(shape);
        window.display();
    }

    return 0;
} 
```
Is there something wrong with my individual setup, or is this normal?  If it is normal, this is a terrible bug, and i have a hard time believing that no one has noticed...

**Comment by binary1248** [comment]
Cannot reproduce. Keys produce correct codes with and without modifiers held down. Modifiers themselves also produce the correct codes when they are pressed/released.

**Comment by stacksmith** [comment]
Checked again, and still getting -1, both from the laptop's keyboard and a plugged-in USB keyboard.  - Both left and right shift result in -1 for all subsequent keys, until released;
- Shift keys themselves produce 38 for left shift and 42 for right shift;
- Caps-lock does not produce a keystroke, but acts as shift, and results in -1 for all keys...
- Other modifiers work.   

Anthoughts on how to debug?

**Comment by DanielJPetersen** [comment]
Weird.  I'm not on Ubuntu 16.04 (Linux Mint 18 w/ SFML 2.4.1), but the sample code is working correctly on my machine too.

**Comment by stacksmith** [comment]
Found the problem, my fault.  Found SFML 2.3 installed in another directory; I think the test compiled with .h files not matching he library...  Works fine now. Apologies for wasted time.
