### ISSUE TITLE
Declare music causes problem

### ISSUE THREAD

**Issue by hurrymomo** [SFML/SFML#1175]
AL lib: (EE) alc_cleanup: 1 device not closed
Assertion failed: (lockret == althrd_success), function LockLists, file /Users/m/Desktop/tmp/openal/build_deps/openal-soft-openal-soft-1.17.2/Alc/ALc.c, line 776.
Abort trap: 6

I am using mac sierra.I just declare a sf::music in my hpp file , and did nothing  to msuic in cpp file. when i quit the window. the above error will occur

**Comment by LaurentGomila** [comment]
Please use the forum for help requests. This tracker is for confirmed features and bugs.

You should not define SFML resources at global scope. Declare your music inside main() and everything should be fine.
