### ISSUE TITLE
sf::Font::loadFromFile fails to find Unicode data in font and dumps memory to console.

### ISSUE THREAD

**Issue by tjohnman** [SFML/SFML#1177]
I've found that I can't call sf::Font::loadFromFile to open Consolas, Quivira or Google's Noto Mono (the last two certainly should carry Unicode data?). The method prints an error to console stating that it cannot find Unicode data in the font and then proceeds to dump the program's memory onto the console and crash with an access violation exception. I've tested this on Windows 10 using MSVS 14 2015.

If the font is read using an ifstream into a buffer and then passed to sf::Font::loadFromMemory, it still fails but it doesn't do the memory dump.

**Comment by LaurentGomila** [comment]
Please use the forum for help requests. This tracker is for confirmed tasks & bugs.

For your problem... the émemory dump" is typical of someone that uses release libs in debug configuration (or the other way round).

**Comment by tjohnman** [comment]
Regardless of the dump, loading any font fails after complaining it cannot find unicode data in the font.
Should I create a topic over at the forums and then an issue here when/if you confirm it's a bug?

**Comment by LaurentGomila** [comment]
> Should I create a topic over at the forums

Yes please.
