### ISSUE TITLE
Error with text.setcolor

### ISSUE THREAD

**Issue by Fastor01** [SFML/SFML#1189]
I tryed to print a text on the window. I used this code:
// Declare and load a font
sf::Font font;
font.loadFromFile("arial.ttf");
// Create a text
sf::Text text("hello", font);
text.setCharacterSize(30);
text.setStyle(sf::Text::Bold);
text.setColor(sf::Color::Red);
// Draw it
window.draw(text);

its form the offical SMFL tuturial webpage.

But I cant compile it because VS2015 print me this error: C4996 on "text.setColor(sf::Color::Red);"
I'm using SFML2.4 32bit

**Comment by LaurentGomila** [comment]
I'm pretty sure that the compiler outputs more details about this *warning*, especially the fact that the function is marked as *deprecated*, as written in the *documentation*.

And please next time use the forum, this tracker is for confirmed tasks and bugs.
