### ISSUE TITLE
constexpr functions/members

### ISSUE THREAD

**Issue by Crisspl** [SFML/SFML#1202]
`Color`'s static member constants (`Color::Red`, `Color::Blue` etc...) and `Vector[2|3]` related operators perfectly qualifies for `constexpr` (and probably many more, but these are the first that came to my mind). 
I read on [Contribution](http://www.sfml-dev.org/contribute.php) subsite, that every PR should be proceeded with corresponding issue. So here it is. 
Do you think it's a good idea?

**Comment by eXpl0it3r** [comment]
SFML 2.x is set to be using C++03. Since `constexpr` is a C++11 feature, we can't add it to SFML. [We're planning](http://en.sfml-dev.org/forums/index.php?topic=21571.0) to use C++11 or even C++14 (partially) for SFML 3.
