### ISSUE TITLE
CMakeLists not compatible with stated cmake version(s)

### ISSUE THREAD

**Issue by JonnyPtn** [SFML/SFML#1205]
The cmake minimum version is set to 2.8.3, however the policy which was introduced in 5fe5e5d now causes it to error on my version (2.8.11): 

CmakeLists line 20: `cmake_policy(SET CMP0042 NEW)`

Error: 
`CMake Error at CMakeLists.txt:20 (cmake_policy):
  Policy "CMP0042" is not known to this version of CMake.`

Looking at the [docs](https://cmake.org/cmake/help/v3.0/policy/CMP0042.html) it seems this was added in 3.0.

Either the minimum version needs to be updated, or this policy needs to be removed. I'd prefer the latter, but I don't know what impact it would have on OSX (I suppose adding a platform check to the CMakeLists would be a good middle ground)

@rkitover able to shed a bit more light on what this line does?

**Comment by rkitover** [comment]
I'm sorry, this will fix the problem:

```cmake
if(NOT CMAKE_VERSION VERSION_LESS 3.0)
    cmake_policy(SET CMP0042 NEW)
endif()
```

**Comment by mantognini** [comment]
@rkitover Would be awesome if you could create a PR for that. :-)

**Comment by JonnyPtn** [comment]
Might I suggest the build bot is set up to use the minimum recommended version of cmake to catch things like this in the future?

**Comment by mantognini** [comment]
Yes, absolutely. We are looking into this.

BTW, thanks for the PR. :)

**Comment by mantognini** [comment]
Superseded by #1206.
