### ISSUE TITLE
iOS port

### ISSUE THREAD

**Issue by sol-prog** [SFML/SFML#1207]
The extlibs from the iOS port are not compatible with latest iOS versions and simulators. Please update these to contain binaries for armv7, arm64, i386, x86_64.

**Comment by eXpl0it3r** [comment]
Would you be able to help us out with that? We're still lacking a person to maintain the iOS code base.

**Comment by sol-prog** [comment]
I was able to partially build the extlibs on my system (libogg.a, 
libjpeg.a, libflac.a, libfreetype). If you have the build scripts, from 
by the previous maintainer, I could have a look and try to build the 
remaining libs (libvorbis*.a).

**Comment by sol-prog** [comment]
Good news, I was able to build the remaining libraries (libvorbis). The audio system seems to work now (although is crashes the iOS app if you don't link the libraries in a particular order).

I can draw simple shapes and play sounds on both my iPhone 6s+ and the simulator.

**Comment by eXpl0it3r** [comment]
Yes, that would be appreciated. And don't hesitate to provide fixes for other iOS issues you might encounter!

**Comment by eXpl0it3r** [comment]
Merged in 700fc7d9e0f97c7cf1b9be28dcb01d766a451d04
