### ISSUE TITLE
Add support for VS 2017

### ISSUE THREAD

**Issue by exitc0d3** [SFML/SFML#1211]
Add libraries to the sfml download page for Visual Studio 2017 released a week or so ago.

**Comment by kennyrkun** [comment]
The 2015 SFML version works fine with the latest toolset.

All that's really needed, and not even, is for them to rename it to "2015 and 2017"

**Comment by RUSshy** [comment]
From user point of view, it makes the lib not dated to have up to date libs

I mean as a project, seeing old version numbers can be seen as an "not maintained project anymore" thing, so +1 for 2017 release, just for psychological effect :p

**Comment by minirop** [comment]
@kennyrkun this is just pure luck that 2015 compiled libs work with 2017. Each release of a compiler can break something (VS 2013 lib are not compatible with VS 2015).

**Comment by jantzeno** [comment]
@minirop It's not pure luck.  
https://blogs.msdn.microsoft.com/vcblog/2017/03/07/visual-studio-2017-for-c-developers-you-will-love-it/
http://cppcast.com/2017/03/daniel-moth/

**Comment by eXpl0it3r** [comment]
SFML already supports Visual Studio 2017.

With the introduction of the [Universal CRT with Visual Studio 2015](https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/) future Visual Studio releases have (theoretically) been made compatible. So, as pointed out already, you should be able to use the libraries provided for Visual Studio 2015.

Alternatively, you can just update CMake for the Visual Studio 2017 support and build SFML from source - it might even work directly within in Visual Studio 2017, as it now supports CMake.

**Comment by BenjaminHolland** [comment]
this whole disucssion is great to know about, but it's DIRECTLY contradicted by the download page:
"The compiler versions have to match 100%"
https://www.sfml-dev.org/download/sfml/2.4.2/

If you're not going to fix the names, at least fix the page.
