### ISSUE TITLE
Is there a way to use SFML with OSMESA?

### ISSUE THREAD

**Issue by Degot** [SFML/SFML#1212]
Hi, I'm using OSMESA for server side rendering.
I want to use SFML to rebuild it.
Is there a way to create a sf::Context for OSMESA with OSMesaCreateContextAttribs(). I do it like this: 
```

	int attribs[100], n = 0;
	attribs[n++] = OSMESA_FORMAT;
	attribs[n++] = GL_RGBA;
	attribs[n++] = OSMESA_DEPTH_BITS;
	attribs[n++] = 32;
	attribs[n++] = OSMESA_STENCIL_BITS;
	attribs[n++] = 32;
	attribs[n++] = OSMESA_ACCUM_BITS;
	attribs[n++] = 32;
	attribs[n++] = OSMESA_PROFILE;
	attribs[n++] = OSMESA_CORE_PROFILE;
	attribs[n++] = 0;	
	OSMesaContext ctx = OSMesaCreateContextAttribs(attribs, NULL);
```

**Comment by eXpl0it3r** [comment]
Please use the [forum](https://en.sfml-dev.org/forums/index.php) for general questions around SFML. As mentioned in the [Contribution Guidelines](https://www.sfml-dev.org/contribute.php) we want to keep this tracker for confirmed issues only. [Feature requests](https://en.sfml-dev.org/forums/index.php?board=2.0) should also be made in the dedicated forum section.

SFML requires the use of a window and thus depends on X11 for Linux. As such OSMESA is not supported.
