### ISSUE TITLE
Shader.loadFromFile() causing seg fault

### ISSUE THREAD

**Issue by lukehayes** [SFML/SFML#1213]
I have started a very basic project that simply opens a window and sets an OpenGL context. That is all working fine.

When I call the shader.loadFromFile() method I get a segmentation fault.

The shader files do exist. If I give the wrong path to them, the window appears fine, the screen clears and there is no crash at all.

Am I missing something simple?

Im using SFML 2.4.2 and I am on OSX 10.10.3.

Here is all of the code that I am using:

    `#include <SFML/Window.hpp>
    #include <SFML/Graphics.hpp>
    #include <OpenGL/gl3.h>
    #include <iostream>

    int main()
    {

    sf::ContextSettings settings;
    settings.depthBits = 24;
    settings.stencilBits = 8;
    settings.antialiasingLevel = 4;
    settings.majorVersion = 3;
    settings.minorVersion = 3;

    sf::Window window(sf::VideoMode(800, 600), "OpenGL", sf::Style::Default, settings);
    window.setVerticalSyncEnabled(true);

    // activate the window
    window.setActive(true);

    sf::Shader shader;
    shader.loadFromFile("../shaders/vert.glsl", "../shaders/frag.glsl");

    // run the main loop
    bool running = true;
    while (running)
    {

	// handle events
    sf::Event event;
    while (window.pollEvent(event))
     {
        if (event.type == sf::Event::Closed)
        {
	       // end the program
            running = false;
        }
    }

     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

      window.display();
    }

        return 0;
    }`

**Comment by eXpl0it3r** [comment]
Please use the [SFML forum](https://en.sfml-dev.org/forums/index.php), as mentioned in the [contribution guidelines](https://www.sfml-dev.org/contribute.php), to discuss problems with your code.

And make sure to provide a stack trace.

**Comment by mantognini** [comment]
I just tested and it works fine here. As @eXpl0it3r said, provide all the required information to reproduce the issue on the forum. Thanks.

**Comment by lukehayes** [comment]
Hmm, strange. Thanks for taking a look anyway :)
