### ISSUE TITLE
RenderWindow disables GL_DEPTH_TEST in draw()

### ISSUE THREAD

**Issue by augustjd** [SFML/SFML#1218]
While trying to use a `RenderWindow` for SFML and OpenGL 4.4 rendering, the `RenderTexture::draw()` function appears to disable `GL_DEPTH_TEST`, so I have to re-enable it myself after all the SFML rendering has been done.

At the very least, this should be mentioned in the documentation, but if possible, this should be handled in some kind of cleanup code (maybe in `display()`?). Other than this, `resetGLStates()` seems to suffice.

Granted, the guide recommends using `glPushAttrib()` and `glPopAttrib()`, which may solve this problem, but these have been deprecated. Perhaps it's now appropriate to have some sort of counterpart to `resetGLStates()` that does cleanup after SFML rendering is done.

**Comment by LaurentGomila** [comment]
SFML uses a set of OpenGL states for its own drawing, and leaves them active after it has finished for obvious reasons; `GL_DEPTH_TEST` is just one of them, there's nothing special about it.

How to mix sfml-graphics and your own OpenGL code is explained in the tutorial, documentation and in various forum posts. Please read these resources carefully before posting, and if you do, please do it on the forum. This tracker is for confirmed bugs and tasks.
