### ISSUE TITLE
Segmentation fault texture

### ISSUE THREAD

**Issue by BigfootN** [SFML/SFML#1220]
Hello,

I am having a problem with the library. When creating a simple program:

```cpp
int main() {
   sf::Texture texture;
}
```
I get `[1] 6699 Segmentation fault (core dumped) <program path>`

When running it in gdb I get 
```
in ?? () from /usr/lib/libsfml-window.so.2.4
in ?? () from /usr/lib/libsfml-window.so.2.4
in ?? () from /usr/lib/libsfml-window.so.2.4
in sf::Texture::Texture() () from /usr/lib/libsfml-graphics.so.2.4
```

Some other information:
OS: Archlinux
SFML version: 2.4 (tried `sfml-git` and `sfml` packages)

Thank you very much in advance

**Comment by eXpl0it3r** [comment]
This has been solved on [the forum](https://en.sfml-dev.org/forums/index.php?topic=21866.0).
