### ISSUE TITLE
Fullscreen does not go over task bars on top and left on Ubuntu 16.04

### ISSUE THREAD

**Issue by naezith** [SFML/SFML#1224]
Fullscreen does not go over task bars on top and left on Ubuntu 16.04, SFML 2.4.1.

YouTube's and other games' fullscreen modes work normally.

Here is [a screenshot of it](http://i.imgur.com/D427jpo.png).
Here is the minimal code:
```cpp
#include <SFML/Graphics.hpp>

int main (int argc, char* argv[]) {
    sf::RenderWindow window(sf::VideoMode(1920, 1080), "Window", sf::Style::Fullscreen);

    while (window.isOpen()) {
        sf::Event event;
        while (window.pollEvent(event)) {
            switch(event.type) {
                case sf::Event::Closed:
                    window.close();
                    break;
            }
        }

        window.clear();
        window.display();
    }

    return 0;
}
```

**Comment by MarioLiebisch** [comment]
Always thought this is the expected behavior on Unity, although I might be wrong. Only using Linux for occasional test builds, no full time user here.

**Comment by naezith** [comment]
YouTube's and other games' fullscreen modes work normally like in Windows though.

**Comment by MarioLiebisch** [comment]
Okay, then this should probably be changed. By someone actually knowing X11 * shudder *. Any volunteers?

**Comment by naezith** [comment]
This is very critical for my game. Performance is very poor at windowed mode so fullscreen is a must. Can anyone help with this?

**Comment by MarioLiebisch** [comment]
Tried and clearly too much X11/XRandR shenanigans going on for my likings. It seems like we'd have to use XRandR 1.2 and newer [the way described here](https://www.reddit.com/r/gamedev/comments/2w8ahe/changing_resolutions_for_fullscreen_in_x11_linux/).

**Comment by naezith** [comment]
I just tested @bloodsword 's commit, it fixes the issue. Please add this.

**Comment by edwrodrig** [comment]
Wow! This is a clear reason to NOT use SFML in my current project

**Comment by danieljpetersen** [comment]
This fixes the issue for me.  Tested on Ubuntu 16.04.5 (Unity) in Virtualbox.
* Using latest version on master (5e10e1f0c9b0a5c095df0f8e9be96914f75297d0), fullscreen takes up the entire monitor as expected.
* I chose a build a few commits before the latest master (be3556d76ab956bab63d96b1d117546e6bf9897e) and was able to replicate the issue, fullscreen did not cover the top bar / side bar.

**Comment by eXpl0it3r** [comment]
Thanks, forgot to close it this after the merge. 🙂
