### ISSUE TITLE
The impl of AudioDevice uses deprecated std::auto_ptr

### ISSUE THREAD

**Issue by YukinoHayakawa** [SFML/SFML#1227]
The auto_ptr is deprecated as of C++11, and the library fails to build with newer standard library such as the one came with VS2017. Please consider replacing them with unique_ptr.

**Comment by minirop** [comment]
They will switch to C++11 with SFML3 (and I suppose they don't want to add `#if __cplusplus >= 2011` everywhere).

**Comment by MarioLiebisch** [comment]
Are you using any custom compiler flags? Current master builds just fine for me using Visual Studio 2017?

**Comment by YukinoHayakawa** [comment]
@MarioLiebisch  My bad. Just found out that my global setting was to use the latest standard (/std:c++latest). Thank you.

**Comment by MarioLiebisch** [comment]
Expected. :) If you want to keep the flag, you can try the `unstable` branch, which has `std::auto_ptr` removed.
