### ISSUE TITLE
Xlib and sfml

### ISSUE THREAD

**Issue by deadgamer1030** [SFML/SFML#1239]
I have found a small issue when using xlib and sfml on linux. The predefined "Status" in xlib interferes with the "enum Status" in SoundSource.hpp. xlib is needed if you want to make a window in a thread. If  xinitthreads() before threading and creating the a new window, you can an error in the console and the program exits.

**Comment by eXpl0it3r** [comment]
> The predefined "Status" in xlib interferes with the "enum Status" in SoundSource.hpp.

The enum is part of the `SoundSource` class and can't really interfere with any type that is just called `Status`. How do you notice the problem? What's the compiler error? What's the example code?

> If xinitthreads() before threading and creating the a new window, you can an error in the console and the program exits.

This is expected and not something SFML can or needs to handle. If you want to use Xlib yourself, you'll have to understand its restrictions and requirements.

For further discussions like these, please use the forum, as mentioned in the [contribution guidelines](https://www.sfml-dev.org/contribute.php).

**Comment by deadgamer1030** [comment]
The problem happens whenever x11/xlib.h is included in one of my  cpp files. 
                                                    Compiler error
SFML/include/SFML/Audio/SoundSource.hpp|50|error: expected identifier before ‘int’|
SFML/include/SFML/Audio/SoundSource.hpp|51|error: expected unqualified-id before ‘{’ token|

If i undefine "Status" before including SFML/Audio.hpp then I do not get this error but his has to be done every time you include x11/xlib.h.
Here is a minimal example Including x11/xlib.h before the SFML/Audio.hpp or SFML/Network.hpp. 

#include<x11/xlib.h>
#include<SFML/Audio.hpp> // or SFML/Network.hpp
//more includes here

int main(){
//normal code

}

I also tested if this happens with the SFML/Network.hpp and i get the same problem.

**Comment by LaurentGomila** [comment]
SFML is not supposed to (and won't) solve problems causes by libraries that define common names as macros in the global scope. The best we can do is to suggest workarounds to users that face these problems.
