### ISSUE TITLE
iOS OpenGL ES version string incorrect formatting

### ISSUE THREAD

**Issue by kingnobody8** [SFML/SFML#1249]
SFML calls glGetVersionString in GLContext.cpp. It assumes the first 3 characters of the string are major.minor. example (on windows PC): "4.5.0 NVIDEA 382.53"

However, on iOS devices this format is not consistent. Here are examples below:
dev iPad Air: "OpenGL ES-CM 1.1 Apple A7 GPU - 95.58"
dev iPhone SE: "OpenGL ES-CM 1.1 Metal - 33"
sim iPhone 5: "OpenGL ES-CM 1.1 APPLE-14.0.15"
sim iPad Pro 9.7in: "OpenGL ES-CM 1.1 APPLE-14.0.15"

this causes some undefined behavior with rendering, because sfml doesn't use the correct opengl es version.

Please implement a fix to take into account iOS formatting. 
I also recommend this be tested for android as well, unfortunately I am not set with android to confirm or deny if there is even a problem for that platform.

**Comment by mantognini** [comment]
> Please implement a fix to take into account iOS formatting.

We solely rely on the community for the iOS implementation. If you can, please follow our [Contribution Guidelines](https://www.sfml-dev.org/contribute.php) to provide a patch (and report future bugs). Thanks.

**Comment by JonnyPtn** [comment]
@kingnobody8 do you still have this issue? What are the symptoms and the reproduction steps?

**Comment by kingnobody8** [comment]
Yes this issue still persists. To see this, just run anything on iOS, and put a breakpoint inside function `void GlContext::initialize(const ContextSettings& requestedSettings)`. You will see that the 'version' is NOT null, but the format is different, so major and minor version are set to incorrect values. Currently sfml doesn't suppport OpenGL ES higher than 1.1, so this should just set the version to 1.1 only if iOS/Android is detected. 
I have implemented a workaround locally. But i haven't put up a pull request for it yet. Here is the temporary fix: Starting at line 584 of GLContext.cpp is this block of "Try the old way". Replace that whole block with the following code. 

    ` // Try the old way
     const GLubyte* version = glGetString(GL_VERSION);
		
    #ifndef SFML_SYSTEM_IOS /*EDIT START*/
        if (version)
        {
            // The beginning of the returned string is "major.minor" (this is standard)
            m_settings.majorVersion = version[0] - '0';
            m_settings.minorVersion = version[2] - '0';
        }
        else
        {
            // Can't get the version number, assume 1.1
            m_settings.majorVersion = 1;
            m_settings.minorVersion = 1;
        }
    #else
		m_settings.majorVersion = 1;
		m_settings.minorVersion = 1;
    #endif /*EDIT FINISH*/`

**Comment by binary1248** [comment]
Just out of curiosity... what does the exact version string look like on iOS?

**Comment by LaurentGomila** [comment]
> Just out of curiosity... what does the exact version string look like on iOS?

Examples are given in the first post:

dev iPad Air: "`OpenGL ES-CM 1.1 Apple A7 GPU - 95.58`"
dev iPhone SE: "`OpenGL ES-CM 1.1 Metal - 33`"
sim iPhone 5: "`OpenGL ES-CM 1.1 APPLE-14.0.15`"
sim iPad Pro 9.7in: "`OpenGL ES-CM 1.1 APPLE-14.0.15`"
```

**Comment by binary1248** [comment]
@kingnobody8 Try out #1390.

**Comment by kingnobody8** [comment]
Looks good. Thank you very much.
