### ISSUE TITLE
Drawing at incorrect position. MinGW64_6.3.0 MSYS2 Windows10

### ISSUE THREAD

**Issue by Somniantis** [SFML/SFML#1250]
Using minimal code with an 800x600 window with default settings.

Drawing a sf::Vertex at position (0, 0) results in the vertex being drawn off screen. 

I must draw the vertex at (8, 30) for it to be positioned at the top left of the viewable area (and at (791, 592) for it to be positioned at the bottom right of the viewable area. 

I've checked the view and viewport values for the window which are all correct.

Also, the mouse position is being correctly reported, so I'm not able to draw anything directly at the mouse position (mouse position correct / drawable position incorrect).

The offset between the desired position and the actual drawn position is not constant across the area of the window, so not sure if there's a workaround that will work for all window sizes...

Minimal code:
https://pastebin.com/s9NfCvwQ

**Comment by eXpl0it3r** [comment]
Please use the forum to discuss issues that you're experiencing. This issue tracker is reserved for confirmed bugs. See also the [contribution guidelines](https://www.sfml-dev.org/contribute.php).

The issue is more likely that the OpenGL rasterizer doesn't display the points. Since a point needs to aligned in the middle of a pixel, you need to add `.5f`, so you'll end up with ```0.5f, 0.5f``` and ```799.5f, 599.5f```. See the example code below that works just fine.

```
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(800, 600), "SFML works!");
    window.setVerticalSyncEnabled(true);

    sf::VertexArray points(sf::Points, 2);
    points[0].position = sf::Vector2f(0.5f, 0.5f);
    points[0].color = sf::Color::Green;
    points[1].position = sf::Vector2f(799.5f, 599.5f);
    points[1].color = sf::Color::Red;


    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
            if (event.type == sf::Event::Closed)
                window.close();

        window.clear();
        window.draw(points);
        window.display();
    }
}
```

**Comment by Somniantis** [comment]
Ok. But your suggested explanation is wrong.

**Comment by eXpl0it3r** [comment]
The example code works fine for me. Since you didn't provide any code, I can only assume what you may or may have done differently/wrong.

**Comment by Somniantis** [comment]
I did supply code. The pastebin link is at the bottom.

**Comment by eXpl0it3r** [comment]
Oh, well you edited that after I've opened the issue. :wink:

Your example code works fine for me (after adding .5f).

![](http://i.imgur.com/gvqvxkD.png)

**Comment by Somniantis** [comment]
That EXACT same code draws the pixel at (1, 1) on my system...

**Comment by Somniantis** [comment]
Sorry about the late edits :P

**Comment by Somniantis** [comment]
I also downloaded and built the main branch to be sure that's what I had.

**Comment by eXpl0it3r** [comment]
Using SFML inside MSYS2 or Cygwin is not supported by SFML, if you try to build SFML from within MSYS2 you'll get error messages and just using binaries build with native MinGW-w64 doesn't mix with MSYS2 and you may run into weird issues as you're experiencing right now.

**Comment by Somniantis** [comment]
Ah, okay. I built it using the MSYS2 mingw64 compiler, but did it using cmake OUTSIDE of MSYS2 and just pointed to the compiler, linker, make program, etc... Knew I was probably doing something wonky. Thank you. Sorry for wasting your time.
