### ISSUE TITLE
More audio options? (feature)

### ISSUE THREAD

**Issue by CosminPerRam** [SFML/SFML#1252]
Can we have ONLY pitch command? (One which is included now has with it a speed changer, idk why)
Can we have ONLY speed command?
Support for mp3?
Also, how i can know when an audio/music/sound reached 0:07 seconds?
Those are just requested features from me! (I know that programming is hard, just wanted to wrote this thread, maybe we can have them in an future release!) :D

**Comment by eXpl0it3r** [comment]
Please follow the [Contribution Guidelines](https://www.sfml-dev.org/contribute.php#requesting-features) and use the [SFML forum](https://en.sfml-dev.org/forums/index.php?board=2.0) to request features and before you do, make sure to use the search function.

Use the help section on the forum to ask questions.
