### ISSUE TITLE
Renaming "OSX" directory to "MacOS"

### ISSUE THREAD

**Issue by KRMisha** [SFML/SFML#1254]
Starting with macOS 10.12 (Sierra), released in September of 2016, Mac OS X was officially renamed to "macOS," with all mentions of "Mac OS X" or "OS X" switching to the new name. In order to avoid using a now obsolete term for the operating system, I recommend to rename the Git directory for macOS source files from "OSX" to "MacOS" (or "macOS" or even simply "Mac") for future-proof consistency.

**Comment by mantognini** [comment]
I'm not sure this is worth it. Besides, we still support older versions of Mac OS X so... Anyway, thanks for your suggestion.
