### ISSUE TITLE
Reported image size is incorrect.

### ISSUE THREAD

**Issue by Cryru** [SFML/SFML#1256]
Hey, I'm using SFML.Net 2.2 and I'm having trouble with the Image class. I'm trying to create an image and manipulate its pixels individually.

I declare the image like so:

`sfmlImage = new SFML.Graphics.Image(960, 540);`

and probing for the size returns:

```
{[Vector2u] X(960) Y(540)}
image.Pixels.Length == 2073600
```

however when trying to get or set (using getPixel/setPixel) the pixel at coordinate 760x540
I receive a memory access violation. 

Any ideas what I'm doing wrong?

**Comment by mantognini** [comment]
Wrong repo. ;-)

Please read [here](https://www.sfml-dev.org/contribute.php#reporting-bugs) how to get help.

**Comment by eXpl0it3r** [comment]
`image.Pixels` returns the array of pixels, `Length` on an array returns the size of the array and not the size as in width x height. For that the image class has the `Size` function: `image.Size`.

**Comment by LaurentGomila** [comment]
If height is 540 then the last valid Y position is 539, 540 is already out of bounds.

**Comment by Cryru** [comment]
@mantognini Thanks
@eXpl0it3r 
Sorry for posting in the wrong place. You can see I've posted the result of image.Size as well.
@LaurentGomila 
I didn't realize that setting the height to 540 means that. Thanks!

Problem solved, thanks everyone, my mistake :)
