### ISSUE TITLE
Please consider to compile static libraries with -fPIC on Linux

### ISSUE THREAD

**Issue by realead** [SFML/SFML#1257]
Static libraries (2.4.2) cannot be used for linking of a shared library on x86-64 Linux, the linker returns the following error:

> relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC SFML/lib/libsfml-system-s.a: error adding symbols: Bad value

**Comment by eXpl0it3r** [comment]
Do you mean we should add this to CMake? Or do you just mean for the builds on the website? Or the builds that come with your package manager?

**Comment by realead** [comment]
I encountered this problems with static libraries downloaded from the homepage as I tried to use them for linking of a shared library. But I think if you are going change that, it only makes sense if you change it everywhere.

Here is a small reproducer, I hope it explains what I mean:

    //error.cpp
    #include <SFML/System.hpp>
    void log_error(){
       sf::err()<<"Error!";
    }

and now:

    g++ -c error.cpp -o error.o -fPIC -ISFML-2.4.2/include
    g++ error.o -shared -LSFML-2.4.2/lib -lsfml-system-s -o my_err.so

leads to:

>  /usr/bin/ld: SFML-2.4.2/lib/libsfml-system-s.a(Err.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
> SFML-2.4.2/lib/libsfml-system-s.a: error adding symbols: Bad value
> collect2: error: ld returned 1 exit status

I'm not sure this is a feature request and consider it to be a bug of the build-configuration: I think the option `-fPIC` should be used, so the built SFML-libraries can be used for building shared libraries out of the box. But it is also possible, that I'm wrong - I don't have much experience with this kind of things.

**Comment by MarioLiebisch** [comment]
Never noticed this not set. Can't test it right now, but does it compile if you omit `-fPIC` for our own code? Besides that I'd say it should be added by default. Can't think of any reason not to use it right now.

**Comment by jcowgill** [comment]
Traditionally, static libraries are compiled without `-fPIC` on Linux because it usually doesn't have much use and on some architectures there is a small performance penalty for using it. You only need it if you're compiling a shared library using it, whereas I expect most people want to compile their entire executable statically (which does not need the flag).

**Comment by realead** [comment]
@MarioLiebisch To my knowledge, `-fPIC` is obligatory for shared libraries on Linux x86-64. So if I omit  `-fPIC` for the cpp, the linker will complain already about the first object-file.

**Comment by eXpl0it3r** [comment]
As pointed out by @jcowgill, static libraries on Linux are commonly compiled without `-fPIC`, as such SFML will follow this semi-standard.

Additionally the Linux binaries provided as download on the website are not really the recommended way to use SFML under Linux. Either use the SFML package provided by your package manager or if you need some special version or changes (like having the SFML libraries built with `-fPIC`), build SFML from source yourself.

I'm going to close this issue. If you think this is too important to not be followed up further, please make a case for it on the SFML forum.
