### ISSUE TITLE
Embedded Linux How To Use It To Deal With it??

### ISSUE THREAD

**Issue by lishaohsuai** [SFML/SFML#1262]
I want to move it to OpenWRT to Create more Events ,Then make it to be a unit to deal with message,like a key. Can you tell me How to deal with it ??

**Comment by MarioLiebisch** [comment]
Are you sure you picked the correct tracker? If you're having some question or issue, create a thread on the [SFML forums](https://en.sfml-dev.org/forums/), but also make sure to include enough details and code so people can actually understand what you want.
