### ISSUE TITLE
iOS build fails because of import in ClipboardImpl.mm

### ISSUE THREAD

**Issue by tlein** [SFML/SFML#1271]
When building master for iOS I get the following error: 

```

SFML/src/SFML/Window/iOS/ClipboardImpl.mm:30:1: error: use of '@import' when C++ modules are disabled, consider using
      fmodules and fcxx-modules
@import UIKit
^
1 error generated.
```

This can be fixed if `#import <UIKit/UIKit.h>` was used instead of the `@import UIKit` line.

**Comment by eXpl0it3r** [comment]
Fixed with #1272 in a2f448ab4cc29bffb9c91d7ee55c83f5adeaa2c8
