### ISSUE TITLE
Update Doxygen CSS

### ISSUE THREAD

**Issue by pixelherodev** [SFML/SFML#1273]
![image](https://user-images.githubusercontent.com/10342579/30004796-bcdec752-90a3-11e7-8746-63b9f27b2de8.png) That shows up at the top of every page of the local documentation, both with package libsfml-doc, and the copy I built myself.

![image](https://user-images.githubusercontent.com/10342579/30004817-fb598d14-90a3-11e7-9051-b117744b4390.png)
If you look at the URL bars, you can tell one is from the Debian documentation browser (aka libsfml-doc package), and on the local copy.

I cleared the JS console and refreshed the page:

```
Loading failed for the <script> with source “http://localhost/cgi-bin/dwww/usr/share/doc/libsfml-doc/html/dynsections.js”.  modules.html:9
jQuery.Deferred exception: $(...).smartmenus is not a function initMenu@http://localhost/cgi-bin/dwww/usr/share/doc/libsfml-doc/html/menu.js:25:3
@http://localhost/cgi-bin/dwww/usr/share/doc/libsfml-doc/html/modules.html:23:3
mightThrow@http://localhost/cgi-bin/dwww/usr/share/doc/libsfml-doc/html/jquery.js:3570:21
resolve/</process<@http://localhost/cgi-bin/dwww/usr/share/doc/libsfml-doc/html/jquery.js:3638:12
 undefined  jquery.js:3846
TypeError: $(...).smartmenus is not a function  menu.js:25:3
```
I checked the folder and sure enough there is no file `dynsections.js`
I copied the file from https://www.sfml-dev.org/documentation/2.4.2/dynsections.js and the error messages shrank to
```
jQuery.Deferred exception: $(...).smartmenus is not a function initMenu@http://localhost/cgi-bin/dwww/usr/share/doc/libsfml-doc/html/menu.js:25:3
@http://localhost/cgi-bin/dwww/usr/share/doc/libsfml-doc/html/modules.html:23:3
mightThrow@http://localhost/cgi-bin/dwww/usr/share/doc/libsfml-doc/html/jquery.js:3570:21
resolve/</process<@http://localhost/cgi-bin/dwww/usr/share/doc/libsfml-doc/html/jquery.js:3638:12
 undefined  jquery.js:3846
TypeError: $(...).smartmenus is not a function  menu.js:25:3
```
And the page didn't change.

**Comment by np511** [comment]
I just checked the console for the official site, and there was nothing there.

**Comment by eXpl0it3r** [comment]
Doxygen changed their styling, thus our custom CSS doesn't work anymore with docs built with newer Doxygen versions. Either use an older Doxygen version or use the default styling.

**Comment by np511** [comment]
What's the latest version of Doxygen that I can use w/o this being a problem?

**Comment by mantognini** [comment]
1.8.8 is probably the safest bet.

**Comment by np511** [comment]
Thanks.
Also, is the CSS going to be updated to work with the newer Doxygen versions?

**Comment by mantognini** [comment]
Ideally, yes, we'd like to do that. Contributions to https://github.com/SFML/SFML-Website are welcomed. ;-)

**Comment by pixelherodev** [comment]
I don't really know CSS.

**Comment by pixelherodev** [comment]
Also, can confirm that 1.8.8 works - and that 1.8.13 does not.

**Comment by mantognini** [comment]
Superseded by #1273.
