### ISSUE TITLE
Graphics: Set anti-aliasing at RenderTexture

### ISSUE THREAD

**Issue by hydroper** [SFML/SFML#1274]
It should be possible to control the anti-aliasing like on `RenderWindow`. Smooth changed in nothing.

My reason: I simply need to cache a `Drawable`. On `RenderWindow` I'm able to explain the anti-aliasing amount with `ContextSettings`. [Is it possible to draw a Drawable and get a bitmap from it?](https://stackoverflow.com/q/46037260).

**Comment by 18kaioken** [comment]
@eXpl0it3r @LaurentGomila Yea, could you guys look this?

**Comment by LaurentGomila** [comment]
I'd rather ask @binary1248 his opinion about it.

**Comment by eXpl0it3r** [comment]
https://en.sfml-dev.org/forums/index.php?topic=22147.msg156438#msg156438

**Comment by JonnyPtn** [comment]
I'll throw my hat in as someone who's wanted this for a while and would make use of it - I also know of others who would appreciate it.

If the answer is still "It's too much effort", then I'm happy to put effort in to work on an implementation

**Comment by binary1248** [comment]
The TL;DR of my posts is: you don't have to supersample your intermediate surfaces if you make sure that aliasing can't happen when rendering to them. If you supersample both intermediate surfaces and final framebuffer you will end up losing more image quality than if you only did it in the final render pass.

This is like video editing: You don't compress your source video and edit the compressed clips into a final output. You work at the native resolution in some raw uncompressed format and only compress right before publishing it.

**Comment by hydroper** [comment]
@binary1248

I did something like that with the green circle example. I drew the circle on a _render-texture_ without anti-aliasing settings, then did get the _render-texture_'s texture after drawn and drew it on a _render-window_. No anti-aliasing did happen at the end...

In order to enable anti-aliasing samples, someone suggested me to use _context-settings_ on a _context_, making sure the _render-texture_ is the active context. Though I couldn't compile my test code because the `Context` constructor is deleted. :/

**Comment by naezith** [comment]
I'd also love to have this because my whole game is on a RenderTexture, I draw that to RenderWindow.

**Comment by binary1248** [comment]
@naezith Are you applying some full screen post-processing or is there another reason that you need to do this?

**Comment by naezith** [comment]
@binary1248 Yes, vignette effect shader.

**Comment by binary1248** [comment]
Try #1285 branch [feature/rendertexture_stencil_multisample](https://github.com/SFML/SFML/tree/feature/rendertexture_stencil_multisample).

**Comment by naezith** [comment]
@binary1248 Your test works nicely.

I tried it in my game, it's not good for me.

It makes the **tiles bleed** as you see in this GIF:
![aa8](https://user-images.githubusercontent.com/6732486/30522665-7fc3d2c4-9bdc-11e7-8cb9-e149751c3511.gif)

Also I expected my water shader to look smoother but it does not help on that. Can you explain why?

**Without AA**
![aa0](https://user-images.githubusercontent.com/6732486/30522656-6969fd32-9bdc-11e7-825c-e86f13aaa64e.png)

**With AA**
![aa8](https://user-images.githubusercontent.com/6732486/30522660-6f768e16-9bdc-11e7-8a59-cd3548ba60a0.png)

**Comment by binary1248** [comment]
@naezith If with "bleed" you mean the seams that appear in between tiles, that is a side-effect of drawing them on individual polygons with multi-sampling enabled. OpenGL is working as intended... if the tiles are supposed to align with each other they need to share vertices among other things so the rasterizer can resolve the samples properly based on the correct data.

As for your water shaders... you need to describe a bit more what I am supposed to be seeing... because I don't notice anything out of the ordinary...

**Comment by naezith** [comment]
@binary1248 Yeah everything seems to work as it is supposed to work as you said. Just not a good option for me unlike I thought. 

About water shader, Those bright white lines are normally rectangles drawn first. Then that area is passed to a frag shader. Then water bends and twists the background as you see there. The end result is pixelated, I expected AA to draw them smoother but I guess AA works only for the polygon's edge pixels.

**Comment by hydroper** [comment]
@naezith Man, that's nice!

**Comment by eXpl0it3r** [comment]
Implemented with #1285
