### ISSUE TITLE
Newest version in the apt repository is 2.3?

### ISSUE THREAD

**Issue by j4cobgarby** [SFML/SFML#1277]
I don't _think_ this has already been posted here, but correct me if I'm wrong.

Is there any good reason why to install any version later than 2.3, you need to manually install it?
I've tried - on two different Ubuntu systems - to install SFML like this:

```
sudo apt-get install libsfml-dev
```

And while of course it _worked_, I would rather like to use the newest version (2.4.2). I'm currently in the process of installing SFML by means of copying the header files and stuff to my `/usr/local/...`, but it's a nuisance to do this. Especially having the need to install SFML on two different systems.

**Comment by eXpl0it3r** [comment]
This is the issue tracker for confirmed issues, for general questions, please use the official forums.

Package managers aren't updated by the SFML Team but by package maintainers. The managers also have their own rules on when packages get updated. Stable Debian and Ubuntu packages are updated quite rarely, thus they will fall behind current versions. Just checkout the version of your compiler or CMake and you'll notice they're all behind the latest versions.

There are other Linux distros like Arch that are built more around getting you the latest and greatest. Or you can switch to "unstable" branches of Ubuntu which also runs more up to date packages.

**Comment by j4cobgarby** [comment]
Okay, thanks. I'm going to install Arch Linux as soon as I get home, it turns out it does have the absolute newest version! :smile:
