### ISSUE TITLE
Errors and crashes reading certain wav formats

### ISSUE THREAD

**Issue by andyorange** [SFML/SFML#1283]
I tried reading a wav file created by Audacity. Any 32 bit float file is rejected by sfml::soundBuffer::loadFromFile, any 16 bit integer wav file even crashes in SoundBuffer::initialize(...). Other tools (MediaPlayer, VLC, Cubase, ...) read both formats without any issues.
Both wav files are attached, clap_long1.wav is the 32 bit float file, clap_long2.wav the 16 bit one.

[wavFiles.zip](https://github.com/SFML/SFML/files/1298817/wavFiles.zip)

**Comment by MarioLiebisch** [comment]
So far SFML is only able to read 16 bit integer files, so 32 bit being rejected is intentional. Other formats shouldn't crash though.

**Comment by LaurentGomila** [comment]
SFML handles 8-, 16-, 24- and 32-bit integer samples. Float is rejected (anything else than "PCM" as internal format is rejected).

16-bit integer crashing is definitely a bug.

**Comment by andyorange** [comment]
Just to complete this report, here another file created with Nero Wave Editor, which also results in a crash, same method as above. Best regards,
Andy
[clap_long3.zip](https://github.com/SFML/SFML/files/1299152/clap_long3.zip)

**Comment by andyorange** [comment]
Unless this is fixed, a workaround for those facing the same crash issue:
`
	auto loadOK = sfile.openFromFile(FilenameOfWavFileHere);
	if ( !(loadOK && (sfile.getSampleCount() > 0) && (sfile.getDuration().asMicroseconds() > 0) && (sfile.getSampleRate() > 0)) )
	{
		// handle error
	}`

**Comment by LaurentGomila** [comment]
So what's wrong in the sound parameters? How did you come to this workaround?

**Comment by andyorange** [comment]
I debugged when it crashed. The values I test (samplerate, duration, samplecount) are the values that SoundBuffer::initialize() reads and the crash happens right afterwards.

**Comment by LaurentGomila** [comment]
But why did you write this specific test? Is one of these values zero? Why does SoundBuffer::initialize() crash with them?

**Comment by andyorange** [comment]
Yep, the sampleCount for instance was zero with the files attached (xxx2.wav and xxx3.wav). Why the initialized() crashes is not really clear to me yet, esp. considering that the resize call seems to evoke the crash, which should not happen. I will have time to investigate further tomorrow and hope I can bring some more insight into this.

**Comment by andyorange** [comment]
As this seemed rather stranged I created a completely clean project just reading those wav files. It showed that sfml did actually NOT crash but that the problem was, once again, a sample project sfmlSoundFileReaderMP3 which was responsible for the crash. Considering this, please accept my apologies for not testing this well enough before sending a report! I guess you can invalidate this now.
