### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by galvesribeiro** [SFML/SFML#1288]
Hello,

I have an ARMv6 device that we ported Mono .Net to run in it and we are looking for a UI library to run in it. We have both Cairo and Skia libraries running on it on top of Linux Framebuffer both with proper bindings for C#.

So, Does SFML support build for ARM? In case of yes, can someone point me on how to build and integrate SFML for my use case?

Thank yoU!

**Comment by LaurentGomila** [comment]
Please use the forum for help requests and questions about the project. This tracker is for confirmed bugs and features.
