### ISSUE TITLE
pySFML bindings no longer available through PyPi

### ISSUE THREAD

**Issue by wtty-fool** [SFML/SFML#1289]
[This](https://www.sfml-dev.org/download/bindings.php) website contains a link to SFML's Python bindings. However pySFML is no longer available at PyPi. Hence `pip install pySFML` does not work anymore. Is there any workaround? Will pySFML return to PyPi?

**Comment by eXpl0it3r** [comment]
@Sonkun hasn't been active with SFML's development as such I'm not sure what his status with pySFML is or why it was removed from PyPi.

This issue tracker here is for confirmed issues with SFML. Check out the [pySFML official repository](https://github.com/Sonkun/python-sfml) to potentially get more infos.
