### ISSUE TITLE
Support for extensible format PCM wave files

### ISSUE THREAD

**Issue by tgnottingham** [SFML/SFML#1295]
Since removing the libsndfile dependency, SFML only supports integer-encoded PCM wave files with the PCM format tag. However, there are identically encoded wave files that use the "extensible" tag instead. Since some applications use this extensible tag when saving PCM waves, it would be nice to support the format.

With an extensible format file, the example below outputs "Failed to open WAV sound file (invalid or unsupported file)" (assuming the file is named "tone_24.wav" and it's in your working directory).

```
#include <SFML/Audio.hpp>
#include <SFML/System.hpp>

int main() {
    sf::SoundBuffer sb; 
    sb.loadFromFile("tone_24.wav");

    sf::Sound s(sb);
    s.play();

    sf::sleep(sf::seconds(2.5));
}
```

I'll post a pull request shortly to help you see if you want to include support.

[Forum Thread](https://en.sfml-dev.org/forums/index.php?topic=22559.0)
[Wave File Specifications](http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/WAVE.html)
[Example of Unsupported File](https://www.dropbox.com/s/4j48bvpa35daowp/tone_24.wav?dl=1)

**Comment by eXpl0it3r** [comment]
Merged in fc54dba3d7ff15d99d9e86fea7d5cb593dd86106
