### ISSUE TITLE
Missing JPEG dependency line on FindSFML.cmake

### ISSUE THREAD

**Issue by JoaoBaptMG** [SFML/SFML#1300]
This new `FindSFML.cmake` CMake module fails to search for and define the dependency for `libjpeg`. It seems the exact line that does this is (as defined on a previous version on the module):
```
find_sfml_dependency(JPEG_LIBRARY "libjpeg" jpeg)
```
This has caused a lot of `undefined reference` errors when I tried to build my game today. Seems to be a mis-deletion?

**Comment by eXpl0it3r** [comment]
libjpeg was removed as dependency for SFML (see #1279). As such you either need to use the older FindSFML.cmake or rebuild SFML.

**Comment by JoaoBaptMG** [comment]
The dependency seems to not be “properly” removed then, because it still generated undefined references on the final link phase on my project... and I built it right from 2.4.2 source right after downloading it.

**Comment by JoaoBaptMG** [comment]
I just had a look on the source of SFML... I’ll find out if it’s something with my code, because it’s strange.

**Comment by mantognini** [comment]
Just in case, the removal was done *after* the release of 2.4.2. Try getting the latest version from git master instead.

**Comment by LaurentGomila** [comment]
Also, make sure to "make clean" first.

**Comment by JoaoBaptMG** [comment]
Thanks. Anyway, I added that line from the old module and I’m using it on my project from version 2.4.2.
