### ISSUE TITLE
freetype header search path not found for Mono.framework

### ISSUE THREAD

**Issue by crookedbard** [SFML/SFML#1302]
I had to include this header search path:
/Users/[username]/Documents/Libraries/SFML/extlibs/headers
for **libsfml-graphics-s-d.a**
and also inside headers folder I copied **freetype2** folder and then renamed it to **freetype**

**Comment by eXpl0it3r** [comment]
Please provide enough information that your issue can actually be understood by anyone.

What's your platform/OS? What SFML version did you use?

What was your intention/goal? What did you expect to happen? What actually happened?

What were your steps involved?

**Comment by eXpl0it3r** [comment]
When more information is provided this may be reopened again.
