### ISSUE TITLE
Strange bug on Visual studio 2017 with Texture::loadFromFile

### ISSUE THREAD

**Issue by Milerius** [SFML/SFML#1303]
Hello, i'm working on an C++ engine using SFML with modern C++, its works fine on OSX/Linux, but i have a strange bug on windows : 

![image](https://user-images.githubusercontent.com/21139416/31363265-892fb214-ad5d-11e7-852e-13e042c3ef48.png)

as you can see here, i dont have any problem, then it call my resourceLoader : 

![image](https://user-images.githubusercontent.com/21139416/31363292-c6b7cd56-ad5d-11e7-977e-5857799c9923.png)

then i forward my argument to the SFML function loadFromFile : 
![image](https://user-images.githubusercontent.com/21139416/31363315-f78abbe6-ad5d-11e7-8dae-e824ab19c8c4.png)

![image](https://user-images.githubusercontent.com/21139416/31363338-08b73e80-ad5e-11e7-9549-728e766a40e6.png)

as you can see a 140701072898327 sized string with weird char, and as i say at the beginning, it works perfectly fine on Linux/OSX. I tried a const char *, a std::string, a std::string_view , by value, by reference, by rvalue reference, nothing works and my string is always resized with weird char

I'm using MSVC 19.11.25508.2 with SFML 2.4.2 on windows, gcc 7.2 on linux, and clang 5.0 on osx.

**Comment by LaurentGomila** [comment]
It seems like you're using release libraries in debug mode. The "getting started" tutorials mentions that you shouldn't do that.

**Comment by Milerius** [comment]
anyway the problem was on my package manager vcpkg , which install release sfml in debug mode and vice versa , so i just manually installed SFML and this solved my problem :)
