### ISSUE TITLE
First argument of alcCaptureOpenDevice

### ISSUE THREAD

**Issue by SoczuGGS** [SFML/SFML#1304]
https://github.com/SFML/SFML/blob/898c2350f7507356b7cac6fb9e83b0507761388b/src/SFML/Audio/SoundRecorder.cpp#L191

I think that should be m_deviceName.c_str()

**Comment by mantognini** [comment]
It looks like you're right. Could you please create a PR for that? Thanks.

**Comment by Foaly** [comment]
Hmm indeed! This looks like an oversight I made when implementing b1ad9dceacb10afb9618cce011ca3dfd061a3f18...
@SoczuGGS Would you like to fix it or should I send a PR?

**Comment by mantognini** [comment]
Superseded by #1305.
