### ISSUE TITLE
Example 'window' does not create an binary with the executable flag on Linux

### ISSUE THREAD

**Issue by Turbine1991** [SFML/SFML#1307]
After compiling the 'Examples' on Linux, one of the examples 'window' does not set the binary flag.

**Comment by eXpl0it3r** [comment]
Please keep in mind that [we like to keep this tracker for confirmed issues](https://www.sfml-dev.org/contribute.php) and are happy to help with situational issues on the [Help subforum](https://en.sfml-dev.org/forums/index.php#c3).
