### ISSUE TITLE
Gloabl keyboard hook

### ISSUE THREAD

**Issue by Lewiskong** [SFML/SFML#1314]
Hello , i need to hook keyboard events when the window is not focused.
I didn't found anything pertinent to this . 
Is there anyway to realize it in SFML?

**Comment by eXpl0it3r** [comment]
Please use the [forum](https://en.sfml-dev.org/forums/) for general questions and/or feature requests as mentioned in the [Contribution Guidelines](https://www.sfml-dev.org/contribute.php).
