### ISSUE TITLE
Way to sf::Texture::bind() to openGL with GL_TEXTURE_RECTANGLE instead of GL_TEXTURE_2D

### ISSUE THREAD

**Issue by N00byEdge** [SFML/SFML#1316]
So that integer coordinates can be used in the openGL context. Maybe even let the user provide the mode itself, with `GL_TEXTURE_2D` as the default? The line
https://github.com/SFML/SFML/blob/master/src/SFML/Graphics/Texture.cpp#L728
currently binds with `GL_TEXTURE_2D`  and that only. Would you like that to be changed? I could make a tested pull request, but not sure if you are interested.

`Texture::bind()` is only ever called from two places internally, `RenderTarget::applyTexture` where it's using the `Texture::Pixels` mode and `Shader::bindTextures()` with the default argument, `Texture::Normalized`.

**Comment by eXpl0it3r** [comment]
Please use [the forum](https://en.sfml-dev.org/forums/index.php?board=2.0) for feature requests as outlined in the [contribution guidelines](https://www.sfml-dev.org/contribute.php).
