### ISSUE TITLE
sf::Text crashes on destruction when _GLIBCXX_DEBUG is defined

### ISSUE THREAD

**Issue by jesyspa** [SFML/SFML#1318]
On x86_64 Arch Linux with GCC 7.2.0, the destructor of `sf::Text` causes a segmentation fault when `_GLIBCXX_DEBUG` is defined.  The following code

    #include <SFML/Graphics>
    int main() {
        sf::Text text;
    }

compiled with

    g++ main.cpp -D_GLIBCXX_DEBUG -lsfml-graphics

should reproduce the error; I've attached the valgrind output.  This was tested with SFML 2.4.2 from the repos, but I've also checked with SFML built from the latest source and the result is the same.
[valgrind.log](https://github.com/SFML/SFML/files/1472154/valgrind.log)

**Comment by LaurentGomila** [comment]
For consistent results, maybe you have to compile SFML with `_GLIBCXX_DEBUG` too.

**Comment by jesyspa** [comment]
That's a good point—I seem to be getting a crash even when SFML is compiled using it (by passing `-DCMAKE_CXX_FLAGS=-D_GLIBCXX_DEBUG` to cmake), but you're right that I shouldn't expect this to work, so I don't think it's really an issue.
