### ISSUE TITLE
PTITLEBARINFO is not declared error during compilation using G++ 6.3.0 on MinGW on SFML 2.4.2 and lower versions too

### ISSUE THREAD

**Issue by Dawid90dd** [SFML/SFML#1322]
Hello. I've encountered a very annoying error after try of compilation using MinGW with G++ version 6.3.0

![gimp](https://user-images.githubusercontent.com/6539087/33186935-143b5f7c-d08e-11e7-9085-236d023f5031.png)

I'm building using cmake command:
cmake -G"Unix Makefiles"

And after that: 
make -j2

Can you help me? I'm trying to write my own library for game development which uses newest SFML 2.4.2, and i'm encountering this error.

I've also found this topic:
https://stackoverflow.com/questions/46396148/compiling-sfml-with-mingw-has-ptitlebarinfo-not-declared

But it doesn't help me much...

Edit Postscriptum:
I'm also compiling the same library but on linux (ubuntu) but it doesn't throw me any errors. (as i understand this is windows related problem and more peculiarly winapi?)

Also, i know that it says SFML 2.3.2 but i've tried SFML 2.4.1 and SFML 2.4.2, it throws me the same error.

**Comment by eXpl0it3r** [comment]
Please use the [Help section on the forum](https://en.sfml-dev.org/forums/index.php#c3) to get help with your compilation issue. This tracker is, as mentioned in the [contribution guidelines](https://www.sfml-dev.org/contribute.php), for confirmed issues only.

> I'm building using cmake command:
> cmake -G"Unix Makefiles"

Unless you're also running it within MSYS or Cygwin, the correct generator is `MinGW Makefiles`.

**Comment by Dawid90dd** [comment]
Ok. I will use the forum. Apolagies for inappropriate using of SFML github issues
