### ISSUE TITLE
Cannot work in Release mode in Visual Studio

### ISSUE THREAD

**Issue by qinyt** [SFML/SFML#1328]
sf::Image works fine in Debug mode. However, it generates access inviolation in release mode. any solutions?

**Comment by LaurentGomila** [comment]
This is most likely not a bug in SFML, but an issue in your environment, or in the way you configured your project. Please post on the forum to get more help.

**Comment by qinyt** [comment]
Based on my limited understanding of how C++ works, I mistook the debug version xxx-d-2.dll for release version. Sorry for the trouble or any misleading information it entails whatsoever
