### ISSUE TITLE
Moving analog stick very slowly does not trigger sf::Event::JoystickMoved

### ISSUE THREAD

**Issue by naezith** [SFML/SFML#1329]
When I move the analog stick very slowly, sf::Event::JoystickMoved event does not trigger. However it's fine if I move it fast.

I tried this with Dualshock 4 controller and Logitech F310 which has two modes, X (XInput) and D (Dualshock?), I tried both of them and it's same on those too.

I tried this with @binary1248 's new DirectInput patch (https://github.com/SFML/SFML/pull/1326) and without it. Same problem exists.

One player also tried the same and approves.

On the other hand, Windows Control Panel -> Set up USB Game controllers -> Properties does not have the same issue, maybe it's polling the current value instead of working with events.

I already implemented XInput for my game. If I use an XInput emulator for these gamepads, Game's XInput library works fine. 

I am incredibly busy these days so I can't provide a code snippet but it's just the most basic pollEvent loop.

Windows 10
Dualshock 4
Logitech F310
g++ (x86_64-posix-seh-rev1, Built by MinGW-W64 project) 7.2.0

**Comment by MarioLiebisch** [comment]
This is most likely not directly a bug, but the joystick threshold instead. Check out [`sf::Window::setJoystickThreshold()`](https://www.sfml-dev.org/documentation/2.4.2/classsf_1_1Window.php#aa45b8f54e29a6f59f1fc7ee66b2fab68).

It will basically remove tiny movement, but should most likely work in a different way (i.e. only allowing the axes to center properly).

**Comment by naezith** [comment]
Yes you are correct, sorry about it. @MarioLiebisch

**Comment by MarioLiebisch** [comment]
Well, you're actually right about this being a bug I think. It should prevent tiny movements, but if you've moved the axis far enough, it should be considered a movement.

**Comment by MarioLiebisch** [comment]
Just checked the source and we do indeed compare the previous state with the current one rather than with the threshold itself. So we basically filter out tiny relative movement rather than tiny absolute movement.

**Comment by LaurentGomila** [comment]
... and that's on purpose, to avoid spamming the event queue; this is *not* supposed to act as a dead zone.

**Comment by MarioLiebisch** [comment]
But even then it shouldn't drop movement below the threshold. It should just add it up to emit an event once the total movement since the last event was significant enough, correct?

For example, moving the axis by – no idea – 0.01 between measurements shouldn't trigger the event, but after 100 steps it should emit a movement by 1, because all those tiny moves happened.

**Comment by naezith** [comment]
"The joystick threshold is the value below which no JoystickMoved event will be generated."

This means if you put 10, and position value came as 5, it will be ignored. but if you hop from 10 to 12 then you will get 12.

But it works like if you jump from 10 to 12, you don't get the event because next event is at 20 (from 10 if you pull so fast).

I was using the value 6 to solve someone's event spamming gamepad so it was helpful but it broke the other thing.

**Comment by LaurentGomila** [comment]
Yes, I agree that we can certainly improve this behaviour.

**Comment by MarioLiebisch** [comment]
@naezith The branch bugfix/joystick_threshold should fix this issue, without you having to lower the threshold value.

**Comment by naezith** [comment]
I am fine with getting inputs in 0.01 precision. I only want to block the events when gamepad is not doing anything. Like a deadzone.

**Comment by MarioLiebisch** [comment]
That'd be something for you to add/implement, basically adding up the movement event's value and comparing the absolute value to 0.

Or just set a higher threshold: The full axis movement is -100 to +100, so if you set it to 5, you won't get movement unless the player moves the stick by at least 5% (with the bugfix applied).

**Comment by eXpl0it3r** [comment]
Fixed in #1331
