### ISSUE TITLE
Cannot handle keyboard input while using Chinese IME

### ISSUE THREAD

**Issue by TianxinTse** [SFML/SFML#1332]
Hi, bros. I'm writing some code to handle user input. When the inputs are Enter, Escape or Numbers, the keyboard event system works well. But when I press letter keys like A, B, C, or D, the program does not respond. I found that this problem was caused by the IME that I installed. And it's a Chinese IME software. If I press Shift to turn the mode of IME into English mode, the keyboard event system also worked. But when the mode is Chinese mode (Pinyin), the event system does not respond to the user inputs. Is there any solution for this problem? Because I don't want the users of my program to turn their IME into English mode every time they run my program.

**Comment by eXpl0it3r** [comment]
IME "support" and what needs to be handled how is a longer discussion and we already had discussed a few points. Please refer to the forum thread: https://en.sfml-dev.org/forums/index.php?topic=22659.0

We like to keep feature discussions on the forum and use the issue tracker for confirmed issues only.
