### ISSUE TITLE
VertexArray not drawn on Android

### ISSUE THREAD

**Issue by DennisSc** [SFML/SFML#1336]
Hello.

I'm trying to port my finished SFML game application from win32 to android, and am having major trouble with drawing a textured quad vertex array. Banging head against wall for three days now. Can anyone try if he can reproduce this issue please?

I've got the sfml sources to compile smoothly for ARMEABIv7a (after just a couple of hours), and now I can compile and run my game on a test device (android 5.1, and old one). Results are so-so: sound plays, and UI/HUD is visible... but thats all. No gfx whatsoever, apart from the HUD...

Now on windows, all is fine... on android, everything vertexarray-quad-related is not drawn properly.

No map, no player character, no animations can be seen in the newly created "android version" of my game.

I can move around in the game world though, so physics are working apparently, so the code portation to armeabi was somehow successful. :) "Just" graphics are not working... The animations and character sprites were originally coded using the animatedsprite example from the sfml wiki (which didn't work on android too, but i found a workaround), and the map is generated from a tileset as a vertex array, which is drawn to a rendertexture, which is then scrolled/transformed and drawn to the window as needed.

I've got it narrowed down to the case where I can draw a tileset from a quad vertex array, which is displayed on windows, but not when compiling for android.

Repro code: (working on windows, "not working" on android 5.1 - compiles and runs fine but shows nothing)

```
#include <SFML/Graphics.hpp>
#include <iostream>



int main(int argc, char* argv[]) {

	sf::RenderWindow window(sf::VideoMode(1024, 768), "Repro");

	const int level[] =
	{
		0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
		0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0,
		1, 1, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3, 3,
		0, 1, 0, 0, 2, 0, 3, 3, 3, 0, 1, 1, 1, 0, 0, 0,
		0, 1, 1, 0, 3, 3, 3, 0, 0, 0, 1, 1, 1, 2, 0, 0,
		0, 0, 1, 0, 3, 0, 2, 2, 0, 0, 1, 1, 1, 1, 2, 0,
		2, 0, 1, 0, 3, 0, 2, 2, 2, 0, 1, 1, 1, 1, 1, 1,
		0, 0, 1, 0, 3, 2, 2, 2, 0, 0, 0, 0, 1, 1, 1, 1,
	};


	const std::string tileset = "assets\\gfx\\spritesheet1.png";
	sf::Vector2u tileSize(32, 32);
	unsigned int width = 16;
	unsigned int height = 8;
	sf::VertexArray m_vertices(sf::Quads, width * height * 4);
	sf::Texture m_tileset;
	m_tileset.loadFromFile(tileset);

	for (unsigned int i = 0; i < width; ++i)
	{
		for (unsigned int j = 0; j < height; ++j)
		{
			// get the current tile number
			int tileNumber = level[i + j * width];

			// find its position in the tileset texture
			int tu = tileNumber % (m_tileset.getSize().x / tileSize.x);
			int tv = tileNumber / (m_tileset.getSize().x / tileSize.x);

			// get a pointer to the current tile's quad
			sf::Vertex* quad = &m_vertices[(i + j * width) * 4];

			// define its 4 corners
			quad[0].position = sf::Vector2f(i * tileSize.x, j * tileSize.y);
			quad[1].position = sf::Vector2f((i + 1) * tileSize.x, j * tileSize.y);
			quad[2].position = sf::Vector2f((i + 1) * tileSize.x, (j + 1) * tileSize.y);
			quad[3].position = sf::Vector2f(i * tileSize.x, (j + 1) * tileSize.y);

			//set texture coordinates
			quad[0].texCoords = sf::Vector2f(tu * tileSize.x, tv * tileSize.y);
			quad[1].texCoords = sf::Vector2f((tu + 1) * tileSize.x, tv * tileSize.y);
			quad[2].texCoords = sf::Vector2f((tu + 1) * tileSize.x, (tv + 1) * tileSize.y);
			quad[3].texCoords = sf::Vector2f(tu * tileSize.x, (tv + 1) * tileSize.y);
		}
	}



	while (window.isOpen()) {
		sf::Event event;

		while (window.pollEvent(event)) {
			if (event.type == sf::Event::Closed) {
				window.close();
			}

			if (event.type == sf::Event::KeyReleased) {
				if (event.key.code == sf::Keyboard::Escape || event.key.code == sf::Keyboard::Q) {
					window.close();
				}
			}
		}


		window.draw(m_vertices, &m_tileset);
		window.display();
		
	}
	return 0;
};


```

DO I have an error in my code, or is this a bug?

EDIT  -also noteworthy, a vertex array made from points or trianlges is drawn properly on android - just not the one that is comprised of quads. ANd I need quads for my map ;)

EDIT2 - I can confirm the texture IS loaded correctly on android, of course after adjustment of png file path, so thats not the issue here

br

**Comment by MarioLiebisch** [comment]
The vertex type `sf::Quads` is deprecated because it doesn't work using OpenGL ES. Use `sf::Triangles` or any other form instead and it will work. This isn't a bug in itself.

**Comment by DennisSc** [comment]
Oh, I see.. (I was hoping it would be just my cheap testing device's openGL driver being at fault).

Thanks for the perfect explanation to my observation.

Any chance that SFML someday will have a wrapper/handler (or something) to define quad rectangles, which are then internally handled as being two triangles? Or should I redesign my game (which currently relies on square tiles as the game map) to work with triangles?

Does anyone have an example at hand for drawing a textured, triangular tile map?  :)

thanks (and all the best for the new year).

**Comment by MarioLiebisch** [comment]
Better use triangles directly. Since you can access vertices in a vertex array, having some conversion on the fly would be rather odd and unnecessary complicated.

**Comment by DennisSc** [comment]
OK thanks again, I've now successfully drawn my map using two triangles instead of one quad! Easier than thought, once you wrap your head around it.

In case anyone needs to draw rectangular tilemaps using a vertex array of sf::triangles, here's my simple, working code (for replacement of the quad-based tilemap example of the sfml wiki):

```
class TileMap : public sf::Drawable, public sf::Transformable
{
public:
    bool load(const std::string& tileset, sf::Vector2u tileSize, const int* tiles, unsigned int width, unsigned int height)
    {
        // load the tileset texture
        if (!m_tileset.loadFromFile(tileset))
            return false;

        // resize the vertex array to fit the level size
        m_vertices.setPrimitiveType(sf::Triangles);
        m_vertices.resize(width * height * 6);

        // populate the vertex array, with one quad per tile
        for (unsigned int i = 0; i < width; ++i)
            for (unsigned int j = 0; j < height; ++j)
            {
                // get the current tile number
                int tileNumber = tiles[i + j * width];

                // find its position in the tileset texture
                int tu = tileNumber % (m_tileset.getSize().x / tileSize.x);
                int tv = tileNumber / (m_tileset.getSize().x / tileSize.x);

                // get a pointer to the current tile's quad
                sf::Vertex* triangle = &m_vertices[(i + j * width) * 6];

                // define the 3 corners of the first triangle
                triangle[0].position = sf::Vector2f(i * tileSize.x, j * tileSize.y);
				triangle[1].position = sf::Vector2f((i + 1) * tileSize.x, j * tileSize.y);
				triangle[2].position = sf::Vector2f((i + 1) * tileSize.x, (j + 1) * tileSize.y);
                // define the 3 corners of the secod triangle
				triangle[3].position = sf::Vector2f(i * tileSize.x, j * tileSize.y);
                triangle[4].position = sf::Vector2f(i * tileSize.x, (j + 1) * tileSize.y);
				triangle[5].position = sf::Vector2f((i + 1) * tileSize.x, (j + 1) * tileSize.y);

                // define 3 texture coordinates for first triangle
                triangle[0].texCoords = sf::Vector2f(tu * tileSize.x, tv * tileSize.y);
                triangle[1].texCoords = sf::Vector2f((tu + 1) * tileSize.x, tv * tileSize.y);
                triangle[2].texCoords = sf::Vector2f((tu + 1) * tileSize.x, (tv + 1) * tileSize.y);
                // define 3 texture coordinates for second triangle
				triangle[3].texCoords = sf::Vector2f(tu * tileSize.x, tv * tileSize.y);
				triangle[4].texCoords = sf::Vector2f(tu * tileSize.x, (tv+1) * tileSize.y);
				triangle[5].texCoords = sf::Vector2f((tu + 1) * tileSize.x, (tv + 1) * tileSize.y);
            }
        return true;
    }

```
