### ISSUE TITLE
compiling with CMake

### ISSUE THREAD

**Issue by fishyperil** [SFML/SFML#1341]
I'm trying to make a solution from the source code available here using CMake so that I can recompile it myself since I can't use the precompiled binaries available on the SFML site.

I downloaded the code from the repository and listed the folder containing the CMakeLists under "Where is the source code" in the Cmake GUI wizard. However, when I try to configure it, I get the following errors  : 

Selecting Windows SDK version 10.0.16299.0 to target Windows 6.1.7601.
CMake Error at CMakeLists.txt:3 (include):
  include could not find load file:

    C:/Users/Name/Desktop/SFML-master/src/SFML/cmake/Macros.cmake

CMake Error at System/CMakeLists.txt:103 (sfml_add_library):
  Unknown CMake command "sfml_add_library".

Do you know what the problem could be ?

**Comment by eXpl0it3r** [comment]
This issue tracker is for confirmed bugs and issues, please use [the forum](https://en.sfml-dev.org/forums/index.php) for general questions and troubleshooting.

**Comment by fishyperil** [comment]
That's true, but when I try to specify the root directory I get an error too : 
CMake Error: The source "C:/Users/Name/Desktop/SFML-master/CMakeLists.txt" does not match the source "C:/Users/Name/Desktop/SFML-master/src/SFML/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

Sorry, wasn't aware this was bugs only....will take any future questions to the forums then.

**Comment by eXpl0it3r** [comment]
Since you ran in on the wrong CMakeLists.txt file it now already created a cache. Clear the cache in CMake and run with the correct path again.

**Comment by fishyperil** [comment]
Looks like that was it ! Completely new to CMake , literally the first time ever using it. Thanks a lot for the help.
