### ISSUE TITLE
Android - sf::RenderWindow::Create doesn't take the button drawer into account

### ISSUE THREAD

**Issue by xxzoltanxx** [SFML/SFML#1349]
Best described in pictures:

![image_012](https://user-images.githubusercontent.com/30089504/35384899-086d7b7a-01c7-11e8-8b12-0d84cd3856d0.jpg)

Over here is when the app opens, everything looks fine.

But due to the bug with the android sticky I'm manually recreating the window with sf::RenderWindow::Create on mouseEntered event, and this is the result:

![image_013](https://user-images.githubusercontent.com/30089504/35384970-35779fec-01c7-11e8-9cf7-616260717080.jpg)

It seems like sf::RenderWindow::Create doesn't take the button drawer into account.

Virtual device - Nexus5X API 26
IDE - Android Studio
NDK Version - compiled with r15c, using r16b ( When I try to compile with r16b I get a version unsupported error)
The bug persists on the pixel2 API 26

**Comment by xxzoltanxx** [comment]
I tried running it on my android in debugging mode, Sony Xperia Z1 compact with lollipop on it, and the black bar isn't there. Does anyone know if there is an  emulator for the same phone with lollipop in android studio so I could check if it is caused by the virtual machine? I can't find it in the devices list.

**Comment by Alia5** [comment]
The emulators run pure android aka. AOSP
Most real devices have modifications made to the Android OS they're running on.

So no, you won't get "the same device" in the Emulator.

---

Just a wild guess here, as I haven't looked into anything.
Could it be that the event runs before the Android NavBar is hidden again?
In that case, just delaying the render texture recreation, or implementing some jni calls could workaround this.

**Comment by eXpl0it3r** [comment]
This should be fixed in SFML 2.6.2 in the sense that when you start the application you might get the resolution of the window without the navigation bar size and once the navigation bar disappears, you get a resize event that you should handle to get the fullscreen size.
