### ISSUE TITLE
Remove libsndfile from Android script

### ISSUE THREAD

**Issue by Foaly** [SFML/SFML#1355]
Looking at [`tools/android/compile_libs.sh`](https://github.com/SFML/SFML/blob/master/tools/android/compile_libs.sh#L52) and also `download_sources.sh` libsndfile is still being downloaded and built. Im not to terribly familiar with the android build chain, but since we got rid of libsndfile long ago I can't imagine it still being needed. If nobody has to say anything against it I will submit a PR.

**Comment by eXpl0it3r** [comment]
This seems to have been last changed 4 years ago, so yeah outdated. However in its place we'd need vorbis, ogg and flac.

Maybe #1350 removes the need to this anyways, @MarioLiebisch?

**Comment by Foaly** [comment]
I am not so sure as those script are only concerned with downloading and building the 3rd party libraries. And to my understanding the CMake script only builds SFML and links those libraries. I might be wrong though. Ping @MarioLiebisch 😃

**Comment by Foaly** [comment]
This seems like an easy fix. And an important one too, I think not cluttering the users hard drive by not downloading and build an unneed lib is worth it. Maybe the author knows @Sonkun? Or maybe @texus @MarioLiebisch
