### ISSUE TITLE
I would like to push my anisotropic filtering commit, but...

### ISSUE THREAD

**Issue by oomek** [SFML/SFML#1370]
Is it allowed to include the glTools?
https://github.com/msteinert/gltools/blob/194db704a99c68bcf1b6cdbb4b7265edba049108/src/GLTools.cpp
I would need to use the function gltIsExtSupported() to check if the extension is supported on the target device.

**Comment by Foaly** [comment]
Well no. SFML uses a [modified version of glLoadGen](https://github.com/SFML/SFML-glLoadGen) for the extension management. The files containing this are [GLLoader.cpp](https://github.com/SFML/SFML/blob/master/src/SFML/Graphics/GLLoader.cpp) and [GLExtensions.cpp](https://github.com/SFML/SFML/blob/master/src/SFML/Graphics/GLExtensions.cpp). I have no idea how it works exactly though. @binary1248 has always managed this. I don't know if there is a documentation on how to add a check for an extension somewhere.

**Comment by eXpl0it3r** [comment]
Please use the forum to ask question like this. The issue tracker is for confirmed issues-only.

Also see here: https://github.com/SFML/SFML-glLoadGen

**Comment by oomek** [comment]
I must have missed that. Will check it out and used the forum next time

**Comment by binary1248** [comment]
It might help just a little to [get to know the features of a library](https://www.sfml-dev.org/documentation/2.4.2/classsf_1_1Context.php#a163c7f72c0c20133606657d895faa147) before trying to contribute to it.

**Comment by roughbits01** [comment]
And that's how you encourage people to contribute to an open-source project!

**Comment by oomek** [comment]
Thanks. I feel better here than in the Kodi nazi camp :)
