### ISSUE TITLE
iOS build defaults to x86_64 architecture, regardless of specified platform

### ISSUE THREAD

**Issue by JonnyPtn** [SFML/SFML#1373]
See discussion [here](https://en.sfml-dev.org/forums/index.php?topic=23517.msg161517#msg161517)

as the toolchain file is processed when `project(SFML)` is called, it doesn't overwrite the previous setting of CMAKE_OSX_ARCHITECTURES, configured [here](https://github.com/SFML/SFML/blob/master/CMakeLists.txt#L31)

Not 100% sure of the best way to fix this. @Ceylo fixed it by checking if a toolchain file is being used, which will work, but I think there should be a better way.

I also found that moving the call to `project()` to be above that block of Code also fixes it, and doesn't have any adverse effects on osx builds, however the 
[docs](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html#variable:CMAKE_OSX_ARCHITECTURES) indicate it must be set before the first call to project(), so I'm reluctant to do that

**Comment by Ceylo** [comment]
Anotherpossible way is to force updating the cache entry in the toolcgain file. This means the user will be unable to change the architecture in CMake GUI but that may be ok as it’ll most likely not be needed anytime soon.

**Comment by JonnyPtn** [comment]
That actually sounds like a decent solution - the architecture in the toolchain is determined by the IOS_PLATFORM variable, which the user can modify so it wouldn't really restrict anything
