### ISSUE TITLE
Mac: Screen saver doesn't turn off with the game

### ISSUE THREAD

**Issue by naezith** [SFML/SFML#1381]
Just got a bug report and I don't think I can fix this. Maybe you know something. Here is the report:

```
Hello, I play on my MacBook Pro, lastest version of macOS High Sierra,

When I play the game, my screen saver don't turn off. 
It is not deactivated by the game, as all other games. 
It is thus necessary to me to deactivate it before playing and 
reactivating it manually every time. 
Could resolve you this bug? Result is same in in full screen or not.
```

Source: http://steamcommunity.com/app/590590/discussions/0/1694914735996718695/

Feel free to remove this if it's inappropriate for this place but I am not able do anything else.

**Comment by LaurentGomila** [comment]
I don't think it's a bug, as you probably haven't written anything in your game to turn off the screen saver. Or if you did, it's not using SFML :)

**Comment by MarioLiebisch** [comment]
SFML simply doesn't communicate with the OS regarding screen savers or power management (think standby/hibernate). I started something regarding this quite some while ago but in the end didn't finish it. It's quite trivial to do on Windows but no idea about the other supported platforms. It's certainly something I could imagine fitting SFML's scope as a multimedia library. For example, you don't want your computer to enter sleep mode while playing music in some SFML app or watching a cut scene in a game.

**Comment by eXpl0it3r** [comment]
Power management isn't part of SFML (yet), as such this isn't a bug. Check out the forum for previous discussion on this topic and if someone wants to take the time, create a feature request/proposal on the forum.

**Comment by eXpl0it3r** [comment]
See also #772
