### ISSUE TITLE
MinGW build broken

### ISSUE THREAD

**Issue by pixelherodev** [SFML/SFML#1391]
At some point recently, the MinGW build has been broken.
This occurred when the Dbt.h include was added to `src/SFML/Window/Win32/WindowImplWin32.cpp`. I encountered this in an automated Travis build and reproduced it locally on my Debian Linux system.

I am unsure if this occurs on native Windows builds. This is, however, problematic.

There is a public-domain version at `https://github.com/Alexpux/mingw-w64/blob/master/mingw-w64-headers/include/dbt.h`.

**Comment by MarioLiebisch** [comment]
Yes, and it's basically due to MinGW using different casing than the official SDK, see also #1386. For a quick and easy workaround outside code just create a symbolic link with the uppercase version for now. Closing this as a duplicate.
