### ISSUE TITLE
The sfml release library font.loadFromFile does not work properly while the debug library works well

### ISSUE THREAD

**Issue by wu1274704958** [SFML/SFML#1392]

**Comment by mantognini** [comment]
You should make sure you specifically followed this instruction from [the tutorial](https://www.sfml-dev.org/tutorials/2.4/start-vc.php):

> It is important to link to the libraries that match the configuration: "sfml-xxx-d.lib" for Debug, and "sfml-xxx.lib" for Release. A bad mix may result in crashes.

Read more on that on the forum -- many had the same issue.
