### ISSUE TITLE
refresh while resizing?

### ISSUE THREAD

**Issue by KnIfER** [SFML/SFML#1397]
when dragging one of the 4 borders and resizing,I can't see contents refreshing at the same time.  
However,almost every windows application allows that——contents will adapt to right positions just during the process of resizing.

**Comment by KnIfER** [comment]
it seems that "resizing" will pause the main loop.

**Comment by LaurentGomila** [comment]
Yes, there are many posts about this issue on the forum, please have a look first.

**Comment by KnIfER** [comment]
Although one flaw cannot obscure the splendor of the jade,I still want this feature,since I am trying to mimic potplayer(by sfml+imgui+vlc).  


In one of the posts on the forum,you said the only solution is to use a secondary thread,what does that actually require me to do?

**Comment by eXpl0it3r** [comment]
Please use the forums for discussions like this. See our [contribution guidelines](https://www.sfml-dev.org/contribute.php).

**Comment by LaurentGomila** [comment]
If I remember correctly, this problem has already been discussed in depth and all you need to know is already written in a forum post.

**Comment by KnIfER** [comment]
May I ask where's the internal blocking resize loop located?

**Comment by LaurentGomila** [comment]
Inside the Win32 API.

**Comment by KnIfER** [comment]
will a separate event-polling thread help?  
I tried using that but in a second thread window.pollEvent(event) always return false.  
`class ThreadX
{
       ...
	void ThreadEntryPoint()
	{
		while (window->isOpen()) {
			std::cout << "isOpen" << std::endl;
			sf::Event event;
			while (window->pollEvent(event)) {
                           ...event loop...
                         }
		}
	}
}

int main() {
         ...
	ThreadX * t1 = new ThreadX();
	HANDLE   hth1;
	unsigned  uiThread1ID;

	hth1 = (HANDLE)_beginthreadex(NULL,         // security
		0,            // stack size
		ThreadX::ThreadStaticEntryPoint,
		t1,           // arg list
		CREATE_SUSPENDED,  // so we can later call ResumeThread()
		&uiThread1ID);
	t1->threadName = "t1";
        ResumeThread(hth1);

	while (window->isOpen()) {
                       ...draw loop...
                }

	ImGui::DestroyContext();
	return 0;
}`

**Comment by KnIfER** [comment]
maybe i have to abandon the default titlebar and borders.  
T👃T

**Comment by LaurentGomila** [comment]
Please use the forum so you can have proper support and help from the community.

**Comment by KnIfER** [comment]
can't register for forum:  
The letters you typed don't match the letters that were shown in the picture.  
but I see no pictures
