### ISSUE TITLE
Missing cursor types on macos

### ISSUE THREAD

**Issue by JonnyPtn** [SFML/SFML#1401]
I noticed there are some cursor types missing on macOS:

SizeAll
SizeTopLeftBottomRight
SizeBottomLeftTopRight

Based on some quick research, it seems they just aren't exposed or documented by apple, which is helpful.... but [this](https://stackoverflow.com/a/46635398) SO answer suggests a solution which appears to work for me, implemented [here](https://github.com/JonnyPtn/SFML/commit/ecc50f318712cd60db48391e9565b7a8f39bb7b7)

I should mention I'm not really experienced with objective-C at all, so apologies if that code is bad in any way... If not, I can PR whenever you'd like

**Comment by MarioLiebisch** [comment]
Would probably be worth a try. What happens if you try to pass an invalid value (let's assume something is changed later)?

**Comment by JonnyPtn** [comment]
If I change `[NSCursor _________]` to use a non-existent value it compiles fine but then get SIGABRT at runtime. 

Following the SO article again, checking `if ([NSCursor respondsToSelector:@selector(______)])` would stop the SIGABRT, and could just return false from `loadFromSystem()`, which would match the current behaviour?

I'm using high Sierra 10.13.4 and Xcode 9.2 (9C40b), for the record.

**Comment by MarioLiebisch** [comment]
Sounds reasonable. My company Mac isn't up to date, so can't really check at the moment.

**Comment by eXpl0it3r** [comment]
What happens on minimum supported macOS versions?

**Comment by mantognini** [comment]
> but this SO answer suggests a solution which appears to work for me, implemented here

Interesting! This information wasn't available to me when #827 was being worked on.

> What happens on minimum supported macOS versions?

Nothing. This would be an addition based on non-documented API from Apple so we do not enforce users to have a system supporting those cursors. Instead, the users can only be certain at runtime that the cursor exists. The documentation should therefore be very clear on that.

Implementation wise, a patch along those lines (and proper formatting) would be good I think:

```cpp
// adding a private function to anonymous namespace
bool loadFromSelector(SEL selector, NSCursorRef& cursor) {
  if ([NSCursor respondsToSelector:selector]) { cursor = [NSCursor performSelector:selector]; return true; }
  else return false;
}

...
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wundeclared-selector"
switch (type) {
  case SizeBottomLeftTopRight: return loadFromSelector(@selector(_windowResizeNorthEastSouthWestCursor), m_cursor);
  // similarly for others...
}
#pragma clang diagnostic pop
```

@JonnyPtn, would you like to submit a PR? :)

**Comment by JonnyPtn** [comment]
Sure thing, I’m skiing this week so might not get round to it for a few days

**Comment by mantognini** [comment]
Superseded by #1425.
