### ISSUE TITLE
Performance drop in the current master

### ISSUE THREAD

**Issue by oomek** [SFML/SFML#1415]
There is a severe drop in performance in the current master when a computer is suspended and then resumed while a SFML app is running.

I tested SFML 2.4.2 and the current 2.5.0 WIP

There is a noticeable stuttering in the 2.5.0 version when PC is resumed from sleep.

2.4.2
https://www.youtube.com/watch?v=F5MtC6uIxgQ

2.5.0 WIP
https://www.youtube.com/watch?v=k7IxEEyCb0I

Both versions cross-compiled with MXE x86_64-w64-mingw32.static toolchain

**Comment by oomek** [comment]
22f1b85515242c44d7e5a1be1e3960bdf6648b52 is the first bad commit
commit 22f1b85515242c44d7e5a1be1e3960bdf6648b52
Author: binary1248 <binary1248@hotmail.com>
Date:   Thu Dec 21 20:54:58 2017 +0100

    Added support for interfacing with joysticks via DirectInput when it is available.

**Comment by binary1248** [comment]
@oomek Does SFML output anything to the console?

**Comment by oomek** [comment]
I know, but it gets even weirder. I'll try to explain the best I can.
This bug happens in the project I've recently started contributing to, the Attract Mode frontend for emulators. https://github.com/mickelson/attract
I cannot use MinGW because so far there is no known way to properly link to static MinGW libraries when AM is compiled. The weird part is that this bug only happens when I have an Ipac2 controller connected. Any other controller I own doesn't cause stuttering. What's more, it only affect 2 USB ports on my motherboard, other 2 ports work just fine. SFML does not output anything. I've tried linking to debug libraries.

There is many people using the configuration as I do, but since it's a very specific issue I'll try my best to help solving this mystery.

**Comment by binary1248** [comment]
This doesn't sound like something that can be fixed in SFML code... More like a BIOS or driver issue.

**Comment by oomek** [comment]
I've checked the bios and drivers already and I have the latest. This bug started happening after your commit, so forgive me if I'll disagree here. It's worth to mention that ipac2 acts like a keyboard, but they probably used some multidevice trick internally to get rid of the max 6 key pressed limit.

**Comment by binary1248** [comment]
I didn't imply you don't have the latest bios/drivers. Even the latest versions of things can still have bugs in them. The only difference that was introduced in that commit was the addition of DirectInput support. This is the same kind of implementation you will find in many other similar libraries such as SDL and GLFW. If you have the exact same issue using other DirectInput applications as well, then like I said, this is not something that can be resolved at the library level.

**Comment by oomek** [comment]
Since Attract Mode is using standard sfml input events is there any way to disable dinput from within app source?

**Comment by binary1248** [comment]
Comment out [lines 206-209 in JoystickImpl.cpp](https://github.com/SFML/SFML/blob/master/src/SFML/Window/Win32/JoystickImpl.cpp#L206).

**Comment by oomek** [comment]
I've commented the lines and the stuttering is gone. Since AttractMode project owner keep on insisting to stick to the official SFML release would you consider switching directinput off by default and leave it to the developers to decide if they want to use it as a good workaround?

**Comment by binary1248** [comment]
The primary reason for implementing DirectInput was to fix a crash a lot of people were getting when using the legacy windows joystick API. I don't think we would be doing the majority of SFML users a favour by defaulting to only using the broken API over DirectInput.

If you can insert some debug `printf`s into JoystickImpl.cpp and provide some kind of trace with timing information, maybe we can build in some kind of workaround for such setups.

**Comment by oomek** [comment]
I’ll do it. Do you want the timestamps in every function?

**Comment by binary1248** [comment]
Yes.

**Comment by oomek** [comment]
There is a flood of calls to updateConnections() function after resuming from sleep. Each call takes approximately 50ms
```
Attract-Mode v2.3.0-33 (Windows, SFML 2.4 +7z)
avcodec 57.107.100 / avformat 57.83.100 / swscale 4.8.100 / swresample 2.9.100

Config: D:\ATTRACTMODE\attract.cfg

*** Initializing display: 'mame'
 - Loaded master romlist 'mame' in 99 ms (4961 entries kept, 6542 discarded)
 - Constructed 8 filters in 6 ms (39688 comparisons)
initializeDInput: 8
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections: 55
 - Loaded layout: D:\ATTRACTMODE\layouts/test suspend/ (layout.nut)
sleep
resume
updateConnections directInput true: 0
updateConnectionsDInput: 57
updateConnections directInput true: 0
updateConnectionsDInput: 59
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 52
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 52
updateConnections directInput true: 0
updateConnectionsDInput: 55
updateConnections directInput true: 0
updateConnectionsDInput: 52
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 52
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 52
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 52
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 52
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 52
updateConnections directInput true: 0
updateConnectionsDInput: 55
updateConnections directInput true: 0
updateConnectionsDInput: 56
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 52
updateConnections directInput true: 0
updateConnectionsDInput: 55
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 52
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 52
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 52
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 52
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 52
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 54
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 52
updateConnections directInput true: 0
updateConnectionsDInput: 53
updateConnections directInput true: 0
updateConnectionsDInput: 53
```

**Comment by oomek** [comment]
When I swap my keyboard from usb 3.0 to 2.0 the calls take around 10ms with 2 spikes of 39 and 63 ms
When I have Edge browser open those 2 spikes are around 500-600 ms
```
Attract-Mode v2.3.0-33 (Windows, SFML 2.4 +7z)
avcodec 57.107.100 / avformat 57.83.100 / swscale 4.8.100 / swresample 2.9.100

Config: D:\ATTRACTMODE\attract.cfg

*** Initializing display: 'mame'
 - Loaded master romlist 'mame' in 100 ms (4961 entries kept, 6542 discarded)
 - Constructed 8 filters in 6 ms (39688 comparisons)
initializeDInput: 7
updateConnections directInput true: 0
updateConnectionsDInput: 11
updateConnections: 11
 - Loaded layout: D:\ATTRACTMODE\layouts/test suspend/ (layout.nut)
updateConnections directInput true: 0
updateConnectionsDInput: 12
updateConnections directInput true: 0
updateConnectionsDInput: 39
updateConnections directInput true: 0
updateConnectionsDInput: 11
updateConnections directInput true: 0
updateConnectionsDInput: 63
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 11
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 11
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 11
updateConnections directInput true: 0
updateConnectionsDInput: 11
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 11
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 11
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 11
updateConnections directInput true: 0
updateConnectionsDInput: 12
updateConnections directInput true: 0
updateConnectionsDInput: 11
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 11
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 11
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 11
updateConnections directInput true: 0
updateConnectionsDInput: 11
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
updateConnections directInput true: 0
updateConnectionsDInput: 10
```

**Comment by binary1248** [comment]
What happens if you change the last parameter of `EnumDevices` [here](https://github.com/SFML/SFML/blob/master/src/SFML/Window/Win32/JoystickImpl.cpp#L452) to `DIEDFL_ATTACHEDONLY`?

**Comment by oomek** [comment]
Will check a bit later tonight as my daughter is occupying my pc atm :)

**Comment by oomek** [comment]
Btw, attract mode was also crashing on usb plugging/unplugging with the older method I just rememberd.

**Comment by oomek** [comment]
The same thing unfortunately. The calls count hasn't changed. I was messing with the usb ports plugging it randomly and I've managed to make it even worse. Now every EnumDevices() call takes 80+ ms

**Comment by oomek** [comment]
Oh and btw, When unplugging the usb device I get around 15 calls of around 10-20ms. When I plug it back I get 10 calls taking 100+ ms. This is unaffectedby the last function flag.

**Comment by oomek** [comment]
I'm no expert, but this code [link](https://github.com/SFML/SFML/blob/master/src/SFML/Window/Win32/WindowImplWin32.cpp#L986) seems to me a bit over-complicated and may fire many unnecessary events while the devices are being initialised 

Wouldn't this be enough?
```
case WM_DEVICECHANGE:
{
    if (wParam == DBT_DEVNODES_CHANGED) JoystickImpl::updateConnections();
    break;
}
```

It works fine on my end, 3 calls for my 3 devices, and it reacts on the port changes. USB 3.0 lag is still present.

**Comment by binary1248** [comment]
Try out #1421.

**Comment by oomek** [comment]
Your commit fixed the issue with misfiring when resuming from sleep and when plugging unplugging there is less calls, but i still see duplicates of lParam/wParam:

keyboard unplugged
lParam:2cae5a0 wParam:8004   updateConnectionsDInput: 21
lParam:2cae590 wParam:8004   updateConnectionsDInput: 10
lParam:2cae590 wParam:8004   updateConnectionsDInput: 9
lParam:2cae590 wParam:8004   updateConnectionsDInput: 9
lParam:2cae590 wParam:8004   updateConnectionsDInput: 13
lParam:2cae590 wParam:8004   updateConnectionsDInput: 12
lParam:2cae590 wParam:8004   updateConnectionsDInput: 9
lParam:2cae590 wParam:8004   updateConnectionsDInput: 9
keyboard plugged back in
lParam:2cae590 wParam:8000   updateConnectionsDInput: 97
lParam:2cae590 wParam:8000   updateConnectionsDInput: 108
lParam:2cae590 wParam:8000   updateConnectionsDInput: 109
lParam:2cae590 wParam:8000   updateConnectionsDInput: 113
lParam:2cae590 wParam:8000   updateConnectionsDInput: 104
lParam:2cae590 wParam:8000   updateConnectionsDInput: 108
lParam:2cae5a0 wParam:8000   updateConnectionsDInput: 108
lParam:2cae590 wParam:8000   updateConnectionsDInput: 111

This keyboard has integrated touchpad so that's possibly why one lParam is different, but the rest is just duplicates.When I tried DBT_DEVNODES_CHANGED it gave me one call per device.

**Comment by oomek** [comment]
Thanks for that fix, btw.

**Comment by binary1248** [comment]
Using `DBT_DEVNODES_CHANGED` is not the right method for our purposes. We only care about when devices are actually ready and fully configured for use, or when they are completely removed, hence `DBT_DEVICEARRIVAL` and `DBT_DEVICEREMOVECOMPLETE`. See [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363218(v=vs.85).aspx).

When you plug in e.g. a keyboard with integrated USB hub and into that USB hub a joystick, we will get a `DBT_DEVNODES_CHANGED` notification once the device tree hierarchy is made available to Windows, this however does not mean the devices are ready for use. If we went ahead and polled for new joysticks then, we wouldn't register the joystick as connected, and since we don't wait for it to become fully operational either we would never detect it as connected.

On typical systems, you get a single `DBT_DEVNODES_CHANGED` and then either a `DBT_DEVICEARRIVAL` or `DBT_DEVICEREMOVECOMPLETE` per device that was connected or disconnected from the system. Why in your case you get a single `DBT_DEVNODES_CHANGED` and then multiple `DBT_DEVICEARRIVAL` for the same device I cannot say. It has something to do with the device and its driver.

If my patch reduces the performance degradation to the first few seconds after resuming from sleep, then that will have to do. When resuming from sleep, all connected devices will have to be re-initialized and this will always require some effort by the operating system.

**Comment by oomek** [comment]
After applying your fix there is no stuttering on resume. It's not reduced, it's gone completely. The calls are made only when plugging/unplugging the devices, so I consider it as a complete fix. I don't care about a little stuttering when unplugging/ plugging the keyboard, this is the rare circumstance. In plugging/unplugging gamepads there is only 1 stutter when a keyboard is connected to the usb 3.0 port.

And thank you for the explanation regarding `DBT_DEVNODES_CHANGED`

**Comment by eXpl0it3r** [comment]
Superseded by #1421
