### ISSUE TITLE
Outdated documentation regarding CMake projects

### ISSUE THREAD

**Issue by EXio4** [SFML/SFML#1423]
There's an outdated/broken link to FindSFML (https://github.com/SFML/SFML/blob/master/cmake/Modules/FindSFML.cmake) on https://github.com/SFML/SFML/wiki/Tutorial%3A-Build-your-SFML-project-with-CMake

**Comment by LaurentGomila** [comment]
Hi

Thanks for reporting it.

There's a dedicated section of the forum for the wiki, this repository is about SFML sources only.

And it's a wiki, everyone (including you) can edit it, and we're not responsible for its content.

**Comment by eXpl0it3r** [comment]
The wiki is not the documentation of SFML. It's a community wiki and as such anyone can update it.
