### ISSUE TITLE
SFML Android will not build with NDK r16

### ISSUE THREAD

**Issue by SteelGiant87** [SFML/SFML#1426]
It appears that the structure of the NDK changed in r16. The first issue encountered is that api-level.h has moved locations and changed structure (so just fixing the path doesn't work).

This problem can be worked around by using NDK r15 or older. 

In the future, it would probably be desirable for builds to work with the latest version of the NDK. This link appears to have the solution: NDK r16 has its own cmake toolchain files which can be used instead (hopefully reducing the workload on SFML developers):

https://github.com/caffe2/caffe2/pull/1740/commits/39622be4ca8e243d530ff0a08c5cfd483dda96ba

Unfortunately I am still not able to get an android build working on Windows 10, so I can't test this process further.

**Comment by MarioLiebisch** [comment]
SFML no longer provides its own toolchain file (for the very reason of reducing maintenance work) and is (right now) meant to be used with the one provided by CMake. Not really sure how up to date that one is at the moment. As for your other issues, no idea, it builds fine for me under Windows 10. We'd need more details there.

**Comment by SteelGiant87** [comment]
Ok, thanks.

My other issue is that somehow the build doesn't detect any of the libraries like Freetype or OpenAL:

I'm building using MinGW, NDK r15c and SDK 26, and a clone of SFML/master from a couple of days ago.

Attempting to build using the command:

`cmake -G "MinGW Makefiles" -DANDROID_ABI=armeabi -DANDROID_STL=stlport_shared -DANDROID_NATIVE_API_LEVEL=26 -DCMAKE_TOOLCHAIN_FILE=../../cmake/toolchains/android.toolchain.cmake ../..`

I get the error:

>  CMake Error at cmake/Macros.cmake:291 (message):
>   Missing item in FREETYPE_LIBRARY
> Call Stack (most recent call first):
>   src/SFML/Graphics/CMakeLists.txt:137 (sfml_find_package)

I tested commenting out the bit where it searches for Freetype, but then it fails on OpenAL. All those libraries appear to have .a or .so files where I think it is looking: ../../extlibs/libs-android/armeabi, so I'm very confused why it isn't finding them.

This appears to be the problem encountered by this person: 
https://en.sfml-dev.org/forums/index.php?topic=23699
and they worked around it using android studio.

**Comment by MarioLiebisch** [comment]
You're using outdated instructions. You no longer have to use a toolchain file, just define `CMAKE_SYSTEM_NAME` and set it to `Android`, see PR #1350.

**Comment by SteelGiant87** [comment]
It works! I can build SFML. Thank you so much! 

I was thrown off by the wiki page, which specified the build process I was using. I'll try and edit the wiki tomorrow.

For anyone else reading this, I built with:

`cmake -G "MinGW Makefiles" -DANDROID_ABI=armeabi -DANDROID_STL=stlport_shared -DANDROID_NATIVE_API_LEVEL=26 -DCMAKE_SYSTEM_NAME=Android ../..`

followed by

`mingw32-make.exe && mingw32-make.exe install`

Then I tried building the example project, I had to create a file `local.properties` containing the line:

> sdk.dir=C:/Users/Me/AppData/Local/Android/Sdk/

I downloaded gradle 4.7 and, after a few errors, uninstalled all javas, then reinstalled only JDK 1.8u172.

It now runs `gradle` successfully, but `gradle build` fails with the error:

> C:\Users\Me\source\repos\SFML\SFML-android\SFML\examples\android>gradle build
> 
> > Task :app:generateJsonModelDebug FAILED
> process_begin: CreateProcess(NULL, "", ...) failed.
> C:\Users\Me\source\repos\SFML\SFML-android\SFML\examples\android\app\src\main\jni\Android.mk:20: *** Android NDK: Aborting.    .  Stop.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:generateJsonModelDebug'.
> > Build command failed.
>   Error while executing process C:\Users\Me\AppData\Local\Android\Sdk\ndk-bundle\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\Me\source\repos\SFML\SFML-android\SFML\examples\android\app\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\Users\Me\source\repos\SFML\SFML-android\SFML\examples\android\app\src\main\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 APP_PLATFORM=android-14 NDK_OUT=C:/Users/Me/source/repos/SFML/SFML-android/SFML/examples/android/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\Me\source\repos\SFML\SFML-android\SFML\examples\android\app\build\intermediates\ndkBuild\debug\lib APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
>   Android NDK: C:\Users\Me\source\repos\SFML\SFML-android\SFML\examples\android\app\src\main\jni\Android.mk: Cannot find module with tag 'third_party/sfml' in import path
>   Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?
>   Android NDK: The following directories were searched:
>   Android NDK:
>   process_begin: CreateProcess(NULL, "", ...) failed.
>   C:\Users\Me\source\repos\SFML\SFML-android\SFML\examples\android\app\src\main\jni\Android.mk:20: *** Android NDK: Aborting.    .  Stop.

Am I supposed to set NDK_PROJECT_PATH somewhere? Where should it point?

I feel I'm so close to having it working...

**Comment by MarioLiebisch** [comment]
From memory, so might be wrong: Add `ndk.dir` to your `local.properties` and set it to your NDK directory.

**Comment by SteelGiant87** [comment]
Adding the NDK dir to `local.properties` has helped, although it seems to have revealed another problem in my build: It couldn't find the armeabi-v7a files. 

As mentioned in https://github.com/SFML/SFML/pull/1350 the ABI flag has changed from `ANDROID_ABI` (which is silently ignored) to `CMAKE_ANDROID_ARCH_ABI`, and so it was still targeting `armeabi`:

> -- Android: Targeting API '26' with architecture 'arm', ABI 'armeabi', and processor 'armv5te'

The working build command is now:
`cmake -G "MinGW Makefiles" -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DANDROID_STL=stlport_shared -DANDROID_NATIVE_API_LEVEL=26 -DCMAKE_SYSTEM_NAME=Android ../..`

which targets v7a:

> -- Android: Targeting API '26' with architecture 'arm', ABI 'armeabi-v7a', and processor 'armv7-a'

Unfortunately `gradle build` (and `gradle assembleDebug` or `gradle assembleRelease`) still fail:

> C:/Users/Me/source/repos/AndroidNDK/android-ndk-r15c/build//../build/core/build-binary.mk:688: Android NDK: Module sfml-example depends on undefined modules: sfml-main-d sfml-system-d sfml-window-d sfml-graphics-d sfml-audio-d sfml-network-d sfml-activity-d

It looks like it is trying to pull in the debug versions, and I'm not sure how to stop this?

**Comment by MarioLiebisch** [comment]
It's actually configured that way right now, something we probably should change (the whole updated build is still work in progress, unfortunately massively low on time atm).

In `examples/android/app/src/main/jni` there are `Application.mk` and `Android.mk`, both referencing the debug versions with `-d`. Edit them and it should build.

**Comment by SteelGiant87** [comment]
Thanks for the lightning fast response!

I tried changing to `stlport_static` but I get the same corrupt/crash behaviour.

**Comment by SteelGiant87** [comment]
I have given up on the current build for the moment. It will be great when it works for me, but I can't find a way to get valid apks at the moment.

I did manage to get a valid build of the example working using old SFML and old tools and the Windows tutorial https://github.com/SFML/SFML/wiki/Tutorial%3A-Building-SFML-for-Android-on-Windows

with the changes I list in this thread (it is hard to get hold of the outdated tools necessary to build with the old instructions now):

https://en.sfml-dev.org/forums/index.php?topic=21547.msg162773#msg162773
