### ISSUE TITLE
[docs] Add canonical link to old docs so that search engines point to latest docs

### ISSUE THREAD

**Issue by sherjilozair** [SFML/SFML#1430]
Pretty much the title. Right now, searching for any SFML concept leads to the old docs page (2.0 most of the time). If we add a canonical link to the docs pointing to the latest doc pages, search engines will replace the page with the newer docs, and avoid having to click twice to see docs. I'd be happy to make the changes if the maintainers agree with the change.

**Comment by eXpl0it3r** [comment]
Could you open an issue (or directly send a PR) on the [SFML/SFML-Website](https://github.com/SFML/SFML-Website) repository as the changes will mostly have to be applied there?

I was once researching if such a thing existed, but couldn't find anything, so this is definitely good news!
