### ISSUE TITLE
[macOS] Core context support for OpenGL >3.30

### ISSUE THREAD

**Issue by gurki** [SFML/SFML#1434]
## Description 

I'm aware, that there has been discussion on this before [[1]](https://github.com/SFML/SFML/pull/779)[[2]](https://github.com/SFML/SFML/issues/176)[[3]](https://stackoverflow.com/questions/45088299/core-opengl-context-when-compatibility-requested), but after 6 years it's still an issue.
On macOS, there is currently no option to use new GLSL shaders (i.e. >3.30 core), as SFML does not support the Graphics module with Core (non-compatibilty) contexts.
Are there any plans to implement this?
It is reason for me and others to move to other frameworks, which is a pity, as SFML honestly has one of the nicest API's of them all 😊.

## Environment 

macOS High Sierra 10.13.4
MacBook Pro (Retina, 15-inch, Early 2013)
Intel HD Graphics 4000 / NVIDIA GeForce GT 650M
SFML 2.4.2
C++14 / Apple Clang (arm64)

**Comment by binary1248** [comment]
@gurki Try out #1443.

You won't be able to use anything inside the graphics module when you create a core context. That is still being worked on. You can however create a core profile context/window and do your OpenGL stuff with it.

**Comment by gurki** [comment]
@binary1248 Ah, thanks for the x-ref! Was able to get the example running on my machine. 

As an implication though and as you mentioned, you loose the convenience of being able to draw 2d UI/debugging with SFML on top of custom OpenGL stuff. Reading through the forums, that seems to be a rather common use case for SFML as well (myself included). 

The linked thread (thanks!) is rather controversial, as there are several approaches to this. After evaluating some final concepts, I'll also drop my two cents over there :).

**Comment by installgentoo** [comment]
Actually it mite b cool if sfml supported 3.3 first.

With glfw on linux i can create 3.3 contexts at my leisure. With the last sfml it gives me 3.0

**Comment by eXpl0it3r** [comment]
This is exclusively related to macOS and unrelated to your issue on Linux. I suggest to open a forum thread with plenty of information (OS, driver version, WM, minimal example, error, etc) so we can help you figure out what's going on. 🙂

**Comment by eXpl0it3r** [comment]
Merged in ac98be760b8b1401fd7a3b141883cbf04feba7b7
