### ISSUE TITLE
Add CMake script for an empty project

### ISSUE THREAD

**Issue by gale93** [SFML/SFML#1448]
Have a mantained and ready to use CMake script that generate an empty project would be really handy.

**Comment by LaurentGomila** [comment]
You mean, something like this?

```cmake
cmake_minimum_required(VERSION 3.1)

project(SFMLTest)

## If you want to link SFML statically
# set(SFML_STATIC_LIBRARIES TRUE)

## In most cases better set in the CMake cache
# set(SFML_DIR "<sfml root prefix>/lib/cmake/SFML")

find_package(SFML 2.5 COMPONENTS graphics audio REQUIRED)
add_executable(SFMLTest main.cpp)
target_link_libraries(SFMLTest sfml-graphics sfml-audio)
```

https://en.sfml-dev.org/forums/index.php?topic=24070.0

**Comment by gale93** [comment]
Yes ! Very nice. Sorry I didn't see.
It should definitely stay in the "gettig started" section on the website. I think it needs a lot more visibility, do you think it makes sense?

P.s.: I've been following SFML for many years and I'm very fond of it, great job !

**Comment by eXpl0it3r** [comment]
I think a section "SFML and CMake" or similar would be nice. As this is a topic for the SFML website, please open an issue on [SFML-Website repository](https://github.com/SFML/SFML-Website/issues).
