### ISSUE TITLE
android build   Missing item in FREETYPE_LIBRARY

### ISSUE THREAD

**Issue by mumin16** [SFML/SFML#1455]
Missing item in FREETYPE_LIBRARY
Call Stack (most recent call first):
  src/SFML/Graphics/CMakeLists.txt:137 (sfml_find_package)

**Comment by MarioLiebisch** [comment]
You'll have to provide more than those two lines. What exactly is missing? What are you trying to build, which SDK/NDK versions are you using, etc. If you're unsure and need help in general, try the forums on https://en.sfml-dev.org/forums/. Feel free to edit/update this issue once you have more details.
