### ISSUE TITLE
sf::String destruction causes crashes with Visual Studio in debug

### ISSUE THREAD

**Issue by Bulmanator** [SFML/SFML#1468]
## Subject of the issue
When attempting to create a window passing a string will cause a fatal error with the message _'An invalid parameter was passed to a function that considers invalid parameters fatal'_. Caused by urctbased.dll
I did a bit more research and simply creating a string in a local scope and waiting for it to be deleted will cause a _'Stack cookie instrumentation code detected a stack-based buffer overrun'_. This is an issue with deleting the basic_string it uses as a backing store.
When passing an empty string (sf::String()) to the RenderWindow constructor it crashes with an _Access violation exception instead_
Also when trying to debug through visual studio whenever sf::String is referenced via the call stack it states 'Source Not Available' even though I have added the .pdb files to my symbols path.
There is a high chance this is an issue with the Windows CRT.
## Environment
Windows 10 64-bit
SFML 2.5.0 64-bit (pre-built and compiled from source both produce this issue)
I also tried building master and the same issue occurred.
cl.exe was used to compile. From Visual Studio 2017 Community (Version 15.5.6), 19.12.25835 is the version number that it gives.

## Steps to reproduce
**Invalid parameter example:**
```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(1280, 720), "Minimal, complete and verifiable example");
}
```
**Access violation example:**
```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(1280, 720), sf::String());
}
```
**Stack cookie buffer overrun:**
```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::String test = "Hello World";
}
```
**Command Used to compile:**
`cl -Zi /EHsc /I\SFML\include Test.cpp /link /LIBPATH:\SFML\lib sfml-graphics-d.lib sfml-window-d.lib sfml-system-d.lib`

## Expected behavior
The window should be created and the game loop can start

## Actual behavior
The program crashes due to ucrtbased.dll with 'An invalid parameter was passed to a function that considers invalid parameters fatal.', 'Stack cookie instrumentation detected a stack-based buffer overrun' or an 'Access violation'

**Comment by eXpl0it3r** [comment]
`sf::String` has a default constructor and the only member it has is a `std::basic_string<sf::Uint32>` which gets properly destructed by the STL.

Your issue is, that by leaving out any /MT[d] /MD[d] flag, Visual Studio will automatically default to `/MD`  which is for the release runtime library, while SFML uses `/MDd` for the debug libraries, causing a conflict between runtime versions and thus a crash. 🙂 

Might be better to be more verbose in the build command, but then you at least know what you pick and don't rely on hoping to get the right default picked out by VS. 😉

**Comment by Bulmanator** [comment]
Ohh, thank you very much for your help. Sorry to both you with an issue that wasn't due to the library

**Comment by eXpl0it3r** [comment]
No worries. If you're unsure about something, you might find quicker help on the [SFML forum](https://www.sfml-dev.org/community.php) next time. 🙂
