### ISSUE TITLE
False window.getPosition(); values

### ISSUE THREAD

**Issue by MisleaderYT** [SFML/SFML#1488]
## Subject of the issue
I tried to make a window that can move and resize and change colors, it worked fine, but the `window.getPosition()` of point (0,0) is wrong and false.

## Your environment
* Your OS / distro / window manager used : **Windows 10**.
* Your version of SFML (2.5.0, git master, etc) : **SFML 2.5.0**.
* Your compiler and compiler version used : **Microsoft Visual Studio Community 2017 (v15.8.4)**.
* Special compiler flags used : **_I don't know what it means_**.

## Steps to reproduce:
Basically, try to call `window.setPosition(sf::Vector2i(0,0));` then after that `std::cout << "POSITION: " << window.getPosition().x << " : " << window.getPosition().y << std::endl;`, and the output says **POSITION: 0 : 0**, but the window isn't truly at (0,0).
```cpp
#include <iostream>
#include <SFML/Graphics.hpp>
int main()
{
	sf::RenderWindow window(sf::VideoMode(1280,720),"Minimal, complete and verifiable example");
	window.setFramerateLimit(60);
	while(window.isOpen())
	{
		sf::Event event;
		while(window.pollEvent(event))
		{
			if(event.type == sf::Event::Closed)
				window.close();
		}
		window.clear();
		window.setPosition(sf::Vector2i(0,0));
		std::cout << "POSITION: " << window.getPosition().x << " : " << window.getPosition().y << std::endl;
		window.display();
	}
}
```

## Expected behavior:
The (0,0) of `window.getPosition()` should've been correct, but it is not.

## Actual behavior:
The (0,0) of `window.getPosition()` has some kind of offset from the actual screen, the offset is like (9,1).
![image](https://user-images.githubusercontent.com/43376807/45690569-58266a80-bb5f-11e8-9023-e8b9a37df869.png)
![image](https://user-images.githubusercontent.com/43376807/45690838-f31f4480-bb5f-11e8-9863-846ec962c25f.png)

**Comment by LaurentGomila** [comment]
It is at (0, 0). In Windows 10, the borders are transparent, giving the (false) feeling that the window is offseted. But if you move the mouse cursor on this empty space on the left, you'll see that it changes to the "resize" cursor, so you're indeed on the border of the window.

**Comment by MisleaderYT** [comment]
Great to know that, but the window will get out of the screen bounds if you don't give a pixel offset to it, for example if you make a window, and make 4 unsigned integer variables "x" "y" "width" "height", then modify these with keyboard input(for example move the window with arrow keys by adding to "x" and "y" variables), the window could reach outside of the screen, i applied offsets for both "x" and "y", now they work correctly, but if the window position goes below 0, it will return 4294967293 as window position for both "x" and "y", and it will cause my clamping functions to think that it reached the right side of the screen and get it back to a "safe-zone".

Why is it returning 4294967293 as a value when "x" or "y" reach 0 and go below it? isn't this a bug or something?

Thanks for your fast response.

**Comment by eXpl0it3r** [comment]
It's called an "underflow" and since you have *unsigned* integers they wrap around to the maximum value. You'll probably find more detailed explanations by googling "underflow" (or "overflow" same concept).

**Comment by MisleaderYT** [comment]
Oh right, i don't know why i didn't get that, "unsigned" means that it can't be negative, my bad, i guess i haven't got enough sleep today..

But still the position and size values aren't really correct, if i set the window's position to (0,0), then set size to (1366,768) which is my PC's resolution, i won't get a window that covers the whole screen and be at (0,0), also by the way i'm not trying to make a fullscreen-like feature, i'm just trying to limit the window's position and size like:
```
//METHOD        (VALUE,      KEY        ,   MULTIPLIER(or)SIDE       , MIN VALUE, MAX VALUE);
ChangeProperty(&x,sf::Keyboard::Key::RControl,horizontalInput,0,screen[0] - width);
ChangeProperty(&y,sf::Keyboard::Key::RControl,-verticalInput,0,screen[1] - height);
ChangeProperty(&width,sf::Keyboard::Key::RAlt,horizontalInput,720,screen[0] - x);
ChangeProperty(&height,sf::Keyboard::Key::RAlt,-verticalInput,480,screen[1] - y);
```
Here you can see i've clamped them well in a method called 'ChangeProperty()`, but the window not actually being in (0,0) makes the whole operation look bad and not function correctly.

**Comment by eXpl0it3r** [comment]
SFML is not a "window managing" library, as such we don't offer functionalities specific to window management. If you really require this kind of check (why does it matter if it's moved too far to the left or right?), then you can still achieve it, by retrieving the window handle from the SFML window and then use the WinAPI to get the decoration size and offset by that.

Btw. these kind of questions are better suited for the [SFML forum](https://en.sfml-dev.org/forums/). 🙂

**Comment by MisleaderYT** [comment]
Oh great, thanks for your responses, it's ok now if it isn't a "window managing".
I thought it was a bug.
Thanks again, you're free to close this Issue.
Sorry for taking your time.

**Comment by LaurentGomila** [comment]
> But still the position and size values aren't really correct, if i set the window's position to (0,0), then set size to (1366,768) which is my PC's resolution, i won't get a window that covers the whole screen and be at (0,0)

Keep in mind that the size you set is the size of the drawing area, not including the decorations (title bar + borders). The full window is always bigger than the size you set programatically.

**Comment by MisleaderYT** [comment]
Thanks for the information, but is it possible to set width/height of the window with its decorations? sorry if this isn't the right place to ask, for some reason i can't register an account in SFML because the ReCaptcha keeps saying that i did it wrong and i must do it again.

I would like to get an answer about this here, and fast if possible, i'm about to switch to GLFW, if i get the true `x` `y` `width` `height` values, then i won't have to switch to GLFW.

I look forward to keep developing with SFML, and thanks again.

**Comment by MisleaderYT** [comment]
I can confirm that the same "Position & Size changes by Keyboard input with Limitations" feature works fine in GLFW, it is even smoother, i don't understand why SFML couldn't get a true `x` and `y` position of the window, and i couldn't find a function or a variable to get windows 10's decoration sizes in pixels in SFML, but in GLFW it was there.

I switched to GLFW, but i hope that someday in the future SFML could find a solution to this problem, anyway, thanks for your responses again, and sorry for taking your time.

Note: i deleted my last comment that was posted 2 hours ago.
