### ISSUE TITLE
SFML WebAssembly support?

### ISSUE THREAD

**Issue by blackjyn** [SFML/SFML#1494]
I was looking for official stmt on SML support on WASM.
When will SFML supports WASM?

**Comment by MarioLiebisch** [comment]
Find out why it's not working, write a patch/PR or suggest the necessary changes and chances aren't that low to get it added. :) I've seen people run SFML games in browsers using Emscripten, so I don't think WebAssembly could be that far off or completely off the table. It might be a 15 minutes change or more – no idea, unfortunately.

Keep in mind everyone working on SFML does so in their spare time, so easiest way to get features you want is getting them done yourself (or find someone who's got both time and interest in that specific thing) – and right now there are still tons of open features (or even bugs) we're lacking manpower to get them done.

**Comment by eXpl0it3r** [comment]
There's no support at the moment. We don't have any specific plans, but given the work towards decoupling SFML from legacy OpenGL, having different backends certainly becomes something to discuss.

For general questions and discussions please utilize the forum: https://en.sfml-dev.org/forums/index.php#c3

**Comment by jeancode** [comment]
Me parece interesante estado trabajando con sfml  y estoy especializarme en webAssembly  creo que puede haber un acople simple dependiente de los navegadores comunes  modificando el motor vh de chrome  tendríamos la oportunidad de ensamblar el motor de graficos sfml independiente de opengl por medido de un adds modificado para canvas, eso seria espectacular las posibilidades abarcan desde la creación de interfaces para linux   y dispositivos portatiles,  ademas de aplicaciones aisladas serian como pequeños motores  en javascript + WebAssembly

**Comment by Awsomiihill** [comment]
it would certainly be cool to make sfml work in webasm tho, a friend of mine uses sfml a lot and is currently working on a project

**Comment by fluffrabbit** [comment]
I use my own GLES2 renderer. SDL2 worked fairly well as a context initializer in the browser until recently. Now it's being screwy with keyboard input. I'm feeling burned by the whole monolithic SDL thing and I have SFML as an alternate backend. Maybe SFML can be used for this purpose if its renderer is discarded?

**Comment by siauderman** [comment]
Bump. Hope that emscripten support will come out soon.

**Comment by fluffrabbit** [comment]
SFML is a small project. Have you tried SDL?

**Comment by siauderman** [comment]
> 
> SFML is a small project. Have you tried SDL?
> […](#)
> On October 5, 2020 8:31:30 PM PDT, Custom Automated Systems Pte Ltd ***@***.***> wrote: Bump. Hope that emscripten support will come out soon. -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#1494 (comment)](https://github.com/SFML/SFML/issues/1494#issuecomment-704006889)

But I prefer C++ over C.

**Comment by fluffrabbit** [comment]
The SDL API isn't bad. It's all namespaced SDL_ and is pretty low-fuss. It even has sprite batching now, assuming you're using the 2D functionality.

Also, you should be aware that Emscripten itself has some complications when it comes to display modes and canvas scaling. It's not quite 1:1 with desktop, so any API that works on both may be a bumpy ride, SDL included.

**Comment by siauderman** [comment]
If I liked the SDL C style of programming I wouldn't even bother with SFML lol.🤪

**Comment by Laguna1989** [comment]
Another user requesting interest here. Being able to use SFML in emscripten would be highly appreciated

The SDL API is broken in countless ways, it is an absolute pain to work with. It is not about c or c++ but about SDL being inconsistent af and poorly documentated. It violates the SOLID principles and forces the user to do weird things.
Being able to use SFML would be a clear improvement.

I have some experience with both SDL and SFML, as I develop a game framework which uses both to allow for native and web-builds. See [the github repo](https://github.com/Laguna1989/JamTemplateCpp)

**Comment by blackjyn** [comment]
@Laguna1989 
> It is not about c or c++ but about SDL being inconsistent af and poorly documentated

Yes, SDL is poorly documented. 

Thanks for your JamTemplateCpp , I'll try it!

**Comment by ryanrezrez** [comment]
So, does SFML work with Emscripten?

**Comment by eXpl0it3r** [comment]
> So, does SFML work with Emscripten?

Not as is, no.

**Comment by aakarshan-raj** [comment]
the only way i found to run SFML is porting it to SDL and then use Emscripten, sadly.

**Comment by vittorioromeo** [comment]
> the only way i found to run SFML is porting it to SDL and then use Emscripten, sadly.

How difficult was it to "port" SFML to SDL? Would it be reasonable to implement SDL as a possible backend for SFML and enable it via a CMake flag to support WebAssembly? Could be a very cool addition to the library and a nice opportunity for a PR :)

**Comment by Laguna1989** [comment]
As mentioned already in 2021, I have made my [game template](https://github.com/Laguna1989/JamTemplateCpp) to work with both sdl and sfml. The porting process was not so nice, mostly because SDL as a plain, organically grown c-library, is a real pain to use (see [this statement](https://github.com/SFML/SFML/issues/1494#issuecomment-913104731)).
I strongly advice against using sdl as a backend to sfml. Supporting both frameworks in parallel is a rather big effort, stacking them on top of each other will make things very brittle and hard to support.


It would really be great to see full support of SFML for emscripten. Webassembly is clearly the future. Having an alternative game related library officially supported there would be awesome!

**Comment by seoProductions** [comment]
Bump. Its 2025 and still looking for solutions, anyone out there?

**Comment by vittorioromeo** [comment]
> Bump. Its 2025 and still looking for solutions, anyone out there?

My personal fork, VRSFML, support Emscripten, but it also makes some other major changes that deviate from SFML's philosophy. You can read about it [here](https://vittorioromeo.com/index/blog/vrsfml.html) and [here](https://vittorioromeo.com/index/blog/vrsfml2.html).

There's also another fork for SFML 2/3, check out [this video](https://youtu.be/1kiwpAIU454).

**Comment by seoProductions** [comment]
> > Bump. Its 2025 and still looking for solutions, anyone out there?
> 
> My personal fork, VRSFML, support Emscripten, but it also makes some other major changes that deviate from SFML's philosophy. You can read about it [here](https://vittorioromeo.com/index/blog/vrsfml.html) and [here](https://vittorioromeo.com/index/blog/vrsfml2.html).
> 
> There's also another fork for SFML 2/3, check out [this video](https://youtu.be/1kiwpAIU454).

Looks promising! Been in search of this for over a year
