### ISSUE TITLE
MacOS: Installation prefix path is ignore when installing framework files

### ISSUE THREAD

**Issue by gracicot** [SFML/SFML#1496]
## Subject of the issue

When building sfml from source with cmake on mac, the install script ignore the given installation prefix.

This broke my build because I was installing sfml without root rights since it was in a local repository.

## Your environment

* MacOS
* sfml 2.4.2
* CMake 3.11 and Apple clang 9

## Steps to reproduce

Tell us how to reproduce this issue. Please provide a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve), you can use the follow template as a start:

```
# (clone sources)
$ mkdir build && cd build
$ cmake .. -DCMAKE_INSTALL_PREFIX=/Users/me/some_directory
$ make install
```

## Expected behavior

It should successfully install using the prefix

## Actual behavior

Installation fails since it tries to install framework file in the root.

```
-- Installing: /Library/Frameworks/FLAC.framework
CMake Error at cmake_install.cmake:60 (file):
 file INSTALL cannot make directory "/Library/Frameworks/FLAC.framework":
 Permission denied

make: *** [install] Error 1
```

I'm not used with MacOS. Is this intended behavior? Are mac library forced to install in this location?

**Comment by mantognini** [comment]
Please have a look at the documentation. The install options have indeed been updated. You might want to set `SFML_DEPENDENCIES_INSTALL_PREFIX` and `SFML_MISC_INSTALL_PREFIX` as well. More here: https://www.sfml-dev.org/tutorials/2.5/compile-with-cmake.php
