### ISSUE TITLE
Offscreen rendering problem when display is in power save mode

### ISSUE THREAD

**Issue by yngvix** [SFML/SFML#1502]
## Subject of the issue
When rendering offscreen with RenderTexture, the drawing functions have no effect once the lock screen is activated on the desktop and the display is powered down. This is despite the fact that no display is used by the program and nothing is drawn on the screen. No errors are reported, and the rendering activity is simply ignored. The GPU itself is active, e.g. CUDA computations work normally in the same process.

## Your environment

* Debian 4.9 / Xfce
* SFML 2.4.1 according to the package manager (the latest in Debian)
* GCC 6.3.0
* No flags

## Steps to reproduce
Code:
```cpp
#include <GL/glew.h>
#include <GL/gl.h>
#include <SFML/Graphics.hpp>
#include <iostream>
#include <chrono>
#include <thread>

using namespace std;

sf::RenderTexture render_texture;
sf::Font font;

void print(const string& to_print, int x, int y) {
	sf::Text text(to_print, font, 30); // in pixels, not points!

	// set the color
	text.setFillColor(sf::Color::Black);
	text.setOutlineColor(sf::Color(255, 250, 240, 255));
	text.setOutlineThickness(4.0f);

	text.setPosition(x, y);

	render_texture.pushGLStates();
	render_texture.draw(text);
	render_texture.popGLStates();
}


void opengl_message_callback(GLenum source, GLenum type, GLuint id,
		GLenum severity, GLsizei length, const GLchar* message,
		const void* userParam) {
	cerr << "GL CALLBACK: "
			<< (type == GL_DEBUG_TYPE_ERROR ? "** GL ERROR **" : "")
			<< " type = " << type << ", severity = " << severity
			<< ", message = " << message << endl;
}


int main() {
	int window_side = 500;


	if (!font.loadFromFile("Cabin-Regular.ttf"))
		throw runtime_error("Could not load font");

	render_texture.create(window_side, window_side, false);

	auto glew_init_res = glewInit();
	if (glew_init_res != GLEW_OK)
		throw runtime_error("Could not initialize GLEW: "  + string((const char*)glewGetErrorString(glew_init_res)));

	// get version info
	const GLubyte* renderer = glGetString(GL_RENDERER); // get renderer string
	const GLubyte* version = glGetString(GL_VERSION); // version as a string

	cout << "Renderer: " << renderer << ", OpenGL version supported: "
			<< version << endl;

	// During init, enable debug output
	glEnable (GL_DEBUG_OUTPUT);
	glDebugMessageCallback((GLDEBUGPROC) opengl_message_callback, 0);


	for (int i = 0;; ++i) {
		render_texture.clear(sf::Color::Black);
		render_texture.setActive(true);
		print("wow" + to_string(i), i % 400, (i / 100) % 400);
		render_texture.setActive(false);
		render_texture.display();

		const sf::Texture& texture = render_texture.getTexture();
		string name = to_string(i);
		string padded_name = std::string(8 - name.length(), '0') + name;
		texture.copyToImage().saveToFile(padded_name + ".jpg");
		this_thread::sleep_for(chrono::milliseconds(100));
	}

	return 0;
}
```

GLEW/GL stuff can be removed, it has no effect. The example uses Text, but all other rendering functions don't work in the same way. Start the program, bring up the lock screen and wait until the display is powered off. Wait 30 seconds, then unlock the desktop and stop the program.

## Expected behavior
A series of JPEG files should appear in the startup folder, each named as a number, and the corresponding number should appear on each image.

## Actual behavior
Starting from the display power-down time, the saved images will all be the same and they will show a number from the past. E.g. the image 00000200.jpg will show number 96. After the display is powered up again, the content of the saved images becomes as expected.

**Comment by eXpl0it3r** [comment]
As far as I can tell, this isn't exactly SFML specific. I'm pretty sure if you used pure OpenGL, you'll run into the same issue. What happens to the OpenGL rendering while no monitor is active, is mostly up to the desktop/window manager or the GPU driver. In most cases it makes sense to not render anything to preserve battery power.

If you need headless rendering, then what you probably want is a virtual X screen (see also [this](https://github.com/OKaluza/LavaVu/wiki/Headless-rendering) and [this](https://stackoverflow.com/questions/3326641/opengl-without-x-org-in-linux)).

**Comment by eXpl0it3r** [comment]
This isn't really something that SFML can solve or at least, I don't see how. As mentioned there are options for headless rendering, but those unrelated to SFML.

If anyone has a specific idea how to approach this, please feel free to reopen the issue.
