### ISSUE TITLE
Why are SFML's Linux dependencies not static?

### ISSUE THREAD

**Issue by jawaff** [SFML/SFML#1508]
## Packaging SFML in a Python 'manylinux' Wheel.

Hello, I'm helping out the python-sfml binding with the automated build/deploy system efforts. Python's [Pypi](https://pypi.org/) deployment requirements are causing me some grief. A debian-based Python Wheel cannot be published to [Pypi](https://pypi.org/) because that Wheel isn't guaranteed to work on other Linux distros. However, the alternative is to build a Wheel inside a really old Linux environment that only has access to a restricted set of external libraries. That is due to the efforts of the [manylinux](https://github.com/pypa/manylinux) project. As far as I can tell, only a manlinux Wheel can be published to Pypi. Therefore, the python-sfml project needs access to an SFML build that statically links against the necessary media libraries.

## Your environment

* CentOS 5
* 2.3.2
* GCC

## Steps to reproduce

The specific issue that I'm running into currently is that the SFML build that I downloaded from [here](https://www.sfml-dev.org/download/sfml/2.3.2/) is linked against some external libraries. In the manylinux environment, we're not allowed to have much external libraries at all. So my build is failing because gcc can't find the necessary external libraries.

My TravisCI build script can reproduce the issue. [Here](https://github.com/jawaff/python-sfml/blob/master/scripts/build_linux_wheels.sh) is the specific script that is creating the manylinux Wheel.
[This](https://travis-ci.org/jawaff/python-sfml/builds/449155439) is a specific build where I'm running into my problems -- at the bottom an error says, that "libopenal.so.1" can't be found.

## Expected behavior

SFML should statically link against external libraries for its Linux builds -- all other OS environments for SFML seem to go the static linking route. The external libraries may be provided on modern Linux distros, but may not be present on others -- CentOS 5 doesn't have access to the correct openAL libraries for SFML-2.3.2. 

## Actual behavior

The Linux build of [SFML-2.3.2](https://www.sfml-dev.org/download/sfml/2.3.2/) is dependent on external libraries that are built into the build machine's Linux distro -- whatever that may be. This prevents python-sfml from utilizing SFML's Linux builds.

**Comment by jawaff** [comment]
I'm going to have to build SFML-2.3.2 with the static dependencies anyway, but it might be helpful in the future if SFML made the switch.

**Comment by jawaff** [comment]
If it's not too much trouble, then can someone point me in the right direction for statically linking those external dependencies? I saw the place in the CMakeList.txt file where the dependencies should be installed. My main issue is that I'm not sure what version of those dependencies SFML-2.3.2 is actually built off of. If I knew the Linux distro/version for the build machine, then I could probably find out.

**Comment by MarioLiebisch** [comment]
Is there any specific reason you want to build 2.3.2 over 2.5.1?

Besides that, easiest solution for this is to utilize CMake properly:

* Build all your static libraries and install them to a specific path, e.g. `~/static-libs/`.
* When invoking CMake for the first time (i.e. empty build directory), tell it where this is by adding an argument `-DCMAKE_FIND_ROOT_PATH=~/static-libs/`.
* This should then cause it to first look in `~/static-libs/include`, `~/static-libs/lib`, etc.

**Comment by MarioLiebisch** [comment]
Also closing this, as it's not really an issue. Using system provided shared libraries is the intended default behavior as this way you're not only speeding up compiling, you also ensure that patches are applied to all programs once the shared files are update, not just when linking stuff once again.

**Comment by jawaff** [comment]
I'm not the author of the python-sfml project. It was last built against
2.3.2. I'm just trying to get to a point where the Python community can
start building off of SFML in addition to SDL.
