### ISSUE TITLE
Crash SFML 2.5 - Debian 9 stretch

### ISSUE THREAD

**Issue by EArminjon** [SFML/SFML#1513]
Hello,

I tried to run the simple sfml window test but it crash.
I have used sfml 2.4 since one year and I would change to 2.5.1.

I think my environment is incompatible, can you confirm ?

My Environnement:
Linux - Debian 9 
Sfml 2.5.1 / 2.5.0 (from apt repo, 2.4 works)
Glibc 2.24
C++  11
cmake 3.12
No compil flag

My main code:
```
#include <SFML/Graphics.hpp>

int main()
{
	sf::RenderWindow window(sf::VideoMode(800, 600), "My window");
	
	while (window.isOpen())
	{
		sf::Event event;
		while (window.pollEvent(event))
		{
			if (event.type == sf::Event::Closed)
				window.close();
		}
		window.clear(sf::Color::Black);
		
		window.display();
	}
	return 0;
}

```

Error: exit 6

*** Error in `./bin/client': free(): invalid pointer: 0x00005556e91a47d8 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bfb)[0x7f56ae170bfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76fc6)[0x7f56ae176fc6]
/lib/x86_64-linux-gnu/libc.so.6(+0x7780e)[0x7f56ae17780e]
./bin/client(+0x1690)[0x5556e78ef690]
./bin/client(+0x1645)[0x5556e78ef645]
./bin/client(+0x15c8)[0x5556e78ef5c8]
./bin/client(+0x153e)[0x5556e78ef53e]
./bin/client(+0x14dc)[0x5556e78ef4dc]
./bin/client(_ZN2sf6StringD1Ev+0x18)[0x5556e78ef4a4]
./bin/client(+0x133c)[0x5556e78ef33c]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f56ae1202e1]
./bin/client(+0x118a)[0x5556e78ef18a]
======= Memory map: ========
5556e78ee000-5556e78f0000 r-xp 00000000 08:06 1311660                    /home/student/cpp/build/bin/client
5556e7aef000-5556e7af0000 r--p 00001000 08:06 1311660                    /home/student/cpp/build/bin/client
5556e7af0000-5556e7af1000 rw-p 00002000 08:06 1311660                   /home/student/cpp/build/bin/client
5556e9192000-5556e9647000 rw-p 00000000 00:00 0                          [heap]

**Comment by eXpl0it3r** [comment]
Sounds like the version is not compatible. Try building SFML from source.

**Comment by EArminjon** [comment]
Okay it works, thx :)
