### ISSUE TITLE
sf::Shape::draw is private

### ISSUE THREAD

**Issue by Defavlt** [SFML/SFML#1515]
## `sf::Shape::draw` is private

Well, it's `private`. Wouldn't it make more sense if it were `protected`? Especially considering `sf::Drawable::draw` is `protected`

## Usage example

```cpp
struct CustomShape : public sf::Shape {
protected:
    virtual void draw(/* ... */) const override
    {
        /* ... */
        sf::Shape::draw(/* ... */);
        /* ... */
    }
};
```

## Possible solution

Move the [`private` specifier][0] a couple of lines down.

[0]: https://github.com/SFML/SFML/blob/1159ac5c522a4819263ef7fd8628e0ea8d624862/include/SFML/Graphics/Shape.hpp#L268

**Comment by LaurentGomila** [comment]
You're not supposed to override the draw function when you inherit from sf::Shape. What are you trying to achieve?

**Comment by eXpl0it3r** [comment]
As @LaurentGomila said, you shouldn't be overwriting the shape draw function, it's not part of the "interface".

If you have questions regarding usages of different SFML classes, feel free to ask on [the forum](https://en.sfml-dev.org/forums/index.php#c3).
