### ISSUE TITLE
Why is setUniform(..) creating a new std::vector each call?

### ISSUE THREAD

**Issue by eigenbom** [SFML/SFML#1518]
Why is setUniform(..) creating a std::vector each call? The data seems like it's already in the correct layout.

https://github.com/SFML/SFML/blob/1159ac5c522a4819263ef7fd8628e0ea8d624862/src/SFML/Graphics/Shader.cpp#L603

**Comment by LaurentGomila** [comment]
It would work, indeed, but I think casting a Vec2* to a float* is UB in C++. So the answer would be: this is the only standard-compliant way to accomplish this task.

**Comment by eigenbom** [comment]
Ah I see, thanks! I think a small vector optimisation here would improve performance for most cases.
