### ISSUE TITLE
Problem with rwindow.draw()

### ISSUE THREAD

**Issue by EKashpersky** [SFML/SFML#1521]
## Subject of the issue

Problem with rwindow.draw();

### Laptop #1

Linux 4.18.0-11-generic x86_64 / Kubuntu 18.10 / Dolphin / AMD ATI Radeon R7 M265/M365X/M465 / Mesa 18.2.2
SFML 2.5.1
gcc 8.2.0
no special flags

### Laptop #2

Linux 4.18.0-11-generic x86_64 / Kubuntu 18.10 / Dolphin / UHD Graphics 630 / Mesa 18.2.2
SFML 2.5.1
gcc 8.2.0
no special flags

### Laptop #3

Linux 4.18.0-11-generic x86_64 / Kubuntu 18.10 / Dolphin / nVidia GTX 950m / nVidia driver v394 (or smth like this)
SFML 2.5.1
gcc 8.2.0
no special flags

## Steps to reproduce

1. create render window
2. load texture
3. create sprite from texture
4. draw sprite with window.draw()

```cpp
#include <SFML/Graphics.hpp>
#include <thread>

sf::RenderWindow * createWindow(const std::string &title, uint width, uint height) {
  auto* window = new sf::RenderWindow();

  sf::VideoMode vm(width, height, 16);

  sf::ContextSettings settings;
  settings.antialiasingLevel = 4;
  settings.majorVersion = 3;
  settings.minorVersion = 3;
  settings.depthBits = 24;
  settings.attributeFlags = sf::ContextSettings::Core;

  window->setVerticalSyncEnabled(true);
  window->create(vm, title, sf::Style::Default, settings);

  return window;
}

int main () {
  auto* window = createWindow("tmp", 800, 600);

  sf::Texture texture;
  texture.loadFromFile("texture.png");

  sf::Sprite sprite;
  sprite.setTexture(texture);

  window->clear(sf::Color::Black)
  window->draw(sprite);
  window->display();

  std::this_thread::sleep_for(std::chrono::milliseconds(1000));

  texture.copyToImage().saveToFile("saved.png");

  return 0;
}
```

## Expected behavior

Expected sprite to be drawn, and the image to be saved.

## Actual behavior

Nothing is drawn except of black screen and no errors are yelled.
Image is saved successfully, so the problem is not in file/image/texture loader.

**Comment by MarioLiebisch** [comment]
And just to mention it: Right now this is the intended behavior, but only because SFML still uses legacy OpenGL for drawing. Long term plan is to update the graphics library to use modern OpenGL instead.

**Comment by EKashpersky** [comment]
@MarioLiebisch I've tried the sf::ContextSettings::Default and 3.0 ogl, but result was the same.

Forgot to mention.

**Comment by MarioLiebisch** [comment]
Use `window->getSettings()` to retrieve the context settings and see if you get a core context or not. On some systems you might only get a core context based on the version you request.

**Comment by EKashpersky** [comment]
@MarioLiebisch well, when I use default settings, after window is created I get 3.0 ogl and 0(Default context).

**Comment by MarioLiebisch** [comment]
Then drawing should work. What happens if you don't provide context settings? As for debugging, linking a debug build of SFML should be enough.

**Comment by eXpl0it3r** [comment]
I think that's an issue of rendering a single frame. It's not really a use-case we support and is rarely a real use-case. Maybe it's something one can investigate, but it certainly has a very low priority. If you want to investigate it, feel free to do so. If you want it rendered properly, you may want to render the sprite for the time you're now sleeping your thread.

**Comment by MarioLiebisch** [comment]
Just as a random idea. Render to a render texture instead and save it to a file. If it's really just double buffering screwing up some way, this should work properly.

**Comment by EKashpersky** [comment]
I've changed nothing, made make clean & recompiled.
Suddenly code works now on # 1 laptop.

I think I wasn't that attentive while writing programs-prototypes.

Thanks @eXpl0it3r, @MarioLiebisch and @LaurentGomila for your time.
