### ISSUE TITLE
EGl Context EGL_BAD_SURFACE issue when pausing and resuming app and solution

### ISSUE THREAD

**Issue by DanielDorn** [SFML/SFML#1530]
Hello i am current creating a smaller more compact version of SFML mainly for use as my inhouse game engine, i came across a bug with EGLContext and patched it, but seeing as my engines code cant being integrated i would just like to post it as an issue and hopefully someone in the community can create a patch based on my findings,

this effects all versions of SFML supporting android to date, including 2.5.x

under the EGLContext.cpp file

    //-------------------------------------------------------------------
    void EglContext::destroySurface()
    {	
	    eglCheck(eglDestroySurface(m_display, m_surface));
	    m_surface = EGL_NO_SURFACE;

           // Ensure that this context is no longer active since our surface is now destroyed
	   setActive(false);
    }

this code is bugged, you are essentially calling makecurrent with no surface which will in part cause many issues, the solution is pretty simple just move setActive before you destroy the active surface,

    //-------------------------------------------------------------------
    void EglContext::destroySurface()
    {
  	    // Ensure that this context is no longer active since our surface is now destroyed
	    setActive(false);
	
	    eglCheck(eglDestroySurface(m_display, m_surface));
  	    m_surface = EGL_NO_SURFACE;
    }

hope this helps, cheers (=

**Comment by binary1248** [comment]
Should be fixed with #1531.
