### ISSUE TITLE
Android Window waitEvent issues with OpenGL Context

### ISSUE THREAD

**Issue by DanielDorn** [SFML/SFML#1532]
Bug effecting all versions of SFML supporting android,

this bug is caused from ALooper, essentially when waiting for an event rather then polling the android looper prevents the creation of a OpenGL Context till ALooper recieves an event rather then allowing creation at the appropriate time, and this is just one of a few issues caused by this,

The solution is rather simple inside MainAndroid.cpp add the following line of code to the initializeMain function

    ALooper_wake(); this will asynchronously wake the poll 

here is the patch for anyone wishing to fix this bug

	//-------------------------------------------------------------------
	static void initializeMain(ActivityStates* states)
	{
		// Protect from concurrent access
		Lock lock(states->mutex);

		// Prepare and share the looper to be read later
		ALooper* looper = ALooper_prepare(ALOOPER_PREPARE_ALLOW_NON_CALLBACKS);
		states->looper = looper;

		/**
		 * Acquire increments a reference counter on the looper. This keeps android 
		 * from collecting it before the activity thread has a chance to detach its 
		 * input queue.
		 */
		ALooper_acquire(states->looper);
		ALooper_wake(states->looper);

		// Get the default configuration
		states->config = AConfiguration_new();
		AConfiguration_fromAssetManager(states->config, states->activity->assetManager);
	}

Hope this bug helps anyone experiencing issues with waitEvent on android, cheers (=

**Comment by DanielDorn** [comment]
@eXpl0it3r you mislabeled this as sfml-audio when it was sfml-window and sfml-main, just letting you know 😄

**Comment by eXpl0it3r** [comment]
Thanks for raising this issue. Let us know whether the merged change does indeed fix your issue. 🙂 
Happy to receive any other fixes as we're a bit short "staffed" on Android contributors 😅
