### ISSUE TITLE
Setting CMAKE_ANDROID_ARCH_ABI doesn't make a difference 

### ISSUE THREAD

**Issue by Pchovidze** [SFML/SFML#1542]
## Subject of the issue

I'm aware that **armeabi** is no longer supported with the new NDK versions, thats why I`m trying to use **armeabi-v7a** as a CMake flag, but according to the output it still searches for the old non-existent **armabi**

## Your environment

* Windows 7 Ultimate
* [git master](https://github.com/SFML/SFML/commit/489482a630c5286e488ffc270c10562809056d8e)
* MinGW/GCC 6.3.0

## Steps to reproduce

By setting everything up one by one just like described in this [tutorial](https://github.com/SFML/SFML/wiki/Tutorial%3A-Building-SFML-for-Android)

## Expected behavior

cmake -G "MinGW Makefiles" -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_NDK=C:/Android/NDK -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_ANDROID_STL_TYPE=c++_static -DCMAKE_BUILD_TYPE=Debug ../..

Should build everything

## Actual behavior

Cmake Error
Android: No toolchain for ABI 'armeabi' found in the NDK: C:/Android/NDK

**Comment by MarioLiebisch** [comment]
This completely relies on CMake's toolchain file/definition. Is your CMake up to date? And if so, which version is it?

**Comment by Pchovidze** [comment]
Problem solved after updating CMake to the latest version (3.12.2 at the moment).
