### ISSUE TITLE
Images not showing in Views tutorial on Github.

### ISSUE THREAD

**Issue by MrZeusTheCoder** [SFML/SFML#1551]
I just read through the wiki tutorial on SFML Views(very helpful I might add), but the images were not showing: 
![screen shot 2019-01-28 at 7 40 31 pm](https://user-images.githubusercontent.com/37903528/51875780-46867800-2334-11e9-9b17-6c00196f01a3.png)

Though I was able to access the images via the links directly in my browser, though.

**Comment by eXpl0it3r** [comment]
It's an issue with GitHub. The GitHub User Content cache server returns 502 Bad Gateway.
I have contacted GitHub support and will await their response.

In the meantime I've updated the originally linked images to use HTTPS, but that has no effect.

Things related to the Wiki are best asked in the [Wiki sub-forum](https://en.sfml-dev.org/forums/index.php?board=11.0).
