### ISSUE TITLE
Sometimes it works, sometimes not.

### ISSUE THREAD

**Issue by LaurentDuroisin** [SFML/SFML#1555]
Thanks for raising your issue here! 🙂

Before you submit the issue however, we'd like you to consider the follow points.

* We like to use the issue tracker for confirmed issues.
* If you're stuck with SFML, please use [the forum](https://en.sfml-dev.org/forums/index.php#c3) to get help.

----

## Subject of the issue

Sometimes it crash while opengl context creation, sometimes not, sometimes it isn't displaying anything, sometimes it does. I guess it's a problem with opengl context creation.

## Your environment

* Ubuntu 18.04 64 bits and windows7 pro 64 bits.
* 2.5.
* g++4.9
* -std=c++14

## Steps to reproduce

It's difficult to provide a minimal code to reproduce the problem because I haven't problems with a minimal code, the problem comes when I create multiple windows and I add them into a class by example (crash at the opengl context creation), or when I create RenderTexture into a class.
Sometimes I can't draw to them because the opengl context is not valid.
I looked into opengl context creation with SFML and the code is very weird.
To solve those problems I tried to encode my own window module with a simple opengl context creation as explained here for context with windows : 

https://www.khronos.org/opengl/wiki/Tutorial:_OpenGL_3.0_Context_Creation_(GLX) 

And here for contexts without windows :

https://sidvind.com/wiki/Opengl/windowless

Without transcient contexts, shared contexts and glx initialization functions with globalInit.

But it doesn't solve anything because it's not compatible with the SFML graphic module, it even fails to create the frame buffer object, and the max texture size returned is only 250x250.
I tried other libs but it doens't seems there is one which is compatible with the SFML graphic module (I had to code it again for displaying 3D vertices)

And it seems we can't include <X11/xlib.h> otherwise there are conflits with SFML enums. (None, Status and BadRequest), forward declarations doesn't works too because declaring XVisualInfo gets me a compilation error. (conflict definition of the struct, previously defined in X11) 

And on windows it doens't display shadows and lights. 
And when I use simple variables (without copying it) instead of pointers to the render textures and shaders on linux, it doesn't display shadows.

Sometimes it works, sometimes not. I don't use opengl outside of SFML, so the opengl contexts should be correctly activated but it's not always the case. 

I really don't know what to do.
 
## Expected behavior

Create valid opengl contexts.

## Actual behavior

The opengl contexts created are not valid.

**Comment by eXpl0it3r** [comment]
Please use [the forum](https://en.sfml-dev.org/forums/index.php#c3) for such questions. 🙂 

Sounds like you aren't handling the activation of the context, see also: https://www.sfml-dev.org/tutorials/2.5/window-opengl.php#managing-opengl-contexts
