### ISSUE TITLE
assert in src/SFML/graphics/text.cpp

### ISSUE THREAD

**Issue by gmcode** [SFML/SFML#1558]
* Your OS / distro / window manager used:
Windows 7
* Your version of SFML (2.5.0, git master, etc)
git master
* Your compiler and compiler version used
VS2019

In src\SFML\Graphics\Text.cpp

                if (m_outlineVertices.getVertexCount() > 0)
Line 241 has this line:
                    m_outlineVerticesBuffer.update(&m_outlineVertices[0]);
The above line triggers an assert when m_outlineVertices is empty.
Because address of item at index 0 isn't a legal statement to make in such a situation.

I believe it needs something like this:
                if (m_outlineVertices.getVertexCount() > 0)
                    m_outlineVerticesBuffer.update(&m_outlineVertices[0]);
Or possibly a line like this:
                    m_outlineVerticesBuffer.update(
                        m_outlineVertices.getVertexCount() > 0 ? &m_outlineVertices[0] : nullptr
                    );
There are other parts of the codebase that could use similar guards.
Thanks.

**Comment by binary1248** [comment]
Should be fixed with #1560.
