### ISSUE TITLE
Use GNUInstallDirs in CMake for install flexibility

### ISSUE THREAD

**Issue by eliasdaler** [SFML/SFML#1563]
Right now, we have a lot of folders hard coded for install rules [here](https://github.com/SFML/SFML/blob/6d8143088ec8ffc31a12ee3a9a60119474407872/cmake/Macros.cmake#L176). I think that for that, we can use [GNUInstallDirs](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) module which sets a lot of sensible defaults which can easily be redefined as needed, e.g. if you want libraries to go to some other place than `${CMAKE_INSTALL_PREFIX}/lib`, you'll be able to set `${CMAKE_INSTALL_LIBDIR}`.

This will make lives of our *BSD folks easier, plus it will allow users of some unconventional distros to be able to configure install directories as they want.

Thoughts?

(Related to #189, #1561, #1510)

**Comment by LaurentGomila** [comment]
We're happily using that at work to simplify the install configuration. It works fine for our needs on Windows/Linux/MacOS.

**Comment by JonnyPtn** [comment]
Should be a pretty straightforward change, just need to clarify which variables should be used for what. So I think these are the ones we want to replace, and my suggested replacements. Once the SFML team confirm these a PR can be done pretty quickly

* `lib` replace with `CMAKE_INSTALL_LIBDIR`
* `SFML_DEPENDENCIES_INSTALL_PREFIX` : replace with `CMAKE_INSTALL_LIBDIR`
* `SFML_MISC_INSTALL_PREFIX`: replace with
    * `CMAKE_INSTALL_INFODIR` for the license/readme
    *  `CMAKE_INSTALL_DOCDIR` for the docs
* `bin`: replace with `CMAKE_INSTALL_BINDIR`

Not sure what we should do with `SFML_PKGCONFIG_INSTALL_PREFIX`?

**Comment by eliasdaler** [comment]
I think for pkg-config files, it'll be good to use ```${CMAKE_INSTALL_LIBDIR}/pkgconfig``` as the default, but still make it configurable (right now, I have lots of *.pc files in /usr/local/lib/pkgconfig and in /usr/lib/...)

**Comment by eXpl0it3r** [comment]
Don't forget the considerations that were taken into account for the current PKGCONFIG setup in #1433 / #1466 and others. 😉

**Comment by eXpl0it3r** [comment]
Fixed with #1576
