### ISSUE TITLE
it's not an issue but my account to the forum was deleted.

### ISSUE THREAD

**Issue by LaurentDuroisin** [SFML/SFML#1564]
I know it's not an issue but my forum account was deleted when I was saying that SFML is bugged, it's just to say I recoded the window module of SFML (not entierly, just the linux part and only functionalities I use) and it solved the issue.

**Comment by eXpl0it3r** [comment]
Accounts are usually only delete if they either:

- Repeatedly violate the rules
- The account showed all signs of a spam account (e.g. non-sense posts, links to odd sites, etc)

If you think that your account deletion was not correct, please reach out to webmaster@sfml-dev.org with your account name and forum post content.
