### ISSUE TITLE
Building SFML from source - running examples missing resources folder

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [SFML/SFML#1567]
## Build from source  - examples are missing resource folder

After using cmake and make to build and install, the examples were built but the ones that needed resources like fonts and shaders, could not run because the `/resources` folder was missing.

## Your environment

* Latest Ubuntu, X11
* master branch
* Ubuntu 7.3.0 g++

## Steps to reproduce

Install all dependencies using `apt`
Use the cmake gui and follow the official doc on building with cmake
Run make all
Run make install
Cd to the examples folders and run the binaries

## Expected behavior

Examples requiring resources should run or at least have the resources folder made available to copy

## Actual behavior

Program fails to run - missing resources

**Comment by TheMaverickProgrammer** [comment]
The resources folders are in the forked SFML file, just not next to the built binaries which was a little misleading but it's there to copy. Nvm

**Comment by eXpl0it3r** [comment]
If you build the INSTALL target, they will be copied.
