### ISSUE TITLE
Can't set a completely transparent image with sf::Cursor under Windows.

### ISSUE THREAD

**Issue by eigenbom** [SFML/SFML#1571]
In Windows, setting a completely transparent cursor using sf::Cursor::loadFromPixels doesn't work. This is because:

> When the window manager sees a 32bpp bitmap, it looks at the alpha channel. If it’s all zeroes, then it assumes that the image is in 0RGB format; (from https://devblogs.microsoft.com/oldnewthing/?p=12483)

**Comment by eigenbom** [comment]
The solution may be to create an appropriate mask, although my initial attempts failed. Here's some related code: [https://github.com/adobe/chromium/blob/master/ui/gfx/icon_util.cc](https://github.com/adobe/chromium/blob/master/ui/gfx/icon_util.cc#L78)

The easiest workaround may be to just detect for this special case and create a blank cursor.

**Comment by LaurentGomila** [comment]
Why would you want to create a completely transparent cursor?

**Comment by MarioLiebisch** [comment]
Think this might warrant a short note in the docs, but wouldn't consider it an actual issue. It's a platform thing after all. Just for comparison, for file system operations, SFML doesn't check whether your provided paths have invalid characters in them, it just passes it without checks or sanitizing them.

**Comment by eigenbom** [comment]
Ok I spent enough time investigating this. Seeya.
