### ISSUE TITLE
website not working

### ISSUE THREAD

**Issue by JeanMarcZimmer** [SFML/SFML#1572]
I keep getting gateway errors from https://www.sfml-dev.org/ , what is going on ?

I hope it's just temporary, as I'm in a game jam right now, and an inaccessible documentation is annoying.

**Comment by eXpl0it3r** [comment]
We're currently experiencing a DDoS attack and are looking into mitigation options.
Check Twitter for further updates: https://twitter.com/sfmldev/status/1107972526012022784

Note that you can easily build the SFML documentation from source. You can also grab the SFML 2.5 documentation from [here](http://mirror2.sfml-dev.org/files/SFML-2.5.0-doc.zip). 🙂
