### ISSUE TITLE
undefined reference to sf::FileInputStream and sf::String

### ISSUE THREAD

**Issue by linkdd** [SFML/SFML#1586]
When linking my shared library (that depends on SFML) to my executable, I get only 2 undefined references:

```
_build/linux/engine/***.so: undefined reference to `sf::FileInputStream::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
_build/linux/engine/***.so: undefined reference to `sf::String::String(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::locale const&)'
```

## Environment

* OS: Debian 9
* SFML: 2.5.1
* CLang 9

## Steps to reproduce

Command used to link:

```
clang++-9 $OBJECTS -lc++ -L_build/linux/engine -l*** -Lvendor/sfml/lib/linux -Wl,-rpath=vendor/sfml/lib/linux -lsfml-graphics -lsfml-window -lsfml-audio -lsfml-network -lsfml-system -o _build/linux/game/***
```

## Expected behavior

Either my linking options are wrong and I should get an undefined reference for every SFML function I use in my library, or it should link propery

**Comment by LaurentGomila** [comment]
Maybe these are the only functions that you use that have _std::string_ parameters, and your standard library is not compatible with the one SFML was compiled with.

You should recompile SFML if using a different compiler and/or standard library.

**Comment by linkdd** [comment]
Seems legit, I have been using the GCC/MingW binaries and building with CLang.

I shall include the sources in my project then and retry.

Thank you for the hint.
