### ISSUE TITLE
How to switch from GLES to GLES2 and GLES3 headers ?

### ISSUE THREAD

**Issue by RsPlayer** [SFML/SFML#1587]
I use Ubuntu and ubuntu has libGLESv1_CM shared lib but doesn't provide GLES headers. I tried to search for it and it seems libgles1-mesa-dev is no longer avaible. how to make SFML work for GLES2 on linux? is it supported?

**Comment by binary1248** [comment]
This issue tracker is for confirmed and/or reproducible bugs. All support enquiries should go to the SFML forum.

SFML currently does not support OpenGL ES 2 or 3. Support for it might come in the future.

It is recommended to not use OpenGL ES on a desktop system that can provide desktop OpenGL (non ES) anyway. If your system supports desktop OpenGL, build SFML without OpenGL ES support.
