### ISSUE TITLE
Scalar operations with Vector

### ISSUE THREAD

**Issue by Ok23** [SFML/SFML#1588]
Add scalar operations to vectors like: Vector /= 2

**Comment by LaurentGomila** [comment]
They are all defined. So either you didn't read the doc before asking, or I don't understand what you're trying to request.

**Comment by eXpl0it3r** [comment]
See also the documentation: https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Vector2.php#ac4d293c9dc7954ccfd5e373972f38b03

**Comment by Ok23** [comment]
> See also the documentation: https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Vector2.php#ac4d293c9dc7954ccfd5e373972f38b03

Sorry, i'm trying divide Vector2f by integer but not float
