### ISSUE TITLE
rotating image around center with setOrigin() causing issues in SFML C++

### ISSUE THREAD

**Issue by Daragh-Keating** [SFML/SFML#1589]
void draw(RenderWindow &window)
{
Texture t;
t.loadFromFile("../Images/" + fileName);
Sprite s;
s.setTexture(t);
s.setScale(size.x/t.getSize().x, size.y/t.getSize().y);
s.setOrigin(size.x/4,size.y/4);
s.setPosition(position.x,position.y);
s.setRotation(angle);
window.draw(s);
CircleShape c; // drawing centerpoint
c.setRadius(2);
c.setFillColor(Color::Red);
c.setPosition(position);
window.draw(c);
}

this is the function I am using to draw an object class. I can set an image and I want it to draw the image at a position at a certain size and rotation with a centerpoint in the middle of the image. When I can't setOrigin() without the position getting screwed up though.

![screencap](https://user-images.githubusercontent.com/51334559/58820488-a797c280-862a-11e9-925e-2c68862114b6.png)

this image shows two objects being drawn. the top one is of size 75 x 75 and isn't rotated, the second and lower one is of size 50 x 50. The centerpoint is drawn as a red circle.
My issue is that the texture isn't being drawn with the centerpoint in the center of the image do you know how to fix this? Thanks so much

**Comment by LaurentGomila** [comment]
The origin must be given in *local* coordinates. So if you want it to be at the center of the sprite, you should use `getLocalBounds().width / 2` (same for height), and never something related to a scaled size.

Next time please use the forum, this tracker is for tasks (confirmed bugs to fix, improvements), not for asking help.
