### ISSUE TITLE
Failure To Find Freetype Using VCPKG x64-windows-static

### ISSUE THREAD

**Issue by esduran** [SFML/SFML#1595]
Thanks for raising your issue here! 🙂

Before you submit the issue however, we'd like you to consider the follow points.

* We like to use the issue tracker for confirmed issues.
* If you're stuck with SFML, please use [the forum](https://en.sfml-dev.org/forums/index.php#c3) to get help.

----

## Subject of the issue
I am trying to build my CMake project using the latest version of vcpkg as my package manager with SFML:x64-windows-static but I get the following error:

`[cmake] CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):`
`[cmake]   Could NOT find Freetype (missing: FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)`
`[cmake] Call Stack (most recent call first):`
`[cmake]   C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)`
`[cmake]   C:/Program Files/CMake/share/cmake-3.15/Modules/FindFreetype.cmake:157 (find_package_handle_standard_args)`
`[cmake]   C:/Program Files/CMake/share/cmake-3.15/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)`
`[cmake]   C:/Users/esteban.duran/vcpkg/installed/x64-windows-static/share/sfml/SFMLConfig.cmake:3 (find_dependency)`
`[cmake]   CMakeLists.txt:87 (find_package)`

Describe your issue here.

## Your environment
* Windows 10
* Vcpkg package management program version 2019.06.21-nohash
* SFML 2.5.1 from vcpkg x64-windows-static
* CMake 3.15
* Visual Studio Community 2019 amd64 (MSVC 16)

## Steps to reproduce
In my CMakeLists.txt file I set the following
`set(VCPKG_TARGET_TRIPLET x64-windows-static)`
`set(CMAKE_PREFIX_PATH ${VCPKG_ROOT}/installed/x64-windows-static/share)`

Then I set:
`find_package(SFML COMPONENTS system window graphics REQUIRED`

Then I try to build (with the VCPKG toolchain path set) and I get the build error.

**Comment by esduran** [comment]
I decided to just go with the sfml:x64-windows version instead of the sfml:x64-windows-static version. That worked out of the box.

**Comment by eXpl0it3r** [comment]
Sounds like an issue with the VCPKG, as such I suggest to open an issue on the VCPKG repository. I'll close this for now, but feel free to reopen if it turns out to be something that we need to fix on our end.

**Comment by RichardDally** [comment]
Hello, issue is still happening, I've opened this https://github.com/microsoft/vcpkg/issues/25780
