### ISSUE TITLE
some images are missing at wiki

### ISSUE THREAD

**Issue by masums** [SFML/SFML#1598]
Some images are missing at wiki. Please see the following page
[https://github.com/SFML/SFML/wiki/Source%3A-Color-Gradient](https://github.com/SFML/SFML/wiki/Source%3A-Color-Gradient)

Also have broken images at some other wiki pages.

**Comment by eXpl0it3r** [comment]
The wiki is a community Wiki and not officially maintained. If images can't be found, it means that the original author has deleted the images from wherever they linked it from.

Feel free to hunt down the different images and upload them directly to the wiki, so they don't get lost anymore. 😉 

Also such reports are better done on [the forum](https://en.sfml-dev.org/forums/index.php?board=11.0) as we try to reserve this issue tracker for confirmed issues about the library itself.
