### ISSUE TITLE
Bag in my project

### ISSUE THREAD

**Issue by Aplaus228** [SFML/SFML#1599]
Hello, I develop my simple game and I have a small bag.
When I run my application my sprite invisible, but when I push (up, down, left, right) my sprite starts rendering.
thank you 

`#include "pch.h"
#include <iostream>
#include <SFML/Graphics.hpp>
#include <string>

class Player {
public:
	float x, y, w, h, dx, dy, speed;
	int dir;
	std::string File;
	sf::Image image;
	sf::Texture texture;
	sf::Sprite sprite;

	Player(std::string path, float X, float Y, float W, float H) :
		dx(0), dy(0), speed(0), dir(0), File(path), w(w), h(H),
	x(X), y(Y)
	{
		image.loadFromFile("../img/" + File);
		image.createMaskFromColor(sf::Color(41, 33, 59)); // delete dark blue color

		texture.loadFromImage(image);
		sprite.setTexture(texture);
		sprite.setTextureRect(sf::IntRect(0.0, 0.0, w, h));
		sprite.setPosition(x, y);
	}

	void update(float time) {
		switch (dir) {
		case 0 :
			dx = speed;
			dy = 0;
			break;
		case 1:
			dx = -speed;
			dy = 0;
			break;
		case 2:
			dy = speed;
			dx = 0;
			break;
		case 3:
			dy = -speed;
			dx = 0;
			break;
		}
		x += dx * time;
		y += dy * time;
		speed = 0;
		sprite.setPosition(x, y);
	}

};

int main()
{
	sf::RenderWindow window(sf::VideoMode(640, 480), "HEro world");

	float currentFrime = 0;// variable for animation

	Player player("hero.png", 250, 250, 96.0, 96.0); //

	sf::Clock clock;
	

	while (window.isOpen())
	{

		float time = clock.getElapsedTime().asMicroseconds();
		clock.restart();
		time = time / 800;

		sf::Event event;

		while (window.pollEvent(event))
		{
			if (event.type == sf::Event::Closed)
				window.close();

		}

		if (sf::Keyboard::isKeyPressed(sf::Keyboard::Left)) {
			player.dir = 1;
			player.speed = 0.1;
			currentFrime += 0.005*time;
			if (currentFrime > 3) {
				currentFrime -= 3;
			}
			player.sprite.setTextureRect(sf::IntRect(96 * static_cast<int>(currentFrime), 96, 96, 96));
		}

		if (sf::Keyboard::isKeyPressed(sf::Keyboard::Right)) {
			currentFrime += 0.005*time;
			player.dir = 0;
			player.speed = 0.1;
			if (currentFrime > 3) {
				currentFrime -= 3;
			}
			player.sprite.setTextureRect(sf::IntRect(96*static_cast<int>(currentFrime), 192, 96, 96));
		}
		if (sf::Keyboard::isKeyPressed(sf::Keyboard::Up)) {
			currentFrime += 0.005*time;
			player.dir = 3;
			player.speed = 0.1;
			if (currentFrime > 3) {
				currentFrime -= 3;
			}
			player.sprite.setTextureRect(sf::IntRect(96 * static_cast<int>(currentFrime), 288, 96, 96));
		}
		if (sf::Keyboard::isKeyPressed(sf::Keyboard::Down)) {
			currentFrime += 0.005*time;
			player.dir = 2;
			player.speed = 0.1;
			if (currentFrime > 3) {
				currentFrime -= 3;
			}
			player.sprite.setTextureRect(sf::IntRect(96 * static_cast<int>(currentFrime), 0, 96, 96));
		}
		
		player.update(time);

		window.clear();
		window.draw(player.sprite);
		window.display();
	}

	return 0;
}

`

**Comment by eXpl0it3r** [comment]
Please use the forum to discuss issues with your project, as we like to keep this issue tracker for confirmed issues with SFML itself.

https://en.sfml-dev.org/forums/index.php#c3

PS: You probably meant bug and not bag 😉
