### ISSUE TITLE
Loading textures before a RenderWindow is made breaks things on Linux


### ISSUE THREAD

**Issue by Jookia** [SFML/SFML#160]
Here's a simple piece of test code: http://www.mediafire.com/?19bc9h2py839e2a

**Comment by MGNeo** [comment]
Hello, guys.

I have the same problem.

OS: Windows 10
SFML: 2.5.1
PC: A715-72G-518Z (has two video cards)

I create sf::Texture then load it from file and all very well. But If I try to copy loaded texture (to std::map) before creating of render window I get next error:

```
An internal OpenGL call failed in Texture.cpp(98).

Expression:
    glFlush()
Error description:
    GL_INVALID_OPERATION
    The specified operation is not allowed in the current state.

An internal OpenGL call failed in Texture.cpp(98).
Expression:
   glFlush()
Error description:
   GL_INVALID_OPERATION
   The specified operation is not allowed in the current state.

```
Next code allows to reproduce the problem:

```
std::map<std::string, sf::Texture> textures;
sf::Texture texture;

if (texture.loadFromFile("texture.bmp") == true)
{
    textures.insert({"texture.bmp", texture});// We get error from here.
}
```

Sorry for my English :-) I am Russian.
