### ISSUE TITLE
How to set port in http post reqest?

### ISSUE THREAD

**Issue by uuuvn** [SFML/SFML#1602]
How to set port in http post reqest?
I use SFML/Network.h

**Comment by eXpl0it3r** [comment]
Please use the [forum](https://en.sfml-dev.org/forums/index.php#c3) to ask question as we like to keep this issue tracker for confirmed issues with SFML itself.

See also the [setHost function](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Http.php#a55121d543b61c41cf20b885a97b04e65) in `sf::Http`.
