### ISSUE TITLE
Fullscreen spans over multiple monitors

### ISSUE THREAD

**Issue by naezith** [SFML/SFML#1607]
## Subject of the issue

Fullscreen is running on multiple monitors, spanning. On Linux, many people including me have this issue, maybe 100% guaranteed. But only one player has this issue in Windows

## Your environment

* Windows & Linux
* 2.5.0
* MinGW64 latest
* Nvidia GTX 1070 from Windows user, any other Nvidia card for Linux

## Steps to reproduce

Have multiple monitors and run the program in fullscreen.

```cpp
#include <SFML/Graphics.hpp>

int main() {
    sf::RenderWindow window(sf::VideoMode(1920, 1080), "Fullscreen issue", sf::Style::Fullscreen);

    while (window.isOpen()) {
        sf::Event event;
        while (window.pollEvent(event)) {
            if(event.type == sf::Event::Closed) window.close();
        }

        window.clear();
        window.display();
    }
}
```

## Expected behavior

Work on main monitor only.

## Actual behavior

Fullscreen spans over all monitors, resolution does not matter, like even if it's 1920x1080.

**Comment by pawankholiya01** [comment]
//
    3 // SFML - Simple and Fast Multimedia Library
    4 // Copyright (C) 2007-2018 Laurent Gomila (laurent@sfml-dev.org)
    5 //
    6 // This software is provided 'as-is', without any express or implied warranty.
    7 // In no event will the authors be held liable for any damages arising from the use of this software.
    8 //
    9 // Permission is granted to anyone to use this software for any purpose,
   10 // including commercial applications, and to alter it and redistribute it freely,
   11 // subject to the following restrictions:
   12 //
   13 // 1. The origin of this software must not be misrepresented;
   14 //    you must not claim that you wrote the original software.
   15 //    If you use this software in a product, an acknowledgment
   16 //    in the product documentation would be appreciated but is not required.
   17 //
   18 // 2. Altered source versions must be plainly marked as such,
   19 //    and must not be misrepresented as being the original software.
   20 //
   21 // 3. This notice may not be removed or altered from any source distribution.
   22 //
   24 
   25 #ifndef SFML_WINDOWSTYLE_HPP
   26 #define SFML_WINDOWSTYLE_HPP
   27 
   28 
   29 namespace sf
   30 {
   31 namespace Style
   32 {
   38     enum
   39     {
   40         None       = 0,      
   41         Titlebar   = 1 << 0, 
   42         Resize     = 1 << 1, 
   43         Close      = 1 << 2, 
   44         Fullscreen = 1 << 3, 
   45 
   46         Default = Titlebar | Resize | Close 
   47     };
   48 }
   49 
   50 } // namespace sf
   51 
   52 
   53 #endif // SFML_WINDOWSTYLE_HPP

yes it has a problem, even fullscreen is not part of Default

**Comment by eXpl0it3r** [comment]
What Linux distro are you using? What window manager are you using? What's your DISPLAY settings?

> yes it has a problem, even fullscreen is not part of Default

That's intentional

**Comment by eXpl0it3r** [comment]
Closing this for now, as no additional information was provided.

A common mistake (novice) Linux users make, is to have their xrandr setting misconfigured. If you tell your window manager that it should treat your multiple monitors as one surface, then SFML will span across multiple monitors in fullscreen mode, as the OS/window manager is serving the single surface as one "monitor".
