### ISSUE TITLE
Documentation misleading concerning the order when combining transforms

### ISSUE THREAD

**Issue by pvigier** [SFML/SFML#1608]
Hello,

If I understand well the source code of `sf::Transform`, when we do:

```cpp
auto A = sf::Transform(...);
auto B = sf::Transform(...);
auto C = A.combine(B);
```
C is equal to A*B with * the matrix multiplication.

And when we want to transform a point:

```cpp
auto u = sf::Vector2f(...);
auto v = C.transformPoint(u);
```
We have v = A\*B\*u.

So it is B that is applied first on u, then A.

However, in the documentation of [combine](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Transform.php#acd978f60421a0f839bb9a8263e8877ff), it is said that:

> The result is a transform that is equivalent to applying *this followed by transform. 

According, to this sentence, C would be equal to B*A (applying A followed by B). I think it is misleading.

Correct me if I am wrong.

Best regards,
Pierre

**Comment by LaurentGomila** [comment]
I don't remember this kind of stuff that was written a long time ago, so the best thing would probably be to test it. A rotation combined with a translation should be a good case to figure out which one is applied first.

**Comment by pvigier** [comment]
Indeed, I have done exactly that before posting to be sure.

Here is the snippet:

```cpp
auto transform = sf::Transform();
transform.translate(2.0f, 3.0f);
transform.rotate(90.0f);
```

Then, I print the entries of the matrix:

```
-4.37114e-08 -1 0 2 
1 -4.37114e-08 0 3 
0 0 1 0 
0 0 0 1 
```

Which corresponds to rotation first, translation then.

I think that the tutorial on [transforms](https://www.sfml-dev.org/tutorials/2.5/graphics-transform.php) is also misleading. It is said that :

>  You can apply several predefined transformations to the same transform as well. They will all be combined sequentially: 

I think it should be written: "They will all be combined sequentially in reversed order".

**Comment by Bromeon** [comment]
Thanks for the report, I created a PR to address this.
