### ISSUE TITLE
Add the possibility to get a glyph by its index in sf::Font

### ISSUE THREAD

**Issue by JoaoBaptMG** [SFML/SFML#1615]
This is a necessity that has arisen in a game I was developing a year ago. I am using [HarfBuzz](https://github.com/harfbuzz/harfbuzz) to be able to handle text in different scripts in different languages. The goal is to be able to output text in any language, utilizing any script and complex fonts shapes.

The issue I got through (and that had me modify SFML) is that `sf::Font`'s `getGlyph` accepts _Unicode code points_, whereas HarfBuzz's `hb_shape` method returns _glyph indices_, and thus it is impossible to pass those to `getGlyph`.

I am proposing (code in a pull request) to add another function (not so conveniently called `getGlyphId`) that allows me to get information about the glyph using the glyph index, instead of the code point.

The important code (that would demonstrate its ability) is [this one](https://github.com/JoaoBaptMG/ReboundTheGame/blob/master/MainGame/drawables/TextDrawable.cpp#L197-L223):

    auto prop = wrapper.shape(curPos, nextWordPos - curPos);
    for (const auto& glyphData : prop.glyphs)
    {
        // Even though here I call the index as code point, it is really the glyph index,
        // I need to change it in my next commit
        uint32_t c = glyphData.codepoint;
        size_t cluster = glyphData.cluster;

        if (outline)
        {
            auto tempPos = position + glyphData.offset - sf::Vector2f(outlineThickness, outlineThickness);
            const auto& glyph = font.getGlyphId(c, fontSize, false, outlineThickness);
            addGlyphQuad(verticesOutline, tempPos, defaultOutlineColor, glyph);
        }

        const auto& glyph = font.getGlyphId(c, fontSize, false);
        auto p = addGlyphQuad(vertices, position + glyphData.offset, defaultColor, glyph);

        position += glyphData.advance;
        // ...
    }

Here, `wrapper.shape` is just a wrapper over HarfBuzz's API. Its implementation can be found [here](https://github.com/JoaoBaptMG/ReboundTheGame/blob/master/MainGame/unicode/HarfBuzzWrapper.cpp#L48-L84).

**Comment by LaurentGomila** [comment]
Thanks for your feedback. However you don't have to open an issue if you already have a PR ; I close this one, so that discussions about your modifications are not split.
