### ISSUE TITLE
Window larger than desktop size gets truncated on Linux/KDE

### ISSUE THREAD

**Issue by isage** [SFML/SFML#1617]
## Window larger than desktop size gets truncated on Linux/KDE

My desktop size is 1920x1080.
While trying to create window larger than this, it gets truncated.
E.g.
```
window.create(sf::VideoMode(3534, 550), "My window");
```
Height is ok, since it's smaller that desktop, but width is only 1920. Even if i resize the window afterwards (by hand, or by code) it's initial size stays truncated, so coordinate conversion doesn't work and image i'm drawing as background (which is 3534x550) stays truncated on right.
This seems to be Linux (or KDE)-only issue, because i can't reproduce it on windows.

## Environment

* Linux Fedora 30, KDE Plasma
* SFML 2.5.1
* gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC)

## Steps to reproduce

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(3534, 550), "Minimal, complete and verifiable example");
    window.setFramerateLimit(60);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.display();
    }
}
```

## Expected behavior

Window is created with size 3534x550

## Actual behavior

Window is created with size 1920x550

**Comment by isage** [comment]
UPD: this doesn't happen with SDL2, so it doesn't look like it's a KDE Plasma bug.

**Comment by isage** [comment]
I can also reproduce in in LXQT, and with latest master.

**Comment by isage** [comment]
Creating window without Style::Resize set creates large window as intended, but i can't resize it, of course.

**Comment by isage** [comment]
Damn, i was wrong, it doesn't work with SDL2 if i create resizable window.

**Comment by isage** [comment]
Digging into hell that xlib is, it doesn't seem possible to programmaticaly forbid every WM to auto-maximize window on start.
The main issue is that it breaks scaling and coordinate conversion.
So, i would be satisfied with a fix, that creates smaller window than requested (constrained by desktop size), but scales contents accordingly and keeps coordinate conversion working.
Sorry about lots of comments.

**Comment by eXpl0it3r** [comment]
As you noticed yourself, we can't really force the WM to just do stuff. Creating windows that are larger than the screen resolution isn't really a supported use case. It can also cause focus issues on Windows.
Keeping the scaling even if the WM provides a different window size doesn't really seem like a good idea, even if it might be so for your own use case. In the end setting a video mode is just a request/suggestion to the OS/WM and not enforced values (similar to requesting a specific OpenGL version).

If you want something scaled differently than the window size, then you really should be doing this manually with a view and not rely on SFML to provide a broken scaling.
