### ISSUE TITLE
2.5.1: Pre-compiled version for Visual Studio 2019

### ISSUE THREAD

**Issue by pfpoitras** [SFML/SFML#1620]
Hello all,

I was wondering if anyone knows what the process would be to add a Visual Studio 2019 pre-compiled library on the website (like there is for the other VS versions) 

VS2019 came out after 2.5.1, so I'm not sure if we're just waiting on the next stable version to get VS2019 on board, or if it just isn't supported yet. 

I have downloaded VS2019, and have successfully compiled it. I wouldn't mind running any tests and/or doing any other required work to make it happen if someone pointed me in the right direction.

**Comment by MarioLiebisch** [comment]
Visual Studio 2015, 2017, and 2019 are binary compatible, which is the reason there's no new/extra download. Although this could be marked more clearly on the downloads page.

**Comment by pfpoitras** [comment]
Ah, this explains it. Thanks!
