### ISSUE TITLE
find_package(Vorbis REQUIRED) fail quietly

### ISSUE THREAD

**Issue by Hinara** [SFML/SFML#1626]
## Subject of the issue

find_package(Vorbis REQUIRED) fail quietly, and make fail configuration later in the process

CMake is case-sensitive however VORBIS is used instead of Vorbis in FindVorbis.cmake file which cause it to not see the Vorbis_FIND_REQUIRED which should make the configuration failed on `find_package(Vorbis REQUIRED)` and not later when using variables

Possible fixes
- Change FindVorbis.cmake to FindVORBIS.cmake and use `find_package(VORBIS REQUIRED)` instead
- Use `Vorbis*` variables instead of `VORBIS*` ones in FindVorbis (requires to fix cmake using old variables)

## Your environment

OS:Ubuntu 18.04
SFML: master(80c3bdc23c1874494196bbf8a481a859712ece88)
Compiler: Not relevant

## Steps to reproduce

Have libvorbis installed without libvorbis-dev

## Expected behavior

```
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Vorbis (missing: VORBIS_INCLUDE_DIR VORBIS_LIBRARY
  VORBISFILE_LIBRARY)
```

## Actual behavior

```
CMake Error at cmake/Macros.cmake:333 (message):
  Missing item in
  VORBISENC_LIBRARY-NOTFOUND;VORBISFILE_LIBRARY-NOTFOUND;VORBIS_LIBRARY-NOTFOUND;/usr/lib/x86_64-linux-gnu/libogg.so
```

**Comment by Bromeon** [comment]
Looking at [FindVorbis.cmake](https://github.com/SFML/SFML/blob/master/cmake/Modules/FindVorbis.cmake#L25), the uppercase CMake package `VORBIS` is searched, and variables referring to it also use upper case:

    find_package_handle_standard_args(VORBIS DEFAULT_MSG VORBIS_LIBRARIES VORBIS_INCLUDE_DIR OGG_INCLUDE_DIR)
    set(VORBIS_INCLUDE_DIRS ${OGG_INCLUDE_DIR} ${VORBIS_INCLUDE_DIR})

The Vorbis package is found at [this line in the Audio config](https://github.com/SFML/SFML/blob/master/src/SFML/Audio/CMakeLists.txt#L70):

    sfml_find_package(Vorbis INCLUDE "VORBIS_INCLUDE_DIRS" LINK "VORBIS_LIBRARIES")

But here we use the uppercase variables as exported in `FindVorbis.cmake`. If we changed the line to `sfml_find_package(VORBIS...`, then the filename `FindVorbis.cmake` would not match anymore.

Where exactly is the conflict?

**Comment by Hinara** [comment]
The conflict is between `sfml_find_package(Vorbis` and `find_package_handle_standard_args(VORBIS`
Cause `find_package_handle_standard_args` will search in `VORBIS_FIND_REQUIRED` instead of `Vorbis_FIND_REQUIRED` which is set by `find_package(${target} REQUIRED)` where target is `Vorbis`

**Comment by Bromeon** [comment]
Thanks for the elaboration. I was looking at other find modules which are not all-uppercase (`FindFreetype.cmake`, `FindUDev.cmake`), and the problem doesn't exist there, because the `FREETYPE_FOUND`/`UDEV_FOUND` is set manually and not through a call to `find_package_handle_standard_args()`.

I added a pull request, could you check if that branch works for you?

**Comment by Hinara** [comment]
Seems to work I correctly get 👍 
```
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find VORBIS (missing: VORBIS_INCLUDE_DIR)
```

**Comment by AndrewMbugua** [comment]
A potential error that one might face for future reference:

Description:    Ubuntu 22.04.5 LTS
Release:        22.04


Error I encountered while using the **cmake-sfml-project template**

`$ cmake .`
-- libudev stable: 1
-- Found UDev: /usr/lib/x86_64-linux-gnu/libudev.so
--    include: /usr/include
CMake Error at /snap/cmake/1463/share/cmake-4.0/Modules/FindPackageHandleStandardArgs.cmake:227 (message):
  Could NOT find Vorbis (missing: VORBIS_INCLUDE_DIR VORBIS_LIBRARY)
Call Stack (most recent call first):
  /snap/cmake/1463/share/cmake-4.0/Modules/FindPackageHandleStandardArgs.cmake:591 (_FPHSA_FAILURE_MESSAGE)
  _deps/sfml-src/cmake/Modules/FindVorbis.cmake:20 (find_package_handle_standard_args)
  _deps/sfml-src/src/SFML/Audio/CMakeLists.txt:72 (find_package)


-- Configuring incomplete, errors occurred!


Solved by: `$ sudo apt install libvorbis-dev`

**Comment by ChrisThrasher** [comment]
@AndrewMbugua the instructions for that template already tell you to do that.

**Comment by AndrewMbugua** [comment]
@ChrisThrasher sorry,I think I missed that.
