### ISSUE TITLE
Non-free stuff in dist tar ball

### ISSUE THREAD

**Issue by kloczek** [SFML/SFML#1627]
From fedora spec files:
```
# This is https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip
# with the non free contents removed - See rhbz#1310387 and rhbz#1003569
# List of deleted files
#
# examples/sound/resources/canary.wav
# examples/iOS/resources/canary.wav
# examples/android/app/src/main/assets/canary.wav
# examples/sound/resources/orchestral.ogg
# examples/iOS/resources/orchestral.ogg
# examples/android/app/src/main/assets/orchestral.ogg
# tools/xcode/templates/SFML/SFML CLT.xctemplate/sansation.ttf
# tools/xcode/templates/SFML/SFML App.xctemplate/sansation.ttf
# examples/shader/resources/sansation.ttf
# examples/pong/resources/sansation.ttf
# examples/opengl/resources/sansation.ttf
# examples/joystick/resources/sansation.ttf
# examples/island/resources/sansation.ttf
# examples/iOS/resources/sansation.ttf
# examples/cocoa/resources/sansation.ttf
# examples/android/app/src/main/assets/sansation.ttf
# examples/shader/resources/background.jpg
# examples/opengl/resources/background.jpg
# examples/opengl/resources/texture.jpg
# examples/pong/resources/ball.wav
# examples/shader/resources/devices.png
# examples/win32/resources/image1.jpg
# examples/win32/resources/image2.jpg
```
Could you please consider create dist tar ball without that stuff to allow directly grab dist tar ball immediately after new release?

**Comment by Bromeon** [comment]
Can you provide some context, e.g. link to the issues under "See rbhz..."?

Why are _all_ of those resources considered as non-free? Because there's no explicit license listing each of them?

**Comment by kloczek** [comment]
https://src.fedoraproject.org/rpms/SFML/c/309ddd0f3c233ee2090f1378e47daffeb2202b77?branch=master
In that patch is refference to rhbz#1310387            
https://bugzilla.redhat.com/show_bug.cgi?id=1310387

**Comment by Bromeon** [comment]
Also related: [Copyright status of example resources](https://en.sfml-dev.org/forums/index.php?topic=13420) on forum

> Could you please consider create dist tar ball without that stuff to allow directly grab dist tar ball immediately after new release?

You are referring to the Linux archive on the [Download page](https://www.sfml-dev.org/download/sfml/2.5.1/) -- i.e. there would be a 2nd download link without non-free resources?

**Comment by eXpl0it3r** [comment]
@kloczek & @jcowgill for the SFML 2.6 release (TBD) you should be able to drop current patches and use the provided resources directly thanks to @MrZeusTheCoder updates in #1718
