### ISSUE TITLE
Bad and choppy rendering when trying to draw shapes

### ISSUE THREAD

**Issue by cata0309** [SFML/SFML#1631]
## Subject of the issue
I tried to draw some basic shapes like a rectangle rotated 45 degrees or a circle

## Your environment
* Your OS / distro / window manager used
 Solus Linux Fortitude 4 /Budgie DE
* Your version of SFML (2.5.0, git master, etc) 
2.5.1
* Your compiler and compiler version used
g++ , version 9.2.0
* Special compiler flags used
 g++ sfml_test.cpp -o sfmlapp  -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio -lGL -LGLU -lm
## Steps to reproduce

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(500, 500), "SFML works!",sf::Style::Default);
    sf::CircleShape shape(200.f);
    shape.setFillColor(sf::Color::White);
shape.setOutlineColor(sf::Color::Black);
shape.setOutlineThickness(2.f);
    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear(sf::Color::White);
        window.draw(shape);
        window.display();
    }

    return 0;
}
```

## Expected behavior
See a perfectly drawn circle with smooth outline
(This image was generated using Processing to show that is not my GPU's fault that the shapes are not rendered corectly)
![image](https://user-images.githubusercontent.com/35623921/70631423-d2944c00-1c35-11ea-92fb-8b6d2ef6150c.png)

## Actual behavior
I see pointy outline, very ugly with SFML and C++
![image](https://user-images.githubusercontent.com/35623921/70631469-e2139500-1c35-11ea-870c-d978aadd62b2.png)

**Comment by LaurentGomila** [comment]
Compared to the first one, the SFML circle lacks two things:
* antialiasing (sf::ContextSettings in window constructor -- see documentation)
* more edges than the default number (constructor of sf::CircleShape)

**Comment by cata0309** [comment]
I did some research on sf::ContextSettings in the window constructor but it show me a warning and sets the antialising to the 16 and everything to the default, what I am trying to say is that it doesn't matter what options I write it says it takes others

**Comment by LaurentGomila** [comment]
> Questions: What are the maximum numbers that can be passed as arguments to sf::ContextSettings options ?

It totally depends on your graphics card capabilities.

**Comment by cata0309** [comment]
So how could I find out ?
