### ISSUE TITLE
FT_LOAD_FORCE_AUTOHINT causes undesired effects on some fonts

### ISSUE THREAD

**Issue by oomek** [SFML/SFML#1633]
## Subject of the issue

FT_LOAD_FORCE_AUTOHINT causes shift of dots in letters `i` and `j` on the X axis

## Your environment

* Windows 10
* Latest master
* MXE cross compiling

## Steps to reproduce

Use fonts that have dots in letters `i` and `j` wider that the base of the letter
example: Barlow Condensed SemiBold

## Expected behavior

The dot should be aligned with the base of letter

## Actual behavior

The mentioned flag causes hinting to be done separately on the base and the dot of the letters
Additionally this flag causes too wide spacing between glyphs at small font sizes.

I'm aware this has been requested to make small fonts look crisper, but it has it's own disadvantages. 

![image](https://user-images.githubusercontent.com/2974860/71449119-7f92bc80-273e-11ea-84f3-242b8c61a06e.png)

![image](https://user-images.githubusercontent.com/2974860/71449319-e1085a80-2741-11ea-853b-96f207d5cdf5.png)

**Comment by matjam** [comment]
It also causes PCF fonts to render badly. Typically if you're loading a bitmap font like a PCF you don't want any anti-aliasing.

**Comment by eXpl0it3r** [comment]
> Typically if you're loading a bitmap font like a PCF you don't want any anti-aliasing

This is unrelated to this issue however.

**Comment by eXpl0it3r** [comment]
@LaurentGomila is there some specific reason why this was added in the first place?

Other than that, I'd be happy to merge a PR with that fix. 🙂

**Comment by oomek** [comment]
The fix for expanded kerning would be this stuck issue:
https://github.com/SFML/SFML/issues/1642

The reason of adding autohint was this:
https://github.com/SFML/SFML/issues/228

**Comment by Bromeon** [comment]
@oomek thanks for finding that!

To sum up the old thread, the `FT_LOAD_FORCE_AUTOHINT` flag improved the rendering of small fonts and avoided blurrying of pixelated fonts. This seems to be more important than a properly aligned i-dot, especially for pixel-art games. 

Also, if you look at the lower, small text in your example, the quality is actually worse (more blurred) **without** the flag:
![grafik](https://user-images.githubusercontent.com/708488/105023204-f3d78680-5a4a-11eb-8341-bb00bda2e010.png)


As such, we would need to find a way of improving the behavior without regressing.

**Comment by oomek** [comment]
I agree, misaligment of glyph shape's sub-elements is less important than proper kerning compensation discussed in my other thread. We should focus on that first. I'm closing that issue. Please post your further thoughts in https://github.com/SFML/SFML/issues/1642
