### ISSUE TITLE
priv::getActivity returns NULL on Android NativeActivity app

### ISSUE THREAD

**Issue by sevagh** [SFML/SFML#1638]
## Subject of the issue

![image](https://user-images.githubusercontent.com/8574092/73569087-b93e9d80-4437-11ea-8178-d2f34707c192.png)

Trying to use SFML segfaults my Android NativeActivity app. It seems that `sf::priv::getActivity` is returning NULL. Not sure if this is by design. I can't use `sfml-activity` since it requires OpenAL.

I don't know if I'm missing some permission in AndroidManifest.xml to allow SFML to read the NativeActivity pointer.

## Your environment

* Android NDK r21, arm64-v8a
* SFML: git master
* Compiled with cmake and clang++ in Android NDK

I have built SFML with only graphics:

```
# compile freetype2 from source
set(FREETYPE_DIR ./freetype2)
set(CMAKE_BUILD_TYPE Release)
add_subdirectory(${FREETYPE_DIR} ./freetype2)
include_directories(${FREETYPE_DIR}/include)

# SFML for graphics
set(CMAKE_IGNORE_PATH "")
set(SFML_BUILD_AUDIO FALSE)
set(SFML_BUILD_NETWORK FALSE)
set(SFML_USE_SYSTEM_DEPS TRUE)
set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_ANDROID_NDK ${ANDROID_NDK})
set(CMAKE_ANDROID_ARCH_ABI aarch64)
set(CMAKE_ANDROID_STL_TYPE c++_static)
set(FREETYPE_LIBRARY ${CMAKE_CURRENT_BINARY_DIR}/freetype2/libfreetype.a)
set(SFML_DIR ./SFML)
add_subdirectory(${SFML_DIR} ./SFML)
include_directories(${SFML_DIR}/include )

target_link_libraries( # Specifies the target library.
        myapp
        android
        app-glue
        EGL
        GLESv1_CM
        sfml-system
        sfml-graphics
        ${log-lib})
```

## Steps to reproduce

```c++
#include <android_native_app_glue.h>
#include <SFML/Graphics.hpp>
#include <SFML/Window.hpp>

void android_main(struct android_app* app)
{
    // Set the callback to process system events
    app->onAppCmd = handle_cmd;

    // Used to poll the events in the main loop
    int events;
    android_poll_source* source;

    sf::RenderWindow window(sf::VideoMode::getDesktopMode(), "MyApp");
```

## Expected behavior

No segfaults - SFML somehow finds the main activity.

## Actual behavior

Segfault.

**Comment by sevagh** [comment]
I have a better minimally reproducible example:

![image](https://user-images.githubusercontent.com/8574092/73570858-3a4b6400-443b-11ea-8538-e4cffbf319ad.png)

I'm doing some digging now and it looks like this is important to run, and is possibly not being run during my startup: https://github.com/SFML/SFML/blob/master/src/SFML/Main/MainAndroid.cpp#L479

**Comment by sevagh** [comment]
It could be this way is unsupported: https://en.sfml-dev.org/forums/index.php?topic=21304.0

I'll try to switch to `sfml-activity` + `int main(int argc, char **argv)` for now.

**Comment by MarioLiebisch** [comment]
SFML has its own entry point/native app glue, where the activity (and a few other things) are set up. You can't skip `sfml-activity` and expect things to be set up, unless you add its loader to `android_main` on your own or include the proper exports from it. Feel free to reopen this, in case it's also broken when using `sfml-activity`.

**Comment by sevagh** [comment]
Here's the openal problem I'm having with `sfml-activity`:

```
I/sfml-activity: dlopen("/data/app/xyz.sevag.animals_as_meter-TuUmJkG2k4J0p3Ov31OBcA==/lib/arm64/libopenal.so"): dlopen failed: library "/data/app/xyz.sevag.animals_as_meter-TuUmJkG2k4J0p3Ov31OBcA==/lib/arm64/libopenal.so" not found```

I have compiled libopenal.so but I'm pretty sure I can't copy it into `/lib/arm64/`. Is there a workaround for this?

**Comment by MarioLiebisch** [comment]
If you've built it with the proper toolset etc. put it in the proper NDK directory (where the other SFML dependencies are) and include it in your project.
