### ISSUE TITLE
Testing without display [CI, Gtest]

### ISSUE THREAD

**Issue by ArturBa** [SFML/SFML#1643]
## Testing without display [CI, Gtest]

Hi, I'd like to run CI test using Travis checking loading textures into program memory.
I'm using GTest for this purpose.
While running it locally it works. When I try to run it only in CLI it has an error: 
`Failed to open X11 display; make sure the DISPLAY environment variable is set correctly`

## Your environment
* GUI
  * Ubuntu 18LST / Gnome
  * SFML = 2.5.1
  * GCC
* Travis
  * Ubuntu 18
  * SFML = 2.5.1
  * GCC
  * [more details](https://travis-ci.com/ArturBa/AlmostAgricola/jobs/289201483/config)

## Steps to reproduce

Try to run test as follow in clean CLI interface
```cpp
#include <gmock/gmock.h>
#include <SFML/Graphics.hpp>

TEST(Test, Texture){
    sf::Texture texture;
    texture.loadFromFile("../test/res/img/test.png");
    ASSERT_EQ(sf::Vector2u(2, 2), texture.getSize());
}
```

## Expected behavior

Test should pass, as in GUI interface

## Actual behavior

Test error: 
`Failed to open X11 display; make sure the DISPLAY environment variable is set correctly`

**Comment by LaurentGomila** [comment]
What makes you think that it should pass although the error message clearly states that it needs a display?

**Comment by ArturBa** [comment]
> What makes you think that it should pass although the error message clearly states that it needs a display?

When I run it on my local computer with GUI it has no problems with passing the test. 
When I run it in CLI (or on Travis) it has errors like that:
```
Running main() from /home/travis/build/ArturBa/AlmostAgricola/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 16 tests from 5 test suites.
[----------] Global test environment set-up.
[----------] 1 test from Test
[ RUN      ] Test.Texture
Failed to open X11 display; make sure the DISPLAY environment variable is set correctly
[1] PID aborded(core dumped) ./runUnitTests 
```
And it stops form running the tests

**Comment by LaurentGomila** [comment]
Yes, because you're trying to do graphical stuff without a GUI (X11 server) running.

**Comment by ArturBa** [comment]
@LaurentGomila 
Could you tell me how to bypass this error? 
I want to check loaded textures etc. in my test. This doesn't require showing them in any GUI.

**Comment by LaurentGomila** [comment]
But this requires an OpenGL context, and an OpenGL context (at least in SFML) requires a valid X11 display.

I don't think you can bypass this. If you want to test a graphics library, then do it where you have a graphical environment available 😉

**Comment by texus** [comment]
You should be able to use X11 on travis by adding something like this to travis.yml
```
services:
  - xvfb
```

See https://docs.travis-ci.com/user/gui-and-headless-browsers/

**Comment by ArturBa** [comment]
@LaurentGomila 
Thanks for your help
@texus 
I've found it and right now I'm testing it 
Looks like it works well. 
Thanks for support guys.

**Comment by MarioLiebisch** [comment]
Btw. if you really have to verify that loading an image works as a basic element, don't test `sf::Texture`. Instead, use `sf::Image`, which is really just the image representation in system memory. `sf::Texture` is the GPU based equivalent.
