### ISSUE TITLE
Build fails for arm64-v8a

### ISSUE THREAD

**Issue by easeccy** [SFML/SFML#1648]
## Cmake can't find OpenAL

Tutorial on wiki page [excludes](https://github.com/acsbendi/Build-SFML-For-Android-On-Linux/blob/master/build-sfml.sh#L41) 64-bit to prevent this error. Google [announced](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html) that 32-bit will not be allowed after 1 August 2020 so 64-bit support is a must for Android.

When building for arm64-v8a Cmake gives this error:

```
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenAL (missing: OPENAL_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.13/Modules/FindOpenAL.cmake:77 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/Macros.cmake:398 (find_package)
  src/SFML/Audio/CMakeLists.txt:78 (sfml_find_package)
```
OpenAL library is installed on my system already.
```
$ apt list --installed | grep openal

libopenal-data/eoan,eoan,now 1:1.19.1-1 all [installed,automatic]
libopenal-dev/eoan,now 1:1.19.1-1 amd64 [installed]
libopenal1/eoan,now 1:1.19.1-1 amd64 [installed,automatic]
```

##  Environment

* Ubuntu 19.10 
* SFML 2.5.1

**Comment by MarioLiebisch** [comment]
SFML doesn't provide a pre-built binary for OpenAL (or the other dependencies) so far.

For the time being, you can use the scripts in the SFML repository (`/tools/android`) to build the dependencies yourself.

**Comment by MarioLiebisch** [comment]
Oh, and noteworthy: When building for Android, you're cross-compiling. So your system's OpenAL isn't considered (nor viable).

**Comment by easeccy** [comment]
`/tools/android` has only the 32-bit helpers. 

After some adjustments and setup, I just managed to build SFML for armeabi-v7. Now I don't have any idea why does following the same steps to build 64-bit fail? Should I take extra steps, does them mentioned in anywhere (github, forum etc.) ?

**Comment by easeccy** [comment]
> Oh, and noteworthy: When building for Android, you're cross-compiling. So your system's OpenAL isn't considered (nor viable).
Do you mean that I sould install OpenAL in NDK?

**Comment by MarioLiebisch** [comment]
> Do you mean that I sould install OpenAL in NDK?
That's the basic idea. You'll need an arm64-v8 build.

For this you should be able to copy and edit the file `compile_arm-v7a.sh` to make an arm64-v8 version of the files. Is it that easy? Possible, but haven't really tried, massively short on time these days.

**Comment by easeccy** [comment]
Couldn't make it that way. Looked through all of the scripts under `/tools/android` , they had a lot of hard-coded paths which are invalid for my system too. At the end of the day I had no success on building arm64. 

The question here is, will there be 64-bit helpers on repo any soon? As Play Store will only accept 64 bit, example codes and tutorials for Android without arm64 will become irrelevant.

It could be possible to setup everything manually but I think it's very challenging to deal with those build errors as a user of this framework. My request is to have an Android project template and build scripts for arm64-v8a.

**Comment by eXpl0it3r** [comment]
64bits libraries (x86_64 + arm64-v8a) have been added to 2.6.x with #2165 and will be merged back to master a bit later

Ping @easeccy 😉
