### ISSUE TITLE
Add vcpkg installation instructions

### ISSUE THREAD

**Issue by NancyLi1013** [SFML/SFML#1650]
`sfml`  is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for sfml and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build sfml, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/sfml/portfile.cmake) We try to keep the library maintained as close as possible to the original library.

I try to add vcpkg installation instructions but I couldn't find the related docs in GitHub except for on https://www.sfml-dev.org/tutorials/2.5/ page.

Could you please help add the following contents to this port?

Installing and building sfml via vcpkg

You can download and install sfml using the vcpkg dependency manager:

     git clone https://github.com/Microsoft/vcpkg.git
     cd vcpkg
     ./bootstrap-vcpkg.sh
     ./vcpkg integrate install
     vcpkg install sfml

The sfml port in vcpkg is kept up to date by Microsoft team members and community contributors. If the version is out of date, please [create an issue or pull request](https://github.com/Microsoft/vcpkg) on the vcpkg repository.

Thanks.

**Comment by eXpl0it3r** [comment]
Similar as I mentioned on the [SFML-Website repository](https://github.com/SFML/SFML-Website/issues/140#issuecomment-603348734) recently.

> My plan so far was to have a new setup tutorial that shows different options with different package managers (vcpkg, conan, conda, etc).

I think it's best to move this to the existing SFML-Website issue. Also feel free to provide a PR on said repository, but keep in mind that it shouldn't just be specific to the vcpkg package manager. 🙂

**Comment by NancyLi1013** [comment]
Thanks for your update and suggestion.
