### ISSUE TITLE
Doc builds index.html with invalid link to "annotated.php"

### ISSUE THREAD

**Issue by FalcoGer** [SFML/SFML#1652]
## Subject of the issue

When building documents with the `-DSFML_BUILD_DOC=TRUE` flags, the index.html file will have a link to `annotated.php`

```html
<div class="textblock"><h1><a class="anchor" id="welcome"></a>
Welcome</h1>
<p>Welcome to the official SFML documentation. Here you will find a detailed view of all the SFML <a href="./annotated.php">classes</a> and functions. <br />
```

However neither does this file exist, nor should a .php file be included in the offline documentation.

## Your environment

* OS: Ubuntu Mate 18.04 LTS (`Linux *** 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`)
* SFML Version: 2.5.1 (master 50e173e403ef8912e3d8ac3c7ab3e27e32243339)
* Your compiler and compiler version used: `gcc/g++ (Ubuntu 9.3.0-10ubuntu2~18.04) 9.3.0` 
* Special compiler flags used: none

## Steps to reproduce

Build documentation and check index.html

## Expected behavior

The word Classes links to a page with a list of classes, or isn't a linkg at all

## Actual behavior

The word Classes links to annotated.php, which does not exist

**Comment by eXpl0it3r** [comment]
Thanks for pointing this out. The same files are being used to generate the [official documentation on the website](https://www.sfml-dev.org/documentation/2.5.1/) and there exists an annotated.php. The link is part of the custom HTML for the landing page.
I don't really think, that's a big issue, but the only "fix" I see to keep it compatible, would be to just remove the link.

Do you have any other suggestion on how to solve this?

**Comment by FalcoGer** [comment]
you could make it a fully qualified link to `https://stml-dev.org/annotated.php` (or wherever it is located) instead of using a relative link.

**Comment by eXpl0it3r** [comment]
That unfortunately doesn't really work, if you're browsing an older version of the API documentation, for example like this: https://www.sfml-dev.org/documentation/2.3.1/annotated.php

I think it's probably better to just remove the link, as the same navigation point is available on the same page.
