### ISSUE TITLE
Question: Can sf::TcpListener pick a random available port?

### ISSUE THREAD

**Issue by Unarelith** [SFML/SFML#1657]
## Subject

`sf::UdpSocket` is capable of selecting a random available port as described in the [documentation](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1UdpSocket.php#ad764c3d06d90b4714dcc97a0d1647bcc), using `sf::UdpSocket::bind(sf::Socket::AnyPort)`:

> You can use the special value Socket::AnyPort to tell the system to automatically pick an available port, and then call getLocalPort to retrieve the chosen port.

But there is nothing about `sf::TcpListener::listen(sf::Socket::AnyPort)`.

I tried on my ArchLinux. It works as expected, and I can use `sf::TcpListener::getLocalPort` to know which port it decided to pick.

Is the documentation missing, or is it unsupported/not portable/something else?

## Your environment

* ArchLinux
* SFML 2.5

**Comment by LaurentGomila** [comment]
I'd say the documentation is missing. Internally, `TcpListener::listen` uses the same call to` ::bind` as `sf::UdpSocket`, so it should work the same.

**Comment by Unarelith** [comment]
I just opened #1658 to add documentation on that topic, closing this ticket.
