### ISSUE TITLE
Fails to build SFML library for Android using CMake

### ISSUE THREAD

**Issue by seccpur** [SFML/SFML#1662]
## Subject of the issue

Unable to generate SFML library for Android using CMake

## Your environment

* OS Windows 10
* SFML version 2.5.0
* Your compiler: Clang
* Location of NDK: D:\Apps\AndroidStudioSDK\ndk\21.1.6352462
* Location of CMake: D:\Apps\AndroidStudioSDK\cmake\3.10.2.4988404\bin\

## Steps to reproduce

Downloaded SFML from git and created subdirectories SFML\build and SFML\build\armeabi-v7a 
Issue this command

## Expected behavior

SFML library for android should be built.

## Actual behavior
 Included -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang in the commandline, but instead of compiling with clang , it  is trying to use Visual Studio 15  compiler and results in CMake error as the build fails. However, the command made a CMakeCache.txt  and a CMakeFiles folder.

##Commandline log

> D:\Apps\AndroidStudio\sfml related\SFML\build\armeabi-v7a>D:\Apps\AndroidStudioSDK\cmake\3.10.2.4988404\bin\cmake.exe -DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_NDK=D:\Apps\AndroidStudioSDK\ndk\21.1.6352462 -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang  -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a -DCMAKE_ANDROID_STL_TYPE=c++_static -DCMAKE_BUILD_TYPE=Debug ../..
> -- Building for: Visual Studio 15 2017
> CMake Error at CMakeLists.txt:45 (project):
>   Failed to run MSBuild command:
> 
>     MSBuild.exe
> 
>   to get the value of VCTargetsPath:
> 
>     The system cannot find the file specified
> 
> 
> 
> -- Configuring incomplete, errors occurred!

**Comment by eXpl0it3r** [comment]
Since you have multiple toolchains installed, you need to specify a project/make file generator, e.g. `-G "MinGW Makefiles"`. CMake will by default pick Visual Studio.

**Comment by seccpur** [comment]
@eXpl0it3r : For clang toolchain, I use -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang, as described in git, but doesn't work. Command -G "MinGW Makefiles" seems for MinGW toolchain, i need for clang compiler.

**Comment by eXpl0it3r** [comment]
It's about project/make file generation...

**Comment by eXpl0it3r** [comment]
You may want to ask for some help on how to setup your build environment for Android on the forum or the Discord server.
