### ISSUE TITLE
Why is Packet::getReadPosition() not included in the 2.5.1 release?

### ISSUE THREAD

**Issue by benpm** [SFML/SFML#1663]
Packet::getReadPosition() was added to Packet in March 2018, and the commit was to the master branch. 2.5.1 was released in October 2018, but does not include this commit. I am wondering why it was not included in the release? I would like to be able to use this function, as I am trying to overload the Packet stream operators to allow streaming of std::array. Writing to the packet is fine, but in order to read the array data at the correct position, I need to know what the read position is.
Here is the commit in which Packet::getReadPosition() was added: 632a015663487181ea817731779c2b225937eaa0

**Comment by eXpl0it3r** [comment]
The commit was originally made in March 2018 indeed, but it was not merged until February 2020, see #1641 which is why it's not part of SFML 2.5.1 

Building SFML from source is quite easy and you can get all the latest changes from master.
