### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by CatalinNic1** [SFML/SFML#1664]
## Subject of the issue

I just tested a simple SFML example with vargrind just for curiosity and to my surprise i saw that it reported a memory leak

## Your environment

* Manjaro 20 KDE
* SFML 2.5.1-2
* GCC 9.3.0
* -g -Wall -std=c++2a

## Steps to reproduce

The code used:

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(1280, 720), "Minimal, complete and verifiable example");

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.display();
    }
}
```
Compiled it using the flags from above and then type: valgrind -s --leak-check=full --show-leak-kinds=all ./a.out &> leak.out
This will produce a text file with all allocations and information

## Expected behavior
To not report any leak

## Actual behavior
```
==8969== LEAK SUMMARY:
==8969==    definitely lost: 256 bytes in 1 blocks
==8969==    indirectly lost: 0 bytes in 0 blocks
==8969==      possibly lost: 0 bytes in 0 blocks
==8969==    still reachable: 233,309 bytes in 2,673 blocks
==8969==         suppressed: 0 bytes in 0 blocks
```

And here is a file from valgrind:
[leak.txt](https://github.com/SFML/SFML/files/4681233/leak.txt)

**Comment by eXpl0it3r** [comment]
As Laurent mentioned in the other recently opened issue #1673 

> We don't know exactly what it is, either a leak in the OpenGL driver, or a false positive (memory deallocated at global exit, not seen by valgrind), but there's no known memory leak in SFML.
