### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by fireuse** [SFML/SFML#1673]
## Subject of the issue
When I have run Valgrind check on default SFML example, it has detected memory leak.

## Your environment

* Kali Linux, NVIDIA GPU
* 2.5.1
* GCC 9.3.0

## Steps to reproduce
Run `valgrind -s --leak-check=full ./a.out &> report.txt` on compiled SFML example.

## Expected behavior

No memory errors should be detected.

## Current behavior
[report.txt](https://github.com/SFML/SFML/files/4736913/report.txt)

**Comment by LaurentGomila** [comment]
Every week or so we see such a valgrind report 😉 

We don't know exactly what it is, either a leak in the OpenGL driver, or a false positive (memory deallocated at global exit, not seen by valgrind), but there's no known memory leak in SFML.
