### ISSUE TITLE
sf::Shader is not moveable

### ISSUE THREAD

**Issue by Eren121** [SFML/SFML#1675]
## Subject of the issue

It is not possible to return `sf::Shader` from function.

## Your environment

Any environnement

## Steps to reproduce

```cpp
#include <SFML/Graphics.hpp>

sf::Shader loadShader() {
    sf::Shader shader;
    /* Probably more code here */
    return shader;
}
int main() {
    sf::Shader myShader = loadShader();
}
```

## Expected behavior

The `sf::Shader` should not be copiable but should be moveable.

## Actual behavior

Compilation error.

## Solution

The compilation error comes from the implementation of `NonCopyable`. `NonCopyable` class mean also non moveable.
Trivial change in `sf::Shader` or code design change with `NonCopyable` to accept move semantic, but may / may not break other classes.

**Comment by LaurentGomila** [comment]
We know that move semantics are not implemented in SFML, what we need is someone to actually do it ;)

**Comment by Bromeon** [comment]
See [this forum thread](https://en.sfml-dev.org/forums/index.php?topic=21571) for discussion on C++ standards.

**Comment by eliasdaler** [comment]
Just as a workaround for now - you can use `std::unique_ptr<sf::Shader>` for non-moveable objects and do something like this:

```cpp
#include <SFML/Graphics.hpp>

std::unique_ptr<sf::Shader> loadShader() {
    auto shader = std::make_unique<sf::Shader>();
    /* Probably more code here */
    return shader;
}

int main() {
    auto myShader = loadShader();
}
```

The solution isn't perfect, but I think it's wrong to add move constructor only for one class (and before we "officially" say that we support C++11 or newer in the SFML)

**Comment by ChrisThrasher** [comment]
`sf::Shader` is now moveable
