### ISSUE TITLE
Unable to play mp3

### ISSUE THREAD

**Issue by sonulohani** [SFML/SFML#1682]
Thanks for raising your issue here! 🙂

Before you submit the issue however, we'd like you to consider the follow points.

* We like to use the issue tracker for confirmed issues.
* If you're stuck with SFML, please use [the forum](https://en.sfml-dev.org/forums/index.php#c3) to get help.

----

## Subject of the issue

I am making an audio player for which I am using SFML. However its not able to play mp3.  Referred example from here.

## Your environment

* Your OS / distro / window manager used - WIndows 10 2004
* Your version of SFML (2.5.0, git master, etc) - 2.5.1
* Your compiler and compiler version used - MSVC 2019
* Special compiler flags used - Nope

## Steps to reproduce

Tell us how to reproduce this issue. Please provide a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve), you can use the follow template as a start:

```cpp
#include <SFML/Audio/Music.hpp>

int main()
{
    sf::Music m;
    m.openFromFile("C:\file.mp3");
    m.play();
}
```

## Expected behavior

Should play music

## Actual behavior
CPU info (x86-64):
  CMOV ....... Y
  MMX ........ Y
  SSE ........ Y
  SSE2 ....... Y
  SSE3 ....... Y
  SSSE3 ...... Y
  SSE41 ...... Y
  SSE42 ...... Y
  AVX ........ Y
  FMA ........ Y
  AVX2 ....... Y
  AVX OS sup . Y

Failed to open sound file "C:\file.mp3" (format not supported)
Failed to play audio stream: sound parameters have not been initialized (call initialize() first)

**Comment by Kvaz1r** [comment]
SFML hasn't mp3 support. See #1232 for details.

**Comment by fahlmant** [comment]
Also from https://www.sfml-dev.org/tutorials/2.5/audio-sounds.php

` SFML supports the audio file formats WAV, OGG/Vorbis and FLAC. Due to licensing issues MP3 is not supported. `

**Comment by sonulohani** [comment]
> 
> 
> SFML hasn't mp3 support. See #1232 for details.

Oh this is very bad news. Actually the most popular format in the world for audio is mp3. If I don't give support for that then my software would not be complete. I guess I would need to find the alternative. Anyway thanks for such a quick response. Very much appreciated.

**Comment by jamesrwaugh** [comment]
There's currently a WIP to add this, since it seems MP3 no longer has licensing issues
https://github.com/SFML/SFML/issues/1232
But has been WIP since 2017
