### ISSUE TITLE
Loading vertex and fragment shaders in a single call breaks texture coordinates

### ISSUE THREAD

**Issue by flarn2006** [SFML/SFML#1691]
## Subject of the issue

When using the `sf::Shader::loadFrom` methods, there is the option of loading both a vertex and fragment shader in the same call. But I've found that using this option prevents texture coordinates from being passed to the shader. It only works properly if I call the method twice, once for the vertex shader and once for the fragment shader.

## Your environment

* OS: Arch Linux
* SFML 2.5.1-2
* g++ (GCC) 10.1.0
* Compiler options: `g++ -o program program.cpp -lsfml-graphics -lsfml-window -lsfml-system`

## Steps to reproduce

Compile and run the following program:

```cpp
#include <iostream>
#include <SFML/Graphics.hpp>

const char* vertex_shader = "void main() { gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex; }";
const char* fragment_shader = "void main() { gl_FragColor = vec4(gl_TexCoord[0].x, gl_TexCoord[0].y, 1.0, 1.0); }";

int main()
{
    sf::RenderWindow win(sf::VideoMode(512, 256), "TexCoord Bug Test");

    sf::Shader shader1;
    shader1.loadFromMemory(vertex_shader, sf::Shader::Vertex);
    shader1.loadFromMemory(fragment_shader, sf::Shader::Fragment);

    sf::Shader shader2;
    shader2.loadFromMemory(vertex_shader, fragment_shader);

    sf::RenderStates rstates1;
    rstates1.shader = &shader1;
    rstates1.transform.scale(256.0f, 256.0f);

    sf::RenderStates rstates2;
    rstates2.shader = &shader2;
    rstates2.transform.scale(256.0f, 256.0f);
    rstates2.transform.translate(1.0f, 0.0f);

    sf::VertexArray va(sf::TriangleStrip);
    for (int i=0; i<4; ++i) {
        float x = (i & 1) ? 1.0f : 0.0f;
        float y = (i & 2) ? 1.0f : 0.0f;
        std::cout << "Vertex " << i << " @ (" << x << ", " << y << ")" << std::endl;
        sf::Vector2f vec(x, y);
        va.append(sf::Vertex(vec, vec));
    }

    for (;;) {
        sf::Event ev;
        while (win.pollEvent(ev)) {
            if (ev.type == ev.Closed)
                goto window_closed;
        }

        win.clear();
        win.draw(va, rstates1);
        win.draw(va, rstates2);
        win.display();
    }

window_closed:
    return 0;
}
```

## Expected behavior
![](https://user-images.githubusercontent.com/687313/90347397-33aec380-dffe-11ea-922f-691caba319aa.png)
Both sides of the window should appear the same, as the only difference (other than translation) is how the shaders were loaded. (I got the above image by changing the source code to use `&shader1` for both `sf::RenderStates`` instances.)

## Actual behavior
![](https://user-images.githubusercontent.com/687313/90347430-7375ab00-dffe-11ea-9a04-50818a694e00.png)
The left side of the window (two `loadFromMemory` calls) appears correctly, but the right side of the window (single `loadFromMemory` call) is solid blue, indicating the texture coordinates are 0 everywhere.

**Comment by LaurentGomila** [comment]
There is a bug in your vertex shader. Calling `sf::Shader::loadFromXxx` twice will not load both shaders, only the last one. Otherwise the overload that loads both in a single call would be useless. In other words, in the buggy version, shader1 is not using your vertex shader, that's why it works fine.

Next time please read the tutorials and documentation carefully.

https://www.sfml-dev.org/tutorials/2.5/graphics-shader.php#minimal-shaders

**Comment by flarn2006** [comment]
Oh okay; that makes sense. I thought the single-call version was just for convenience. Thanks for explaining!

Does that mean there's no way to load, e.g. the vertex shader from memory and the fragment shader from a file, other than by writing code to load the file and read it into memory, or using a file stream and a string stream with `loadFromStream`?

**Comment by LaurentGomila** [comment]
> Does that mean there's no way to load, e.g. the vertex shader from memory and the fragment shader from a file, other than by writing code to load the file and read it into memory, or using a file stream and a string stream with loadFromStream?

Yes. I agree that this part of the API is not perfect. Especially with the addition of geometry shaders, it's hard to manage all the possible combinations.
