### ISSUE TITLE
Allow setting cursors with colors on Linux

### ISSUE THREAD

**Issue by cschreib** [SFML/SFML#1693]
## Subject of the issue

SFML 2.5 added the Cursor class to allow changing the system cursor to an arbitrary bitmap using ``sf::Cursor::loadFromPixels()``. On Linux, the implementation with X11 only supports "monochrome" cursors (black, white, or transparent pixels). This should be improved to support full ARGB, which is possible with X11. See reference implementation in GDK which supports both methods: http://web.mit.edu/ghudson/dev/nokrb/third/gtk2/gdk/x11/gdkcursor-x11.c

The monochrome implementation seems available on all/most platforms, but the ARGB implementation is not. I suspect, however, that most desktop distributions do support it.

## Your environment

* Linux Mint 19
* 2.5.0
* Clang-10 / GCC-8
* None

## Steps to reproduce

Use ``sf::Cursor::loadFromPixels()`` on a Linux platform, with an input image that contains color.

## Expected behavior

Color is displayed correctly.

## Actual behavior

Only monochrome output.

**Comment by cschreib** [comment]
FYI I'm keen to look into providing an implementation for this, if no one is already working on it.

**Comment by eXpl0it3r** [comment]
Would be awesome if you could write an implementation. I'm not aware of anyone working on one right now.

Keep in mind that the linked code is licensed under GPL and as such incompatible with zlib, but it's a good way to see an example of the API usage. 😉

**Comment by cschreib** [comment]
@eXpl0it3r Ok great! 

I see the original implementation is from @binary1248 and @fundies. Asking them: is there any particular reason why Linux only got the monochrome implementation? Or was it just a practical decision to get the feature merged in quickly?

**Comment by cschreib** [comment]
That was way easier than I expected. I've opened a PR: https://github.com/SFML/SFML/pull/1694

**Comment by binary1248** [comment]
To be honest, I wasn't even aware of this limitation. When I initially wrote the XCB implementation many years ago it supported BGRA images from the start. During the refactor in f65459d0e1ea385da370ae8ecc8ee7fcaf89b268 and 34ea68bd1dc336ae709fb0875022e0924562e7bb, the implementation was moved to where it lives now, however the new implementation only supported monochrome cursors. Since @mantognini wrote the new implementation, only he will be able to answer the question.

**Comment by mantognini** [comment]
That wasn't yesterday, so my memory is a bit fuzzy... It was one of the first and rare time I had to implement something for Linux and the documentation I had mentioned that only monochrome was supported ([ref](https://github.com/SFML/SFML/pull/827#discussion_r109711564)). I guess for a first implementation it was agreed to be fine and peer review failed to show the loss of functionality. Glad to see this being addressed! :)

**Comment by eXpl0it3r** [comment]
Implemented with #1694
