### ISSUE TITLE
How can I read wav save to mp3 with compression control  then convert to wav without dump mp3 data to file?

### ISSUE THREAD

**Issue by zh794390558** [SFML/SFML#1695]
Thanks for raising your issue here! 🙂

Before you submit the issue however, we'd like you to consider the follow points.

* We like to use the issue tracker for confirmed issues.
* If you're stuck with SFML, please use [the forum](https://en.sfml-dev.org/forums/index.php#c3) to get help.

----

## Subject of the issue

How can I read wav save to mp3 with compression control then convert to wav without dump mp3 data to file?

**Comment by LaurentGomila** [comment]
SFML doesn't support MP3 audio files.

**Comment by zh794390558** [comment]
Mp3 can be FLAC.

**Comment by LaurentGomila** [comment]
> We like to use the issue tracker for confirmed issues.
> If you're stuck with SFML, please **use the forum** to get help

**Comment by eXpl0it3r** [comment]
SFML is not an audio conversion tool with options to specify parameters. You can load and save audio files (see the API documentation & tutorials), but you can't specify how things are saved.
