### ISSUE TITLE
[xcb] Unknown sequence number while processing reply

### ISSUE THREAD

**Issue by DmitruMoth** [SFML/SFML#1696]
## Subject of the issue

I have 2 threads application, in first thread are drawing sprites. Second thread get some data over network and change the position of sprite. All work fine while work only one app, then i start one more app i got this error:
```
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
Client: ../../src/xcb_io.c:643: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

## Environment

* distro - debian 10 stable
* sfml - 2.5.1 from repo
* compiler - gcc gnu 8.3.0
* xfce4

## Steps to reproduce

My code is similar like this:
```cpp
#include <SFML/Graphics.hpp>
#include <thread>

bool isRunning = false;
sf::Sprite sprite;

void networkUpdate();

int main()
{
    sf::RenderWindow window(sf::VideoMode(1280, 720), "Minimal, complete and verifiable example");
    window.setFramerateLimit(60);
    //load texture and set to sprite
    isRunning = true;
    std::thread networkThread(networkUpdate);
    networkThread.detach();

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.draw(sprite);
        window.display();
    }
}

void networkUpdate()
{
    while(isRunning)
    {
        float x = //get over network;
        float y = //get over network;
        sprite.setPosition(x, y);
    }
}
```

**Comment by eXpl0it3r** [comment]
When using threads on Linux you need to be calling XInitThreads as the error messages suggests.
Keep in mind that you should not be using globally initialized SFML resources.
And when you do multi-threading, you have to properly synchronize the shared resources (the sprite and boolean in your case).
