### ISSUE TITLE
Suggestion: throw an exception instead of aborting during XOpenDisplay() failure

### ISSUE THREAD

**Issue by tildearrow** [SFML/SFML#1699]
Currently, SFML uses abort() when XOpenDisplay fails, as there doesn't seem to be any way to return a value in a constructor, e.g.:

```cpp
#include <SFML/Graphics.hpp>

int main() {
  sf::RenderWindow w(sf::VideoMode(1280,720),"window");
  // no way to check if the window was opened successfully
  return 0;
}
```

However, one effective and standard way could be by using [exceptions](https://en.cppreference.com/w/cpp/error/exception), which would allow the programmer to catch an error and handle it appropriately without aborting, e.g.:

```cpp
#include <SFML/Graphics.hpp>

int main() {
  try {
    sf::RenderWindow w(sf::VideoMode(1280,720),"window");
  } catch (std::exception& e) {
    return 1;
  }
  return 0;
}
```

This also has the benefit that it remains compatible with existing code (that does not do try/catch), because unhandled exceptions in C++ abort the program anyway.

**Comment by eXpl0it3r** [comment]
SFML currently doesn't use exceptions, as such we can't really do that and the correct behavior if the window can't be created is to abort, as SFML becomes unusable if it can't create a window.
