### ISSUE TITLE
Error in compiling: ft2build.h no such file or directory

### ISSUE THREAD

**Issue by stalinium45** [SFML/SFML#1700]
In building target sfml-network for dinamic libray have error:
`CURRENT_DIRECTORY/SFML/src/SFML/Graphics/Font.cpp:35:10: fatal error: ft2build.h: No such file or directory`

OS: Linux mint 19
Compiler: GCC Ubuntu 7.5.0

**Comment by MarioLiebisch** [comment]
This "issue" would be better suited on the SFML forum (which is a lot more active) as long as it's no confirmed issue within the library files.

---

You might have files from an older version of Freetype in your system that make CMake trip and find the wrong directory.

What you could try to do:

* Double check whether you have `libfreetype6-dev` installed.
* If it is installed and you get the issue:
  * Make sure CMake is fully up to date.
  * Uninstall `libfreetype6-dev`.
  * Delete or rename `/usr/include/freetype2` if it still exists.
  * Reinstall `libfreetype6-dev`.
  * Try building again.

If that doesn't solve the issue, check your CMakeCache.txt and look which Freetype variables are set and whether they make sense (e.g. pointing to a directory with `ft2build.h` inside).
