### ISSUE TITLE
Compiling with -Wfloat-equal results in warnings on Vector2 and Vector3.

### ISSUE THREAD

**Issue by ChrisBlueStone** [SFML/SFML#1704]
When compiling my project with the -Wfloat-equal compiler flag, I get a bunch of warnings on Vector2.inl when using the == or != operators. I would suggest the fix to replace the implementation of  `operator==` and `operator!=` to internally use `std::equal_to()` and `std::not_equal_to`.
E.g.
```cpp
    return std::equal_to<T>()(left.x, right.x)
        && std::equal_to<T>()(left.y, right.y);
```
and
```cpp
    return std::not_equal_to<T>()(left.x, right.x)
        || std::not_equal_to<T>()(left.y, right.y);
```

These produces the same code generated by using `==` or `!=` but without the warnings, at least on GCC. I'm not sure if the warnings would be suppressed on other compilers as well.

## Environment

* OS: Windows 10
* SFML 2.5.1
* Compiler: gcc 6.3.0
* Compiler flags: -Wfloat-equal

## Steps to reproduce

Invoke the `==` or `!=` operators on any two Vector2 or Vector3 objects and the compiler will produce warnings.

```cpp
#include <iostream>
#include <SFML/Graphics.hpp>

int main()
{
    sf::Vector2f a, b;

    if (a == b)
        std::cout << "equal\n";
    else if (a != b)
        std::cout << "not equal\n";

    return 0;
}
```

## Expected behavior

Compile without warnings.

## Actual behavior

The compile emits the warnings 

> \SFML-2.5.1\include/SFML/System/Vector2.inl:160:20: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
>      return (left.x != right.x) || (left.y != right.y);
>             ~~~~~~~~^~~~~~~~~~~

**Comment by ChrisBlueStone** [comment]
Note that attempting `not_equal_to<sf::Vector2f>()(a, b)` also still emits the warnings.

**Comment by MrZeusTheCoder** [comment]
This is really not an issue with SFML. Or really too much of an issue at all. The warning that is being emitted cannot be avoided. It happens when you compare two floats when you have warnings set really high. Due to floating-point inaccuracy such operations can be an issue, but it isn't SFML's fault. Refer to this SO page for more info: https://stackoverflow.com/questions/11421756/weverything-yielding-comparing-floating-point-with-or-is-unsafe

**Comment by ChrisBlueStone** [comment]
I agree that it's not much of an issue but disagree that it can't be avoided. By using std::equal_to and std::not_equal_to the warnings will go away. Or are you suggesting that the warnings should remain for when consumers compare Vectors objects with the == and != operators? As the warnings are quite annoying and the compiler flag is handy for non-library code, how should one compare SFML Vectors?

**Comment by eXpl0it3r** [comment]
`std::equal_to` and `std::not_equal_to` are C++14 features, as such we could implement this for SFML 3

**Comment by LaurentGomila** [comment]
Comparing two `sf::Vector2f` using `==` has the same issues as comparing two floats. So, in my opinion, it should trigger the same warnings.

If you don't want to see these warnings, either configure your compiler accordingly (if you understand the warning and know what you're doing), or compare vectors with another function, that takes the floating point inaccuracy in account.

In short, handling `sf::Vector2f` (which is just a pair of floats) exactly the same way you would handle floats, seems rather logical to me. I don't see any reason to treat it differently.

**Comment by MrZeusTheCoder** [comment]
Whoops. I mis-read the issue. Serves me right for reading quickly, :P. You were saying we should move to `std` stuff.

**Comment by ChrisBlueStone** [comment]
That is fair. I guess writing my own explicit compare function for vector equality should be good enough. I'll close the issue then.
