### ISSUE TITLE
Fatal error when compiling SFML from sources

### ISSUE THREAD

**Issue by jul3x** [SFML/SFML#1705]
## Subject of the issue

Compiling SFML from sources from current master (commit 59df9d0d887f11724679f2c99dec0f05d6caeaf4) causes a fatal error:

```bash
/home/jul3x/SFML/src/SFML/Window/Unix/CursorImpl.cpp:32:10: fatal error: X11/Xcursor/Xcursor.h: No such file or directory
   32 | #include <X11/Xcursor/Xcursor.h>
```

## Your environment

* OS: Ubuntu 20.04
* SFML from master (commit 59df9d0d887f11724679f2c99dec0f05d6caeaf4)
* gcc 9.3.0

## Steps to reproduce

Commands:

```bash
sudo apt-get install libudev-dev libvorbis-dev libflac-dev libopenal-dev libfreetype6-dev libx11-dev libxrandr-dev
git clone https://github.com/SFML/SFML --branch master
cd SFML
cmake .
make
```

## Expected behavior

Compilation should be successful.

## Actual behavior

Fatal error occured:

```bash
/home/jul3x/SFML/src/SFML/Window/Unix/CursorImpl.cpp:32:10: fatal error: X11/Xcursor/Xcursor.h: No such file or directory
   32 | #include <X11/Xcursor/Xcursor.h>
```

I suppose that I am missing some dependency but why CMake haven't found any errors then?

**Comment by jul3x** [comment]
Executing:

```bash
sudo apt-get install libxcursor-dev
```

fixes compilation process.

**Comment by eXpl0it3r** [comment]
Yes, with #1694 we added a new dependency, so this is expected. 🙂
