### ISSUE TITLE
Call to Window::create can take up to a minute

### ISSUE THREAD

**Issue by Lauchmelder23** [SFML/SFML#1706]
## `Window::create` executes very slowly

When creating a new `sf::RenderWindow`, the eventual call to `WindowImpl::WindowImpl` can take up to a minute to complete. In a [StackOverflow thread](https://stackoverflow.com/questions/53017551/sfml-renderwindow-taking-a-long-time-to-open-a-window) I found out that the problem is DirectInput, and apparently only occurs when certain hardware is connected (Corsair K55 keyboard). This problem doesn't occur immediately, but only after building the project a couple dozen times. It's a very weird issue.

## Your environment

* Windows 10 Pro 64 Bit
* SFML built from source (commit 59df9d0)
* MSVC 14.27.29110

## Steps to reproduce

As described above, this issue is specific to the connected USB devices. Steps to reproduce are:

1. Connect a Corsair K55 Keyboard
2. Start working on a project using SFML.

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    // After a couple dozen builds while working on the project this is the call SFML gets stuck on
    sf::RenderWindow window(sf::VideoMode(1280, 720), "Minimal, complete and verifiable example");

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.display();
    }
}
```

## Expected behavior

SFML should not get stuck when creating a new RenderWindow

## Actual behavior

SFML gets stuck when creating a new RenderWindow

**Comment by milosz263** [comment]
Updating firmware of keyboard by Corsair iCUE application fixes this issue. Now creating a new RenderWindow takes ~400ms.
![image](https://user-images.githubusercontent.com/31561481/97087756-a9ea2a80-162c-11eb-9700-94ca0b2a0046.png)

**Comment by MrZeusTheCoder** [comment]
@Lauchmelder23 any info on this? Does @milosz263 suggestion help?

**Comment by Lauchmelder23** [comment]
@MrZeusTheCoder I don't know if @milosz263 answer works, I haven't tested it yet. I found a hacky """"workaround"""" tho, if you don't mind building sfml yourself.

https://stackoverflow.com/a/64139867

**Comment by MrZeusTheCoder** [comment]
There has been known issues with K55s. Your workaround may work, but by removing the `processJoystickEvents` you are disabling use of any joystick. (Hence, of course, your note) Some more debug info would be awesome. Could you track down what line in the `processJoystickEvents` is taking forever? Hopefully this is fixable!

**Comment by Lauchmelder23** [comment]
@MrZeusTheCoder I have located the culprit. In file [JoyStickImpl.cpp line 472](https://github.com/SFML/SFML/blob/c10c458169128e001ff886a18b3963894fb5052f/src/SFML/Window/Win32/JoystickImpl.cpp#L472) there is a call to a DirectInput function which can take a solid 30 seconds to return. So unfortunately the problem isn't with SFML, but with either DirectInput or Corsair. I don't know enough about DirectInput to attempt a fix myself, but maybe someone else can take over from here.

**Comment by MrZeusTheCoder** [comment]
If updating the firmware fixes then it is a Corsair issue. I was pretty sure of this in the first place, but it is good to know for sure. https://forum.corsair.com/forums/showthread.php?t=173987 <<< You don't seem to be the only one having trouble with the K55.

From Corsair from that page: 

> What we have found through our own rigorous testing is that Steam will continuously poll all USB devices looking for controllers once you start the program. This causes HID devices to get confused as to which program takes priority and which to respond to, and will cause hangs or crashes with either Steam or CUE. If a fix is possible through CUE, we will provide it once available.

Polling the device happens to be what we are doing. Of course we need to do this. I assume the firmware update contains a fix for the above issue. Thanks for posting, @Lauchmelder23 . Probably safe to close this one seeing it is an issue on Corsair's side.

**Comment by Lauchmelder23** [comment]
@MrZeusTheCoder I would leave this issue open for just a bit longer. This is obviously a fault with Corsair's driver, but I feel like there should still be a way to prevent this from happening in this library. Lots of software uses DirectInput, and none of them have ever raised this exact issue for me. I don't know enough about DirectInput to confidently change that part of the code, but maybe someone stumbling upon this will!

I'll do some experiments as well to see if I can find a way to circumvent this.

**Comment by MrZeusTheCoder** [comment]
Relate: https://github.com/glfw/glfw/issues/1284

Their fix was to wait on initializing joysticks till after the window is made. This isn't really desirable. I am pretty sure this would delay the joystick(/keyboard?) working until a minute after the window is created. I really don't think it is possible to fix this from the SFML side, but yo do what you think is best. Best of luck and happy coding!

**Comment by Bromeon** [comment]
How GLFW addressed it, is lazy initialization of joysticks on first use, see https://github.com/glfw/glfw/commit/782e6b6cefc9ac2a2b6779f9e658ab948809253b. This had the nice effect that programs which don't use the joystick don't have to pay for its initialization/deinitialization.

I'm not sure what happens if you access a joystick before the window, or if that's even possible.

**Comment by Lauchmelder23** [comment]
I'm still no expert in DirectInput, so I couldn't find a solution to this problem that doesn't break a fundamental part of the library. The only possibility I see would be to have the user initialize the Joystick explicitely (e.g. in SDL2 the user chooses what parts of the library he wants to initialize). However this would change a fundamental feature and would probably break every project that uses Joysticks.

**Comment by ventsin** [comment]
I used a K55 myself and a lot of other software, like literally any Capcom game, would freeze for 1-2 minutes after window creation before starting. In the Persona 4 Golden PC port, I would get frequent minute-long freezes during gameplay (every 3 minutes or so). SFML window creation took exactly 40 seconds every time, which made debugging a nightmare, etc.

I think at this point it's really just a problem with Corsair and their very substandard drivers and overall software. My particular keyboard had all sorts of other defects and firmware issues, and couldn't be updated/reset properly.

So yeah, I don't want to be _that_ guy, but anyone using the K55 or other Corsair peripherals should probably just switch boards. 
I don't think libraries like SFML should have to bend over backwards to try and avoid a driver issue from one company. And Corsair should be ashamed of their driver department.

**Comment by ChrisThrasher** [comment]
How much of a problem is this these days? Has the situation significantly improved with Corsair firmware quality?

**Comment by eXpl0it3r** [comment]
Beyond just removing any hardware input polling, there isn't really anything we can do about broken driver or firmware.
I haven't heard of this issue in quite a while, so I assume it's safe to just close it.
