### ISSUE TITLE
sf::Event::MouseMoved 'y' is always 32767

### ISSUE THREAD

**Issue by xubury** [SFML/SFML#1728]
----

## Subject of the issue
By running the code snippet below, I always get y=32767 in `sf::Event::MouseMoved` event. But the `sf::Event::MouseButtonReleased` is normal. What's going on here?

Output:
```
Moved: 317 32767
Moved: 317 32767
Moved: 316 32767
Moved: 314 32767
Clicked:552 314
Moved: 314 32767
Moved: 313 32767
Moved: 312 32767
```

## Your environment

* windows10
* mingw-w64-x86_64-sfml 2.5.1-2
* compiler: mingw-w64-x86_64-gcc 10.2.0-6 
* compiler flags used:  -Wall -Wextra -Wundef -pedantic -std=c++17

## Steps to reproduce
```cpp
#include <iostream>

int main() {
        sf::RenderWindow window(sf::VideoMode(1280, 720), "test");
    while (window.isOpen()) {
        sf::Event event;
        while (window.pollEvent(event)) {
            if (event.type == sf::Event::KeyPressed) {
                if (event.key.code == sf::Keyboard::Escape) {
                    window.close();
                }
            } else if (event.type == sf::Event::MouseButtonReleased){
                std::cout << "Clicked:" << event.mouseButton.x << " " << event.mouseButton.y << std::endl;
            } else if (event.type == sf::Event::MouseMoved) {
                std::cout << "Moved: "<<event.mouseButton.x << " " << event.mouseButton.y << std::endl;

            }
        }
    }
    return 0;
}
```

## Expected behavior
The value of mouse pos in move event should be about the same as click event.

## Actual behavior
Abnormal mouse pos value in  `sf::Event::MouseMoved`

**Comment by xubury** [comment]
Ok. So `sf::Event::MouseMoved` should use `event.mouseMove.x, event.mouseMove.y`. I thought both event will use `event.mouseButton`. That's kind of confusing..

**Comment by Bromeon** [comment]
It may be a bit confusing indeed, but unfortunately there's no idiomatic and simple way of type-safe unions in C++ (especially not C++98).

This is however explained [in the tutorial](https://www.sfml-dev.org/tutorials/latest/window-events.php#the-mousemoved-event).
