### ISSUE TITLE
Compiling on windows in command line

### ISSUE THREAD

**Issue by HubertFraczek** [SFML/SFML#1730]
## My environment

* Windows 10
*  SFML (2.5.01 GCC 7.3.0 MinGW (SEH) - 64-bit version)
* MinGW7.3.0 (64-bit)
last 2 lines of g++ -v:
Thread model: posix
gcc version 7.3.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)

## Steps to reproduce
```bash
g++ main.cpp *other cpp files* -o main.o -I*path to*\SFML-2.5.1\include -g -m64 -Wall && g++ main.o -o main -L*path to*\SFML-2.5.1\lib -lsfml-graphics -lsfml-window -lsfml-system
```

## Expected behavior
It should compile my program.

## Actual behavior
I'm getting this error:
fatal error: SFML/Graphics.hpp: No such file or directory
 #include <SFML/Graphics.hpp>
                ^~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by eXpl0it3r** [comment]
This works fine on my end, there must be some setup issues on your end as pointed out on Discord. 🙂

For general help questions, please use the forum instead of the issue tracker.
