### ISSUE TITLE
Question about CMake necessary rule

### ISSUE THREAD

**Issue by paulo-coutinho** [SFML/SFML#1737]
Hi,

In my project im using cmake 3.14.1 only, so i need this?

```
# Suppress Mac OS X RPATH warnings and adopt new related behaviors
cmake_policy(SET CMP0042 NEW)
if (NOT CMAKE_VERSION VERSION_LESS 3.9)
    cmake_policy(SET CMP0068 NEW)
endif()
```

Thanks.

**Comment by eXpl0it3r** [comment]
Please use the [forum](https://en.sfml-dev.org/forums) for questions. Unfortunately, I don't even know what you're trying to ask here?
