### ISSUE TITLE
How is new version going

### ISSUE THREAD

**Issue by MXWXZ** [SFML/SFML#1738]
Friendly ping, I have been using it for about 2 years and recently wanted to upgrade our project. However we find the stable version is just like when we create the project - 2.5.1 :)
But the git log shows that we are doing lots of update to master branch, that may mean lots of bug fix to old version(though we didn't meet very often), so I want to know whether the master branch could be used or the new version is just on the way?

**Comment by eXpl0it3r** [comment]
The master branch can always be used 🙂 

See the [Roadmap](https://en.sfml-dev.org/forums/index.php?topic=24372.0) and [GitHub Project](https://github.com/SFML/SFML/projects/4) for the current plan regarding SFML 2.6 and more.
