### ISSUE TITLE
Image::copy does not throw an exception for empty images

### ISSUE THREAD

**Issue by DeltaNedas** [SFML/SFML#1748]
## Subject of the issue

When an empty image is copied to, no exception is raised and further operations on its null pixelsptr cause a segfault.
Since it already checks for being null in order to print a silly message, it could easily be repurposed to throw an exception.

## Your environment

* Debian Buster
* SFML 2.5.1
* G++ 8.3.0
* `-O3 -Wall -Wextra -pedantic -g -std=c++2a -lsfml-graphics -lsfml-window -lsfml-system`

## Steps to reproduce

```
$ g++ -o crash $cflags $ldflags crash.cpp
$ ./crash
Original pixels ptr 0x56279ad1b060
Trying to access the pixels of an empty image
Copied pixels ptr (nil)
Segmentation fault (core dumped)
```

```cpp
#include <cstdio>

#include <SFML/Graphics.hpp>

int main() {
	sf::Image original, copy;
	// populate the original
	original.create(32, 32);
	// copy it into copy, less a 4px border
	copy.copy(original, 0, 0, sf::IntRect(4, 4, 24, 24));
	// copy() returned instead of throwing an exception!

	printf("Original pixels ptr %p\n", (void*) original.getPixelsPtr()); // a heap address
	printf("Copied pixels ptr %p\n", (void*) copy.getPixelsPtr()); // (nil)
	copy.getPixel(0, 0); // SIGSEGV time :D
	return -1;
}

```

## Expected behavior

An exception is thrown when trying to `copy` into an empty image, or it should be created to fit the source region.

Since it's a clear programmer error, an exception should be thrown and not a message in stderr.

## Actual behavior

A message is simply printed and the program segfaults.

**Comment by LaurentGomila** [comment]
Exceptions are not for programmer errors, they are for unexpected runtime errors. Programmer errors are best handled with assert -- which sf::Image uses. Moreover, SFML doesn't use exceptions at all.

> Since it already checks for being null in order to print a silly message
No it doesn't print anything, it just returns if the source image is empty.

> When an empty image is copied to, no exception is raised and further operations on its null pixelsptr cause a segfault.
This is totally unrelated to the `copy` function. It's just that your `getPixel` call accesses pixels of an empty image, and as the documentation says:

`/// This function doesn't check the validity of the pixel
/// coordinates, using out-of-range values will result in
/// an undefined behavior.
`

**Comment by DeltaNedas** [comment]
ah it's documented there, fair point
