### ISSUE TITLE
MacOS CMake Rejects arm64 arch

### ISSUE THREAD

**Issue by jkeller51** [SFML/SFML#1749]
## Subject of the issue

SFML/CMakeLists.txt contains this fatal error in the MacOS section:
```
    # only the default architecture (i.e. 64-bit) is supported
    if(NOT CMAKE_OSX_ARCHITECTURES STREQUAL "x86_64")
        message(FATAL_ERROR "Only 64-bit architecture is supported")
    endif()
```

However, when bypass this check I am able to build and run native arm64 just fine on a MacBook Pro with an M1 processor.

## Your environment

macOS Big Sur 11.2
Xcode 12.4
CMAKE_OSX_ARCHITECTURES = "x86_64;arm64"

## Suggested Solution
Split the CMAKE_OSX_ARCHITECTURES by semicolon and make sure each item is either x86_64 or arm64. I'm not a CMake wizard but I could maybe do this within a few days.

**Comment by eXpl0it3r** [comment]
Fixed with #1750
