### ISSUE TITLE
McAfee anitvirus alert

### ISSUE THREAD

**Issue by roylowe** [SFML/SFML#1758]
when downloading the SFML C++ for windows  32 bit(SFML-2.5.1). Mcafee triggered a virus alert and blocked a potential virus.

the triggered file is:  sfml2.5.1/examples/island/island.exe

is there a virus there or something that needs fixed?

**Comment by eXpl0it3r** [comment]
That's a false-positive. It would help us a lot if you could [report it as false-positive to McAfee](https://service.mcafee.com/webcenter/portal/oracle/webcenter/page/scopedMD/s55728c97_466d_4ddb_952d_05484ea932c6/Page29.jspx?articleId=TS103032).
If you don't trust it, you can always delete it and build the example from source yourself.
