### ISSUE TITLE
MacOS: When initializing an openGL view with an existing window, call finishInit

### ISSUE THREAD

**Issue by jkeller51** [SFML/SFML#1759]
I had some long-standing bugs in my software dealing with SFML not receiving certain window notifications. I had worked around them outside of SFML but during a recent dig through the code I found the cause. When creating an `sf::RenderWindow` with a frame size (e.g. telling SFML to make its own window), it makes its `SFOpenGLView` receive certain window notifications, including `NSWindowDidChangeScreenNotification` and `NSWindowDidChangeScreenProfileNotification`.

But when instantiating an `sf::RenderWindow` inside of an existing window, the `SFOpenGLView` is never set up to receive these notifications, so certain events are "missed" by SFML. For DPI-aware applications, this can cause unexpected behavior.

I'm not sure if there was a reason for leaving this out, but adding it back in makes more sense to me and more cleanly solves the problems I was having.

## Your environment

* MacOS 11
* SFML https://github.com/SFML/SFML/commit/252d26afb0aa6375e08ef95b754cccf60f31b6df
* Xcode 12.4

## Steps to reproduce

Create an `NSWindow` manually, then create an `sf::RenderWindow` by passing the `NSWindow` handle.

## Expected behavior

When DPI scaling changes occur (e.g. passing between windows or changing display scaling), the sf::RenderWindow should receive an event. Currently this is supposed to be passed to the `Event::Resized` event.

## Actual behavior

When the `sf::RenderWindow` is instantiated inside of an existing NSWindow, this notification is not received.

**Comment by eXpl0it3r** [comment]
Fixed with #1760
