### ISSUE TITLE
[Linux amd64] kubuntu + intel gpu i915: SFML apps yield to high kwin_x11 CPU usage and high GPU usage

### ISSUE THREAD

**Issue by tcosmo** [SFML/SFML#1764]
## Subject of the issue

This issue seems to be intrinsically tied to the following setup:

1. Using KDE window manager: `kwin_x11` (v5.18.5)
2. Having a intel i915 gpu (UHD Graphics 620)

In that scenario, any SFML app that opens a window drives the X server crazy:

1. High CPU usage for `Xorg` and `kwin_x11`: nearly 30% while app is idle
2. High GPU usage, `intel_gpu_top` shows that GPU 3D rendering is busy at 60% even if app draws nothing
3. The app itself shoes a normal CPU usage (<2%, idle app that draws nothing)

Importantly:

1. The issue disappears when using GNOME or i3 on the same machine, hence it is really tied to the combination KDE + X11.
2. The issue does not happen when using SDL or  lib Allegro, so it really seems that it is specific to the way SFML interacts with server X when using `kwin_x11`

## My environment

* Linux / Kubuntu 20.04 / KDE 5.18.5 / Xorg 2:1.20.9-2ubuntu1.2~20.04.1
* Tested on both 2.5.1 and master
* Tested with clang 10 and g++ 9.3
* Standard flags from cmake config

I am happy to add more info about my environment (outputs of specific commands) if needed.

## Steps to reproduce

Any SFML program that opens windows, such as the following examples that draws nothing:

(Note that bug is still there if I replace setFramerateLimit by enabling vsync)

```cpp
#include <SFML/Graphics.hpp>

int main() {
  sf::RenderWindow window(sf::VideoMode(200, 200), "SFML works!");
  window.setFramerateLimit(30);

  while (window.isOpen()) {
    sf::Event event;
    while (window.pollEvent(event)) {
      if (event.type == sf::Event::Closed)
        window.close();
    }

    window.clear();

    window.display();
  }

  return 0;
}
```

## Expected behavior

1. Server X and `kwin_x11` should not go into high CPU usage
2. `intel_gpu_top` should show very minimal GPU activity

The expected behavior is happening on the same machine when using i3 or GNOME instead of KDE.

Note also that the bug is not happening when using lib SDL or lib Allegro with X11 backend in same conditions.

## Actual behavior

1. Server X and `kwin_x11` go into intensive CPU usage, as per screenshot attached
2. `intel_gpu_top` show high GPU usage, as per screenshot attached

![Screenshot_20210323_142641](https://user-images.githubusercontent.com/7616128/112162378-e920a580-8be3-11eb-841a-045359e8157b.png)      

![Screenshot_20210323_142700](https://user-images.githubusercontent.com/7616128/112162375-e8880f00-8be3-11eb-8d60-ed94b1671f43.png)

## I did some digging

I did some more digging and, inspired by the `X11.cpp` example on the SFML repo I came out with a minimum working example of a SFML - X11 code that produces the bug: https://pastebin.com/qxD0Eicx

The Bug arises only when `sfmlView1.display();` is called (line 76).

Behind that call seems to be a call to `sf::priv::GlContext *sf::Window::m_context` `display()` which I guess is platform specific.

Note that again, nothing is drawn on the screen by the code which makes this high GPU usage and X server CPU usage really weird.

**Comment by tcosmo** [comment]
It looks that I solved the issue by lowering the Compositing settings of KDE from Accurate to Smooth and using Opengl 3.1 compositing backend instead of Opengl 2

**Comment by eXpl0it3r** [comment]
Sounds then more like a "performance" issue with that setup and less anything SFML can do.

`display()` does the the buffer swapping (even if you don't "draw" anything).

**Comment by tcosmo** [comment]
But if it is not related to SFML, how can we explain that this behavior was not happening with SDL and liballegro both using x11 as well?

**Comment by eXpl0it3r** [comment]
Maybe they force a different mode somehow?

I don't know enough about the inner workings of X11 and Linux window managers to even start to understand how things work in there. 😅
