### ISSUE TITLE
Investigate support for loop points in musics and sounds

### ISSUE THREAD

**Issue by LaurentGomila** [SFML/SFML#177]
This is not an easy task, because OpenAL doesn't give us full control on the audio playback.

Moreover, the public API should be flexible enough but remain simple.

See this for more details:
http://en.sfml-dev.org/forums/index.php?topic=7079.0

Another topic, with a workaround implementation using two musics:
http://en.sfml-dev.org/forums/index.php?topic=2480.0

_(there are other similar discussions about this feature on the forum)_

**Comment by eXpl0it3r** [comment]
Merged in 93a2e9502dfcf5b69a3e53b5eaf2905ca9b17d7c
Thanks for all the work @Cobaltergeist!
