### ISSUE TITLE
Allow using CoordinateType::Normalized in RenderTarget::draw

### ISSUE THREAD

**Issue by cschreib** [SFML/SFML#1773]
## Subject of the issue

I am maintaining a library which uses several back-ends for rending 2D graphics, and SFML is one of them. Recently, I started implementing optimized batching using vertex buffers. I am kind of stuck writing the SFML implementation for this, because `RenderTarget::draw()` always assumes that texture coordinates are given in pixels rather than normalized.

Unfortunately, in my library, when vertex buffers are created they know nothing of which texture will be used for rendering (and which size it will have). Thus the (back-end agnostic) interface expects normalized texture coordinates. There is no way to know, until the point of rendering, which texture will be used, hence which UV pixel coordinates should be sent to SFML. I could adjust this on the fly, but that would kill any performance gain from using vertex buffers in the first place.

I see that `Texture::bind()` allows specifying whether UV coordinates are in pixels or normalized, but as far as I know, to use `Texture::bind()` I would have to re-implement most of the OpenGL draw calls myself to get something rendered, as `RenderTarget` does not publicly expose functions like `applyTransform()`, `applyCurrentView()`, `applyBlendMode()`, etc., for me to reuse. That would defeat the purpose of using SFML for rendering as opposed to just using raw OpenGL.

My problem would be fixed if either of the following was implemented:
 - `RenderStates` is extended with a new field for specifying whether to bind the texture with normalized or pixel coordinates, rather than forcing `CoordinateType::Pixels`. That field would default to `Pixels` to preserve backward compatibility.
 - `RenderStates` is extended with a new field specifying the matrix transform to apply to texture coordinates (which gets combined with the matrix used internally to switch between pixel and normalised coordinates). By default this would be the identity, to preserve backward compatibility.
 - `RenderTarget::applyTexture`, delegates the choice of coordinate type to (to be added) `Drawable::getCoordinateType()` and `VertexBuffer::getCoordinateType()`. The type of coordinates to use is really a property of the drawable, not of the texture or the renderer. Unless specified, the coordinate type in a newly constructed drawable/vertex buffer would be `Pixels`, to preserve backward compatibility.

I am happy to make a PR to implement either solutions, if this is desirable.

## Your environment

* OS: Linux Mint 20.1
* SFML version: 2.5.1
* Compiler: clang++-10
* Special compiler flags used: none

## Steps to reproduce
N/A

## Expected behavior
N/A

## Actual behavior
N/A

**Comment by Bromeon** [comment]
The challenge here is that the whole SFML API is based in pixel (or world) coordinates, to add normalized coordinates we would need to make the "breach of convention" very clear to the user. That being said, I have nothing general against it.

What do other developers think? @eXpl0it3r @binary1248 @LaurentGomila

**Comment by binary1248** [comment]
I also don't have anything against making the API more accessible to a wider audience as long as we don't have to sacrifice the core value of the library being the simplicity that it offers to beginners. As long as we don't change the default behaviour (pixel coordinates) we should be able to add additional overloads that simultaneously allow for more advanced/fine-grained usage.

**Comment by cschreib** [comment]
Of the various options listed above, the least intrusive is probably
> RenderStates is extended with a new field specifying the matrix transform to apply to texture coordinates (which gets combined with the matrix used internally to switch between pixel and normalised coordinates). By default this would be the identity, to preserve backward compatibility.

With this solution, there is no need to mention pixel vs normalised coordinates any more than is currently done. The new texture transform field can be advertised primarily with pixel coordinates in min, to achieve cool texture effects. It can also be used by those who need normalised coordinates, to undo the internal transform done by SFML to convert pixel coordinates to normalised coordinates.

**Comment by binary1248** [comment]
Passing an entire matrix is a bit too heavy for me. In 99% of all use cases, the user is either going to use either pixel or normalized coordinates. And realistically, if they did go for some other more exotic way of sampling textures, chances are they won't be making use of sfml-graphics at all. sfml-graphics would be more of a hindrance than support compared to doing everything yourself in such special use cases.

**Comment by cschreib** [comment]
`RenderStates` already holds a matrix for the vertex transformation, so it would be at most a doubling in size. I see what you mean if the only purpose is switching between coordinate mode, however.

Yet I think this approach could be used to implement a number of useful things in sfml-graphics, not necessarily exotic stuff. You could for example use this to implement texture atlases (setup tex coords once as if reading from a single texture, but perform a translation with the texture matrix to sample from the right position in the atlas), large number of animated sprites, etc.

You can go a very long way with vertex buffers, which SFML does support.

**Comment by binary1248** [comment]
The OpenGL matrix stack has been deprecated for more than a decade and even removed from the core profile (and newer OpenGL ES). We shouldn't encourage users to make use of this. If they really wanted equivalent functionality they could already achieve it in a future-proof way by using shader uniforms.

**Comment by cschreib** [comment]
I agree. However, unless there is something fundamental about SFML that I missed, this feature does not need to be implemented using the matrix stack. It can start out that way as a first implementation, but it can be implemented in SFML using uniforms & shaders under the hood. That implementation choice is not visible to user, who just sets whatever transform they like.

**Comment by binary1248** [comment]
Assuming we added a texture matrix to `RenderStates` how would it interact with the current texture matrix manipulation that SFML performs? There would have to be some way to indicate that the matrix in `RenderStates` should be ignored. I'm not a fan of unnecessarily multiplying matrices every draw even if the user knows that one of them is always going to be the identity matrix.

**Comment by cschreib** [comment]
If I got this right, this is currently handled by ``Texture::bind()``, which create a new matrix on the fly on each bind:
https://github.com/SFML/SFML/blob/43b2e9dc125954a40af8a4dc135a6841b4adabb8/src/SFML/Graphics/Texture.cpp#L745-L769

The matrix created here would start off as the actual transform instead of the identity (might need tweaking the maths), and would be moved out of ``Texture::bind()`` and into ``RenderTarget::setupDraw()``. That would come at a cost, since ``Texture::bind()`` does not happen on every draw. How much of a cost depends on how often users perform draw calls with the same texture: virtually no cost if each draw call happens with a different texture, max cost if there's only ever one texture used (and in that scenario, you'd likely use a vertex array or vertex buffers, which will turn that into a single draw call and no performance overhead). ``RenderTarget::applyTransform()`` already sends a new matrix (or loads the identity) on each draw call, so it's not going to be a huge performance hit, I think. But there's only one way to find out.

**Comment by cschreib** [comment]
Hmm I forgot `Texture::bind` is public so can't take things out without preserving backward compatibility. Maybe an overload can be added that just binds the texture without setting the matrix.

**Comment by cschreib** [comment]
If this is not your favourite implementation, which alternative would you prefer? A simple flag for normalised vs pixel coordinates in `RenderStates` would probably be the easiest

**Comment by binary1248** [comment]
I think the use case you mentioned above about texture atlases is already typically implemented with pre-computed texture coordinates (pixel coordinates makes this pretty simple).

The key to performance is doing as little work as possible, both on the CPU and GPU. Having to multiply by an additional matrix per draw to e.g. shift an animation to the next frame is way more expensive than just updating the starting index in a vertex array or vertex buffer containing the proper data that has to be computed just once during the entire runtime. In the latter case we even save on data transfers to the GPU since the only thing that changes is the starting point into the already uploaded vertex attribute data.

I just have difficulty thinking of a scenario in which having the flexibility of specifying the entire matrix is necessary to achieve some effect, let alone be better performance-wise than the other alternative implementations.

**Comment by cschreib** [comment]
Ok, fair enough. I am not attached to a particular solution. I mostly wanted to see if there was a more generic solution that would benefit SFML users overall, rather than just satisfy my smaller niche :)

If you want to keep the performance cost at a minimum, I have two designs in mind:
 - add the flag to `RenderStates` as described above
 - add the flag as a member of `sf::Texture`, which could be probed by `sf::RenderTarget` to choose the right arguments for `sf::Texture::bind`. I thought about making it a member of `sf:: Drawable` at first, but a) it is more invasive, and b) it would require more work on each draw call (and/or more state to keep track of).

**Comment by binary1248** [comment]
Adding the flag to `RenderStates` makes more sense. `RenderStates` are meant to be copied around and possibly reused. Adding the flag to `sf::Texture` would just hinder the user from using the same texture in multiple draw calls with differing coordinate types unless they keep switching the flag within the texture.

**Comment by cschreib** [comment]
Ok! I will try to put together a PR for this. Thanks for your input.

**Comment by eXpl0it3r** [comment]
Implemented with #1807
