### ISSUE TITLE
Bug on the sfml site

### ISSUE THREAD

**Issue by ptaszor3** [SFML/SFML#1774]
This one is only cosmetic. On the [page](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1SoundStream.php#a3f717d18846f261fc375d71d6c7e41da) in the detailed description there is no ';' at the end of class CustomStream

**Comment by eXpl0it3r** [comment]
Thanks for the report, I created the tiny PR #1776 to fix it. 🙂
