### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by ptaszor3** [SFML/SFML#1775]
On this [page](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1SoundStream.php#a968ec024a6e45490962c8a1121cb7c5f) play, pause and stop are defined as virtual even though they are actually abstract (pure virtual).

**Comment by eXpl0it3r** [comment]
`play()`, `pause()` and `stop()` are not pure virtual function in `sf::SoundStream` itself, see the [header file](https://www.sfml-dev.org/documentation/2.5.1/SoundStream_8hpp_source.php).

`play()`, `pause()` and `stop()` are pure virtual function in `sf::SoundSource`, which is also represented as such in [the documentation](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1SoundSource.php#a21553d4e8fcf136231dd8c7ad4630aba).
