### ISSUE TITLE
Suggestion: make a new release

### ISSUE THREAD

**Issue by dgengin** [SFML/SFML#1778]
The last release was in late 2018.

While we can always use the latest master, if you're using CI or a package manager (conan, vcpkg), it's useful to have an official release.

Another reason being that the current version in master is set to 2.5.1, so it's hard for devs to feature test based on the version defines because they're the same. There are some things that I would like to use from master that I can't because I have no way of testing from my side if the package that users get will have those changes or not.

I suggest to release what we have now as 2.5.x or 2.6.0 and the rest in a later release.

As an alternative, I suggest changing the defines in master after an official release to be incremented right after so that we can use conditional code on our side. Another option is to have feature tests or something similar so we can detect new features (https://en.cppreference.com/w/cpp/feature_test).

**Comment by eXpl0it3r** [comment]
The next release is not too far away, see the [Roadmap post](https://en.sfml-dev.org/forums/index.php?topic=24372.0) and the [GitHub project](https://github.com/SFML/SFML/projects/4). 

Creating a new release isn't as simple as adding a new tag, but there's quite a bit of [additional work](https://github.com/SFML/SFML/wiki/SD%3A-Releases) involved. I'm hoping however, that we can reduce the amount of work required in the future.

Additionally, for SFML 3 we'll change the way we handle versioning on the repository. It was discussed a long time ago, but we never actually applied it, that the master branch should essentially always carry the next version also in code. That way it's easier to feature test.
