### ISSUE TITLE
Building with Clang under a MinGW environment fails

### ISSUE THREAD

**Issue by SuperV1234** [SFML/SFML#1784]
## Subject of the issue

Building using `-DCMAKE_CXX_COMPILER=clang++` in a MinGW environment (e.g. installed via MSYS2) results in a compilation failure, because SFML's CMake files assume that when `SFML_COMPILER_CLANG` is `TRUE` then `clang-cl` is being used.

## Your environment

* Windows 10, using a MinGW x64 environment obtained via MSYS2
* `master` branch of SFML
* clang version 11
* no special compiler flags

## Steps to reproduce

1. Obtain [MSYS2](https://www.msys2.org/)
2. Open a MSYS shell and install `mingw-w64-x86_64-clang` via `pacman`
3. Open a MinGW 64-bit shell and

    ```bash
    git clone https://github.com/SFML/SFML
    cd SFML
    mkdir build
    cd build
    cmake .. -G"MinGW Makefiles" -DCMAKE_CXX_COMPILER=clang++
    ```

4. Observe the compilation failure -- SFML tries to get libraries from `libs-msvc-universal`

**Comment by eXpl0it3r** [comment]
Looks like this is because of this rule

https://github.com/SFML/SFML/blob/59df9d0d887f11724679f2c99dec0f05d6caeaf4/src/SFML/CMakeLists.txt#L16-L29

If you can figure out a way to support `clang-cl` and clang msys/mingw I'd appreciate a PR!
