### ISSUE TITLE
Building example `window` fails on missing X11 dependencies.

### ISSUE THREAD

**Issue by psiwray** [SFML/SFML#1793]
## Subject of the issue

Building the `window` example fails throwing linker errors about X11.

## Your environment

* Your OS / distro / window manager used: Ubuntu 20.10
* Your version of SFML (2.5.0, git master, etc): git master
* Your compiler and compiler version used: GCC 10.2.0
* Special compiler flags used: none

## Steps to reproduce

Set the CMake flag to build examples and generate the project using the Unix Makefiles generator. Once you run the `make` command, compilation fails even though all development headers and libraries are installed on the system like suggested. The error is about missing X11 functions in `sfml-window.so`.

## Expected behavior

The project's examples should compile.

## Actual behavior

The `window` target isn't properly built. I'm not sure if this is a problem that I'm having because of my own configuration/setup but I've already found a solution and forked the repository. If you think this is an issue and want to accept a pull request, I can create one, otherwise you just need to add `X11` as a dependency to the executable target in `examples/window/CMakeLists.txt` inside the command `sfml_add_example` resulting in a working executable being built.

**Comment by eXpl0it3r** [comment]
Can you provide the complete error message?

**Comment by psiwray** [comment]
I just tried to rebuild the project from scratch without changing anything, no options whatsoever and it's compiling without issues. Could it be because I've installed the targets from the previous build?

**Comment by eXpl0it3r** [comment]
Without the error message, I can't really tell what was missing or what was misconfigured

**Comment by psiwray** [comment]
I'll try to reproduce the error again and will let you know. If I fail, I'll just close the issue.

**Comment by psiwray** [comment]
So the problem seems to be that I didn't update the CMake cache when installing the missing libraries and doing that made the project to successfully compile and link, including all examples, so there's no need to change anything.

Sorry for wasting your time, I should've looked deeper into the problem before opening an issue.

**Comment by eXpl0it3r** [comment]
No worries, glad you could figure it out! 🙂
