### ISSUE TITLE
Bug with checking event of pressed Keyboard::Escape

### ISSUE THREAD

**Issue by AutreTemps** [SFML/SFML#1797]
## Subject of the issue

Let's say we want to write a condition in which the window will be closed by the Escape key. To do this, write if (event.key.code == sf::Keyboard::Escape), at which the window closes. However, when the cursor is about 30 pixels away from the left edge of the window, this condition is triggered without pressing Esc, and the window closes.

## Your environment

* Windows 10
* SFML 2.5.1
* MinGW GCC 7.3.0
* No special compiler flags

## Steps to reproduce

Adding one condition to the basic example from the tutorial:

```cpp
#include <SFML/Graphics.hpp>
#include <iostream>

int main()
{
    sf::RenderWindow window(sf::VideoMode(200, 200), "SFML works!");

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed) {
                window.close();
            }
            else if (event.key.code == sf::Keyboard::Escape) {
                window.close();
                std::cout << "ESC PRESSED\n";
                std::cout << sf::Mouse::getPosition().x << '\n';
            }
        }

        window.clear();
        window.display();
    }

    return 0;
}
```
Then slowly moving the cursor towards left edge of the window.

## Expected behavior

Nothing special, the cursor just moves.

## Actual behavior

Window closes and we recieve message "ESC PRESSED" and x-coordinate of cursor. This coordinate is fluctuating in +-1 diapason in different runs.

**Comment by eXpl0it3r** [comment]
You always have to check the event type, as mentioned in [the tutorial](https://www.sfml-dev.org/tutorials/2.5/window-events.php). Since `sf::Event` is a union, ot can contain random values if the event type is different.
