### ISSUE TITLE
Documentation for sf::Vertex has incorrect coordinate type

### ISSUE THREAD

**Issue by owwk** [SFML/SFML#1799]
The [documentation for sf::Vertex](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Vertex.php) states both in the example code and below text that "texture coordinates are supposed to be an integer amount of pixels". 

However texture coordinates given with this constructor are actually treated as normalized coordinates by default.

**Comment by LaurentGomila** [comment]
At this point, texture coordinates are not interpreted. It's the flag given to `Texture::bind` that selects the coordinates mode. And as long as you use the SFML API (`RenderTarget::draw`), texture coordinates will always be interpreted as pixels. The normalized mode is there only for use with raw OpenGL rendering.

**Comment by owwk** [comment]
If I define vertices like this:

    sf::Vertex vertex[4];
    vertex[0] = sf::Vertex(sf::Vector2f(0.0f, 0.0f), sf::Color::White, sf::Vector2f(0.0f, 0.0f));
    vertex[1] = sf::Vertex(sf::Vector2f(window_size.x, 0.0f), sf::Color::White, sf::Vector2f(1.0f, 0.0f));
    vertex[2] = sf::Vertex(sf::Vector2f(window_size.x, window_size.y), sf::Color::White, sf::Vector2f(1.0f, 1.0f));
    vertex[3] = sf::Vertex(sf::Vector2f(0.0f, window_size.y), sf::Color::White, sf::Vector2f(0.0f, 1.0f));

And then call draw with a shader like this:

    window.draw(vertex, 4, sf::PrimitiveType::Quads, &shader);

Then the texture coordinates will be passed to the shader as normalized coordinates, they won't be scaled by any texture.

If I understand you correctly you are saying that there are some draw methods that would in fact treat these as pixel coordinates? Perhaps the docs could be updated to specify which type of coordinates should be used in each case, because right now the docs make it sounds like pixel coordinates have to be used in all cases.

**Comment by LaurentGomila** [comment]
Indeed, if there's no texture then SFML can't use pixel coordinates (reminder: it's pixels _of the texture_, not the render-target). If you pass a valid texture to `RenderTarget::draw`, then pixel coordinates are used.

It's true that the documentation could be more detailed.

**Comment by eXpl0it3r** [comment]
Closing as I'm not sure what exactly would help clarify the situation.
