### ISSUE TITLE
android java.lang.NullPointerException

### ISSUE THREAD

**Issue by huberti1** [SFML/SFML#1809]
When doing gradle build on android example from examples folder I get:

FAILURE: Build failed with an exception.
What went wrong:
A problem occurred configuring project ':app'.
java.lang.NullPointerException (no error message)

**Comment by Bromeon** [comment]
Is that all the output you get? I don't think we can do much with this information...

**Comment by huberti1** [comment]
Yes, that's all. Do you get the same? I just downloaded the repo, added local.properties and tried to build using gradle build in console.

**Comment by huberti1** [comment]
I fixed the problem by using build scripts from https://github.com/SFML/SFML/wiki/Tutorial%3A-Building-SFML-for-Android. Than I deleted -stdlib=libc++ from them and updated classpath to 'com.android.tools.build:gradle:4.2.0'. After that I typed gradle wrapper, changed distributionUrl to https\://services.gradle.org/distributions/gradle-6.7.1-all.zip in gradle-wrapper.properties.
