### ISSUE TITLE
sfml-system.framework is damaged and can't be opened. 

### ISSUE THREAD

**Issue by hydrarguru** [SFML/SFML#1822]
I followed the tutorial to install SFML on [mac OS](https://www.sfml-dev.org/tutorials/2.5/start-osx.php) except I replaced the sfml binaries to the arm64 version as I have a M1 Mac. I setup a SFML project on XCode using one of the templates provided. The project builds successfully but I get an error that sfml-system.framework is damaged and can't be opened.
See error below:
<img width="258" alt="sfml-system-framework-error" src="https://user-images.githubusercontent.com/17914439/131584136-fab35578-5e16-4c33-a82a-3dac68dd5a02.png">

## Your environment

M1 Mac, macOS Big Sur 11.5.2
SFML Version: 2.5.1
Compiler: Clang, latest version.

Code used when compiling/building the project through XCode.
```cpp
#include <SFML/Graphics.hpp>

int main(int, char const**)
{
    // Create the main window
    sf::RenderWindow window(sf::VideoMode(800, 600), "SFML window");

    // Start the game loop
    while (window.isOpen())
    {
        // Process events
        sf::Event event;
        while (window.pollEvent(event))
        {
            // Close window: exit
            if (event.type == sf::Event::Closed) {
                window.close();
            }

            // Escape pressed: exit
            if (event.type == sf::Event::KeyPressed && event.key.code == sf::Keyboard::Escape) {
                window.close();
            }
        }

        // Clear screen
        window.clear();
        window.display();
    }

    return EXIT_SUCCESS;
}
```

**Comment by The-Good-Goomba** [comment]
I just moved from an old intel mac to the M1 mac and seems to be an issue with the new development. I have tested the snapshot as well and it too is broken

**Comment by ChrisThrasher** [comment]
Is this an issue with trying to a 3.0 framework in a 2.5.1 project? I don't see 2.5.1 ARM binaries on the website.

**Comment by hydrarguru** [comment]
I downloaded the arm64 binaries here: https://artifacts.sfml-dev.org/by-branch/master/

**Comment by ChrisThrasher** [comment]
Look at the URL. You’re using the master branch binaries which are a different major version than 2.5.1 so they’re surely not compatible.

**Comment by ntcc10** [comment]
Hii, for me it stills appear the error please help :(

**Comment by eXpl0it3r** [comment]
Better to open a forum thread or jump on Discord or if you post here, provide a bit more information on what steps you've taken and what exactly doesn't work.

**Comment by justinkwapich** [comment]
Was there a solution to this? I am seeing this problem as well. This file specifically "sfml-system" is damaged and can't be opened, yet the project is still building successfully.

**Comment by joeeliang** [comment]
I also have the same issue, and I'm wondering if there's any solutions yet?

**Comment by eXpl0it3r** [comment]
@justinkwapich & @joeeliang which file exactly are you experience issues with?
