### ISSUE TITLE
Installation tutorial for MacOS could use clarification.

### ISSUE THREAD

**Issue by rjdbcm** [SFML/SFML#1833]
## Frameworks location could be in other places besides /Library

* MacOS with Homebrew
* 2.5.1

I expected that my Frameworks Folder should be in /Library but realized, after some serious contemplation, I have been using homebrew since day 1 so my Frameworks search path is actually /usr/local/Library. Had I not been aware of this from previous frustrating experiences I wouldn't have known. Perhaps some clarification in the tutorial would help prevent any confusion.

**Comment by eXpl0it3r** [comment]
Thanks for bringing this up, I can see how this can be confusing.

As this is a tutorial change, I've moved it over to the SFML Website. If you want to help make this clearer, feel free to open a pull request there. 🙂 

https://github.com/SFML/SFML-Website/issues/149
