### ISSUE TITLE
ball game with SFML in c#

### ISSUE THREAD

**Issue by Priyam1604** [SFML/SFML#1838]
I'm creating a c# code using sfml in which if the user does the left-click, the ball will be shown and it will rotate randomly and we can create as many balls as possible by doing the left-click on the mouse. We can remove the balls by doing the right-click. 

Right now I have given the blue colour to the balls. But I  want to keep changing that colour.
Here is the output:
![unknown](https://user-images.githubusercontent.com/65926967/139329958-fbfe9d0a-286d-40f8-b67d-fc38817a0f76.png)

Instead of that blue colour in the balls, colour should keep on changing
Here is the code:
https://paste.mod.gg/vkqqfrjmdijm/0

or if want a .zip copy,
[1512428_PriyamPatel_SFMLAssignment.zip](https://github.com/SFML/SFML/files/7437130/1512428_PriyamPatel_SFMLAssignment.zip)

The desired output should look like this:
![unnamed12](https://user-images.githubusercontent.com/65926967/139330563-23ba33d6-1d8f-4854-a4e3-a31ba1d02505.jpg)

Can anyone please help?

**Comment by MarioLiebisch** [comment]
Your issue would be something for the [forums](https://en.sfml-dev.org/forums/). This is an issue tracker (as in bugs/problems within the library itself).

**Comment by Bromeon** [comment]
@Priyam1604 Maybe a tip for the forum:

> Here is the code: https://paste.mod.gg/vkqqfrjmdijm/0
> 
> or if want a .zip copy, [1512428_PriyamPatel_SFMLAssignment.zip](https://github.com/SFML/SFML/files/7437130/1512428_PriyamPatel_SFMLAssignment.zip)

People don't want to spend the time to download an entire archive, let alone debugging your entire project. To get help, it's important you reduce your problem to [a minimal and complete example](https://en.sfml-dev.org/forums/index.php?topic=5559.msg36368#msg36368), one that you can paste inline and people can read in a reasonable time.

Doing so will significantly increase the motivation of people to help you 🙂
