### ISSUE TITLE
Event.MouseWheelScroll.Delta sometimes returns 0

### ISSUE THREAD

**Issue by Maxomann** [SFML/SFML#1842]
## Subject of the issue

As the title says.

## Your environment

* Your OS / distro / window manager used
Windows 10 build 19042.1288
* Your version of SFML (2.5.0, git master, etc)
2.5.1#10 via vcpkg
* Your compiler and compiler version used
VisualStudio 2022 Preview 7.0
* Special compiler flags used

## Steps to reproduce
I had a break condition in my code in case this was zero. It took while for this to trigger.. so I don't know how frequently it happens.
![vs screnshot](https://user-images.githubusercontent.com/6807881/139894878-c31981ec-ddad-4595-a984-4cb70c78c225.png)

Might be related to #95?

**Comment by eXpl0it3r** [comment]
Given #810 that should fix this issue, I'm unsure how it still occurs.
What kind of mouse are you using?
If you can reproduce it again, can you step into SFML and see what the detail event from Windows actually was?

**Comment by eXpl0it3r** [comment]
As we don't have more data on this and SFML really just returns what the OS provides on the event itself, I don't see how we could fix anything here.

We might consider at one point some "raw input" support.
