### ISSUE TITLE
Antialiasing doesn't work with RenderTexture

### ISSUE THREAD

**Issue by CluckCluckChicken** [SFML/SFML#1844]
## Subject of the issue

Antialiasing works with RenderWindow, but not RenderTexture.
```cpp
sf::ContextSettings settings;
settings.antialiasingLevel = 8;
this->w.create(sf::VideoMode(width, height), title, sf::Style::Default, settings);
this->w.setVerticalSyncEnabled(true);
```
The above works fine, but with the below, nothing shows.
```cpp
sf::ContextSettings settings;
settings.antialiasingLevel = 8;
this->texture.create(size.x, size.y, settings);
this->sprite.setTexture(this->texture.getTexture());
```

## Your environment

* Windows 11
* vcpkg latest
* cmake and VC++ with Visual Studio 2022

## Steps to reproduce

Tell us how to reproduce this issue. Please provide a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve), you can use the follow template as a start:

```cpp
#include <SFML/Graphics.hpp>
#include <SFML/Graphics/CircleShape.hpp>

int main()
{
    sf::ContextSettings windowSettings;
    windowSettings.antialiasingLevel = 8;
    sf::RenderWindow window(sf::VideoMode(1280, 720), "Minimal, complete and verifiable example", sf::Style::Default, windowSettings);
    window.setFramerateLimit(60);

    sf::ContextSettings textureSettings;
    textureSettings.antialiasingLevel = 8;
    sf::RenderTexture texture;
    texture.create(100, 100, textureSettings);

    sf::Sprite sprite;
    sprite.setTexture(texture.getTexture());

    sf::CircleShape shape(50);
    shape.setFillColor(sf::Color(189, 195, 199));

    texture.draw(shape);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();

        window.draw(sprite);

        window.display();
    }
}
```

## Expected behavior

Half of the circle should show at the top left of the window (other half is of course cut off)

## Actual behavior

Nothing.

**Comment by eXpl0it3r** [comment]
You have to call `display()` on a render texture as well, it's non-optional.
Additionally, you generally want to set the texture rect to the size of the texture, when setting a texture, by passing `true` as second parameter to `setTexture()`.
And finally, check the console output, it maybe that AA level 8 is not supported on your graphics card/driver.

**Comment by CluckCluckChicken** [comment]
Thanks, that seems to have solved the problem.
