### ISSUE TITLE
Using Clang + MSYS2 on Windows generates shared library names starting with "lib"

### ISSUE THREAD

**Issue by vittorioromeo** [SFML/SFML#1923]
This seems inconsistent with what GCC does. For example, compiling with GCC results in `sfml-system-3.dll`, while compiling with Clang results in `libsfml-system-3.dll`. I suspect some mistake in the CMakeLists.

**Comment by eXpl0it3r** [comment]
The logic is only done for GCC and not for Clang:

https://github.com/SFML/SFML/blob/master/cmake/Macros.cmake#L108-L113

**Comment by vittorioromeo** [comment]
What's the reason we remove the prefix anyway? To match what MSVC does?

**Comment by eXpl0it3r** [comment]
The origin is unclear, probably for consistency, see #1422

If we want to change it, I think for SFML 3 it would be fine, I wouldn't change it for SFML 2.x though, for the reasons provided on the other PR.

**Comment by vittorioromeo** [comment]
Fixed in #1924.
