### ISSUE TITLE
Apple Silicon Official Support

### ISSUE THREAD

**Issue by haneenmahd** [SFML/SFML#1945]
Thanks for raising your issue here! 🙂

Before you submit the issue however, we'd like you to consider the follow points.

* We like to use the issue tracker for confirmed issues.
* If you're stuck with SFML, please use [the forum](https://en.sfml-dev.org/forums/index.php#c3) to get help.

----

## Subject of the issue

I guess there is no official support for apple silicon.

## Your environment

* MacOS
* Latest version: 2.5.1
* clang
* none

## Steps to reproduce

There is nothing to reproduce, however the source code does not support apple silicon.
Thus, it would run under rosetta translation. Resulting in less better performance.

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(1280, 720), "Minimal, complete and verifiable example");
    window.setFramerateLimit(60);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.display();
    }
}
```

## Expected behavior

Tell us what should happen

## Actual behavior

Tell us what happens instead

**Comment by eXpl0it3r** [comment]
The Apple M1 chip is fully supported with SFML, but there hasn't been a new release since (see #1761).
Check out the [`2.6.x` branch](https://github.com/SFML/SFML/tree/2.6.x) for the latest SFML 2.x changes that already includes support for the M1 chip.
