### ISSUE TITLE
Recent `sf::Time` changes result in choppy gameplay with frametime limit enabled

### ISSUE THREAD

**Issue by vittorioromeo** [SFML/SFML#1962]
PR #1872 resulted in dramatic performance degradation (multiple reports of choppiness, unstable FPS, input lag) in Open Hexagon when `Window::setFramerateLimit` is used due to commit db83f857feeacaa30a482aa6059b9358e9ccb2ef. Reverting that commit fixes the issue. 

I am not entirely sure what the problem is, but `sf::sleep` seems to be very inaccurate with that commit, possibly related to #1946. For example, setting an FPS limit to 60 results in very varied FPS between 50-64, while with that commit reverted it is quite accurate. I think we might have to revert this one once we figure out exactly why it is inaccurate and if that can be fixed.

**Comment by vittorioromeo** [comment]
@reconndev: for awareness.

**Comment by eXpl0it3r** [comment]
Can you provide the affected platform and any additional information on those systems?

**Comment by vittorioromeo** [comment]
> Can you provide the affected platform and any additional information on those systems?

Windows 10 x64, game built in Release mode with MSYS2/MinGW (latest packages). Specs:
![specs0](https://user-images.githubusercontent.com/918661/148653855-f04dc05a-d6e4-44a5-a490-8ea98b2a9587.PNG)
![specs1](https://user-images.githubusercontent.com/918661/148653863-bdc08d51-bb7a-4daf-8af2-b44b3faef346.PNG)

**Comment by reconndev** [comment]
Could it be reproduced to check if possibly only `sf::sleep` is affecting that? Like, reverting only sleep implementation?
I did not check the internal implementations of sleep for that pull request, only clocks so maybe there's something weird with cross-hosted compilers.

**Comment by vittorioromeo** [comment]
> Could it be reproduced to check if possibly only `sf::sleep` is affecting that? Like, reverting only sleep implementation? I did not check the internal implementations of sleep for that pull request, only clocks so maybe there's something weird with cross-hosted compilers.

I confirm that only reverting the sleep changes fixed the issue (see https://github.com/vittorioromeo/SFML/commit/692954b0b11a9458887ee720d4a05a1339aa7ed4). It saddens me to say it, but this experience has made me a bit skeptical of the quality of implementation of `<chrono>` and `<thread>` on Windows. We should perform more rigorous/thorough testing on larger projects if we do not want to revert the PR.

**Comment by reconndev** [comment]
MSYS and MinGW do not implement the library themselves as far as I know. They bind existing Linux GCC implementation onto Windows which is probably poorly translated, hence low reliability. I doubt the problem lies within chrono or thread library implementation, it's rather cross-hosted compilers that are at fault.

**Comment by vittorioromeo** [comment]
> I doubt the problem lies within chrono or thread library implementation, it's rather cross-hosted compilers that are at fault.

But SFML's "custom" implementation works perfectly fine. `std::this_thread::sleep_for` could use the exact same thing under the hood. Hence, I think it's a quality of implementation issue unless I am missing something, not a compiler issue.

> It's also why native compiler vendors should mostly be the supported ones

If MSVC wasn't crap in so many ways, I would agree with you. I can elaborate if you want, but I am not a fan of MSVC, and my sentiment is widely shared in the Windows C++ development community. MinGW is ubiquitous as well. It is my main development environment on Windows, and I know many other developers who use it as their main environment as well. If I had to choose, I'd rather drop support for MSVC... :)

Anyway, what do we want to do with the issue at hand? It is clear that `std::this_thread::sleep_for` is inferior to SFML's custom implementation. Should we dive deeper into this? Revert the PR? Thoughts @eXpl0it3r @Bromeon ?

**Comment by vittorioromeo** [comment]
My current understanding is that on MinGW-w64, `std::this_thread::sleep_for` ends up calling `nanosleep`, which seems to be defined here:
https://github.com/mingw-w64/mingw-w64/blob/master/mingw-w64-libraries/winpthreads/src/nanosleep.c

**Comment by reconndev** [comment]
I do agree about MSVC but there's nothing else better and native for Windows unfortunately (sigh).

One more question, though. Was MinGW using POSIX as the threading model or Win32 API?

Personally, I'd create a PR to only revert the sleep implementation and dive deeper into the differences of it later.

**Comment by reconndev** [comment]
Also, this may be an ugly workaround: https://stackoverflow.com/questions/54493041/unpredictable-behaviour-of-stdsleep-for-on-windows-10

Windows is scary...

**Comment by eXpl0it3r** [comment]
I sort of remember when we ran into such issues and had to change the implementation to reduce the sleep time.

The alternative to revert to full custom implementations would probably be to call `timeBeginPeriod` (and `timeEndPeriod`) for the Windows implementation, as also suggested by the link above and how we call it in our own implementation.
Then again if we have custom code for Windows, maybe it's really not that far fetched to have custom implementation for Unix as well...

**Comment by Bromeon** [comment]
> Anyway, what do we want to do with the issue at hand? It is clear that `std::this_thread::sleep_for` is inferior to SFML's custom implementation. Should we dive deeper into this? Revert the PR? Thoughts @eXpl0it3r @Bromeon ?

In general, I tend to say "don't change a running system" and voiced my concerns already [here](https://github.com/SFML/SFML/pull/1872#issuecomment-986928141) and [here](https://github.com/SFML/SFML/pull/1872#issuecomment-986928141), but it was definitely worth a try to see whether we could modernize this 🙂 I don't think we should enforce a standard solution if it regresses the user experience. That said, one option is to write a custom implementation only on platforms where the standard facilities are not working. But if it's too time-consuming or with uncertain returns, we might as well keep using the old version, which we know to be functioning.

I have to say, I'm a bit disappointed in the C++ state of affairs -- not only did it take the committee an eternity to get some basic time functionality standardized, but then half the implementors don't even do a proper job... Where's the point in a standard when everyone needs to build their own platform differentiation?

**Comment by vittorioromeo** [comment]
> it was definitely worth a try to see whether we could modernize this

I agree with that. We haven't even released 3.x yet -- this is the right time to try out stuff, break things, and revert changes if needed. If we proceed too carefully, we might miss out on good improvements. 

> I don't think we should enforce a standard solution if it regresses the user experience.

+1.

> we might as well keep using the old version, which we know to be functioning

I think this is the best solution right now. The problem I am describing seems to be limited to sleeping so far, not clocks. But someone should do more thorough tests on clocks.

> Where's the point in a standard when everyone needs to build their own platform differentiation?

One problem here is that the Standard is very lax in its wording: https://eel.is/c++draft/thread.req.timing#2

The other problem is that MinGW is not an official thing. The Microsoft STL seems to use `::Sleep`: https://github.com/microsoft/STL/blob/master/stl/src/cthread.cpp#L72-L79

**Comment by vittorioromeo** [comment]
WinPThreads also seems to be the culprit here. I am not sure if it is still maintained, but the MinGW-w64 contribute page offers an alternative:

![winpthreads](https://user-images.githubusercontent.com/918661/149002911-51dbfe99-c38f-471e-bdb1-cd06632a7e42.PNG)

**Comment by vittorioromeo** [comment]
I've been also reading about sleeping in general in game loops, and it seems that it is widely considered a poor idea to use sleep as it is inherently not accurate independently of the implementation (i.e. `sleep(5)` means *sleep for at least 5ms*, but it can sleep for longer).

Maybe I've been talking smack about MinGW too much while the problem is actually my own code or SFML's. In fact, SFML's `Window::setFramerateLimit` is the thing that causes `sleep` to be invoked in the first place. Maybe we should change that instead, or make `sleep` more reliable with platform-specific hints...?

Some discussion:
- https://gamedev.stackexchange.com/a/18900/7197
- https://old.reddit.com/r/gamedev/comments/fr89k5/using_sleep_in_a_game_loop/fluahlk/
- https://old.reddit.com/r/gamedev/comments/1jemc1/a_thought_about_game_loop_and_sleep_precision/cbe16t0/

**Comment by vittorioromeo** [comment]
I am actually starting to think that SFML is wrong here, and we shouldn't revert #1872. `Window::display` currently does this:

```cpp
////////////////////////////////////////////////////////////
void Window::display()
{
    // Display the backbuffer on screen
    if (setActive())
        m_context->display();

    // Limit the framerate if needed
    if (m_frameTimeLimit != Time::Zero)
    {
        sleep(m_frameTimeLimit - m_clock.getElapsedTime());
        m_clock.restart();
    }
```

It needs to do something more clever, like a multi-stage `sleep` + spinlock. Going through these search results is quite enlightening: https://www.google.com/search?q=gamedev+fps+limit+sleep

**Comment by vittorioromeo** [comment]
I have checked Quake 3 Arena's source code, and it uses a spinloop instead of `Sleep` to limit FPS.

**Comment by vittorioromeo** [comment]
What we did before #1872 was:

```cpp
void sleepImpl(Time time)
{
    // Get the supported timer resolutions on this system
    TIMECAPS tc;
    timeGetDevCaps(&tc, sizeof(TIMECAPS));

    // Set the timer resolution to the minimum for the Sleep call
    timeBeginPeriod(tc.wPeriodMin);

    // Wait...
    ::Sleep(static_cast<DWORD>(time.asMilliseconds()));

    // Reset the timer resolution back to the system default
    timeEndPeriod(tc.wPeriodMin);
}
```

Maybe we could instead do:

```cpp
void sleep(Time duration)
{
    priv::TimerPeriodGuard timerPeriodGuard; // sets time period to min, and restores on dtor

    const auto time = std::chrono::duration<Int64, std::micro>(duration.asMicroseconds());
    std::this_thread::sleep_for(time);
}
```

Where `priv::TimerPeriodGuard` is a platform-specific class:

```cpp
TimerPeriodGuard::TimerPeriodGuard()
{
    // Get the supported timer resolutions on this system
    TIMECAPS tc;
    timeGetDevCaps(&tc, sizeof(TIMECAPS));

    // Set the timer resolution to the minimum for the Sleep call
    timeBeginPeriod(tc.wPeriodMin);
}

TimerPeriodGuard::~TimerPeriodGuard()
{
    // Reset the timer resolution back to the system default
    timeEndPeriod(tc.wPeriodMin);
}
```

Thougts?

**Comment by reconndev** [comment]
Minimum resolution call probably could be saved to a static constant member. I don't think minimum clock resolution can change in runtime.
```cpp
TIMECAPS tc;
timeGetDevCaps(&tc, sizeof(TIMECAPS));
```
similarily:
```cpp
class TimerPeriodGuard
{
// ...

    inline static const auto MinimumClockPeriod = []
    {
        TIMECAPS tc;
        timeGetDevCaps(&tc, sizeof(TIMECAPS));
        return tc.wPeriodMin;
    }();
};

// then

TimerPeriodGuard::TimerPeriodGuard()
{
    timeBeginPeriod(MinimumClockPeriod);
}

// etc.
```

**Comment by vittorioromeo** [comment]
I have tried the `TimerPeriodGuard` approach and it didn't work in practice. The game is still choppy and the framerate is unpredictable. See https://github.com/vittorioromeo/SFML/commit/a34d955f23a13fd501e062bdb97125664bf9f784

It also isn't that much cleaner in terms of code.

#1965 might indeed be the best way to go.

**Comment by eXpl0it3r** [comment]
> I've been also reading about sleeping in general in game loops, and it seems that it is widely considered a poor idea to use sleep as it is inherently not accurate independently of the implementation (i.e. `sleep(5)` means _sleep for at least 5ms_, but it can sleep for longer).
> 
> Maybe I've been talking smack about MinGW too much while the problem is actually my own code or SFML's. In fact, SFML's `Window::setFramerateLimit` is the thing that causes `sleep` to be invoked in the first place. Maybe we should change that instead, or make `sleep` more reliable with platform-specific hints...?

Btw SFML is well aware of this and never claimed that `setFramerateLimit` is *the* solution with all the bells and whistles for dealing with framerates, we even [document this inconsistency](https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Window.php#af4322d315baf93405bf0d5087ad5e784), but it's a good enough solution in a 95-99% cases.

> SFML will try to match the given limit as much as it can, but since it internally uses sf::sleep, whose precision depends on the underlying OS, the results may be a little unprecise as well (for example, you can get 65 FPS when requesting 60).
