### ISSUE TITLE
SFML Node.js bindings

### ISSUE THREAD

**Issue by XadillaX** [SFML/SFML#1968]
Hi I've develop a Node.js binding for [SFML](https://github.com/XadillaX/node-sfml). Do we have any plan for more actions about it?

- SFML Node.js Binding: https://github.com/XadillaX/node-sfml
- Some demos for this binding: https://github.com/XadillaX/node-sfml-demos
- An NES emulator powered by this binding: https://github.com/XadillaX/play-nes

**Comment by Bromeon** [comment]
Hello, that's great to hear! 🙂 
We could add node-sfml to the list of bindings: https://www.sfml-dev.org/download/bindings.php

The SFML website is open-source: https://github.com/SFML/SFML-Website/tree/master/download
So if you want, you could directly create a pull request for the `bindings.php` and `bindings-fr.php` files.

**Comment by Bromeon** [comment]
Closing in favor of https://github.com/SFML/SFML-Website/pull/150
