### ISSUE TITLE
Specification document in Greek

### ISSUE THREAD

**Issue by johnmanthop** [SFML/SFML#1982]
Hi, I am a uni student and we have been asked to create a specification document for an open source software in our language (Greek). 
Would that be acceptable by the community? 
Other than that I have used SFML quite a lot and I think I could deliver.

Would use:
SFML 2.5 (latest edition)
g++ 9.3.0
Ubuntu 20.04

**Comment by eXpl0it3r** [comment]
I don't think this is something that we need. If you need help with any parts, you know where to find us to get some additional information. 🙂
