### ISSUE TITLE
renderTexture Bounding box gives incorrect values

### ISSUE THREAD

**Issue by DelinWorks** [SFML/SFML#1985]
## Subject of the issue

renderTexture Bounding box gives incorrect values

## Your environment

* Windows 10 x64
* SFML 2.5.1
* Microsoft VC++ 2017

## Steps to reproduce

Create a render texture the size of the window (1280x720) and draw everything in it,
it will appear cut like in this photo here

![image](https://user-images.githubusercontent.com/45469625/151654809-b547d5d8-e84a-43b5-983f-4365bacc0009.png)

```cpp
sf::Sprite rtsprite(texture);
std::cout << rtsprite.getLocalBounds().width << std::endl;
rtsprite.setTexture(renderTexture.getTexture());
window.draw(rtsprite);
```

## Expected behavior

when getting the local bounds of the sprite it's supposed to return the actual window size (e.g 1280x720)

## Actual behavior

instead it returns this weird 168x168 size that doesn't match up with the render texture's size thus making the texture appear cut like in the picture above

**Comment by Bromeon** [comment]
Did you call `sf::RenderTexture::display()` at the end?

Also, for help requests please use the [SFML forum](https://en.sfml-dev.org/forums/) 🙂

**Comment by DelinWorks** [comment]
Yes I did everything correct

```
        renderTexture.clear();
        window.clear();
        sb.clear();

        for (size_t i = 0; i < 1000; i++)
        {
            sb.draw(sp);
            sp.setPosition(i * 10, i * 10);
        }

        sb.order();

        renderTexture.draw(sb);

        renderTexture.draw(lines);

        renderTexture.display();

        sf::Sprite rtsprite(texture);
        std::cout << rtsprite.getLocalBounds().width << std::endl;
        rtsprite.setTexture(renderTexture.getTexture());
        window.draw(rtsprite);

        window.display();
```

**Comment by eXpl0it3r** [comment]
You need to reset the texture rect when you set the texture.
See the documentation here: https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1Sprite.php#a3729c88d88ac38c19317c18e87242560

SFML is used by hundred or thousand of people and some of the core concept haven't changed much over the past many years, thus if something basic as such is not working, chances are a lot higher that it's an issue with your own code, than with the library code. 😉

**Comment by DelinWorks** [comment]
that's true setTextureRect sloved my problem.. I thought that it sets the rect as the texture's size automatically, I need to read docs thoroughly next time 😅
