### ISSUE TITLE
Long std::string don't work

### ISSUE THREAD

**Issue by Thorek777** [SFML/SFML#2017]
When i try send long string (as packet) to Server, it occurs:
https://stackoverflow.com/questions/71142919/sfml-weird-problem-about-sending-too-long-stdstring

## Your environment:
* Windows 10 x64
* Master
* VS2022 x64

## Steps to reproduce:
Create std::string in packet (<<) which has more than 15 characters.
This part of source has reproduced this glitch: [Source.zip](https://github.com/SFML/SFML/files/8083010/Source.zip)

**Comment by vittorioromeo** [comment]
I wasn't able to reproduce it, and your code does not compile. Could you provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) of the issue?

**Comment by Thorek777** [comment]
I decided to rewrite whole network and that actually helped, sorry for confusion.
