### ISSUE TITLE
Vector2.inl causing compiler errors with MSVC in VS2022

### ISSUE THREAD

**Issue by Bambo-Borris** [SFML/SFML#2039]
Thanks for raising your issue here! 🙂

Before you submit the issue however, we'd like you to consider the follow points.

* We like to use the issue tracker for confirmed issues.
* If you're stuck with SFML, please use [the forum](https://en.sfml-dev.org/forums/index.php#c3) to get help.

----

## Subject of the issue
Was attempting to test out changes from the most recent master snapshot of the SFML 3.0 changes and was unable to compile my project. This project I had been using to test some of the 3.0 changes with the previous snapshot build, when I updated to the most recent one and did a clean rebuild I noticed the errors. Another user in the Discord server for SFML also reported the same compilation errors.

```
include\SFML\System\Vector2.inl(293,41): error C2370: 'sf::Vector2<T>::UnitX': redefinition; different storage class
include\SFML\System\Vector2.hpp(204): message : see declaration of 'sf::Vector2<T>::UnitX'
include\SFML\System\Vector2.inl(296,41): error C2370: 'sf::Vector2<T>::UnitY': redefinition; different storage class
include\SFML\System\Vector2.hpp(205): message : see declaration of 'sf::Vector2<T>::UnitY'
```

I tried building the SFML from source, then building against the output of that and still the same issues occurred.

## Your environment

Microsoft Windows 11
64 Bit SFML 3.0 (occurs with binaries from snapshot taken from master branch on 03/03/2022 & occurs when using binaries built from source)
Visual Studio 2022 (VC 17)

## Steps to reproduce

- Setup a project which uses SFML 3.0 within VS2022
- Set C++ language version of project to C++17
- Use the source shown below
- Build and the compiler errors should occur

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(1280, 720), "Minimal, complete and verifiable example");
    window.setFramerateLimit(60);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.display();
    }
}
```

## Expected behavior

Compilation should complete without errors.

## Actual behavior

The following compiler errors are thrown

```
include\SFML\System\Vector2.inl(293,41): error C2370: 'sf::Vector2<T>::UnitX': redefinition; different storage class
include\SFML\System\Vector2.hpp(204): message : see declaration of 'sf::Vector2<T>::UnitX'
include\SFML\System\Vector2.inl(296,41): error C2370: 'sf::Vector2<T>::UnitY': redefinition; different storage class
include\SFML\System\Vector2.hpp(205): message : see declaration of 'sf::Vector2<T>::UnitY'
```

**Comment by ChrisThrasher** [comment]
Is Visual C++ 17 older than the oldest version we're supporting? That might be why CI doesn't this error.

What happens if you build SFML `master` from source and build the examples? The examples also use SFML headers so I'd suspect that you'd get similar errors.

**Comment by Bambo-Borris** [comment]
> Is Visual C++ 17 older than the oldest version we're supporting? That might be why CI doesn't catch this error.
> 
> What happens if you build SFML `master` from source and build the examples? The examples use SFML headers so I'd expect that you'd get the same errors.

No issues when I build the examples, they build and run without any issues.

**Comment by Bromeon** [comment]
> Is Visual C++ 17 older than the oldest version we're supporting? That might be why CI doesn't catch this error.

VC 17 is Visual Studio 2022, they keep confusing people up to this day. See also [version history](https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#History).

This version is explicitly part of our CI: 

https://github.com/SFML/SFML/blob/7dfc7f02029b039005fdb1868dccefa4e523d25c/.github/workflows/ci.yml#L15

And according to [this official GitHub Actions page](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#visual-studio-enterprise-2022), Visual Studio Enterprise 2022 is installed on those machines.

---

I was first thinking that since `Vector2<T>` is a template, its member symbols are only instantiated when used, but that wouldn't explain why it happens in a user project (unless that also uses those constants).

For reference, this is how they are declared and defined:
```cpp
template <typename T>
class Vector2
{
public:
    static const Vector2 UnitX; //!< The X unit vector (1, 0), usually facing right
    static const Vector2 UnitY; //!< The Y unit vector (0, 1), usually facing down
};

template <typename T>
constexpr Vector2<T> Vector2<T>::UnitX(static_cast<T>(1), static_cast<T>(0));

template <typename T>
constexpr Vector2<T> Vector2<T>::UnitY(static_cast<T>(0), static_cast<T>(1));
```

Maybe they still need to be explicitly `static constexpr` at their definition site?
@Bambo-Borris could you try if adding `static` in the .inl fixes the issue?

**Comment by Bambo-Borris** [comment]
> Maybe they still need to be explicitly `static constexpr` at their definition site? @Bambo-Borris could you try if adding `static` in the .inl fixes the issue?

@Bromeon I tried this change in the .inl file but it yields the following compilation errors

```
include\SFML\System\Vector2.inl(291): error C2720: 'sf::Vector2<T>::UnitX': 'static ' storage-class specifier illegal on members
include\SFML\System\Vector2.inl(294): error C2720: 'sf::Vector2<T>::UnitY': 'static ' storage-class specifier illegal on members
```

**Comment by eXpl0it3r** [comment]
I can't reproduce this with VS 2022 on Windows, neither with static nor with dynamic libraries (not that this would really matter for a compiler error).

@Bambo-Borris did you create a VS project or use CMake?
Can you maybe share the project file, in case you can reproduce it?

**Comment by Bambo-Borris** [comment]
> I can't reproduce this with VS 2022 on Windows 10, neither with static nor with dynamic libraries (not that this would really matter for a compiler error).
> 
> @Bambo-Borris did you create a VS project or use CMake? Can you maybe share the project file, in case you can reproduce it?

Yeah, I was working with a VS Project. It was also a project that had been using the previous snapshot of master. I didn't change any of the project configuration other than to point it towards the folder for new snapshot. The previous snapshot of master worked with no problems. 

It's set as a statically linked project. When I swapped snapshot I cleaned the whole solution and rebuilt then the errors occurred. I did notice another user suffer this issue in the Discord but they came across it when building against master without intending to. @eXpl0it3r Do you need just the project file or the whole project as a .zip?

**Comment by eXpl0it3r** [comment]
Project file should be fine, so I have all the necessary configurations, put up to you how you want to package it

**Comment by Bambo-Borris** [comment]
> Project file should be fine, so I have all the necessary configurations, put up to you how you want to package it

I just tried swapping from static to dynamic, and it works with the previous snapshot but doesn't build with the current one for me either. I've attached the .vcxproj file for you. I removed the x86 configuration since it wasn't setup at all, and this should be set to the dynamic SFML libs. It's entirely possible I've misconfigured something, just strange it didn't showup on the previous snapshot. 

[Project File .zip](https://github.com/SFML/SFML/files/8227541/Project.File.zip)

**Comment by eXpl0it3r** [comment]
Finally figured out how to trigger the error, when you enable the "Conformance mode" it trips:

![image](https://user-images.githubusercontent.com/920861/157783529-f71b73fe-0887-4742-baea-45e464f73876.png)

Master of constexpr and other C++ magic, @vittorioromeo, any ideas why VS thinks the static and/or constexpr UintX / UintY aren't conformant?

**Comment by ChrisThrasher** [comment]
Ah, no wonder. I was recently playing around with compiler warnings and noticed we're not using `/permissive-`. When I enabled it a lot of things in the Windows CI builds broke. Maybe we reconsider adding that warning back.

**Comment by eXpl0it3r** [comment]
The `/permissive-` flag was disabled due to some issues with the Windows SDK (see [this resolved thread](https://github.com/SFML/SFML/pull/1792#pullrequestreview-638621573)). Maybe the issue has since been fixed and we just have to update the Windows SDK version...

**Comment by ChrisThrasher** [comment]
https://github.com/ChrisThrasher/SFML/actions/runs/1966525225

I enabled `/permissive-` on the last commit prior to adding these `sf::Vector2<T>` constants and the CI pipeline passed, so once we fix this problem I believe we can reenable that flag.

**Comment by ChrisThrasher** [comment]
First, I realized that we're not testing `sf::Vector2<T>::UnitX` and `sf::Vector2<T>::UnitY` in a constexpr context so I added tests for that. Second, I learned that if we specialize those member variable templates then we can get them to work and MSVC will happily compile them with `/permissive-`. https://github.com/ChrisThrasher/SFML/actions/runs/1976986640

What we might need to do is specialize those 2 constants for the 3 type aliases we have, `Vector2u`, `Vector2i`, and `Vector2f`. This solution isn't ideal but it does seem to work and will allow us to enable `/permissive-` which I think is a particularly valuable thing to do as evident by users who are trying to compile SFML headers with that flag.

**Comment by eXpl0it3r** [comment]
And why do they need to be specialized?

**Comment by ChrisThrasher** [comment]
> And why do they need to be specialized?

I'm not sure.

> Is this just a MSCV bug/quirk or is it some standard requirement?

Also not sure.

> What about user-defined Ts?

This solution wouldn't work with user-defined types, sadly. Hopefully we figure out something better but I thought this was still worth sharing.

**Comment by eXpl0it3r** [comment]
Got another report for this issue on the [forum](https://en.sfml-dev.org/forums/index.php?topic=28505.0).

**Comment by ChrisThrasher** [comment]
I think demoting these constants to non-compiletime constants is our best option for fixing this problem in the short term. That will let us enable `/permissive-` in the build ensuring that these kinds of problems aren't reintroduced in the future.

**Comment by ChrisThrasher** [comment]
I submitted #2076 to fix this so we can fix user builds quickly while continuing to discuss what to do about these constants and whether they can ever be made `constexpr`.

**Comment by eXpl0it3r** [comment]
@Bambo-Borris can you give SFML master another try? It should work fine in permissive mode as well 🙂

**Comment by Bambo-Borris** [comment]
> @Bambo-Borris can you give SFML master another try? It should work fine in permissive mode as well 🙂

Yeah it appears that has fixed the issue for me, project compiles with the `permissive` flag set now. Thanks!
