### ISSUE TITLE
Add Discord server link to the README

### ISSUE THREAD

**Issue by PoetaKodu** [SFML/SFML#2041]
Thanks for raising your issue here! 🙂

Before you submit the issue however, we'd like you to consider the follow points.

* We like to use the issue tracker for confirmed issues.
* If you're stuck with SFML, please use [the forum](https://en.sfml-dev.org/forums/index.php#c3) to get help.

----

## Subject of the issue

I just noticed that SFML has in fact an official Discord server. It would be nice to have a link to it (possibly a giant image) in the repo's README.

~~Create an official SFML [Discord](https://discord.com) server for contributions and as a helpdesk.
I know that there's a forum, but I think a Discord server would be a nice addition. People can communicate quicker and I'm sure plenty of SFML users would appreciate that.~~

## Your environment

N/A.

## Steps to reproduce

N/A.

## Expected behavior

N/A.

## Actual behavior

N/A.

**Comment by eXpl0it3r** [comment]
We could consider adding a link to the Discord and forum, but I vote against any banners. No need to heavily advertise it (and Discord's brand).

**Comment by Bromeon** [comment]
It's a bit strange to add only Discord to the ReadMe, without also adding other communication platforms like the forum or Twitter.

Maybe it's better to add a link to https://www.sfml-dev.org/community.php.

**Comment by Nadpher** [comment]
I'd like to work on this issue, if it's not already been taken care of. It would be my first contribution to open source.
