### ISSUE TITLE
Problems with building on Windows on latest version of SFML

### ISSUE THREAD

**Issue by akruglov18** [SFML/SFML#2049]
Thanks for raising your issue here! 🙂

Before you submit the issue however, we'd like you to consider the follow points.

* We like to use the issue tracker for confirmed issues.
* If you're stuck with SFML, please use [the forum](https://en.sfml-dev.org/forums/index.php#c3) to get help.

----

## Subject of the issue

I have a repo:
https://github.com/akruglov18/ConsolGame
It is building with a 3-month-old version of smfl
When I updated submodules and tried to build my project i've got an errors:
* Sleep.obj : error LNK2005: "public: static class sf::Time const sf::Time::Zero"
* SleepImpl.obj : error LNK2005: "public: static class sf::Time const sf::Time::Zero"
And as a result i have an error
bin\sfml-system-d-3.dll : fatal error LNK1169:

To be honest it can be an error in my repo, but it a little bit strange that I have an error not with interfaces after updates
but with multiple defenition of some objects. Because in old version of SFML it works.

## Your environment

* Your OS / distro / window manager used
* * Windows 10 (don't know what i can also mention)
* Your version of SFML (2.5.0, git master, etc)
* * Version of sfml is latest(master)
* Your compiler and compiler version used
* * -- The C compiler identification is MSVC 19.16.27045.0
* * -- The CXX compiler identification is MSVC 19.16.27045.0
* Special compiler flags used
* * set(CMAKE_CXX_STANDARD 17)
* * set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -W3 -WX -w44834 -w34189 -w34100 -w34715 -w34244 -EHsc")
* Special cmake flags
* * cmake -G "Visual Studio 16 2019" -Tv141 -DCMAKE_SYSTEM_VERSION=10.0.19041.0 -DBUILD_SHARED_LIBS=TRUE

## Steps to reproduce

If you have time, you can try to build my repo
It has an instruction

## Expected behavior

I expect that my project will be built)

## Actual behavior

It isn't being built)))

**Comment by ChrisThrasher** [comment]
> It is building with a 3-month-old version of smfl

What commit hash are you using? What happens when you use either the 2.6.x or master branches of SFML as they exist today?

**Comment by akruglov18** [comment]
No, the error appears when i upgrade to the latest version of master branch
With old version of master branch it works

**Comment by ChrisThrasher** [comment]
Can you bisect the problem to figure out what commit introduced this build failure?

**Comment by akruglov18** [comment]
I use this commit
https://github.com/SFML/SFML/tree/6cb10856c6114a4cf2318e5710b5f72518c9dd90

**Comment by akruglov18** [comment]
Okay, may be I will try to find latest commit, when my repo is still working
Now, I use this commit for successful build
https://github.com/SFML/SFML/tree/6cb10856c6114a4cf2318e5710b5f72518c9dd90

**Comment by ChrisThrasher** [comment]
Were you able to figure out what commit introduced this issue?

**Comment by akruglov18** [comment]
I faced with another problem, on commit https://github.com/SFML/SFML/commit/53594dfbe7063d90bc54c1c8694543b5692c6b09
https://github.com/SFML/SFML/blob/53594dfbe7063d90bc54c1c8694543b5692c6b09/src/SFML/Window/GlContext.cpp#L744
I got an error that `callback` and `ptr` are nullpointer
I'm trying to figure out the reason

**Comment by akruglov18** [comment]
May be you will be interested in that:

#include"SFML/Graphics.hpp"
#include <memory>

int main() {
    std::shared_ptr<sf::Texture> text = std::make_shared<sf::Texture>(*(new sf::Texture()));
    text->loadFromFile("image.png");
    return 0;
}
this code returns -1073741819.

But this code is completed succesfully:
#include"SFML/Graphics.hpp"
#include <memory>

int main() {
    std::shared_ptr<sf::Texture> text = std::shared_ptr<sf::Texture>(new sf::Texture());
    text->loadFromFile("image.png");
    return 0;
}

**Comment by akruglov18** [comment]
I get an build error on:
https://github.com/SFML/SFML/commit/0e419543f2193da08858f8c46140b02d31936b3e
This is first commit, which doesn't work
Errors(sorry for strange symbols in logs, my Windows is not on English):
https://pastebin.com/iyR5ryWN

**Comment by akruglov18** [comment]
Update: I build my repo with latest commit of SFML
I changed my cmake from:
`cmake -G "Visual Studio 16 2019" -Tv141 -DCMAKE_SYSTEM_VERSION=10.0.19041.0 -DBUILD_SHARED_LIBS=TRUE ..`
to
`-DBUILD_SHARED_LIBS=TRUE ..`
Tomorrow i will test my repo, if it will be fine, I will close the issue
