### ISSUE TITLE
I have a problem that images are not loading when I run the game (check the screenshot)

### ISSUE THREAD

**Issue by HabebaBakr** [SFML/SFML#2056]
![Screenshot (89)](https://user-images.githubusercontent.com/102870103/161423438-c3764e57-578d-4339-89cb-a180d1b4c8d2.png)

**Comment by HabebaBakr** [comment]
@SFMLBuild @SFMLIntegrator

**Comment by eXpl0it3r** [comment]
Please use [the forum](https://en.sfml-dev.org/forums/index.php#c3) if you need help with something. This issue tracker is for confirmed bugs / issues of the library itself.
