### ISSUE TITLE
Crash accessing DirectInput in Release build with optimizations enabled

### ISSUE THREAD

**Issue by eigenl** [SFML/SFML#2057]
## Crash accessing DirectInput in Release build with optimizations enabled

Wanted to try out the latest master build and after upgrading my toolchain it seems to build fine. But I ran into an issue with running the Release build, in particular when compiled with any optimizations (O1, O2, O3). It simply crashes as soon as RenderWindow is created. Through trial and error I managed to track down the commit and through even more trial and error the particular change causing the issue.

https://github.com/SFML/SFML/commit/9a0cc4b7dc8dae79fc912a04a9d4679d42815a4a#diff-656b585bfaca15adbabda9a47820c2741686549a2c5391c030feb497a77c9fc3L406

This change in src/SFML/Window/Win32/JoystickImpl.cpp:
```cpp
- typedef HRESULT(WINAPI *DirectInput8CreateFunc)(HINSTANCE, DWORD, REFIID, LPVOID*, LPUNKNOWN);
+ using DirectInput8CreateFunc = HRESULT (*)(HINSTANCE, DWORD, const IID &, LPVOID *, LPUNKNOWN);
```
Adding back WINAPI to the function signature seems to resolve the issue, so that it becomes:
```cpp
using DirectInput8CreateFunc = HRESULT (WINAPI *)(HINSTANCE, DWORD, const IID &, LPVOID *, LPUNKNOWN);
```
I'm not sure why that is and why it's not an issue elsewhere. WINAPI is also removed in setProcessDpiAware function in the same commit and doesn't seem to cause an issue. This doesn't happen in the debug build or in release build if optimizations are not performed.

## Your environment

* Windows 7 SP1
* Latest master build
* MinGW32, GCC 11.2.0 (posix thread model)

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(1280, 720), "Minimal, complete and verifiable example");
    return 0;
}
```

## Expected behavior

Process should terminate with status code 0

## Actual behavior

Application crashes as soon as render window is created.

**Comment by binary1248** [comment]
Regarding the other missing `WINAPI`s, they were re-added in following commits, so this `WINAPI` was the only one still missing. As to why it only shows up with optimizations, I assume the compiler uses calling convention information to lay out memory differently for optimization purposes. Calling a function with the wrong calling convention is technically undefined behaviour, so the compiler is at liberty to make the code break whenever it feels like it.
