### ISSUE TITLE
Multi Monitor Support in SFML?

### ISSUE THREAD

**Issue by Ritvik-UX** [SFML/SFML#2061]
----

## Subject of the issue

Does SFML support multi monitors in fullscreen mode (sf :: Style :: Fullscreen)?

## Your environment

* Windows 11
* SFML version: 2.5.1
* GNU g++

## Behavior

How To Open SFML Window in Multiple Monitors?

Thanks :D

**Comment by eXpl0it3r** [comment]
Currently, SFML isn't multi-monitor aware. Allowing a user to pick the wanted monitor and retrieving monitor information would be the "first" step. But even then, I don't think SFML will ever provide support to render to multiple monitors at once. This is already handled by most GPU software (see Nvidia's [Merge Display](https://www.nvidia.com/content/Control-Panel-Help/vLatest/en-us/mergedProjects/nvdsp/To_merge_several_displays_into_one_display.htm)) and it can come with a very complex setup, for example if you have multiple GPUs with connected screens and different framerates and various layouts and ...

As such, I'll reject this feature request and point you to the available GPU options, which in turn should show up fine with SFML as well.
