### ISSUE TITLE
cmake: Target xxx is already defined

### ISSUE THREAD

**Issue by JonathSpirit** [SFML/SFML#2078]
## Subject of the issue

While working on a cmake project that required SFML, I discoverd that adding external library used by SFML with add_subdirectory doesn't work cause SFML try to create a INTERFACE target with the same name.

This cause the impossibility to build a subdirectory with cmake (useful for flexibility and workflow) and the only possibility I see is to build the library out of the top CMakeLists.txt by hand (or maybe an cmake addon like ExternalProject but this is not a solution for me). 

This cause extra overhead for nothing.

## Your environment

* Windows 10, 21H2
* SFML branch 2.6.x
* MSYS2 : (Rev10, Built by MSYS2 project) 11.2.0
* -D SFML_BUILD_NETWORK=OFF
* cmake version 3.22.3

## Steps to reproduce

An good example is to clone the openal-soft project from https://github.com/kcat/openal-soft.git and do in your top CMakeLists : 

```cmake

project(MyProject)


set(ALSOFT_UTILS OFF CACHE BOOL "" FORCE) #OpenAL-soft
set(ALSOFT_EXAMPLES OFF CACHE BOOL "" FORCE)
add_subdirectory("libs/openal-soft" EXCLUDE_FROM_ALL)

set(OPENAL_INCLUDE_DIR "libs/openal-soft/include" CACHE PATH "" FORCE) #needed for being detected by findPackage
set(OPENAL_LIBRARY "OpenAL" CACHE STRING "" FORCE)

#And then add SFML

add_subdirectory("libs/SFML" EXCLUDE_FROM_ALL)

```

## Expected behavior

SFML should correctly use the target created by the add_subdirectory with the help of findPackage

## Actual behavior

SFML cause an Cmake error : 

```cmake
CMake Error at libs/SFML/cmake/Macros.cmake:379 (message):
  Target 'OpenAL' is already defined

```

**Comment by JonathSpirit** [comment]
Maybe a good fix is to create the INTERFACE target with a suffix/prefix like "OpenAL_sfml" in Macros.cmake

**Comment by ChrisThrasher** [comment]
Why do you want to include OpenAL from two locations? If SFML already depends on it, why express that dependency again in your own build? Does this problem exist when you use `find_package` to depend on SFML or only when you include SFML sources in your build?

**Comment by eXpl0it3r** [comment]
Currently SFML doesn't support a mix and match of libs. You can either set `SFML_USE_SYSTEM_DEPS` and provide all the dependencies yourself or let SFML find the dependencies.

If the necessary changes (check target before calling find_package) isn't too cumbersome, I don't really see a reason against adding it.
