### ISSUE TITLE
Signed 16 bit wav files are being corrupted in the endian decode function in v3

### ISSUE THREAD

**Issue by rajetic** [SFML/SFML#2098]
In SoundFileReaderWav.cpp at line 54:
`        value = static_cast<sf::Uint8>(bytes[0] | (bytes[1] << 8));`
this should be:
`        value = static_cast<sf::Int16>(bytes[0] | (bytes[1] << 8));`

It's cutting off the upper byte of signed 16 bit samples (unsigned 16 bit samples look ok), resulting in a static sound for PCM S16 WAV files.
(Tested on Win 10 / VC++, sounds play correctly after the fix above)

**Comment by ChrisThrasher** [comment]
Talking about this? https://github.com/SFML/SFML/pull/2094

**Comment by rajetic** [comment]
Oops, yep. I searched several times for wav related issues but missed that somehow.
It's it's fixed in 2.6, but not merged into 3.0 yet (which I'm running).

**Comment by eXpl0it3r** [comment]
Will do another back merge later today 🙂
