### ISSUE TITLE
[Feature request] .getGlobalSize()

### ISSUE THREAD

**Issue by dogunbound** [SFML/SFML#2109]
## Subject of the issue

You can get the global bounds and positions of objects. Position is essentially the top and left values returned in the global bounds. Why not implement something that returns the global size also? It's more of a convenience thing as getting the global size of an object is as simple as: `Vector2f::new(obj.getGlobalBounds().width, obj.getGlobalBounds().height);`.

**Comment by eXpl0it3r** [comment]
With SFML 2.6 you'll already be able to do: `obj.getGlobalBounds().getSize()`

There's no need to add a specific function for it in my opinion.

**Comment by dogunbound** [comment]
Didn't know that. Thanks!
