### ISSUE TITLE
Utf<8>::decode asserts in Visual Studio with bad UTF-8 string

### ISSUE THREAD

**Issue by texus** [SFML/SFML#2113]
Calling sf::String::fromUtf8 with an invalid UTF-8 string leads to a debug assertion in Visual Studio when compiling in debug mode.

Example code:
```c++
#include <SFML/System.hpp>
int main()
{
    std::string s(1, (char)251);
    sf::String::fromUtf8(s.begin(), s.end());
}
```

The `if (begin + trailingBytes < end)` line at [include/SFML/System/Utf.inl#L69](https://github.com/SFML/SFML/blob/master/include/SFML/System/Utf.inl#L69) checks whether there are sufficient trailing bytes, but if there aren't then then `begin + trailingBytes` will be an invalid iterator. Visual Studio asserts about this inside the `std::string::operator+` function (with "Expression: cannot seek string iterator after end" message).

Changing the if statement to something like the following would fix the assertion:
```c++
if (trailingBytes < std::distance(begin, end))
```

**Comment by Bromeon** [comment]
What should the intended outcome be if the UTF-8 string is indeed invalid?

Assertion is better than just returning a valid string and hiding the error. But it should probably validate UTF-8 in the first place and not show up as a side effect in some STL implementations.

**Comment by texus** [comment]
Personally I feel like providing an invalid string is a programming error and an assertion would be a valid response.
But whether the code silently hides it, asserts for it in debug mode or even throws an exception, the most important thing is that it is consistent on all platforms.

The behavior doesn't matter for me though as I don't actually use the affected code, I'm only reporting this because I discovered this error after someone reported a "crash" in my library (which uses code that was based on fromUtf8's implementation).
