### ISSUE TITLE
[Feature Request] Add a static function that converts HEX rgb and rgba strings into Color objects.

### ISSUE THREAD

**Issue by dogunbound** [SFML/SFML#2122]
## Subject of the issue

I sometimes get HEX codes instead of rgba values from programs, and adding a nifty little HEX to Color converter would be a nice addition to SFML. 

You would need to add a rgba hex to color and a rgb hex to color converter. Example hex colors:

Blue:
`#0000ff`
Blue with alpha information:
`#0000ffff`

What do ya'll think of this feature? Should it be added or not?

**Comment by dogunbound** [comment]
After talking with a bunch of people on the sfml discord, I feel that this feature request is unnecessary. If introduced, it semantically removes the first word in the logo **Simple**.

**Comment by Bromeon** [comment]
Reopened for further input.

**Comment by Bromeon** [comment]
More input always welcome, but since the actual feature is available through `Color` constructor and `toInteger()`, it doesn't need to be open. Unless someone thinks an additional HTML conversion would be helpful (as string, or without alpha).
