### ISSUE TITLE
Sprite don't reset the TextureRect when set other Texture to it

### ISSUE THREAD

**Issue by SAOS200X** [SFML/SFML#2135]
when set another Texture to Sprite by setTexture() in the second time,  it still keep the TextureRect of the first texture.
It cause some issue like:
+ if the first TextureRect smaller than other, then next Texure will be cut off for same size as the first Texture.
![Capture12](https://user-images.githubusercontent.com/107041820/174479091-8ccf1e0b-2717-4b82-ba54-d01b627e2b1e.PNG)       ![Capture11](https://user-images.githubusercontent.com/107041820/174479096-e0774fe4-fa88-4066-9a78-5484b58e5841.PNG)

+ if the first TextureRect Bigger than other, then other Texture will cause some werid stretch pitch black.

![Capture13](https://user-images.githubusercontent.com/107041820/174479132-ce23777a-b87d-4aca-8a9d-e77597a13e16.PNG)       ![Capture14](https://user-images.githubusercontent.com/107041820/174479135-d133bf55-14d9-4b60-a075-5911ab1c8756.PNG)

I could add some code to reset the TextureRect, but it's quite annoy when do it everytime.
```
m_tex.loadFromFile("tx.png");
m_sprite.setTexture(m_tex);
m_sprite.setTextureRect(sf::Vector2i(0, 0), (sf::Vector2i)m_tex.getSize());
```

**Comment by SAOS200X** [comment]
*edit: I'm using SFML 2.5.1.

**Comment by eXpl0it3r** [comment]
That's expected behavior. The `setTexture` has an additional flag `resetRect` which will adjust the rect. When the texture is initially set, the rect is automatically adjusted.
