### ISSUE TITLE
Issue when installing with apt-get: libudev.so.0 missing

### ISSUE THREAD

**Issue by nathanlct** [SFML/SFML#2143]
## Subject of the issue

When installing SFML from apt-get, and then trying to import SFML/Window.hpp, we get the following error:

```bash
/usr/bin/ld: warning: libudev.so.0, needed by /home/nathan/miniconda3/envs/nocturne/lib/libsfml-window.so.2.5.1, not found (try using -rpath or -rpath-link)
# or
ImportError: libudev.so.0: cannot open shared object file
```

This has occurred on several independent machines. We usually fix it by creating a symbolic link from the `libudev.so.1` (which does exist) to the missing `libudev.so.0`:

```
ln -s /usr/lib/x86_64-linux-gnu/libudev.so.1 /usr/lib/x86_64-linux-gnu/libudev.so.0
```

**We were wondering whether the dependencies could be upgraded to support `libudev.so.1` (which seems to work equally well with the symbolic link) or whether we did something wrong?** 

Thanks!

## Your environment

* Ubuntu 20.04 
* SFML 2.5.1

## Steps to reproduce

Installed SFML using

```bash
sudo apt-get install libsfml-dev
```

Error happens when compiling:

```cpp
#include <SFML/Window.hpp>
```

**Comment by eXpl0it3r** [comment]
@jcowgill could this be a packaging issue?

**Comment by kimci86** [comment]
It seems your compilation scripts does not use the version installed by apt-get.
The installed library is `/usr/lib/x86_64-linux-gnu/libsfml-window.so.2.5.1`
but you link to `/home/nathan/miniconda3/envs/nocturne/lib/libsfml-window.so.2.5.1`

**Comment by eXpl0it3r** [comment]
Are you using package sources from newer versions? Can you make sure ld is actually using the `/usr/lib` path and not the python env? To me it seems more like some packaging/package version issue, like using a package made for Ubuntu 22.04 on 20.04 or similar.

Lets wait and see if James as package maintainer has some inputs.

**Comment by nathanlct** [comment]
I will look into that.

About version - I just ran `sudo apt-get install libsfml-dev` as mentioned on the SFML tutorial. I'm not an expert, I assumed this automatically installs the correct version for the OS I'm running the command from?

**Comment by eXpl0it3r** [comment]
This doesn't really seem to be an SFML specific issue and might more be some odd packaging/ distro updating issue.

- https://askubuntu.com/questions/288821/how-do-i-resolve-a-cannot-open-shared-object-file-libudev-so-0-error/593420#593420
- https://askubuntu.com/questions/361651/missing-libudev-so-0
- https://github.com/adobe/brackets/issues/4855

Some say to install the missing package manually, others say to sym link it.

We can't and wouldn't want to provide a "fix" for sym linking the libs or similar. You can try and see if a forced reinstall fixes the issue or not.

Unless anyone has some ideas on how SFML can improve the situation, I'd close the issue.

**Comment by jcowgill** [comment]
Hi, I was away for a while.

@nathanlct is this still a bug?

`libudev.so.0` is a really old library. Ubuntu removed it > 10 years ago. I don't think it's possible for any official packages to be compiled against it (or really anything built from source in the last 10 years). I looked back at the build logs and there has never been an Ubuntu version of SFML compiled against `libudev.so.0`. So are you sure your version of `libsfml-window.so.2.5.1` is the one from `apt-get`?

**Comment by eXpl0it3r** [comment]
Closing this as it seems like a configuration issue.
