### ISSUE TITLE
texture image issue

### ISSUE THREAD

**Issue by DevBeginner1** [SFML/SFML#2180]
Hi.

I am new with SFML. I am working on windows 10, on Visual Studio.
I try to load an image for texture, however, it doesn't works.
Here down, I joined my script and the console issue it returns.

Thank you for your help.

![capture1](https://user-images.githubusercontent.com/111196043/184504872-26ea1eba-159d-4cbe-9d50-98bc0e861046.PNG)
![capture2](https://user-images.githubusercontent.com/111196043/184504875-77b17b32-aa8a-4ea4-b881-98331073522b.PNG)
.

**Comment by ChrisThrasher** [comment]
Are you sure that `.loadFromTexture` is returning `true`? Be sure to check that return value and halt the program if it's false.

**Comment by DevBeginner1** [comment]
> Are you sure that `.loadFromFile` is returning `true`? Be sure to check that return value and halt the program if it's false. [This example program](https://www.sfml-dev.org/documentation/2.5.1/) shows what it looks like to check that return value correctly.

The issue is indeed coming from the function `loadFromFile()`

**Comment by eXpl0it3r** [comment]
This is a common occurrence with VS when mixing debug and release. Make sure you're linking SFML libraries that end in `-d` for debug mode and without suffix in release mode.

Also for help questions please use the forun or join Discord 🙂

**Comment by DevBeginner1** [comment]
> This is a common occurrence with VS when mixing debug and release. Make sure you're linking SFML libraries that end in `-d` for debug mode and without suffix in release mode.
> 
> Also for help questions please use the forun or join Discord 🙂

It's working. Thank you very much.

**Comment by eXpl0it3r** [comment]
Good to hear! 🙂
