### ISSUE TITLE
Initialization Memory Leak - Responsible Library ColorSync Responsible Frame ColorSyncMakeProfile

### ISSUE THREAD

**Issue by dwolrdcojp** [SFML/SFML#2183]
Getting a 48 byte memory leak in my game project when opening the program. 
Leaks is showing...
Leaked Object  - Malloc 48 Bytes
Responsible Library - ColorSync
Responsible Frame - ColorSyncMakeProfile

macOS 12.5 on m2 macbook air
SFML 2.5.1 (stable) (homebrew)
(tried built from source and 3.0 same issue)
Compiler g++ 
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.6.0
compile command
"g++ -g -std=c++17 *.cpp -o prog -I/opt/homebrew/Cellar/sfml/2.5.1_1/include -L/opt/homebrew/Cellar/sfml/2.5.1_1/lib -lsfml-system -lsfml-window -lsfml-graphics -lsfml-audio"

I believe this leak is the reason the game ends up crashing after random amount of time (unable to reproduce after certain event)

![Screen Shot 2022-08-17 at 4 03 18 PM](https://user-images.githubusercontent.com/6629474/185232229-8508c087-2e23-47a8-8a98-1fa147f1a9ca.jpg)

Game repository is located here:

[https://github.com/dwolrdcojp/Alien_Shooter](url)

Any help would be appreciated.... Thanks!

**Comment by ChrisThrasher** [comment]
Is it feasible to produce a minimum viable example or does the bug disappear once you start stripping away the surrounding code?

**Comment by dwolrdcojp** [comment]
> 
Looks like I'm getting the same memory leak with a bare bones SFML window test code. 

Leak: 0x600000eed920  size=48  zone: DefaultMallocZone_0x10514c000   CFString  ObjC  CoreFoundation

`#include <SFML/Window.hpp>

int main()
{
    sf::Window window(sf::VideoMode(800, 600), "My window");

    // run the program as long as the window is open
    while (window.isOpen())
    {
        // check all the window's events that were triggered since the last iteration of the loop
        sf::Event event;
        while (window.pollEvent(event))
        {
            // "close requested" event: we close the window
            if (event.type == sf::Event::Closed)
                window.close();
        }
    }

    return 0;
}`

**Comment by ChrisThrasher** [comment]
What if the entire contents of main() is purely just this?
```cpp
int main()
{
    sf::Window window(sf::VideoMode(800, 600), "");
}
```
Seems like the leak happens when the window is constructed and that no other code is necessary to observe the leak.

**Comment by dwolrdcojp** [comment]
> What if the entire contents of main() is purely just this?
> 
> ```
> int main()
> {
>     sf::Window window(sf::VideoMode(800, 600), "");
> }
> ```
> 
> Seems like the leak happens when the window is constructed and that no other code is necessary to observe the leak.

Got the same leak when I tried just that.  Strange... must be my laptop.

![Screen Shot 2022-08-18 at 3 33 56 PM](https://user-images.githubusercontent.com/6629474/185479336-7ffe302d-d763-405c-b8b6-e8e7262b7397.jpg)

![Screen Shot 2022-08-18 at 3 34 20 PM](https://user-images.githubusercontent.com/6629474/185479357-54f4d682-eb91-4430-9fff-b63447345703.jpg)

**Comment by ChrisThrasher** [comment]
I can observe this in my own SFML projects on macOS. Still unsure what's causing it or what the fix may be though.

**Comment by eXpl0it3r** [comment]
Can you drill down further on where this is originating from?
Also make sure that whatever leak detection tool you're using, it's tracking the whole construction and destruction, even at global scope.

**Comment by ChrisThrasher** [comment]
@dwolrdcojp Any more updates on this?
