### ISSUE TITLE
Compilation fails on UWP

### ISSUE THREAD

**Issue by Zopolis4** [SFML/SFML#2186]
## Subject of the issue

SFML, as a dependency of a larger project, fails to compile for UWP.

## Your environment

* Windows 10
* Visual Studio 2022
* SFML Version 2.5.0
* MSVC

## Steps to reproduce

Compile SFML with CMake, with `-G Visual Studio 17 2022 Win64 -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0`

## Expected behavior

SFML would compile on UWP.

## Actual behavior

It generates a significant amount of errors. This [link](https://pastebin.com/WBrZycmT) has the errors, and also includes some unrelated errors, but I cannot easily separate what is caused by SFML and what is totally unrelated.

**Comment by eXpl0it3r** [comment]
Unfortunately SFML is not compatible with UWP.

Starting with SFML not using UWP approved only API calls and ending with SFML using OpenGL and UWP requiring the use of DirectX. There's currently also no plans to provide support for UWP.

**Comment by Zopolis4** [comment]
The project is only using the network module, which presumably wouldn't require OpenGL. I'll look into it.

**Comment by eXpl0it3r** [comment]
No idea if Windows Sockets work with UWP, but it's also kind of pointless, as the UWP platform already provides APIs for networking, so why not just make use of it?

I'll close this issue, as we're not planning to support UWP.
