### ISSUE TITLE
Replace SFML Vectors with GLM or Eigen

### ISSUE THREAD

**Issue by LDprg** [SFML/SFML#2190]
SFML Vectors have been around for plenty of years and I think with the desicion to move c++17 in SFML 3 we need to get away from them.  I would suggest to use Vectors as abstraction layer to some real math Libary like GLM or Eigen. This step would speed up SFML a whole lot, especially for collision detection and other math heavy calculations, but it wouldn't need that much changes in the Libary itself.

**Comment by ChrisThrasher** [comment]
> This step would speed up SFML a whole lot, especially for collision detection and other math heavy calculations

What makes you say this?

**Comment by LDprg** [comment]
I did some very basic Testing.

**Comment by ChrisThrasher** [comment]
Care to share those results?

**Comment by LDprg** [comment]
Here is my Testing code:
`#define TEST_SFML
//#define TEST_EIGEN

#ifdef TEST_SFML
#include <SFML/Graphics.hpp>
#endif

#ifdef TEST_EIGEN
#include <Eigen/Core>
#endif

#include <iostream>
#include <chrono>
#include <cmath>

#define v11 1.1
#define v12 2.5

#define v21 3.3
#define v22 4.2

#define iter 1000000000

int main() {
    auto start = std::chrono::high_resolution_clock::now();

    for(int i = 0; i < iter; i++) {
#ifdef TEST_SFML
        sf::Vector2f sv1(v11 * i, v12 * i);
        sf::Vector2f sv2(v21 * i, v22 * i);

        sf::Vector2f sDiff = sv1 - sv2;

        [[maybe_unused]] float sDiffLen = std::sqrt(sDiff.x * sDiff.x + sDiff.y * sDiff.y);
#endif
#ifdef TEST_EIGEN
        Eigen::Vector2f ev1(v11 * i, v12 * i);
        Eigen::Vector2f ev2(v21 * i, v22 * i);

        Eigen::Vector2f eDiff = ev1 - ev2;

        [[maybe_unused]] float eDiffLen = eDiff.norm();
#endif
    }

    auto finish = std::chrono::high_resolution_clock::now();

    std::cout
#ifdef TEST_SFML
    << "SFML\tsf::Vector2f\t"
#endif
#ifdef TEST_EIGEN
    << "Eigen\tEigen::Vector2f\t"
#endif
    << std::chrono::duration_cast<std::chrono::nanoseconds>(finish-start).count() << " ns" <<std::endl;
    return 0;
}`

The way it works ist by uncommenting TEST_SFML or TEST_EIGEN don't uncomment both at the same time.

My Computer Specs:
CPU:
	AMD Ryzen 7 5800H with Radeon Graphics 

	Basisgeschwindigkeit:	3,20 GHz
	Sockets:	1
	Kerne:	8
	Logische Prozessoren:	16
	Virtualisierung:	Aktiviert
	L1-Cache:	512 KB
	L2-Cache:	4,0 MB
	L3-Cache:	16,0 MB

GPU:
	NVIDIA GeForce RTX 3060 Laptop GPU

	Treiberversion:	30.0.15.1278
	Treiberdatum:	05.05.2022
	DirectX-Version:	12 (FL 12.1)
	Physischer Standort:	PCI-Bus 1, Gerät 0, Funktion 0

RAM:
	32,0 GB

	Geschwindigkeit:	2667 MHz
	Steckplätze verwendet:	2 von 2
	Formfaktor:	SODIMM
	Für Hardware reserviert:	611 MB

OS: Windows 11

My Results:
SFML    sf::Vector2f    1445257800 ns
Eigen   Eigen::Vector2f 100 ns

So Eigen seems very much faster. If you wish I can add glm too.

**Comment by Bromeon** [comment]
> My Results:
> SFML sf::Vector2f 1445257800 ns
> Eigen Eigen::Vector2f 100 ns

The difference is a factor of... 14’452’578?! 🤔 

This looks very suspicious, as in: one part is completely optimized out, while the other contains lots of unrelated measurements (printing, debug code, whatever...)

**Comment by LDprg** [comment]
I added glm where I get following result:
`GLM     glm::vec2       1455375800 ns`

Ok Results are looking very suspisous. I think I need to do some more Tesing.

**Comment by Bromeon** [comment]
You might want to look for existing benchmarks of these libraries, and port them over to SFML. Such benchmarks are much more meaningful for two reasons:
* Typically, many different operations are covered, making it a more realistic model for real-world usage
* The authors have probably already spent some time thinking about how to lay out the benchmarking (there's a lot one can do wrong).

Also, consider using `sf::Clock`. High-resolution clocks from the standard library are [suprisingly often bugged and/or inaccurate](https://github.com/SFML/SFML/pull/1872).

**Comment by vittorioromeo** [comment]
I am against this suggestion for a few reasons:

- Libraries like `glm` and `Eigen` are quite heavyweight and heavily templated -- it would result in a noticeable compilation time impact

- `glm` or `Eigen` are not going to be faster than SFML for the API SFML currently offers, all the operations we have are quite basic

- If someone needs `glm` or `Eigen`, they can be used in conjunction with SFML -- converting between a `glm::vecX` and `sf::VectorX` is quite straightforward

---

> This step would speed up SFML a whole lot

This requires a strong proof. A microbenchmark of a few basic operations is not going to be representative of a real SFML project.

---

> but it wouldn't need that much changes in the Libary itself

I am very confident you are greatly underestimating the amount of work and testing that would be needed to change one of SFML's most fundamental types.

**Comment by Bambo-Borris** [comment]
Were these benchmarks performed with a Vector3 for a reason? Most SFML users will be using Vector2f. Also I don't think anyone would doubt that there would be a performance benefit but I don't think it justifies replacing `Vector2f` either. I think the current Vector struct and utility functions allow people to achieve a lot in SFML. And those who require the performance benefits of other Vector utilities are probably more than capable of finding a way to use them whilst using SFML. Also you can't really comment on the magnitude of the change unless you've done some start on the work of replacing the current Vector implementations within SFML. The compile time increase maybe isn't so much of a concern to me, but it's still a factor we should consider when making a decision on whether a change like this is worth doing.

**Comment by LDprg** [comment]
@Bambo-Borris I will post a benchmark with vector2f later on. Maybe it's the best if I just try to implement the stated changes. If it works I will make a PR.

**Comment by LDprg** [comment]
So here is the Benchmark for Vector2f

Code: [main.zip](https://github.com/SFML/SFML/files/9491254/main.zip)
Specs as before
Plot Script as before

Output:
```
2022-09-05T16:29:35-00:00
Running D:\coden\c++\SFML vs Eigen\cmake-build-release\SFMLvsEigen.exe
Run on (16 X 3243.98 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x8)
  L1 Instruction 32 KiB (x8)
  L2 Unified 512 KiB (x8)
  L3 Unified 16384 KiB (x1)
----------------------------------------------------------------------
Benchmark                            Time             CPU   Iterations
----------------------------------------------------------------------
BM_Vector2fLength_SFML            11.4 ns         11.5 ns     64000000
BM_Vector2fLength_EIGEN          0.256 ns        0.250 ns   1000000000
BM_Vector2fLength_GLM            0.258 ns        0.266 ns   1000000000
BM_Vector2fLengthSqrt_SFML       0.248 ns        0.250 ns   1000000000
BM_Vector2fLengthSqrt_EIGEN      0.238 ns        0.250 ns   1000000000
BM_Vector2fLengthSqrt_GLM        0.248 ns        0.250 ns   1000000000
BM_Vector2fNorm_SFML              11.3 ns         11.5 ns     64000000
BM_Vector2fNorm_EIGEN            0.242 ns        0.234 ns   1000000000
BM_Vector2fNorm_GLM              0.263 ns        0.266 ns   1000000000
BM_Vector2fSum_SFML              0.252 ns        0.250 ns   1000000000
BM_Vector2fSum_EIGEN             0.240 ns        0.234 ns   1000000000
BM_Vector2fSum_GLM               0.247 ns        0.250 ns   1000000000
BM_Vector2fMul_SFML              0.240 ns        0.234 ns   1000000000
BM_Vector2fMul_EIGEN             0.252 ns        0.250 ns   1000000000
BM_Vector2fMul_GLM               0.242 ns        0.250 ns   1000000000
BM_Vector2fDiv_SFML              0.241 ns        0.234 ns   1000000000
BM_Vector2fDiv_EIGEN             0.239 ns        0.234 ns   1000000000
BM_Vector2fDiv_GLM               0.245 ns        0.250 ns   1000000000
BM_Array2fSum_SFML                 502 ns          500 ns      1000000
BM_Array2fSum_EIGEN                343 ns          345 ns      2036364
BM_Array2fSum_GLM                  499 ns          488 ns      1120000
BM_Array2fDiv_SFML                1607 ns         1604 ns       448000
BM_Array2fDiv_EIGEN                340 ns          338 ns      2036364
BM_Array2fDiv_GLM                 1605 ns         1604 ns       448000
```

Plots:
![grafik](https://user-images.githubusercontent.com/71488985/188489863-d574adf9-686b-4935-b6d4-47165577a648.png)

This is a very interesting result. In general Vector2f does not change anything (time value scaled), but somehow sf::Vector2f takes more time to execute than sf::Vector3f. First I thought that I have done some editing wrong, but the code seems valid, so it seems like sf::Vector2f is just very inefficent when working with sqrt.

So now I will start implementing.

**Comment by Bromeon** [comment]
@LDprg before you spend hours on this: keep in mind that the migration effort is only one of several aspects -- as it stands, the team hasn't seen a compelling reason to use a third-party library yet. So the risk is that such a PR might not be accepted and a lot of your work would end up wasted.

**Comment by vittorioromeo** [comment]
@LDprg: I strongly suspect the culprit of the poor performance is the use of `std::hypot` in `sf::VectorX::length`. I would focus on optimizing that rather than changing some of the most fundamental SFML types.

I would be much more likely to accept a PR that optimizes our `.length` function rather than one introducing `glm` or `Eigen`.

**Comment by vittorioromeo** [comment]
GLM defines inverse sqrt like this:

```cpp
template<length_t L, bool Aligned>
	struct compute_inversesqrt<L, float, lowp, Aligned>
	{
		GLM_FUNC_QUALIFIER static vec<L, float, lowp> call(vec<L, float, lowp> const& x)
		{
			vec<L, float, lowp> tmp(x);
			vec<L, float, lowp> xhalf(tmp * 0.5f);
			vec<L, uint, lowp>* p = reinterpret_cast<vec<L, uint, lowp>*>(const_cast<vec<L, float, lowp>*>(&x));
			vec<L, uint, lowp> i = vec<L, uint, lowp>(0x5f375a86) - (*p >> vec<L, uint, lowp>(1));
			vec<L, float, lowp>* ptmp = reinterpret_cast<vec<L, float, lowp>*>(&i);
			tmp = *ptmp;
			tmp = tmp * (1.5f - xhalf * tmp * tmp);
			return tmp;
		}
	};
```

Then defines sqrt as `1 / inverseSqrt`. That could be a good start.

**Comment by vittorioromeo** [comment]
More inspiration here: https://github.com/HandmadeMath/Handmade-Math/issues/87

**Comment by Bromeon** [comment]
Fully agree with Vittorio here -- if there are functions that are notoriously slow in some standard implementations, we should have a closer look at those in particular, rather than a blanket replacement.

GLM's code is heavily templated, which is a) bad for compile times, b) terrible for error messages.

**Comment by LDprg** [comment]
Ok so I will look into optimising the math functions.

**Comment by eXpl0it3r** [comment]
I believe most things have been said, but just weighing in, as I'm of the same opinion on the topic.
SFML doesn't try to be a math library, which is why we have kept a limited set of functionalities on the vector classes and always recommended people to use their own high performance libraries, if they do a lot of vector math.
But due to the obvious usability and year after year requests for more functionalities, it was (sort of) decided to add more, but still not with the goal to be the best performing library out there.

Happy to see optimizations of actual bottlenecks, as long as it's actually a bottleneck, the code remains readable/maintainable, and there's no significant loss in precision.
