### ISSUE TITLE
Help to understand why only half of the screen is painted over.

### ISSUE THREAD

**Issue by NikitaDotIvanov64** [SFML/SFML#2207]
Windows 10
MINGW W64 9.0
commit/3a3935d00569c5cf3dbd684ab10e54e8480df167

```
#include <SFML/Graphics.hpp>

int main()
{
  sf::RenderWindow window(sf::VideoMode({64, 32}), "SFML works!");


  sf::Texture texture;
  sf::Sprite sprite;

  if (!texture.create({64,32})) throw "";
  sprite.setTexture(texture);

  while (window.isOpen())
  {
    sf::Event event;
    while (window.pollEvent(event))
    {
      if (event.type == sf::Event::Closed)
        window.close();
    }

    uint32_t sfml_pixel_buffer[32 * 64];
    static int a= 0x00FFAADD;

    for(int i = 0; i < 32*64; ++i){
      sfml_pixel_buffer = a;
    }a+= 0xFFFF;

    texture.update(reinterpret_cast<uint8_t *>(&sfml_pixel_buffer[0]));

    window.clear();
    window.draw(sprite);
    window.display();
  }
```

A little more than half the screen is painted over.

but i think it should draw the whole screen.

**Comment by eXpl0it3r** [comment]
Please be a bit more patient with [your forum post](https://en.sfml-dev.org/forums/index.php?topic=28699.0) and don't use the issue tracker for help questions, as we try to use it for confirmed issues.

If you want some more activity, you can join the Discord server, where you might find more active people.

**Comment by NikitaDotIvanov64** [comment]
@eXpl0it3r  I chose the wrong interpretation. I think it's a problem. 
Look at this.  
sf::RenderWindow window(sf::VideoMode({64, 32}), "SFML works!"); // windows size 64*32 
uint32_t sfml_pixel_buffer[32 * 64]; // buffer size 64*32
texture.create({64,32})
sprite.setTexture(texture);
texture.update(reinterpret_cast<uint8_t *>(&sfml_pixel_buffer[0])); // texture size 64*32
I expected the whole screen to be painted

**Comment by eXpl0it3r** [comment]
I replied on your forum post. Let's first check there and if we can determine it to be an actual issue, then we can re-open the issue here.
