### ISSUE TITLE
Exec format error after compiling.

### ISSUE THREAD

**Issue by wetbadger** [SFML/SFML#2209]
## Subject of the issue

Describe your issue here.

## Your environment

* Your OS / distro / window manager used
Linux Mint 21
* Your version of SFML (2.5.0, git master, etc)
git master
* Your compiler and compiler version used
g++11.2.0
* Special compiler flags used
-c

## Steps to reproduce

```
g++ -c main.cpp
./main.o
```

Tell us how to reproduce this issue. Please provide a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve), you can use the follow template as a start:

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(1280, 720), "Minimal, complete and verifiable example");
    window.setFramerateLimit(60);

    while (window.isOpen())
    {
        for (sf::Event event; window.pollEvent(event);)
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.display();
    }
}
```

## Expected behavior

A window should open.

## Actual behavior

[Tell us what happens instead](bash: ./main.o: cannot execute binary file: Exec format error)

**Comment by eXpl0it3r** [comment]
By using the `-c` flag, you just compiled the source code to an object file, which by itself isn't executable.

Please spend some time to understand your toolchain, which is completely unrelated to SFML 😉 

To get help, please use the forum or join the official Discord server.
