### ISSUE TITLE
Windows compilation with Visual Studio 2019 on 3.x master branch fails on int64_t usages in sf::Time

### ISSUE THREAD

**Issue by PierceLBrooks** [SFML/SFML#2211]
- Subject of the issue

When compiling a fresh clone of the SFML repo on Windows with Visual Studio 2019, the "Time" class errors with complaints about the "int64_t" type not being found in the "std" namespace:

```
C:\UserData\SFML\include\SFML/System/Time.inl(223,42): error C2039: 'int64_t': is not a
member of 'std' [C:\UserData\SFML\build\src\SFML\System\sfml-system.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include\chrono(24): message : s
ee declaration of 'std' [C:\UserData\SFML\build\src\SFML\System\sfml-system.vcxproj]
```

- My environment

* My OS used: Windows 10
* My version of SFML: git master
* My compiler and compiler version used: Visual Studio 2019

- Steps to reproduce

```
git clone https://github.com/SFML/SFML.git
cd SFML
git checkout master
mkdir build
cd build
cmake ..
cmake --build .
```

- Expected behavior

SFML should compile.

- Actual behavior

SFML does not compile.

- P.S.

I believe I have found the source of this issue and intend to submit a pull request to resolve it soon.

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/actions/runs/3047035798

Do you know why our CI pipeline may not have caught this? Simply adding `<cstdint>` is likely the easy fix but I want to know how we missed a build break for a common OS and toolchain.

**Comment by PierceLBrooks** [comment]
@ChrisThrasher The pipeline's invokations of CMake seems fine to me, I am currently updating my copy of Visual Studio 2019 in order to see whether that may resolve it. In any case, I still intend to open a pull request for inserting that missing include line where it belongs at https://github.com/SFML/SFML/blob/master/include/SFML/System/Time.hpp#L33 unless that is felt to be unnecessary by your team.

**Comment by ChrisThrasher** [comment]
Go ahead with the PR. It's exactly what I would have done anyways. I just hope in the meantime we can figure out how this slipped through the cracks.

**Comment by ChrisThrasher** [comment]
Can you build the `sf::Time` unit tests? The first header in that test .cpp file is Time.hpp so if Test.hpp was missing something I'd expect that test to not compile. Set the CMake option `SFML_BUILD_TEST_SUITE` to `ON` to build all the tests.

**Comment by PierceLBrooks** [comment]
`cmake -DSFML_BUILD_TEST_SUITE=ON .. && cmake --build .` from inside my temporary `build` subdirectory yields the same errors sadly.

**Comment by ChrisThrasher** [comment]
@eXpl0it3r Any idea why our CI pipeline didn't already catch this? I ensure the tests include the header under test first precisely to catch these kinds of errors so I'm really surprised we missed this. Fix is trivial but I want to shore up our CI process if possible.

**Comment by PierceLBrooks** [comment]
After updating Visual Studio 2019, this does appear to be an issue with my copy having been outdated. Here is a screen to show the difference beforehand:
![image (1)](https://user-images.githubusercontent.com/33040784/191633280-a3f73b98-a9a7-40aa-a3f0-6a6082bf9838.png)

**Comment by ChrisThrasher** [comment]
I'm still fine merging your PR though since I have to imagine that others will also be using outdating versions of VS and I don't want to revisit such bug reports.
