### ISSUE TITLE
Replace empty `struct`s with namespaces

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2224]
Structs like [sf::Joystick](https://github.com/SFML/SFML/blob/939ec267dfa98e97438a5b76f79317c7e0738a92/include/SFML/Window/Joystick.hpp#L42) only exist to provide a namespace. The struct itself only includes public, static functions and types. I propose we convert that struct and all similar structs of which there are a few more to a namespace so that users cannot accidentally construct an instance of `sf::Joystick` since that is a nonsense operation. This change won't even be an API for break anyone except for those taking instances of these empty types who will be forced to fix their code.

**Comment by Bromeon** [comment]
Even though in practice it doesn't matter that much, I agree that namespace is cleaner and underlines the intent of not having instances.

One small disadvantage is that Doxygen still has this old-school view of "class is the main way of grouping functionality", which means that currently [most SFML functionality is grouped in the class view](https://www.sfml-dev.org/documentation/2.5.1/annotated.php). Maybe we should encourage users to look [at the Modules page](https://www.sfml-dev.org/documentation/2.5.1/group__graphics.php) which lists both classes and namespaces, although it can be difficult if they don't know in which module a symbol lies.

Technically, this change would be an API break for people that have `using` or `typedef`, or that use `sf::Joystick` as a type argument in templates (for whatever reason).

**Comment by ChrisThrasher** [comment]
Doxygen can list namespaces in the class view as well. I need to make some small documentation tweaks but it seems like this change wouldn't make the docs any less readable.

<img width="609" alt="Screenshot 2022-11-05 at 10 46 31 PM" src="https://user-images.githubusercontent.com/39244355/200154692-db23207b-de93-4020-9bfa-a5a269848742.png">

**Comment by Jim-Marsden** [comment]
I've went through and found nine places where we should be able to use a namespace over a struct.

I'll be following up with a PR-Draft in a day or two.

**Comment by ChrisThrasher** [comment]
> I've went through and found nine places where we should be able to use a namespace over a struct.

Which nine are they?

**Comment by Jim-Marsden** [comment]
Window/Clipboard.hpp
Window/Joystick.hpp
Window/Keyboard.hpp
Window/Mouse.hpp
Window/Sensor.hpp
Window/Touch.hpp
Window/Vulkan.hpp
System/SystemAwareClock.hpp
Audio/Listener.hpp
