### ISSUE TITLE
Incorporate 3rd party drm-common.[h|c] files into SFML

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2252]
## Subject of the issue

While discussing #2245 it came to our attention how it was odd that 3rd party DRM code needed our attention. Vendoring 3rd party code which we never modify is acceptable as is maintaining 1st party code over which we have full control, but 3rd party code which we must modify is an awkward middle ground.

I propose we integrate [drm-common.h](https://github.com/SFML/SFML/blob/master/extlibs/headers/drm/drm-common.h) and [drm-common.c](https://github.com/SFML/SFML/blob/master/extlibs/headers/drm/drm-common.c) into SFML itself. This means a few things which can be broken apart into multiple commits/PRs as we see fit.

1. Verify the license lets us do this. I believe we're legally cleared to take this code and heavily modify it for our purposes. I'm unsure however if that means maintaining the existing copyright notice or if extensive enough modification lets us use the normal SFML copyright header.
2. Move drm-common.h and drm-common.c into SFML's src/ directory. I'm guessing the precise location will be src/SFML/Window/DRM. This entails patching the build system to point at these new files and will probably result in simpler build code too.

The above steps are sufficient for a PR by itself but I think we need to go further with this.

3. Rename the files to Common.hpp and Common.cpp. This will start building these files as C++ code.

4. Remove any utilities we're not using. The following steps are easier if we initially minimize how much code we're having to modify.

5. Replace C idioms with C++ idioms. Easy examples of this are replacing `struct T` parameters and local variables with `T`. Other easy changes are replacing C standard header with their C++ equivalent.

6. Use SFML C++ code style. This includes conventions for naming variables, functions, and types and adding namespaces.

7. Potentially start manually inlining this code into the callsities where it's used. For example, if a given function is only needed in one file, it's perhaps better to define that function in that one file instead of maintaining it in a separate .hpp/.cpp pair. If we keep doing this, it's possible that both files disappear but I'm unsure until this process actually begins.

**Comment by ChrisThrasher** [comment]
https://github.com/ChrisThrasher/SFML/commit/2ecb24c363c90eae5fc9bb09a7905f0ddbb34660

I started working this out. I can already tell there are a lot of changes we want to make to this C++ to get it up to standards of the rest of SFML.

**Comment by ChrisThrasher** [comment]
@substring @oomek Can you weigh in on this? Would you be willing to upgrade to SFML 3 if it meant getting to make as many changes to DRM code as you want?

**Comment by substring** [comment]
Regarding the changes in SFML 3 that may break 2.5/2.6 retro-compatibility, the time @oomek and I have invested in getting DRM in 2.6, the fuss about enhancing DRM in my last 2 PR and the lack of ETA for next releases, I'm dubitative about the goal you're trying to achieve here.

All in all, we have no idea when to expect DRM with our last changes in a stable DRM.

**Comment by oomek** [comment]
What I agree with is trying to keep the code consistent. What I don't agree with is the tendency to throw conditional roadblocks to the contributions. I find this attitude a little discouraging.

I would like to see more of "I accept your contribution, but we will have to think about refactoring it later" instead of "we won't be able to accept your contribution unless you rewrite the whole file"

**Comment by ChrisThrasher** [comment]
> What I don't agree with is the tendency to throw conditional roadblocks to the contributions.

If I was trying to throw up roadblocks I would not have implemented my proposal. I'm on your side and want you to be able to modify the DRM code as you see fit, but first we need to figure out our philosophy for handing 3rd party source code.

**Comment by eXpl0it3r** [comment]
I think there's a bit of a misunderstanding of the situation. My question on the PR was mainly triggered by the assumption that the common headers are unmodified external source files, which the, don't seem to be. You got to understand that I'm not at all familiar with DRM, so what may seem obvious to you, isn't for me.

We moved thed discussion out of the PR as it wasn't really relevant for it.

The PRs can easily be accepted, as they don't change the status quo. I'm greatful and thank you for these fixes and contributions! 🙂

The question in this issue are more about planning ahead and considering options. As primary contributors for the DRM part, we also wanted to hear your view and find out if and for which option you'd want to help out further. It wasn't meant as condition or roadblock in any way.

Hope that clarified and defuses the situation a bit. 😄

**Comment by ChrisThrasher** [comment]
@substring @oomek can you share your thoughts on whether you think it makes sense to merge these DRM files into SFML itself or should they continue be treated as 3rd party code?

**Comment by oomek** [comment]
@eXpl0it3r @ChrisThrasher Thanks for clarifying this misunderatanding. I'm ok with either option. When we decide to SFML-ize it what happens to the original license in the file header? Shall we leave it as it is, rewrite it to match SFML mentioning the original author, or provide both?

**Comment by ChrisThrasher** [comment]
See #2259
