### ISSUE TITLE
Segfault when closing window in WSL

### ISSUE THREAD

**Issue by oddbookworm** [SFML/SFML#2255]
## Subject of the issue

Segmentation fault in WSL2 when closing a window

## Your environment

* Your OS / distro / window manager used
Windows 11 with Ubuntu on WSL
* Your version of SFML (2.5.0, git master, etc)
2.5.1 (installed through apt-get)
* Your compiler and compiler version used
clang++ (Ubuntu clang version 14.0.0-1ubuntu1)
g++ (g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0)
* Special compiler flags used
clang++: -fcolor-diagnostics -fansi-escape-codes
g++: None

## Steps to reproduce

Just close the window with the "x" button

```cpp
#include <SFML/Graphics.hpp>

int main () {
    sf::RenderWindow window(sf::VideoMode(500, 500), "Hello");
    while (window.isOpen()) {
        sf::Event event;
        while (window.pollEvent(event)) {
            if (event.type == sf::Event::Closed) {
                window.close();
            }
        }

        window.clear();
        window.display();
    }
}
```

## Expected behavior

No segfault?

## Actual behavior

segfault when window is closed. Here is the backtrace from `gdb`:
```
#0  0x00007fffebbb54ba in ?? () from /usr/lib/wsl/drivers/nv_dispi.inf_amd64_1b5e80ff87b1f5c8/libnvwgf2umx.so
#1  0x00007fffebbb38ee in ?? () from /usr/lib/wsl/drivers/nv_dispi.inf_amd64_1b5e80ff87b1f5c8/libnvwgf2umx.so
#2  0x00007fffebbb3866 in ?? () from /usr/lib/wsl/drivers/nv_dispi.inf_amd64_1b5e80ff87b1f5c8/libnvwgf2umx.so
#3  0x00007ffff7a46b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#4  0x00007ffff7ad8a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
Possibly of note: The message "Setting vertical sync not supported" appears whenever I run the linux executable via WSL, so possibly a graphics driver problem in WSL?

**Comment by eXpl0it3r** [comment]
It crashes somewhere in the graphics driver, so not much SFML can do 😅 

What are you using for rendering a window from Linux in Windows?

**Comment by oddbookworm** [comment]
iirc, recent graphics drivers have support for wsl out of the box. I'm currently waiting on nvidia support so I can report the segfault to them

**Comment by oddbookworm** [comment]
I'm gonna close this issue since it's not an SFML issue
