### ISSUE TITLE
#pragma GCC issue warning with MSVC

### ISSUE THREAD

**Issue by pifopi** [SFML/SFML#2266]
## #pragma GCC issue warning with MSVC

Hello ! with the latest change in https://github.com/SFML/SFML/blob/master/include/SFML/System/Vector2.inl from commit https://github.com/SFML/SFML/commit/cd985e37d2239437b33449b95466579c4239d82b
I get this warning at compilation :
SFML/System/Vector2.inl(40,9): warning C4068: unknown pragma 'GCC'

## Your environment

* windows 10
* latest SFML master
* MSVC

I checked the code and I think it could be easily fixed by either adding
`#if defined(__GNUC__)`
around the pragma or removing it totally and using other names for the parameter. Would it be okay to do this ? Would you like me to do the change and do a Pull Request ?

thanks for your awesome library !

**Comment by ChrisThrasher** [comment]
That's my bad. I know how to fix it and want to get that patched soon. In the meantime you can add `/wd4068` to work around this.

**Comment by pifopi** [comment]
No problem ! Thanks the quick answer

**Comment by ChrisThrasher** [comment]
https://github.com/ChrisThrasher/SFML/commit/77dacb2c20bbe8faa631ad72efcbc33faa4163ce

Does this fix your problem?

**Comment by ChrisThrasher** [comment]
Check out #2267 and let me know if that works.

**Comment by pifopi** [comment]
Thanks for the fix, I can confirm it works

**Comment by ChrisThrasher** [comment]
Thanks for reporting this! I merged the fix.
