### ISSUE TITLE
Can't run any programs in SFML without it crashing.

### ISSUE THREAD

**Issue by DavideB2610** [SFML/SFML#2270]
Any SFML program (Sorry if this post is bad, actually my first one in my entire life on any platform)

The title says it all, can't even run the test program on the SFML site, watch the video for more info.

* Windows 11
* SFML 2.5.1
* Visual Studio 2022

This is the code i'm trying to use, but it does it with any code.

```cpp
#include <SFML/Graphics.hpp>
#include <SFML/GpuPreference.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(1280, 720), "Test");
    window.setVerticalSyncEnabled(true);

    sf::RectangleShape rect;

    sf::Vector2f rectanglePosition(600, 350);
    
    rect.setPosition(rectanglePosition);

    rect.setSize(sf::Vector2f(100, 100));

    float xVelocity = 3;
    float yVelocity = 3;

    while (window.isOpen())
    {

        sf::Event event;

        while (window.pollEvent(event))
        {

            if (event.type == sf::Event::Closed) window.close();

            if (sf::Keyboard::isKeyPressed(sf::Keyboard::Escape)) window.close();

        }

        //Physics

        if (rectanglePosition.x < 0 || rectanglePosition.x > 1280) xVelocity *= -1;
        if (rectanglePosition.y < 0 || rectanglePosition.y > 720) yVelocity *= -1;

        rectanglePosition.x += xVelocity;
        rectanglePosition.y += yVelocity;
        rect.setPosition(rectanglePosition);



        //Rendering
        window.clear();

        window.draw(rect);

        window.display();


    }

    return 0;
}
```

https://user-images.githubusercontent.com/117928116/201439568-bfc7ad7f-a2bc-45d8-9809-764da3d136fb.mp4

![image](https://user-images.githubusercontent.com/117928116/201439611-b005c975-1389-4a0e-9686-b6e342ec51a4.png)

I got helped by 2 SFML developers and some guys on the SFML Discord server, we tried everything, CMake, vcpkg. It only does this for me, i tried it on a VM and it works, updated drivers and the GPU is a Nvidia 2070 that works just fine, CPU Ryzen 7 3700x, 16GB ram.

**Comment by Jim-Marsden** [comment]
I helped them build from vcpkg. They were able to build and link.

I was informed that they updated their graphics drivers.

**Comment by Bambo-Borris** [comment]
We tried the following when attempting to help this user:

- Verified their initial Visual Studio project was configured correctly for x86 Debug/Release 
- Got them to configure their Visual Studio project for x64 Debug/Release
- Built from source using the CMake template project
- Used vcpkg to install SFML then use in a Visual Studio project
- Swap between FPS/Vsync (can't remember why we tried this) 
- Update GPU drivers
- Got them to build the basic green circle example from the website (also produced the same errors in the log)

**Comment by eXpl0it3r** [comment]
This is unlikely an SFML issue.

- Try running any other OpenGL applications.
- Make sure you're not running any odd system-wide "utility" applications, like Flux or similar
- Run a basic OpenGL-only application (e.g. render a triangle with OpenGL only)
- Use gDebugger or similar to get more information on the actual failure
- Ensure your PATH doesn't contain some broken OpenGL DLL
- Do a clean install of your GPU driver (remove e.g. with [Display Driver Uninstaller](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html)) and reinstall it
- Reseat your GPU
- Reinstall Windows 🤷
