### ISSUE TITLE
Out dated description for sf::View - setViewport(const FloatRect&)

### ISSUE THREAD

**Issue by Intemporel** [SFML/SFML#2278]
https://github.com/SFML/SFML/blob/1d4db22d6226e21b507975c59a13975bd0416b35/include/SFML/Graphics/View.hpp#L112

You must replace the exemple by :

```cpp
setViewport(sf::FloatRect({ 0.f, 0.f }, { 1.f, 1.f }));
```

**Comment by ChrisThrasher** [comment]
Thanks! We'll be sure to fix this.
