### ISSUE TITLE
Switch from header guards to `#pragma once`

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2305]
## Subject of the issue

#2303 demonstrates a potential class of error with header guards. This was only caught while doing a unity build of SFML and an external project which shows how subtle these header guard bugs can be. Beyond that, `#pragma once` is 66% less code, almost impossible to write wrong, prevents users from mucking about with disabling headers externally, and is supported on every C++ compiler I've ever encountered, especially any compiler that also supports C++17 which cuts out tons of older compilers which maybe hadn't yet implemented it.

**Comment by Jim-Marsden** [comment]
I want to go one step farther. It's cleaner to use #pragma once. The examples I know of where it is not support neither is C++11. As I see it there are more negatives with using include guards than with #pragma once in 2022.

**Comment by eXpl0it3r** [comment]
I don't really mind going in that direction. There are a few (Modern JSON, spdlog) who've taken that direction already and [others as well](https://twitter.com/DarkCisum/status/1604957117324365824), but for most libraries I've looked at, they're still using header guards.

Two points also:
- With `#pragma once` you won't have to fear header guard names collision
- With header guards, you could, if you really wanted to, define the guard yourself and thus exclude the header from being included

**Comment by ChrisThrasher** [comment]
After some Discord discussions we decided this was worth doing. If no one else picks up this issue in the next week or so, I'll eventually get around to implementing this myself. 

https://github.com/cgmb/guardonce

Here's a tool someone found that might be able to help us automate this process.
