### ISSUE TITLE
Remove defaulted or empty, non-virtual destructors

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2312]
## Subject of the issue

I'm not quite sure how they ended up like but a few types have non-virtual destructors that do nothing. The existence of these destructors implicitly disables move semantics even if they're `= default`'d so it's best to remove them entirely. Here are the types where I found this happening. There may be more.

- `sf::Font`
- `sf::SocketSelector`
- `sf::Cursor`
- `sf::Font`

**Comment by kimci86** [comment]
`Cursor` and `ScoketSelector` classes use pimpl idiom, having a `std::unique_ptr` to forward-declared type.
`Font` uses a similar pattern on Android.
So the compiler cannot generate destructor at class definition time.

**Comment by ChrisThrasher** [comment]
This issue didn't end up being nearly as simple as I thought so I'm closing it.
