### ISSUE TITLE
Use `std::clamp`

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2313]
## Subject of the issue

There are some places where `std::min` and `std::max` are used to emulate C++17's `std::clamp` and at least one place where a custom `clamp` function is implemented. Replace all of these with `std::clamp`. See these files:

- Island.cpp
- Joystick.cpp
- Vulkan.cpp
- SFOpenGLView+mouse.mm

**Comment by HelloShiv** [comment]
I actually checked 

- Island.cpp 
- Joystick.cpp 
- SFOpenGLView+mouse.mm

But did not found out std::min and std::max used to replace std::clang , mentioning the code parts below

Island.cpp Includes these 
-------

-  elevation      = std::min(std::max(elevation, 0.0f), 1.0f);
- float factor = std::min((elevation - 0.4f) / 0.1f, 1.f);
- float factor = std::min((elevation - snowcapHeight) / 0.05f, 1.f);
- unsigned int rowEnd   = std::min(rowStart + rowBlockSize, resolutionY);

- std::min(std::max(elevation, 0.0f), 1.0f);

------
### In Joystick.cpp 
there is no use of std::min , std::max or self defined clang

------
In SFOpenGLView+mouse.mm
-------
- rawPos.x       = std::min(std::max(origin.x, rawPos.x), origin.x + size.width - 1);
- rawPos.y       = std::min(std::max(origin.y + 1, rawPos.y), origin.y + size.height);
