### ISSUE TITLE
Remove unnecessary `return EXIT_SUCCESS;`

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2314]
## Subject of the issue

The C++ specification requires that `0` be returned if you reach the end of `main` so you never have to add `return 0;` or `return EXIT_SUCCESS;` as the last expression in your program. This pattern can be removed which also entails potentially removing `#include <cstdlib>` if this is the last place where that header is being used.

**Comment by maddy020** [comment]
I want to work over this issue 
Please assign it to me

**Comment by ChrisThrasher** [comment]
You don’t need to ask for permission

**Comment by eXpl0it3r** [comment]
Implemented with #2330
