### ISSUE TITLE
Replace anonymous `enum`s with `constexpr` variables.

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2328]
## Subject of the issue

https://github.com/SFML/SFML/blob/9a4426fb35e2c4157b769f4d735e45028243ace5/include/SFML/Network/UdpSocket.hpp#L53-L56

Above is an example of an anonymous enum used to define constants. I think these would be better replaced with `static constexpr` variables. It better expresses our intent and gives us more direct control over what type is used to represent the integer.

[Here's my attempt to find all instances of this pattern.](https://github.com/ChrisThrasher/SFML/commit/4ce64203adf28ad5614010e76e85bf6f6176e40f)

**Comment by eXpl0it3r** [comment]
Sounds good to me

**Comment by gnawme** [comment]
An anonymous `enum` is [actually preferred](https://isocpp.org/blog/2016/05/quick-q-static-constexpr-int-vs-old-fashioned-enum-when-and-why).

If you want to specify the type, write the preceding as:
```
enum : std::size_t
{
    MaxDatagramSize = 65507U
 };

**Comment by kimci86** [comment]
> An anonymous enum is [actually preferred](https://isocpp.org/blog/2016/05/quick-q-static-constexpr-int-vs-old-fashioned-enum-when-and-why).

Is this relevant for C++17?
I do not reproduce the linker error from the example in compiler explorer with clang or g++ with C++17 standard (but I do with C++11 and C++14).

**Comment by gnawme** [comment]
> Is this relevant for C++17?

Hmm, it appears that the [guidance has changed](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#S-enum) (specifically vs unnamed `enum`)
