### ISSUE TITLE
and, or, not

### ISSUE THREAD

**Issue by rtkid-nt** [SFML/SFML#2331]
1. Maybe use `and` instead of `&&`
2. Maybe use `or` instead of `||`
3. Maybe use `not` instead of `!`

It`s looks more modern and more simple

```cpp
#include <iostream>

int main()
{
    std::cout << (true and true) << "\n"; // 1
    std::cout << (true or false) << "\n"; // 1
    std::cout << (not false) << "\n";     // 1
}
```

**Comment by eXpl0it3r** [comment]
Interesting that you perceive the alternative operator tokens as more modern and more simple.

I don't see this as something to change for SFML.

Having written C++ and used C-like syntaxes for so long, I would find it much harder to read code like that. Having specific symbols makes it easier to distinguish between variable names and logic operators.  
Historically, it's also interesting to note, that these alternative tokens as well as trigraphs were added for systems which only supported a limited set of ASCII codes, so in that sense it's essentially rather "old" and not sure where the modern perception comes in.

Given the name, they are considered "alternatives" to the "official" tokens.  
Also note, that alternative operator tokens can be disabled for some compilers (e.g. `-fno-operator-names`), so in theory (unlikely) it could break someone's compiler configuration.
