### ISSUE TITLE
Instead of pimpl use CRTP

### ISSUE THREAD

**Issue by rtkid-nt** [SFML/SFML#2333]
Instead of:
```cpp
#define WIN32
// #define UNIX

#ifdef WIN32
using WindowImplType = WindowImplWin32;
#elif defined UNIX
using WindowImplType = WindowImplUnix;
#endif

class WindowImpl
{
public:
    virtual ~WindowImpl() = default;

    virtual bool isOpen() const = 0;
};

class Window
{
public:
    Window() { m_impl = new WindowImplType(); }
    Window() { delete m_impl; }

    bool isOpen() const { return m_impl->isOpen(); }

private:
    WindowImpl* m_impl;
};

class WindowImplWin32 : public WindowImpl
{
public:
    bool isOpen() const override { return true; }
};

class WindowImplUnix : public WindowImpl
{
public:
    bool isOpen() const override { return true; }
};
```
I know that it is implemented a little differently, but the essence is the same

Use:
```cpp
template<typename Implementation>
class WindowInterface
{
public:
    bool isOpen() const { return impl()->isOpen(); }

private:
    Implementation* impl() { return static_cast<Implementation*>(this); }
};

class WindowWin32 : public WindowInterface<WindowWin32>
{
public:
    bool isOpen() const { return true; }
};

class WindowUnix : public WindowInterface<WindowUnix>
{
public:
    bool isOpen() const { return true; }
};


#define WIN32
// #define UNIX

#ifdef WIN32
using Window = WindowWin32;
#elif defined UNIX
using Window = WindowUnix;
#endif


```
We keep strong interface

Example: 
```cpp
class Texture
{
    template<typename T>
    void Texture::update(const WindowInterface<T>& window);
};

int main()
{
    Window window;
    sf::Texture texture;
    texture.update(window);
}
```

[+] We get rid of unnecessary indirection ~~`new WindowImplType()`~~ - perfomance boost
[+] We save strong interface 
[+] We have reusable code in `WindowInterface`
[-] We slow down the build speed

**Comment by ChrisThrasher** [comment]
Would this require moving lots of code from .cpp files to .hpp files?

**Comment by rtkid-nt** [comment]
> Would this require moving lots of code from .cpp files to .hpp files?

Moving:
- `WindowInterface` all 
- Functions that take as an argument `WindowInterface`

Not moving:
-  `WindowWin32`, `WindowUnix` etc...

**Comment by Jim-Marsden** [comment]
I have a few question because I'm honestly not sure.

Please correct me if I'm wrong but CRTP and PIMPL address two different, but related issues? Where PIMPL is about extending the private implementation details, but not changing public interface.

Where CRTP is more about extending the public interface?

As this is a library; would this not be a concern to risk leaking implementation details?

As far as the speed, while static dispatch is faster, when system calls are involved would it make a difference there?

**Comment by rtkid-nt** [comment]
> I have a few question because I'm honestly not sure.
> 
> Please correct me if I'm wrong but CRTP and PIMPL address two different, but related issues? Where PIMPL is about extending the private implementation details, but not changing public interface.
> 
> Where CRTP is more about extending the public interface?
> 
> As this is a library; would this not be a concern to risk leaking implementation details?
> 
> As far as the speed, while static dispatch is faster, when system calls are involved would it make a difference there?

Yep, CRTP and PIMPL different
Yep, implementation details leaked `<Windows.h>` and other os self window api, it`s a problem.
I think yes, because in one frame we call +- 1-5 `pollEvent(event)`
