### ISSUE TITLE
`final` specifier in derived classes

### ISSUE THREAD

**Issue by rtkid-nt** [SFML/SFML#2342]
`x86-64 gcc 12.2` with `-O3` 

Without `final` specifier:
```cpp
#include <iostream>

class Base 
{ 
public:
    virtual ~Base() = default;
    virtual void f() const = 0; 
}; 
 
class Derived : public Base 
{ 
public:
    void f() const override { std::cout << "Derived\n"; } 
};

void call_f(const Derived& d) { 
    d.f(); 
}
```
```asm
.LC0:
        .string "Derived\n"
Derived::f() const:
        mov     edx, 8
        mov     esi, OFFSET FLAT:.LC0
        mov     edi, OFFSET FLAT:_ZSt4cout
        jmp     std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)
call_f(Derived const&):
        mov     rax, QWORD PTR [rdi]
        mov     rax, QWORD PTR [rax+16]
        cmp     rax, OFFSET FLAT:Derived::f() const
        jne     .L4
        mov     edx, 8
        mov     esi, OFFSET FLAT:.LC0
        mov     edi, OFFSET FLAT:_ZSt4cout
        jmp     std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)
.L4:
        jmp     rax
_GLOBAL__sub_I_call_f(Derived const&):
        sub     rsp, 8
        mov     edi, OFFSET FLAT:_ZStL8__ioinit
        call    std::ios_base::Init::Init() [complete object constructor]
        mov     edx, OFFSET FLAT:__dso_handle
        mov     esi, OFFSET FLAT:_ZStL8__ioinit
        mov     edi, OFFSET FLAT:_ZNSt8ios_base4InitD1Ev
        add     rsp, 8
        jmp     __cxa_atexit
```

With `final` specifier:
```cpp
#include <iostream>

class Base 
{ 
public:
    virtual ~Base() = default;
    virtual void f() const = 0; 
}; 
 
class Derived final : public Base 
{ 
public:
    void f() const override { std::cout << "Derived\n"; } 
};

void call_f(const Derived& d) { 
    d.f(); 
}
```

```asm
.LC0:
        .string "Derived\n"
call_f(Derived const&):
        mov     edx, 8
        mov     esi, OFFSET FLAT:.LC0
        mov     edi, OFFSET FLAT:_ZSt4cout
        jmp     std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)
_GLOBAL__sub_I_call_f(Derived const&):
        sub     rsp, 8
        mov     edi, OFFSET FLAT:_ZStL8__ioinit
        call    std::ios_base::Init::Init() [complete object constructor]
        mov     edx, OFFSET FLAT:__dso_handle
        mov     esi, OFFSET FLAT:_ZStL8__ioinit
        mov     edi, OFFSET FLAT:_ZNSt8ios_base4InitD1Ev
        add     rsp, 8
        jmp     __cxa_atexit
```

[+] In rare places performance boost
[+] More convinient interface
[+] Easy to add

if I do it, will you accept it?

**Comment by ChrisThrasher** [comment]
What specific types do you think would benefit from being marked as `final`?

**Comment by eXpl0it3r** [comment]
Beyond a technical perspective, you also need to consider this from an API design side.

While we do not recommend to derive from SFML classes and much rather promote composition instead, applying the `final` keyword turns this "recommendation" into a "restriction" - users simply cannot derive from SFML classes anymore.

Maybe we can find a set of classes, which we believe really shouldn't be extended any further, but I don't think we should apply it to every derived class.

**Comment by rtkid-nt** [comment]
> Beyond a technical perspective, you also need to consider this from an API design side.
> 
> While we do not recommend to derive from SFML classes and much rather promote composition instead, applying the `final` keyword turns this "recommendation" into a "restriction" - users simply cannot derive from SFML classes anymore.
> 
> Maybe we can find a set of classes, which we believe really shouldn't be extended any further, but I don't think we should apply it to every derived class.

What can I do to help the development of SFML? I adore this library

**Comment by ChrisThrasher** [comment]
> What can I do to help the development of SFML? I adore this library

Review any open PRs in case you can find issues with them. Approve the ones you understand and know are good. The issues you've opened require making radical changes. I'd recommend looking for smaller changes to start with.
