### ISSUE TITLE
Build system generator

### ISSUE THREAD

**Issue by rtkid-nt** [SFML/SFML#2345]
What do you think about replacing `CMake` with `Gradle` in SFML 3?

CMake:
- ✔️ Standart, stable, old
- ✔️ Easy to install, use
- ❌ Hard to write `cmake` files
- ❌ Andorid we build with `gradle`, but other with `cmake`

Gradle:
- ✔️ Easy to write build files with `groovy` or `kotlin` language
- ✔️ Single build generator on android and other
- ❌ Not standart, no so old as `cmake`
- ❌ Depend on JVM

**Comment by ChrisThrasher** [comment]
Sorry but we’re not interested in such a thing. We haven’t had significant issues with CMake.
