### ISSUE TITLE
Message from debugger: Terminated due to signal 6, Xcode, macbook m1, SFML

### ISSUE THREAD

**Issue by artiik16** [SFML/SFML#2354]
When I start my SFML app in Xcode on macbook m1 I have error "Message from debugger: Terminated due to signal 6" and this image ![2023-01-11 21 10 53](https://user-images.githubusercontent.com/96563923/211905742-5cb8ab1a-13e6-43b4-8c22-4f216c087514.jpg)
Maybe someone knows how to fix this. Help please

I searched the internet for a solution, but couldn't find a solution.

**Comment by ChrisThrasher** [comment]
Can you provide a minimum viable example that demonstrates this?

**Comment by artiik16** [comment]
https://user-images.githubusercontent.com/96563923/211907918-63780b3c-8534-4a35-b275-b5d056a14cad.mp4

**Comment by eXpl0it3r** [comment]
Have you rebooted your device already? The CI processes were sometimes randomly shutdown by the OS until I rebooted the mac minis

**Comment by artiik16** [comment]
> 

Yes of course. I even reinstalled mac os in desperation.

**Comment by ChrisThrasher** [comment]
Can you share the smallest possible program that recreates this error? For example, can you remove that `sf::Image` code and still observe this error?

**Comment by artiik16** [comment]
https://user-images.githubusercontent.com/96563923/211923561-94ccd897-5aa4-4c27-87ea-67f4cb848840.mp4

I have no problem running the OpenGL library or the simple lite tool command, but SFML doesn't work(

**Comment by eXpl0it3r** [comment]
You got quite a few error in that console of files that couldn't be found and fopen that fails. Might want to look into those.

Also please [use the forum or join Discord](https://www.sfml-dev.org/community.php) to talk about your project problems with SFML, as we try to keep the issue tracker for confirmed issues with SFML itself.
