### ISSUE TITLE
Replace `std::strcmp` with `std::string_view::operator==`

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2366]
## Subject of the issue

<img width="287" alt="Screenshot 2023-01-16 at 4 41 43 PM" src="https://user-images.githubusercontent.com/39244355/212780820-a8c793e6-9c17-4979-8088-b71670c4ef1b.png">

Looks like we're only using `std::strcmp` to detect equality of strings which we can do more expressively with `std::string_view::operator==`.

**Comment by Bromeon** [comment]
I guess you mean `operator==` 😉

But are all these cases using at least one `std::string` argument? Doesn't make sense to allocate if we only have C strings...

**Comment by ChrisThrasher** [comment]
> I guess you mean operator== 😉

Oops yes!

> But are all these cases using at least one std::string argument? Doesn't make sense to allocate if we only have C strings...

I think the readability gains are worth perhaps incurring a single allocation. Besides some of these strings will fall within the small string optimizations so they may not even allocate.

**Comment by kimci86** [comment]
We can also use `std::string_view` to avoid dynamic allocation.
