### ISSUE TITLE
Win32 Exmaple missing required variable note.

### ISSUE THREAD

**Issue by N1NJ4** [SFML/SFML#2382]
## Subject of the issue

Better Example(s), This is a required variable for code to operate, There could be other bugs in the examples like this.
Or include a default with option to change said variable for the coder.

## Your environment

SFML (2.5.0, git master)

## Steps to reproduce

read the win32 example

https://github.com/SFML/SFML/blob/642d981acf5c208877523da3567ff30bc9d3645f/examples/win32/Win32.cpp#L87-L98

No mention of "STATIC" being Required

https://github.com/SFML/SFML/blob/642d981acf5c208877523da3567ff30bc9d3645f/src/SFML/Window/Win32/WglContext.cpp#L579-L590

without this "STATIC", the window will not display or work. as hence. Required. Writing your own you might miss this.

## Expected behavior

Own code works

## Actual behavior

Missing Required Variable.

**Comment by eXpl0it3r** [comment]
It’s not really SFML’s goal to teach you Win32 API programming. Not sure if SFML really needs STATIC or whether there only some supported styles, see the official documentation: https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowa#remarks

**Comment by N1NJ4** [comment]
I did write something else(May have missed a step.) though; That would only allow rendering, It probably still needs to be mentioned, without it being "STATIC" it will be the wrong window Predefined Class type(although only a set number of options are available and not desirable); not SFML's fault, though using SFML, such information might be necessary.

On the other hand, maybe SFML needs to implement an able way to create a base window using Win32 with rendering, rather than use a Child window within.

**Comment by eXpl0it3r** [comment]
Looking at this again it seems that if you want to have an embedded window in the way its done in the example, then you'll need to use `STATIC`. This isn't an SFML requirement, but a Win32 requirement.
You can use SFML on any HWND, but it's not SFML's responsibility to make sure how the HWND was created or whether it's displayed correctly etc.

As such, I'll close this issue.
