### ISSUE TITLE
SFML and Windows XP

### ISSUE THREAD

**Issue by JeanPaulLucien** [SFML/SFML#2387]
Hello. I collect information about software that is possible to use in Windows XP. I would to know what about SFML.
If your software is ready-to-use (see enviroment and reproduce) in Windows XP, I just add that in my list.
If your are agree to bring your software to ready-to-use in Windows XP, I will add MSFL in my list.
SFML in my list means that project welcomes assistance (testing, guide editors and code writer).
What is actual case?

Please, do not close, if you requires guides for cases with Windows XP.

----

## Subject of the issue

...

## Your environment

I'm interested in next option:
1. Create apps on Windows XP with IDE (I use Code::Blocks) + SFML set.
2. Other Windows OS and IDE + SFML to create app for Windows XP.

## Steps to reproduce

1. Install Windows XP.
2. Install IDE to used SFML,
3. Code some app.
4. Build app.

## Expected behavior

We can create an app on Windows XP using SFML

## Actual behavior

Unknown

**Comment by ChrisThrasher** [comment]
SFML 3 will likely not work on XP. Older versions do work on XP but I'm not sure precisely which version is the latest that works on XP. Feel free to join the SFML Discord server or post on the forums if you have any more questions about how to get SFML running XP.

**Comment by eXpl0it3r** [comment]
SFML 2.6 should still run on Windows XP, but it's not really a platform we actively test for, but we also didn't intentionally remove code to break compatibility in SFML 2.x.

It's unfortunately rather unclear, what you're trying to communicate. You don't need our permission to add SFML to some list of tools that run on Windows XP, but we also won't be investing (much of) our time into helping anyone setting up SFML on Windows XP.
