### ISSUE TITLE
Android `sf::VideoMode::getDesktopMode()` returns wrong values (sort of)

### ISSUE THREAD

**Issue by Zombieschannel** [SFML/SFML#2396]
## Subject of the issue

So as described here: https://github.com/SFML/SFML/pull/1559
Currently, on Android, getDesktopMode() is returning the device resolution without the navigation bar. SFML however, draws over the navigation bar. This makes the app look stretched. With this pull request, the issue is fixed slightly. The resolution that getDesktopMode() returns is the actual resolution of the device. This works for older devices. The problem now is that almost all new Android devices have either a notch or a hole punch. Android allows developers to choose how they want their app to be displayed, that is either with the portion of the screen that the notch takes or without it. The resolution returned by getDesktopMode() is the full device resolution, therefore, if you choose to not draw over the notch/hole punch, the app becomes stretched again.

## Your environment

Android Studio 2022.1.1 on Windows 10
SFML 2.6.x branch
Used CMake, Ninja, Android NDK 25

## Steps to reproduce

```cpp
#include <SFML/Graphics.hpp>
int main()
{
    sf::RenderWindow window(sf::VideoMode::getDesktopMode(), "SFML works!");
    sf::CircleShape shape(100.f);
    shape.setFillColor(sf::Color::Green);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.draw(shape);
        window.display();
    }

    return 0;
}
```

## Expected behavior

Round circle.

## Actual behavior

Stretched circle on devices with a notch/hole punch.

**Comment by Zombieschannel** [comment]
Ok, so it seems like I was slightly wrong with this issue. It turns out that the window does get resized to the correct resolution, but only after a specific amount of time (anywhere between 0.5 and 2 seconds). This probably has to do something with the navigation bar, but I'm not sure. I am not familiar if there is a way to check if the device has a navigation bar with c++ (or how to remove it immediately when starting the app), so the best solution I found so far is to just wait those 2 seconds at the start.

```cpp
    sf::RenderWindow window(sf::VideoMode::getDesktopMode(), "SFML works!", sf::Style::Fullscreen);
    for (int i = 0; i < 4; i++)
    {
        for (sf::Event event; window.pollEvent(event);) {}
        sf::sleep(sf::seconds(0.5));
    }
```

**Comment by Zombieschannel** [comment]
Also, I am not sure if this is intentional, but the default view of the window stays the same when the window gets resized at the start. That is not that big of a deal though.

```cpp
    sf::View view;
    view.reset(sf::FloatRect(0, 0, window.getSize().x, window.getSize().y));
    window.setView(view);
```

**Comment by eXpl0it3r** [comment]
Do you get a resize event after the mentioned time?

Like is it an actual "window" resize that happens?

Wonder if there's just some Activity settings that we can specify for a different behavior. 🤔

**Comment by Nathan-M-code** [comment]
In my case I have one sfml resize event
```cpp
for (int i = 0; i < 4; i++)
    {
        for (sf::Event event; m_renderWindow.pollEvent(event);) {
            if(event.type == sf::Event::EventType::Resized){
                LOG_INFO(logger, "Window resized");
            }
        }
        sf::sleep(sf::seconds(0.5));
    }
```

In the logs:
`06-06 17:28:34.558  3671  3734 I FC      : 17:28:34.558283618 INFO      Application.cpp:49 Window resized`

**Comment by eXpl0it3r** [comment]
Maybe, all that it takes is some additional flags at:

https://github.com/SFML/SFML/blob/e39f48742b702400424db46f3b28e8a09459ca38/src/SFML/Main/MainAndroid.cpp#L202

Anyone know what's the official documentation for these flags?  
I only ended up in some C# Android documentation. There they listed `SystemUiFlagLayoutHideNavigation` and `SystemUiFlagLayoutFullscreen`

**Comment by eXpl0it3r** [comment]
Any further insights on this @Zombieschannel?

I'd like to release SFML 2.6.2 soon, so if you think there's a way to fix it, I'm happy to include it.
