### ISSUE TITLE
Replace cmake/Modules/FindFreetype.cmake with CMake-provided module

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2399]
## Subject of the issue

CMake already provides a FindFreetype module so we should try to use that instead of keeping our own copy of it. As far as I can tell we don't to make any custom mods to get it to work so this should be theoretically possible. It also has the benefit of letting us use the `Freetype::Freetype` target it provides instead of having to use an un-namespaced library.

https://cmake.org/cmake/help/latest/module/FindFreetype.html

**Comment by ChrisThrasher** [comment]
For reasons I don't understand, we can't use the `Freetype::Freetype` target. We're using `CMAKE_LIBRARY_PATH` so that the `find_library` call within FindFreetype.cmake will find our macOS Freetype framework in extlibs/. However there's a weird issue with imported targets (`Freetype::Freetype` is an `IMPORTED` target) not understanding how to link frameworks. Hopefully there's a viable solution so that we can use more imported targets and fewer custom Find modules.

For now we can delete our copy of FindFreetype.cmake but we still must create our own non-`IMPORTED` `Freetype` target so that linking frameworks doesn't fail.

@friendlyanon Do you know what may be going on here?

**Comment by ChrisThrasher** [comment]
Here are some relevant links. I still can't figure out if this is a CMake bug or if we're doing something wrong. It sounds like in the past this used to work.

https://gitlab.kitware.com/cmake/cmake/-/issues/18753

https://gitlab.kitware.com/cmake/cmake/-/issues/19410

**Comment by ChrisThrasher** [comment]
```cmake
cmake_minimum_required(VERSION 3.25)
project(freetype_test)

list(APPEND CMAKE_INCLUDE_PATH ~/Projects/sfml/extlibs/headers/)
list(APPEND CMAKE_LIBRARY_PATH ~/Projects/sfml/extlibs/libs-osx/Frameworks/)
find_package(Freetype REQUIRED)

add_executable(main main.cpp)
target_link_libraries(main PRIVATE Freetype::Freetype)
```

Here's a sample project to demonstrate this failure. Change the two paths to reflect where extlibs/ lives on your machine.

**Comment by Akylzhan** [comment]
@ChrisThrasher it works on WSL2, cmake version is 3.25.2

**Comment by ChrisThrasher** [comment]
In writing #2666 I realized that we have to use our own modified FindFreetype.cmake to support finding frameworks. Once CMake 3.28 ships and we can start depending on it then we can use the upstream FindFreetype.cmake.
