### ISSUE TITLE
OpenGL extension string is sometimes null causing crash

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2403]
## Subject of the issue

The `glGetStringFunc` call [here](https://github.com/SFML/SFML/blob/master/src/SFML/Window/GlContext.cpp#L278) sometimes returns null. According to [the OpenGL docs](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glGetString.xhtml) this indicates an error is occurring. This has caused issues with in-development tests for `sf::Texture` and `sf::VertexBuffer`. See a failing CI run [here](https://github.com/ChrisThrasher/SFML/actions/runs/4157535248/jobs/7192096471).

Adding an assertion catches this error but doesn't get us any closer to fixing the underlying issue. It may still be worth merging this for the sake of avoiding UB.

https://github.com/ChrisThrasher/SFML/commit/bdf2f9b1e38b3efcfde004aa2b92ea3658f208a1

**Comment by jeremyelalouf** [comment]
Hello @ChrisThrasher,

This issue still need some work to be done ?
I would love to contribute to SFML as my first open source contribution.

**Comment by ChrisThrasher** [comment]
Not sure if there is anything else to do about this issue so I'm closing it.
