### ISSUE TITLE
Add a function to set window size limit

### ISSUE THREAD

**Issue by OwlHowlinMornSky** [SFML/SFML#2406]
In `Window` module, it will be more convenient if add a function to set min/max size of window.

Windows provide a message named [WM_GETMINMAXINFO](https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-getminmaxinfo), and we can use lParam to simply limit a window's size.
Just use two `sf::Vector2u`s to store the setted minimum and maximum, and post them when get WM_GETMINMAXINFO.

I've only considered this problems about Windows. I'm sorry if it will cause any problem of crossing platform.

**Comment by eXpl0it3r** [comment]
I assume this will then not even allow change the window size to a smaller or larger size?

So you wouldn't need to handle the resize event and re-set the window size when it drops below or goes above a certain value, correct?

**Comment by OwlHowlinMornSky** [comment]
It's close.

More clearly, I don't want that a window drops below or goes above the setted value while user is dragging.
I scanned the code in `WindowImplWin32.cpp`, and saw
```cpp
// The system request the min/max window size and position
case WM_GETMINMAXINFO:
{
    // We override the returned information to remove the default limit
    // (the OS doesn't allow windows bigger than the desktop by default)
    MINMAXINFO* info = reinterpret_cast<MINMAXINFO*>(lParam);
    info->ptMaxTrackSize.x = 50000;
    info->ptMaxTrackSize.y = 50000;
    break;
}
```

But Windows 11 doesn't stop windows going larger than the desktop. This leads to a real maximum of 50000 * 50000 pixels.
I'd like to change this to
```cpp
MINMAXINFO* info = reinterpret_cast<MINMAXINFO*>(lParam);
if (m_windowMaxTrackSize.x > 0)
    info->ptMaxTrackSize.x = m_ windowMaxTrackSize.x;
if (m_windowMaxTrackSize.y > 0)
    info->ptMaxTrackSize.y = m_ windowMaxTrackSize.y;
if (m_windowMinTrackSize.x > 0)
    info->ptMinTrackSize.x = m_ windowMinTrackSize.x;
if (m_windowMinTrackSize.y > 0)
    info->ptMinTrackSize.y = m_ windowMinTrackSize.y;
```
and `m_windowMinTrackSize` and ` m_windowMaxTrackSize ` are two `sf::Vector2u`s which can be changed by a function in class `sf::WindowImpl`.
