### ISSUE TITLE
Single SFML Library

### ISSUE THREAD

**Issue by xrModder** [SFML/SFML#2407]
Compiling SFML into a single library file, something like SFML.dll and SFML.lib (Windows).

**Comment by ChrisThrasher** [comment]
What's the intended use case for this feature?

**Comment by xrModder** [comment]
> What's the intended use case for this feature?

Possibility to compile the library into one file (as it was done with SDL2).

Sorry for my english (I write through a translator).

**Comment by ChrisThrasher** [comment]
What benefit would this have over the status quo of having 5 separate libraries?

**Comment by xrModder** [comment]
> What benefit would this have over the status quo of having 5 separate libraries?

It is not comfortable.

**Comment by ChrisThrasher** [comment]
We can discuss the possibility of having a single `SFML::SFML` CMake target which links to the current 5 libraries, but if you want a single .dll then that would require building all code into a single library which is not something we're willing to do.

**Comment by Bromeon** [comment]
> It is not comfortable.

If you want to change something that big, please spend at least the time to provide a rationale for the change. 

Also, this topic has been discussed a few times before and rejected each time. Please show that you've understood the arguments and bring something new to the discussion.

**Comment by eXpl0it3r** [comment]
There's always a way to do it, but we won't be officially supporting or publishing binaries in such a way.

The simplest approach is to use CMake (e.g. with the [SFML CMake Template](https://github.com/SFML/cmake-sfml-project)) that way you don't have to manually click around to get SFML linked properly.
