### ISSUE TITLE
Tests using `xvfb-run` are flakey

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2408]
## Subject of the issue

As of the merging of #2405 the Linux jobs sometimes fail with the message "Failed to open X11 Display".

https://github.com/SFML/SFML/actions/runs/4161050116/jobs/7198613947#step:9:280

We're not alone in this. I found one other project experiencing a similar with no known fix.

https://github.com/maplibre/maplibre-gl-native/issues/720

My only tentative idea is to go back to disabling these tests on Linux to avoid the flakiness while letting macOS and Windows keep running them. Or maybe we allow these build jobs to get re-ran once if they fail.

**Comment by ChrisThrasher** [comment]
Fixed by #2412

**Comment by eXpl0it3r** [comment]
Ah, I thought you may want to keep this open, until we've actually found a fix for the flakiness of Xvfb, then again, we don't even know if there is a "fix".

**Comment by ChrisThrasher** [comment]
> Ah, I thought you may want to keep this open, until we've actually found a fix for the flakiness of Xvfb, then again, we don't even know if there is a "fix".

I think you're right. I want to keep this issue open for the `xvfb-run` problems. I'm holding out hope that a fix will appear one day.

**Comment by louwers** [comment]
@ChrisThrasher Wonder what the fix was.

**Comment by ChrisThrasher** [comment]
> @ChrisThrasher Wonder what the fix was.

https://github.com/SFML/SFML/issues/2408#issuecomment-1435906897
