### ISSUE TITLE
Use SPDX to simplify copyright headers

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2416]
## Subject of the issue

https://spdx.dev 

SPDX is a standard for specifying software licenses. It lets us continue to keep copyright information in each text file but lets us do it with drastically fewer lines of code. This format is machine-readable in a way that makes SFML easier to analyze by 3rd parties who want to programmatically query its license. It means developers don't have to scroll down as far in the file to start seeing real code. Their screens won't be filled with license comments quite so much.

Here are two examples of this in practice from SerenityOS and the Microsoft STL:

https://github.com/SerenityOS/serenity/blob/master/AK/AllOf.h
https://github.com/microsoft/STL/blob/main/stl/inc/array

Inspired by this CppCon 2019 talk:

https://youtu.be/_5weX5mx8hc?t=763 (timestamped link to relevant portion)

---

Before and after

```cpp
////////////////////////////////////////////////////////////
//
// SFML - Simple and Fast Multimedia Library
// Copyright (C) 2007-2023 Laurent Gomila (laurent@sfml-dev.org)
//
// This software is provided 'as-is', without any express or implied warranty.
// In no event will the authors be held liable for any damages arising from the use of this software.
//
// Permission is granted to anyone to use this software for any purpose,
// including commercial applications, and to alter it and redistribute it freely,
// subject to the following restrictions:
//
// 1. The origin of this software must not be misrepresented;
//    you must not claim that you wrote the original software.
//    If you use this software in a product, an acknowledgment
//    in the product documentation would be appreciated but is not required.
//
// 2. Altered source versions must be plainly marked as such,
//    and must not be misrepresented as being the original software.
//
// 3. This notice may not be removed or altered from any source distribution.
//
////////////////////////////////////////////////////////////
```

```cpp
////////////////////////////////////////////////////////////
//
// Copyright (c) 2007-2023 Laurent Gomila (laurent@sfml-dev.org)
// SPDX-License-Identifier: Zlib
//
////////////////////////////////////////////////////////////
```

**Comment by metaquarx** [comment]
FSF Europe have made a recommendation about this here: https://reuse.software/

As part of the project, they've also made a [tool](https://github.com/fsfe/reuse-tool) to help checking compliance. Heres an example output on their own repository:

```
$ reuse lint
# SUMMARY

* Bad licenses:
* Deprecated licenses:
* Licenses without file extension:
* Missing licenses:
* Unused licenses:
* Used licenses: Apache-2.0, CC-BY-SA-4.0, CC0-1.0, GPL-3.0-or-later
* Read errors: 0
* Files with copyright information: 81 / 81
* Files with license information: 81 / 81

Congratulations! Your project is compliant with version 3.0 of the REUSE Specification :-)
```

**Comment by Bromeon** [comment]
```cpp
// 3. This notice may not be removed or altered from any source distribution.
```
_Strictly_ speaking, we violate the license if we remove this header -- even if the semantics are the same.

Also, I think `SFML - Simple and Fast Multimedia Library` was very intentionally placed in the header.

**Comment by eXpl0it3r** [comment]
I'd rather keep it as is.

**Comment by ChrisThrasher** [comment]
> I'd rather keep it as is.

Okay the you may close this issue

**Comment by ChrisThrasher** [comment]
Closed for lack of consensus
