### ISSUE TITLE
RenderTexture flipped on Android

### ISSUE THREAD

**Issue by Zombieschannel** [SFML/SFML#2419]
## Subject of the issue

Basically, when using render textures on Android, the image gets flipped (for some reason), however on Windows this works normally.
Images of the code below:

Windows 10

![image](https://user-images.githubusercontent.com/54750550/219801780-24e22edf-debb-44a9-9338-ff0fda366e60.png)

Android 8 and Android 13

![image](https://user-images.githubusercontent.com/54750550/219801830-cd3ebc49-f0a7-4d34-9ce9-5043b09fb9f5.png)

## Your environment

Android Studio 2022.1.1 on Windows 10
SFML 2.6.x branch
Used CMake, Ninja, Android NDK 25

## Steps to reproduce

```cpp
#include <SFML/Graphics.hpp>
int main()
{
    sf::RenderWindow window(sf::VideoMode::getDesktopMode(), "SFML works!", sf::Style::Fullscreen);
    window.setFramerateLimit(10);

    sf::CircleShape circle(400.f);
    sf::RectangleShape corner;
    sf::RectangleShape screen;
    circle.setFillColor(sf::Color::Green);
    corner.setSize(sf::Vector2f(400, 400));

    sf::RenderTexture texture;
    texture.create(window.getSize().x, window.getSize().y);
    texture.clear();
    screen.setSize((sf::Vector2f)window.getSize());

    sf::Texture t;

    bool active = window.hasFocus();
    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            switch (event.type)
            {
            case sf::Event::Closed:
                window.close();
                break;
            case sf::Event::LostFocus:
                window.setActive(0);
                active = 0;
                break;
            case sf::Event::GainedFocus:
                window.setActive(1);
                active = 1;
                break;
            case sf::Event::KeyReleased:
                if (event.key.code == sf::Keyboard::Escape)
                    window.close();
                break;
            }
        }
        if (!active)
            continue;
        t = texture.getTexture();
        corner.setTexture(&t);

        texture.clear();
        texture.draw(circle);
        texture.draw(corner);
        texture.display();
        screen.setTexture(&texture.getTexture());

        window.clear();
        window.draw(screen);
        window.display();

    }
}
```

## Expected behavior

As mentioned above, the texture should not get flipped.

## Actual behavior

On Android the texture that we got from rendertexture.getTexture() gets flipped.

**Comment by Nathan-M-code** [comment]
Facing the same issue on Android 13 - Samsung Galaxy A54, is a bug fix considered ?

**Comment by eXpl0it3r** [comment]
> Facing the same issue on Android 13 - Samsung Galaxy A54, is a bug fix considered ?

Just to double check, are you calling `display()` on the render texture?

**Comment by texus** [comment]
RenderTexture itself seems to work fine on Android. The image however gets flipped when copying the texture, which happens in the provided example code at the `t = texture.getTexture();` line. After the texture is copied, it is flipped even when `display()` is called on the render texture.

I think the issue is in `Texture::copyToImage()`, which gets called from `Texture::update` when SFML_OPENGL_ES is defined. The code that gets executed in copyToImage when SFML_OPENGL_ES is defined doesn't access m_pixelsFlipped at all (unlike the desktop OpenGL implementation). I'm currently testing my hypotheses and will send a PR is that is where the issue lies.

**Comment by eXpl0it3r** [comment]
@Zombieschannel / @Nathan-M-code can you try #2719?

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/pull/2730

@Zombieschannel could you please test this PR?
