### ISSUE TITLE
Add right, bottom properties to sf::Rect

### ISSUE THREAD

**Issue by vagra** [SFML/SFML#2431]
## Add right, bottom properties to sf::Rect

sf::Rect have left, top, width, height 4 properties, but I still need right and bottom properties.

## environment
* version of SFML: 2.5.0

## example
```cpp
void Actor::setRegion(int width, int height) {
	region.left = BORDER;
	region.top = BORDER;
        region.width = width - BORDER * 2;
        region.height = height - BORDER * 2;
}
```
if have right and bottom properties:
```cpp
void Actor::setRegion(int width, int height) {
	region.left = BORDER;
	region.top = BORDER;
        region.right = width - BORDER;
        region.bottom = height - BORDER;
}
```

**Comment by eXpl0it3r** [comment]
We don't have plans to add this, as it would lead to a less clear API and it's really not a burden for the user to do some "extra" math in some cases.

Currently the API is defined as (left, top) + (width, height) with mirroring getPosition() + getSize() functions. This is very clear and easy to understand API. Adding more accessors will make the API more confusing and less concise. Additionally, you could end up with `right` and `bottom` being to the left and top of `left` and `top`, which is a lot more confusing that having a negative `width` or `height`.
