### ISSUE TITLE
2.6: XOpenIM call fails due to code that alters the locale

### ISSUE THREAD

**Issue by crumblingstatue** [SFML/SFML#2443]
## Subject of the issue

On the 2.6 branch, there is a `OpenXIM` function to open the X11 input method.
It contains code that alters the locale for reasons unknown to me.
This causes the call to `XOpenIM` to fail (return null), breaking unicode input.
If I remove the code that alters the locale, `XOpenIM` succeeds.

## Your environment

* Arch Linux / openbox / Xorg 21.1.7
* 2.6.x branch
* GCC 12.2.1

## Steps to reproduce

Run any code that opens a window

## Expected behavior

Opening the X11 input method should succeed, like in previous SFML versions.

## Actual behavior

Opening  the input method fails, unicode input breaks.

**Comment by crumblingstatue** [comment]
Okay, bizarrely, if I comment out the `XSetLocaleModifiers("")` call, then `XOpenIM` works.
Even though if I print the previous value (as returned by `XSetLocaleModifiers(NULL)`), that returns an empty string as well, so theoretically this shouldn't change anything.

**Comment by kimci86** [comment]
> It contains code that alters the locale for reasons unknown to me.

Maybe @Edgaru089 can provide some insight.

> Opening the X11 input method should succeed, like in previous SFML versions.

Note that opening X11 input method was not implemented in previous SFML versions. It was added in #1850.

> Opening the input method fails, unicode input breaks.

What does "unicode input breaks" mean?

**Comment by crumblingstatue** [comment]
> Note that opening X11 input method was not implemented in previous SFML versions. It was added in https://github.com/SFML/SFML/pull/1850.

`XOpenIM` was called even in 2.5.x. See https://github.com/SFML/SFML/blob/2.5.x/src/SFML/Window/Unix/WindowImplX11.cpp#L1548
This is the call that breaks in 2.6.

> What does "unicode input breaks" mean?
If I enter a  non-ascii character on the keyboard, the `TextEntered` event won't contain the proper unicode character.

**Comment by ChrisThrasher** [comment]
Do we know which commit introduced this problem? Was it #1850 or something else?

**Comment by Edgaru089** [comment]
Man page `setlocale(3)`:

> On startup of the main program, the portable "C" locale is selected as default. A program may be made portable to all locales by calling: `setlocale(LC_ALL, "")`.

So ```setlocale(LC_ALL, "")``` returns ```C``` as the default locale so without it ```XSetLocaleModifiers``` cannot set X modifiers with the correct locale and thus should not be able to handle (most) Unicode. `setlocale(LC_ALL, "")` resets all locales from the environment variables and is required AFAIK.

Man page `XSupportsLocale(3)`:
> The XSetLocaleModifiers function sets the X modifiers for the current locale setting. The modifier_list argument is a null-terminated string of the form “{\@category=value}” ... The  local host X locale modifiers announcer (on POSIX-compliant systems, the **XMODIFIERS** environment variable) is appended to the modifier_list to provide default values on the local host.

Some IME frameworks require you to set a environment variable like `XMODIFIERS=@im=fcitx`, and this gets appended to the empty string in the `XSetLocaleModifiers("")` call, setting the `@im` modifier. Example: [ArchWiki: Fcitx5](https://wiki.archlinux.org/title/Fcitx5#Integration). Also from the same manpage:

>  At program startup, the modifiers that are in effect are unspecified until the first successful call to set them.

So we should call `XSetLocaleModifiers` before opening the XIM context.

---

@crumblingstatue, what kind of setup do you have? Do you have any IMEs installed? Referring to your previous message:

> Okay, bizarrely, if I comment out the `XSetLocaleModifiers("")` call, then `XOpenIM` works.

You might have `XMODIFIERS` set in your environment? You can also try setting `XMODIFIERS=@im=none` to disable IMEs, or just set `LANG=C` and see what happens.

**Comment by crumblingstatue** [comment]
You're correct, I do have XMODIFIERS set. I used to use a Japanese input method, but it didn't work correctly so I uninstalled it, but I forgot to unset it afterwards.
I'll remove it when I get home and test it without it set.

**Comment by crumblingstatue** [comment]
I apologize, I completely forgot to test with `XMODIFIERS` unset.
The problem does not occur in that case.
I apologize for the inconvenience.
