### ISSUE TITLE
Why there is no Vulkan support for MacOS in SFML 3.0?

### ISSUE THREAD

**Issue by MihlanDOta** [SFML/SFML#2444]
I looked into the source code of the Window module for OS X and I didn't find a Vulkan implementation file there. I think everyone knows about the existence of MoltenVK, why not implement Vulkan functionality for macOS and iOS? This will significantly increase the library's performance on Apple platforms.

**Comment by Bambo-Borris** [comment]
SFML doesn't use Vulkan as a backend, it still uses OpenGL. The Vulkan code you see is examples of using SFML just for windowing, and writing your own Vulkan rendering code.

**Comment by MihlanDOta** [comment]
Ok. I would like to see the possibility of creating a Vulkan window for
macOS. 

P.S. Apparently I inattentively read the roadmap(https://en.sfml-dev.org/forums/index.php?topic=24372.0), seeing there "Setup for multiple rendering backends"

**Comment by ChrisThrasher** [comment]
It would be nice to have but the work to get there will be significant so don't expect it to happen in the near future.

**Comment by eXpl0it3r** [comment]
Re-implementing a renderer isn't a trivial task, doing so for Vulkan is an even bigger task. It's inevitable that Vulkan support will come, as it essentially superseded OpenGL, but the path there is undefined and will take a while.

See also on going discussions here: #2423
