### ISSUE TITLE
Toggling fullscreen + window.setTitle == system locks up (on Linux)

### ISSUE THREAD

**Issue by danieljpetersen** [SFML/SFML#2454]
## Subject of the issue

Calling window.setTitle in conjunction with creating a new window causes my entire system to lock up. No idea if this happens on other distributions of Linux, or if it happens on other OS's.

I also don't know if this happens with just toggling from fullscreen, it's possible that any call to window.create() in conjunction with setWindowTitle will cause the lockup. I've had to restart my PC like 10+ times in tracking this down and I don't want to restart any more to figure that out at the moment. 

## Your environment

* Linux Mint Cinnamon 21.1 -- Cinnamon Version 5.6.7, kernel version 5.15.0-67-generic
* SFML 2.6 and SFML 3.0
* gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

## Steps to reproduce

```cpp
#include <SFML/Graphics.hpp>

int main()
{
	std::string appTitle = "Toggle Fullscreen + Window.setTitle(...) == lockup";
	sf::RenderWindow window(sf::VideoMode({800, 600}), appTitle, sf::Style::Default, sf::ContextSettings(0, 0, 16));
	window.setVerticalSyncEnabled(true);

	bool isFullscreen = false;
	bool toggleFullscreen = false;
	while (window.isOpen())
	{
		sf::Event event;
		while (window.pollEvent(event))
		{
			if (event.type == sf::Event::Closed)
			{
				window.close();
			}

			if (event.type == sf::Event::KeyReleased)
			{
				if (event.key.code == sf::Keyboard::Enter)
				{
					if (event.key.alt)
					{
						toggleFullscreen = true;
					}
				}
			}
		}

		if (toggleFullscreen)
		{
			toggleFullscreen = false;
			isFullscreen = !isFullscreen;

			window.close();
			if (isFullscreen)
			{
				window.create(sf::VideoMode::getDesktopMode(), appTitle, sf::Style::Fullscreen, sf::ContextSettings(0, 0, 16));
			}
			else
			{
				window.create(sf::VideoMode({800, 600}), appTitle, sf::Style::Default, sf::ContextSettings(0, 0, 16));
			}
		}

		window.clear();
		window.display();
		window.setTitle(appTitle);
	}

	return 0;
} 
```

**Comment by wyatthuckaby** [comment]
Does it do this when running `window.SetTitle(appTitle)` before entering the loop?

**Comment by danieljpetersen** [comment]
Yeah, I agree that it's likely that this does have something to do with being set repeatedly in a loop. I feel like that should be supported though, I've seen apps in the wild which update the window title every frame. 

I think more investigation is needed though, because I was also able to trigger it via waiting for > 1 second after the toggle for the setTitle calls, and it still locked up my system.

**Comment by danieljpetersen** [comment]
Thanks for checking the issue out and posting. What's strange though is that I was using vsync + display in my initial tests. This makes me think that it's overwhelming the OS and maybe the threshold at which the OS is overwhelmed is dependent on hardware, where maybe my hardware couldn't handle the 60 FPS case from vsync and yours could?

**Comment by eXpl0it3r** [comment]
To some degree OS API calls shouldn't be able to cause a denial of service attack on the whole OS, so maybe there isn't really something SFML should do. On the other hand, due to the async nature of the X11 protocol, maybe we can add a check, that finds pending requests of a similar type and either replace the existing request or at least not trigger a new one.

If anyone feels like diving into the source and figuring out how the existing code does the title changes.

**Comment by kimci86** [comment]
> What's strange though is that I was using vsync + display in my initial tests.

You enable VSync on your window only the first time you create it. When you close it an recreate it, the setting is lost.

**Comment by danieljpetersen** [comment]
Good catch, that makes sense. I just tested via placing a call to set vsync after the toggling and it no longer locks up. So paul-gangneux is correct, this only happens with an overwhelming amount of frames per second, probably a number so high no real user is going to run into the issue.

**Comment by danieljpetersen** [comment]
Given that it may make sense to close this issue.

**Comment by eXpl0it3r** [comment]
While I see that it's an issue, it also seems like something an user can easily prevent in addition to that the OS API shouldn't be able to fully lock up a system just due to too many requests.

I don't really see us adding a check with added complexity for an unlikely use case. As such I'll close the issue for now, but happy to re-open if this is a re-occuring issue.
