### ISSUE TITLE
Use `IMPORTED` libraries for vendored dependencies instead of `INTERFACE` libraries

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2459]
## Subject of the issue

This will make `sfml_find_package` more similar to have `find_package` works which conventionally will give you an `IMPORTED` library. `IMPORTED` libraries are libraries which already exist on your system somewhere and you're merely creating a target for them which is exactly what we're doing. We're not trying to create any libraries that don't already exist. We just want a target for an existing pair of link libraries and include directories.

I've attempted this before and it gets messy because `sfml_find_package` also has some special behavior for iOS. This is one step towards being able to get rid of `sfml_find_package` in lieu of merely using `find_package`.

**Comment by ChrisThrasher** [comment]
https://github.com/ChrisThrasher/SFML/commit/d16af6a8c970030f3d602dbbdb3e77f14e13d49e

#2359 makes some simplifications that let me inline all of `sfml_add_external` which takes us one step towards a less janky dependency management story and being able to use `IMPORTED` targets.

**Comment by JonnyPtn** [comment]
This somewhat relates to the problem with the openAL dll not being added to `TARGET_RUNTIME_DLLS` - if we use an imported library and set the imported properties correctly then it will be added to that list

**Comment by ChrisThrasher** [comment]
See #2650 for some meaningful progress on this. I replaced 6 `INTERFACE` libraries with `IMPORTED` targets.

**Comment by ChrisThrasher** [comment]
I was able to complete this :)
