### ISSUE TITLE
Use `std::char32_t` for UTF-32 character type in `sf::String`

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2470]
## Subject of the issue

https://en.cppreference.com/w/cpp/language/types#char32_t

I admittedly have no experience with non-ASCII strings but `std::char32_t` appears to be the modern C++ type we ought to use to represent a single character of a UTF-32 string. If you use a UTF-32 string literal, you get a pointer to this type which means users using UTF-32 string literals have to do a reinterpret_cast to use it with `sf::String`. It also means that strongly type string literals like `U"\U00104321"s` cannot be used with the `String(const std::basic_string<std::uint32_t>& u32String)` constructor since they're of type `std::u32string`, another C++11 type not accessible prior to SFML 3.

Perhaps we should implement `sf::String` in terms of `std::u32string` but that's a separate matter.

EDIT: This change would all but require we also implement `sf::String` in terms of `std::u32string`.

**Comment by Bromeon** [comment]
Good idea, I agree that `char32_t` is better suited than `uint32_t`.

> Perhaps we should implement `sf::String` in terms of `std::u32string` but that's a separate matter.

Why separate? `u32string` is defined as `basic_string<char32_t>`, so would probably make sense to modify the member variable's type in the same change. Otherwise we end up with `reinterpret_cast` in every function 🤔

**Comment by ChrisThrasher** [comment]
> Why separate? `u32string` is defined as `basic_string<char32_t>`, so would probably make sense to modify the member variable's type in the same change. Otherwise we end up with `reinterpret_cast` in every function 🤔

Good point. I think you're right.

**Comment by ChrisThrasher** [comment]
https://github.com/ChrisThrasher/SFML/commit/5be08aec9f5f64e8f8b1ea12cfdc672faf941782

The transition is pretty simple. I also used `std::u16string` but we can't yet use `std::u8string` since that's a C++20 feature.
