### ISSUE TITLE
Finish supporting move semantics

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2483]
Here are the types that still lack move semantics or have incomplete support for it. Some of these types may not apply but they're listed regardless until we decide to not bother.

The addition of move operations constitutes a new feature and not an API break so we're free to keep working on this after 3.0.0 ships.

Window:
- [ ] `sf::Context` (https://github.com/SFML/SFML/pull/2805)
- [x] `sf::Cursor` (https://github.com/SFML/SFML/pull/2487 https://github.com/SFML/SFML/pull/2525)
- [ ] `sf::GlResource`
- [ ] `sf::Window` (https://github.com/SFML/SFML/pull/2529)
- [ ] `sf::WindowBase` (https://github.com/SFML/SFML/pull/2529)

Graphics:
- [x] `sf::Drawable`
- [x] `sf::RenderTarget` (https://github.com/SFML/SFML/pull/2656)
- [x] `sf::RenderTexture` (https://github.com/SFML/SFML/pull/2656)
- [x] `sf::VertexBuffer`

Network:
- [ ] `sf::Ftp`
- [ ] `sf::Http`
- [x] `sf::Socket` (https://github.com/SFML/SFML/pull/2658)
- [x] `sf::SocketSelector`
- [x] `sf::TcpListener` (https://github.com/SFML/SFML/pull/2658)
- [x] `sf::TcpSocket` (https://github.com/SFML/SFML/pull/2658)
- [x] `sf::UdpSocket` (https://github.com/SFML/SFML/pull/2658)

Audio:
- [ ] `sf::AlResource` (https://github.com/SFML/SFML/pull/2541)
- [ ] `sf::Music`
- [ ] `sf::Sound`
- [ ] `sf::SoundBuffer`
- [ ] `sf::SoundBufferRecorder`
- [ ] `sf::SoundRecorder`
- [ ] `sf::SoundSource`
- [ ] `sf::SoundStream`

**Comment by shakedechn** [comment]
Hey @ChrisThrasher. How would a contributor go about taking one of these? Should I ask here to take one and declare which one, or is there a dedicated place on the forums?

**Comment by ChrisThrasher** [comment]
You don't need to ask for permission. Start working on a class and if you think you have a viable implementation then submit a PR.

**Comment by boothr16** [comment]
Hello @ChrisThrasher, would this be a good contribution for someone who is new to SFML but familiar with move semantics and modern C++ practices? There are currently no issues labeled "good first issue." Thanks!

**Comment by ChrisThrasher** [comment]
You're welcome to give it a shot, but be forewarned that it may not be easy. We've been adding move semantics starting with the easiest types first so the remaining types require custom implementations to be correct.

**Comment by ChrisThrasher** [comment]
A few thoughts on move semantics:

1. Adding move semantics to a type constitutes a new feature. It's backwards compatible. It's about adding functionality that was not previously present.
2. Features ought to be added with a rationale. Let's not add features if we can't show why they're useful.
3. Add move semantics to SFML types with non-default destructors is historically difficult and error prone. We get it wrong more often than we get it right.
4. We don't have a rational for moving many of these types. It might be nice to have but the rationale needs to be stronger than "wouldn't it be neat?".

Therefore

5. Let's stop spending so much time working on move semantics.

I'm closing this issue because I think we've completed our mission of SFML 3 making a good-faith effort towards supporting C++11 move semantics. Future PRs adding move semantics may be entertained by they are not encouraged. Such PRs need to present a compelling rationale for why this extra development work is worth doing.
