### ISSUE TITLE
Repeated xlib errors when compiling and executing simple C++/SFML program

### ISSUE THREAD

**Issue by hbhutta** [SFML/SFML#2521]
## Your environment

* Using Linux PopOS
* SFML version 2.5.1
* Right now I am using `g++` to compile, but I also have `gcc`; here are their versions:
![image](https://user-images.githubusercontent.com/112280419/232255823-3bc05763-274e-40de-bce5-efe3601c2061.png)

* Compilation command is: `g++ game_from_Weiqi-SFML.cpp -o game_from_Weiqi-SFML -lsfml-graphics -lsfml-window -lsfml-system`

## Steps to reproduce
Here is the [code](https://pastebin.com/iRjMFiHW) that is causing this. Often, compiling and executing the program will *sometimes* and *sometimes not* create this Xlib issue. This means I can run the exact same code, without any changes, and there is a fifty-fifty chance that I will or will not get the Xlib errors and the warning in the terminal.

## Expected behavior

What should happen is the window should display, no matter what changes I make to my sprites, shapes, etc.. (as long as these changes are valid; they are). For example, in the drawHorizontalLine() function, if I want to draw let's say 23 lines instead of 19, the window all of a sudden will not display and will give my the Xlib error

## Actual behavior

What actually happens is that the the warning below and the Xlib errors mentioned above display in the terminal:
![image](https://user-images.githubusercontent.com/112280419/232255641-c0945310-9769-448e-9284-96b78faccbaa.png)
![image](https://user-images.githubusercontent.com/112280419/232255851-7cb5240a-cea0-4435-9960-b6c14a5e36cc.png)

**Comment by eXpl0it3r** [comment]
Seems to be a [Xlib error](https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/176). They reverted already some change. I guess the only way around is to wait for an Xlib update or downgrade to a previous version.

**Comment by hbhutta** [comment]
How do I downgrade to a previous version? That would not affect anything related to rendering, would it?

**Comment by eXpl0it3r** [comment]
Someone just pointed out that your code is actually buggy, because you're passing `SETTINGS` to the `window` before it's initialized. Your compiler should actually be throwing a bunch of warnings at you for that if you'd enable any.

Members in a class are initialized in order of declaration, so since the settings comes after the window, it's not initialized, but you're already using it in the window constructor.

**Comment by kimci86** [comment]
This specific mistake can be detected with [`-Wreorder`](https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html#index-Wreorder) option. You can use [`-Wall`](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wall) option to enable it and a bunch of useful other warnings too.
