### ISSUE TITLE
Use .hpp extension for Objective-C++ files

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2524]
## Subject of the issue

https://github.com/SFML/SFML/tree/master/src/SFML/Window/OSX

Some files in the above directory use an .h extension but contain C++ code. I believe that's an oversight and we actually meant to use .hpp. In general I believe we only use Objective-C++ and have no files where we truly want to be using Objective-C.

**Comment by eXpl0it3r** [comment]
Is it just some or all of them? I could see that we differentiate ObjC with .h & .mm

**Comment by ChrisThrasher** [comment]
At least some of the `.h` files contain C++ code. Maybe one or more of them _technically_ applies as Objective-C. In either case do we _mean_ to use Objective-C? Is there anywhere we intentionally use ObjC over ObjC++?

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/search?l=objective-c

GitHub will list all the Objective-C files for us. I think examples/cocoa/main.m is the only file that doesn't actually use C++ features and keep its Objective-C filename extension. All others directly or transitively include C++ headers and thus ought to be classified as Objective-C++ code.

**Comment by ChrisThrasher** [comment]
https://github.com/ChrisThrasher/SFML/commit/e578fb1af1377a320d641bee1ab2639f8c52a0c4

I found all the files that use C++ features and added a `.hpp` extension. A few headers in src/SFML/Window/OSX don't use any C++ features so I kept their `.h` extension.

**Comment by ChrisThrasher** [comment]
Closed for lack of enthusiasm to bother figuring out what the most correct solution is
