### ISSUE TITLE
Incorrect endian reading

### ISSUE THREAD

**Issue by AN3Orik** [SFML/SFML#2530]
Hi  there,
Server send  this data  to client  (SFML packet  wrapper  in my case)
`02 00 18 00 02 00 0b 00 62 2b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 59 64 7c  ........b+...............Yd|`

But when i'm trying  to read first 2 bytes  to uint16 (like a packet  >> uint16variable) i got  521, not a 2.
I can't find where  at sf::Packet i can change endianness, and don't know it's even possibly.
Ty in advance.

**Comment by ChrisThrasher** [comment]
> I can't find where at sf::Packet i can change endianness

https://github.com/SFML/SFML/blob/a21c3c101cd02e41b79ffc515f93c649e230e263/src/SFML/Network/Packet.cpp#L167

Functions like `htons` is how endianness is converted between host ordering and networking ordering. `sf::Packet` should be handling endianness for you.
