### ISSUE TITLE
Expose anti-aliasing activation in sf::Font

### ISSUE THREAD

**Issue by LaurentGomila** [SFML/SFML#254]
Currently, fonts are always anti-aliased and this cannot be changed. Disabling it would require to use FT_RENDER_MODE_MONO internally when loading glyphs (see [here](https://github.com/LaurentGomila/SFML/blob/master/src/SFML/Graphics/Font.cpp#L424)), but:
- it can be applied only upon glyph creation, so it would be an argument of Font::loadFromXxx and cannot be changed after the font is loaded
- the results are still not perfect, so it would probably require to investigate other FreeType options (sub-pixel rendering, font hinting), but these might not be patent-free

See [this forum thread](http://en.sfml-dev.org/forums/index.php?topic=8523.0) for more details and screenshots.

**Comment by clort81** [comment]
Not using SFML text is a good solution.  If your fonts are to be unscaled bitmaps, draw bitmaps.
