### ISSUE TITLE
Build warning (error) when an old version of freetype2 is installed (on Linux)

### ISSUE THREAD

**Issue by mojca** [SFML/SFML#2575]
Thanks for raising your issue here! 🙂

Before you submit the issue however, we'd like you to consider the follow points.

* We like to use the issue tracker for confirmed issues.
* If you're stuck with SFML, please use [the forum](https://en.sfml-dev.org/forums/index.php#c3) to get help.

----

## Subject of the issue

I'm trying to build some package for Python on `manylinux2014` (which is basically CentOS 7 with some bells and whistles) for an increased backward compatibility.

The software authors decided to go bold and added `-Werror -Wall -Wextra` (as well as some extra flags) which makes the build break with

```
/opt/rh/devtoolset-10/root/usr/bin/g++ -DSFML_STATIC -DSTBI_FAILURE_USERMSG -I/path/to/build/__external/src/sfml/include -I/path/to/build/__external/src/sfml/src -isystem /path/to/build/__external/src/sfml/extlibs/headers/stb_image -isystem /path/to/build/__external/src/sfml/extlibs/headers/glad/include -isystem /usr/include/freetype2 -pthread -Wall -Wextra -Wno-comment -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unknown-pragmas -Wno-parentheses -Wno-misleading-indentation -Wno-unused-variable -Wno-switch -Wno-maybe-uninitialized -Wno-psabi  -Werror=return-type -fexec-charset=UTF-8 -finput-charset=UTF-8 -O3 -DNDEBUG -std=gnu++17 -fPIC -fvisibility=hidden -Werror  -Wall -Wextra -Wshadow -Wnon-virtual-dtor -Wcast-align -Wunused -Woverloaded-virtual -Wconversion -Wsign-conversion -Wdouble-promotion -Wformat=2 -Wnull-dereference -Wold-style-cast -Wpedantic -Wmisleading-indentation -Wduplicated-cond -Wlogical-op -Wduplicated-branches -MD -MT _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/Font.cpp.o -MF _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/Font.cpp.o.d -o _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/Font.cpp.o -c /path/to/build/__external/src/sfml/src/SFML/Graphics/Font.cpp
/path/to/build/__external/src/sfml/src/SFML/Graphics/Font.cpp: In member function ‘sf::Glyph sf::Font::loadGlyph(sf::Uint32, unsigned int, bool, float) const’:
/path/to/build/__external/src/sfml/src/SFML/Graphics/Font.cpp:654:34: error: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
  654 |     unsigned int width  = bitmap.width;
      |                           ~~~~~~~^~~~~
/path/to/build/__external/src/sfml/src/SFML/Graphics/Font.cpp:655:34: error: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
  655 |     unsigned int height = bitmap.rows;
      |                           ~~~~~~~^~~~
cc1plus: all warnings being treated as errors
```

Now, there is a flag `-isystem /usr/include/freetype2` and while your package contains the latest freetype headers, the ones from the distribution get picked up, and those contain:
```c++
  typedef struct  FT_Bitmap_
  {
    int             rows;
    int             width;
    int             pitch;
    unsigned char*  buffer;
    short           num_grays;
    char            pixel_mode;
    char            palette_mode;
    void*           palette;

  } FT_Bitmap;
```

This has been changed 8 years ago in https://gitlab.freedesktop.org/freetype/freetype/-/commit/b3500af717010137046ec4076d1e1c0641e33727.

Describe your issue here.

## Your environment

* Your OS / distro / window manager used: CentOS 7 (manylinux2014)
* Your version of SFML: 2.6.x
* Your compiler and compiler version used: g++ 10
* Special compiler flags used: `-Werror -Wall -Wextra` (and others, see above)

## Steps to reproduce

I could try to prepare a "MWE", but I would prefer to get some feedback first about whether it makes sense to do so.

There are a few different options to address this:

- use `unsigned int height = static_cast<unsigned int>(bitmap.rows);` should get rid of the warning also for older versions (but it's in fact clumsy given that almost any sufficiently new version already contains this fix)
- enforce the use of the headers that get shipped with SFML instead of using the ancient system ones (personal I would prefer to do this, at least for the project that I'm currently building)
- remove `-Werror` or disable some specific warnings (which is already what is being done on Windows anyway)

Is any of those changes (or something different) reasonable to do?

This is the file being used to build SFML via `FetchContent`:

```cmake
if (WIN32 OR MINGW)
    remove_definitions(-DWIN32_LEAN_AND_MEAN)
endif()

get_custom_fetch_content_params(sfml FC_PARAMS)

FetchContent_Declare(
    sfml
    GIT_REPOSITORY https://github.com/SFML/SFML.git
    GIT_TAG        2.6.x
    GIT_PROGRESS ON
    GIT_SHALLOW ON
    GIT_REMOTE_UPDATE_STRATEGY REBASE_CHECKOUT
    ${FC_PARAMS}
)

set(SFML_BUILD_WINDOW ON)
set(SFML_BUILD_GRAPHICS ON)
set(SFML_BUILD_NETWORK OFF)
set(SFML_BUILD_DOC OFF)
set(SFML_BUILD_EXAMPLES OFF)
set(SFML_BUILD_AUDIO OFF)
set(WARNINGS_AS_ERRORS OFF CACHE BOOL "SFML treat warnings as errors")

FetchContent_MakeAvailable(sfml)

if (WIN32)
    set(SFML_WIN sfml-main)
endif()

set(SFML_TAGETS sfml-graphics
                sfml-window
                sfml-system
                ${SFML_WIN}
)

foreach(TARGET_NAME ${SFML_TAGETS})
    set_target_properties(${TARGET_NAME} PROPERTIES FOLDER "external/sfml")
    if (MSVC)
        target_compile_options(${TARGET_NAME} PRIVATE /wd4456 /wd4701 /wd4703 /wd4100 /wd4242 /WX-)
    endif()
endforeach()
```

## Expected behavior

Successful build.

## Actual behavior

A warning (error) gets thrown.

**Comment by ChrisThrasher** [comment]
A workaround is to disable the CMake `WARNINGS_AS_ERRORS` flag.

**Comment by lemzwerg** [comment]
Mojca, I have no idea :slightly_smiling_face:  Seriously, I currently don't have time to track this down, sorry – if you want to do that, `git blame` is your friend.

BTW, the 'bold' issue is not the many `-W` flags but rather that all warnings are treated as errors (which I consider an exceptionally bad idea).

**Comment by ChrisThrasher** [comment]
> (which I consider an exceptionally bad idea).

There's an option right there for you to disable it. You can pick whatever behavior you prefer.

**Comment by mojca** [comment]
May I please just ask if there is any way to build SFML on Linux without having freetype2 installed on the system? Given that you ship the sources, I would imagine that this ought to be possible, but I don't see any configure options to achieve that.

**Comment by mojca** [comment]
> Mojca, I have no idea 🙂 Seriously, I currently don't have time to track this down, sorry – if you want to do that, `git blame` is your friend.

I don't really expect you to do anything. I already tracked down a commit in FT that switched to a more suitable unsigned integers. I'm only puzzled why CentOS claims to ship version 2.8 and yet that commit is not included.

> BTW, the 'bold' issue is not the many `-W` flags but rather that all warnings are treated as errors (which I consider an exceptionally bad idea).

The whole idea of that flag is to make it easy for CI to catch warnings, so that they can get fixed immediately. (I agree that it should not be enabled for end users.) Anyway, `-Wno-error=sign-conversion` is a viable workaround.

**Comment by ChrisThrasher** [comment]
> May I please just ask if there is any way to build SFML on Linux without having freetype2 installed on the system?

Seems feasible. If you look at FindFreetype.cmake in cmake/Modules it appears that you can set the `FREETYPE_DIR` environment variable to change where CMake looks Freetype. I haven't tried this so I can't confirm whether it works.

I'm closing this issue since you have a few options for working around this issue.
