### ISSUE TITLE
pkg-config install location is nonstandard (SFML 2.6.0)

### ISSUE THREAD

**Issue by hdclark** [SFML/SFML#2580]
## pkg-config installs files to a nonstandard location

SFML 2.6.0-1 in Arch Linux installs `pkg-config` files to `/usr/pkgconfig/` rather than `/usr/lib/pkgconfig/` or `/usr/share/pkgconfig/`. This causes the pkg-config binary to erroneously report that SFML is not available.

## Your environment

* Arch Linux (`docker run archlinux:latest`)
* SFML 2.6.0-1 installed with `pacman -Syu sfml pkg-config`.

## Steps to reproduce

```
$> pacman -Syu sfml pkg-config

$> pkg-config --libs sfml-window
Package sfml-window was not found in the pkg-config search path.
Perhaps you should add the directory containing `sfml-window.pc'
to the PKG_CONFIG_PATH environment variable
Package 'sfml-window', required by 'virtual:world', not found

$> find / -type f -iname '*.pc' 2>/dev/null
/usr/share/pkgconfig/hwdata.pc
/usr/share/pkgconfig/libmakepkg.pc
/usr/share/pkgconfig/systemd.pc
/usr/share/pkgconfig/udev.pc
...
/usr/lib/pkgconfig/xcb-dpms.pc
/usr/lib/pkgconfig/libpkgconf.pc
/usr/lib/pkgconfig/alsa-topology.pc
/usr/lib/pkgconfig/jsoncpp.pc
/usr/lib/pkgconfig/x11.pc
/usr/lib/pkgconfig/wayland-egl-backend.pc
/usr/lib/pkgconfig/libout123.pc
/usr/pkgconfig/sfml-audio.pc            <----- *only* SFML files are installed here
/usr/pkgconfig/sfml-system.pc
/usr/pkgconfig/sfml-all.pc
/usr/pkgconfig/sfml-window.pc
/usr/pkgconfig/sfml-graphics.pc
/usr/pkgconfig/sfml-network.pc
```

SFML pkg-config files are the only files installed to `/usr/pkgconfig/`.

Note that the Arch Linux SFML package installation script is here: https://gitlab.archlinux.org/archlinux/packaging/packages/sfml/-/blob/main/PKGBUILD . It doesn't look like it's doing anything strange.

I can't tell if this change was intentional?

## Expected behavior

Prior to SFML 2.6.0, pkg-config files were installed in (I believe) `/usr/share/pkgconfig/`. Wherever they are installed, I expected `pkg-config` to locate them.

## Actual behavior

`pkg-config` files are installed in a location that the `pkg-config` binary is not aware of.

**Comment by ChrisThrasher** [comment]
You may be able to work around this by changing `CMAKE_INSTALL_LIBDIR` before installation. That affects the value of `SFML_PKGCONFIG_DIR` which affects where pkgconfig files get installed.

**Comment by hdclark** [comment]
Only the pkg-config files are installed to /usr/pkgconfig/, but all other files are installed to /usr/lib or /usr/share (i.e., the GNU-standard directories). Won't the CMAKE_INSTALL_LIBDIR change the location for all other files?

**Comment by hdclark** [comment]
I have confirmed that adding `-DSFML_PKGCONFIG_INSTALL_PREFIX=/usr/share/pkgconfig` resolves the issue, so this appears to be a packaging issue. Created a bug report at https://bugs.archlinux.org/task/78854 .

@ChrisThrasher Thanks for your help!

**Comment by ChrisThrasher** [comment]
Ah yes my bad. That's the correct cache variable to change.

**Comment by ChrisThrasher** [comment]
GNUInstallDirs affect conventional CMake installations. pkgconfig is it's own separate thing since it is not the official format for installation of CMake projects.

**Comment by eXpl0it3r** [comment]
We currently set a different path for FreeBSD / OpenBSD / NetBSD, do you think it's worth adding an additional rule for Arch Linux? 

https://github.com/SFML/SFML/blob/b391be2316c0f9859a504deabb5225a02c1b3e89/cmake/Config.cmake#L69-L75

**Comment by hdclark** [comment]
As an end-user, I consider this issue fully resolved.

Practically, if I were to cross-compile or install multiple versions, the
current setup would still work well. So I don't think special-casing is
necessary.
