### ISSUE TITLE
Glyph corruption in sf::Font when using GL_SCISSOR_TEST

### ISSUE THREAD

**Issue by pekfos** [SFML/SFML#2588]
## Subject of the issue

I have observed rendering artifacts when using `sf::Font` with `GL_SCISSOR_TEST`. I tracked it down to `Texture::update(Texture&, ..)`  performed internally in `sf::Font` when rendering new glyphs, in the codepath using `GLEXT_framebuffer_blit`. Copying glyphs to larger texture with `GL_SCISSOR_TEST` enabled may corrupt them and they will stay that way even if `GL_SCISSOR_TEST` is later disabled, resulting in seemingly random glyphs going permanently missing or corrupted for particular font sizes.

## Your environment

Windows 10, Visual Studio 2019, master branch of SFML

## Steps to reproduce

```cpp
#include <SFML/Graphics.hpp>
#include <SFML/OpenGL.hpp>

int main()
{
    sf::RenderWindow okno( sf::VideoMode( {320, 240 }), "Scissors" );
    sf::Font font;
    // https://fonts.google.com/specimen/Charis+SIL/about
    if(!font.loadFromFile("CharisSIL-Regular.ttf"))
        return 0;

    sf::Text text(font, "0123456789ABCDEFGHIJKLMNOPQ", 30);
    text.setFillColor(sf::Color::White);

    glEnable(GL_SCISSOR_TEST);
    glScissor(0, 0, 30, 30);
    okno.draw(text); // Trigger caching several glyphs with GL_SCISSOR_TEST active.
    glDisable(GL_SCISSOR_TEST);

    while( okno.isOpen() )
    {
        sf::Event event;
        while( okno.pollEvent( event ) )
        {
            if( event.type == sf::Event::Closed )
                    okno.close();

        } //while
        okno.clear();
        okno.draw(text);
        okno.display();
    }
}
```

**Comment by eXpl0it3r** [comment]
As mentioned on #2589 correctly handling of OpenGL states, while using the graphics module, is the user's responsibility. You can use `pushGLStates()` / `popGLStates()` or `resetGLStates()` to let SFML deal with its own OpenGL states, but you still have to enable/disable your own states, as SFML won't be tracking that.

See: https://www.sfml-dev.org/tutorials/2.6/window-opengl.php#using-opengl-together-with-the-graphics-module

**Comment by pekfos** [comment]
> As mentioned on #2589 correctly handling of OpenGL states, while using the graphics module, is the user's responsibility. You can use `pushGLStates()` / `popGLStates()` or `resetGLStates()` to let SFML deal with its own OpenGL states, but you still have to enable/disable your own states, as SFML won't be tracking that.
> 
> See: https://www.sfml-dev.org/tutorials/2.6/window-opengl.php#using-opengl-together-with-the-graphics-module

I set scissor test because I want to use it, render text with clipping. How should I know if SFML is going to internally call something that should not have scissor test enabled? Should application code render any text on scratch surface, just to be in the clear when performing proper render? Then perhaps optimize it by remembering size-style-character tuples that should already be safe to draw? This is quite a workaround. Perhaps it should be documented, to save trouble for the next guy?
I don't think it's that much to save. According to https://registry.khronos.org/OpenGL/extensions/EXT/EXT_framebuffer_blit.txt
> The pixel copy bypasses the fragment pipeline.  The only fragment
    operations which affect the blit are the pixel ownership test and
    the scissor test.

**Comment by eXpl0it3r** [comment]
Unfortunatley it's just a bad OpenGL global state handling. You can't really have any two users operate without making some assumptions about these states.  
Switching states isn't exactly free either, so we don't really want to just switch all the possible states when rendering something with SFML "just to be safe". Instead we make not guarantees in general, leave the responsibility up to the user and offer the already mentioned options.

We're also currently in the process of adding native scissor testing to SFML: #1451
