### ISSUE TITLE
Vector2<T>::normalized function wont work if the vector2 is zeroed

### ISSUE THREAD

**Issue by erikbolumburu11** [SFML/SFML#2592]
## Subject of the issue

Using the normalized function on a `Vector2f` whilst both `x` and `y` are 0 causes this error:
```cpp
Assertion failed: *this != Vector2<T>(), file C:\Users\erikf\dev\LIBRARIES\SFML3\src\SFML\System\Vector2.cpp, line 41
```

## Environment

* Windows 10
* git master
* vc++ 17

## Example

```cpp
vc.velocity = { 0, 0 };
sf::Vector2<float> v(0.f, 0.f);
if (sf::Keyboard::isKeyPressed(sf::Keyboard::S)) v.y += 1.f;
if (sf::Keyboard::isKeyPressed(sf::Keyboard::W)) v.y -= 1.f;
if (sf::Keyboard::isKeyPressed(sf::Keyboard::D)) v.x += 1.f;
if (sf::Keyboard::isKeyPressed(sf::Keyboard::A)) v.x -= 1.f;
v = v.normalized();
vc.velocity = vel * speed;

```

## Expected behavior

if normalized is called on a zeroed `Vector2<float>`, it should return a zeroed `Vector2<float`.
## Actual behavior

Causes the following error:
```cpp
Assertion failed: *this != Vector2<T>(), file C:\Users\erikf\dev\LIBRARIES\SFML3\src\SFML\System\Vector2.cpp, line 41
```

**Comment by Marioalexsan** [comment]
To me this looks like it works as expected. Mathematically speaking, you can't normalize a zero vector, and the assert is there to tell you in debug mode that the operation you want to do might be bugged.
