### ISSUE TITLE
Pixelate shader doesn't work

### ISSUE THREAD

**Issue by xzripper** [SFML/SFML#2659]
## Subject of the issue

The texture pixelation shader doesn't work. After applying the shader to the texture, the texture will be grey.

## Your environment

* Windows 10
* SFML (2.6.0
* g++.exe (GCC) 11.1.0

## Steps to reproduce

The shader was used from SFML Shader <a href="https://github.com/SFML/SFML/blob/master/examples/shader/resources/pixelate.frag">Examples.</a>

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode({1280, 720}), "Minimal, complete and verifiable example");
    window.setFramerateLimit(60);

    sf::Texture tex;
    tex.loadFromFile("example.png");

    sf::Shader shader;
    shader.loadFromFile("shaders\\pixelate.frag", sf::Shader::Fragment);

    shader.setParameter("texture", sf::Shader::CurrentTexture);
    shader.setParameter("pixel_threshold", 500);

    sf::Sprite sprite(tex);

    sprite.setPosition(500, 500);
    sprite.setScale(1.0f, 1.0f);

    while (window.isOpen())
    {
        for (sf::Event event; window.pollEvent(event);)
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();

        window.draw(sprite, &shader);

        window.display();
    }
}
```

example.png:
![example](https://github.com/SFML/SFML/assets/94743980/6cfbfc36-167b-49a1-8524-58452ff233b6)

## Expected behavior

Texture should be pixelated.

## Actual behavior

![Screenshot_1](https://github.com/SFML/SFML/assets/94743980/aaa15291-49a6-4cee-beba-54a9a2eb76bc)

**Comment by Bambo-Borris** [comment]
Your minimal example code is broken, please ensure you post working example code when you raise an issue

```
window.draw(sprite, &shader); // this should be between clear/display

window.clear();
window.display();
```

**Comment by xzripper** [comment]
Updated

**Comment by Bambo-Borris** [comment]
> Updated

Just updated my initial reply, see that for a fix to your issue.
