### ISSUE TITLE
Reconsider the names for APIs that return handles to implementation details

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2660]
## Subject of the issue

We have 5 separate APIs that access handles to implementation details. They are as follows:

https://github.com/SFML/SFML/blob/62c376ffa55d7fa1d1c4855a777c3d89670bd4ba/include/SFML/Graphics/Shader.hpp#L599

https://github.com/SFML/SFML/blob/62c376ffa55d7fa1d1c4855a777c3d89670bd4ba/include/SFML/Graphics/Texture.hpp#L542

https://github.com/SFML/SFML/blob/62c376ffa55d7fa1d1c4855a777c3d89670bd4ba/include/SFML/Graphics/VertexBuffer.hpp#L240

https://github.com/SFML/SFML/blob/62c376ffa55d7fa1d1c4855a777c3d89670bd4ba/include/SFML/Network/Socket.hpp#L146

https://github.com/SFML/SFML/blob/62c376ffa55d7fa1d1c4855a777c3d89670bd4ba/include/SFML/Window/WindowBase.hpp#L427

The names feel a bit inconsistent and I'd like to address that inconsistency.

First of all, the C++ standard library uses the term "native handle" in a few places ([`std::thread::native_handle`](https://en.cppreference.com/w/cpp/thread/thread/native_handle) and [`std::mutex::native_handle`](https://en.cppreference.com/w/cpp/thread/mutex/native_handle) among others) to refer to implementation-defined types. The underlying type for a thread for example will be different on Windows versus Linux. These APIs are not meant for writing portable code. They're for supporting advanced use cases and often supporting platform-dependent code. You may want the underlying `pthread` handle to use with the pthread API in your Linux program.

According to that definition of native handles, the APIs that currently don't use the term "native handle" ought to be using it. `sf::Socket::getHandle()` and `sf::WindowBase::getSystemHandle` return OS-specific types. I think it makes sense to rename both to `getNativeHandle()`. This name is more correct and has the bonus of being consistent with the previous 3 APIs.

We could stop here if we want. That would result in 5 APIs all with the same name. That consistency should help users writing code by allow them to use terminology they maybe already understand from the C++ standard library and lets them type the same function name no matter what kind of native handle they're accessing.

There's an argument to be made that the first three APIs which use the name "native handle" actually should not. Those three graphics APIs return an OpenGL handle which is not platform-specific. They're not native handles in the same sense of the word as `std::thread::native_handle`. Perhaps to be ultra-pedantic we'd rename these to `getOpenGLHandle` but I kind of like using the "native handle" terminology everywhere.

**Comment by eXpl0it3r** [comment]
I'd probably stick with `getNativeHandle()` everywhere as well. A discussion could be had whether OpenGL handles are "native" or not, but I don't really see how it would change the understanding of the API.
