### ISSUE TITLE
`sf::Event` API + type-safe unions

### ISSUE THREAD

**Issue by Bromeon** [SFML/SFML#2668]
Since the topic came up again in #2665, I'd like to discuss different possible approaches for `sf::Event`.

### 0. `union`

The current approach based on `union` has multiple problems.

First and foremost, it's not type-safe and allows to easily create undefined behavior by reading the wrong variant. The fact that things are not very distinctly named doesn't help here:
```cpp
if (event.type == sf::Event::MouseWheelScrolled) {
   use(event.mouseWheel); // BAM UB, should have been mouseWheelScrolled
}
```

Second, unions are very limited regarding constructor/destructor, so we cannot e.g. store `std::string` inside a variant.
So, I'd like to use this issue to brainstorm different approaches and then converge on the one we like best 🙂 

### 1. `std::variant`

An option is to directly declare an `std::variant` of all possible event types:
```cpp
using Event = std::variant<Event::Closed, Event::Resized, ... Event::SensorChanged>;
```

`std::variant` has the advantage of being standard. However, there are a few issues:
* The visitor pattern is very verbose. There is the [`overload{}` life hack](https://en.cppreference.com/w/cpp/utility/variant/visit) which makes things a bit nicer, but IIRC it had quite some compile-time impact (this may no longer be true). At the very least, we always need the standard `<variant>` header.
* The visitor must be a lambda (or function object), meaning it interrupts control flow.
  This makes it harder to do things like `if (/* event is XY */) return;`.
* Not sure if this is still an issue, but there were quite some runtime performance impacts ([1](https://www.reddit.com/r/cpp/comments/kst2pu/with_stdvariant_you_choose_either_performance_or/), [2](https://orangejuiceliberationfront.com/surprising-slowness-of-cpp-std-variant/), [3](https://stackoverflow.com/questions/57726401/stdvariant-vs-inheritance-vs-other-ways-performance)). It might not be relevant because event handling involves expensive OS calls, but I'm listing it for completeness.
* By exposing a `std::variant` directly, implementation details may leak:
   * Changing the index of a variant is a breaking change for users.
   * We cannot add variants later, as the public-facing type is then different.

### 2. the OOP way, per event

Have a base `Event` with virtual destructor and inherit concrete events from it. Return the object inside a `std::unique_ptr<sf::Event>`. This needs to be downcast by the user.

Possible but not ideal as all the objects needs to be boxed, although it might not matter performance-wise. Would allow to have hierarchies in case we need that (e.g. intermediate class for different mouse events, containing mouse position) -- but doubtful that it's worth it.

### 3. the OOP way, as an event handler

Instead of having polymorphism on the `Event` itself, we could provide an abstract base class:
```cpp
class MyHandler : public sf::EventHandler {
    // Handle specific events -- return true if handled
    virtual bool onEvent(Event::MouseMove e) override;
    virtual bool onEvent(Event::KeyPressed e) override;

    // Have a fallback for unhandled events -- probably not needed?
    virtual void onUnhandledEvent(??);
};
```
Again a bit the issue of non-locality and verbosity. Possibly a bit too java-style, just thought I'd mention it as a non-generic alternative to `std::visit()`, but it shares similar problems.

### 4. generic get interface, hidden implementation

We would just expose a method to get a concrete type, based on `std::optional`. If the user fetches the wrong type, he will get an empty optional.

```cpp
class Event {
   ...
public:
    // Returns T if it's that variant, or empty
    template <typename T>
    std::optional<T> get() const;
};
```
```cpp
if (auto e = event.get<Event::MouseMove>()) {
    // procedural code
} else if (auto e = event.get<Event::KeyPressed>()) {
    // ...
}
```
This even allows us to use `std::variant` internally, but it's hidden as an implementation detail. If we forward the `get<T>()` invocation to `variant::get<T>()`, we'd implicitly check whether `T` is one of the allowed variants (and in a sense, the internal `std::variant` is then a leaky abstraction).

The disadvantage is that there's no visiting API, but a) this could be added/exposed if really needed, and b) events are typically not queried exhaustively. Users want to know if something they're interested in (like a key press) has happened. 

On the other hand, what this _does_ allow is a "catch-all" `else` branch. If ever we add debugging information such as `event.toString()`, that might be a possible choice to do in an `else` branch. Or when someone has their own event system, to enqueue `std::vector<sf::Event>` or so.

### 5. specific get interface

Same as 3, but with named methods.
```cpp
class Event {
   ...
public:
    std::optional<Event::MouseMove> mouseMove() const;
};
```
```cpp
if (auto e = event.mouseMove()) {
    // procedural code
} else if (auto e = event.keyPressed()) {
    // ...
}
```
Very concise but still safe. It's unlikely that people use `sf::Event` in a generic way, so having a generic interface only benefits us a small bit on the implementation side (reducing some code duplication). On the other hand, we can define everything in the .cpp file here and don't need a `<variant>` header.

This API is almost "boring", but it might come with the least surprises and has no issues regarding compile time or template error messages.

Also, it makes the API very discoverable: for example, when typing `event.` in an IDE, auto-complete will suggest all possible getters. This is not the case for `get<T>()`.

**Comment by eXpl0it3r** [comment]
Might be a good idea to lay out the perceived issue with the current implementation, so it's clear what the discussion is trying to solve 😄

**Comment by Bromeon** [comment]
Good point, updated initial post.

**Comment by ChrisThrasher** [comment]
Thanks for the writeup!

A few initial thoughts stick out in my mind
1. `std::variant` is the obvious pick for how we _implement_ `sf::Event`. It perfectly captures what is actually going on under the hood. I think it's a given that any rewrite of `sf::Event` will use it in some capacity.
2. Raw `std::variant` isn't a good fit for SFML's event API.

I'm leaning towards option 5 because it's the least variant-y API. If we're going to wrap a variant, it doesn't make tons of sense to largely recreate how `std::holds_alternative` and `std::get` already work. I want the power and safety of a variant without users having to understand how variants work.

For what it's worth we could merge options 4 and 5 if someone makes a compelling case for a templated `get` function sometime in the future.

---

This may be a stretch but I wonder if we should still support switch statements to avoid cascading `if` blocks. Maybe we include an enumeration that points to the active type so you can still jump straight to the block that extracts the active element. I just thought of this on the spot but wanted to put it out there.

```cpp
switch(event.getType())
{
case sf::Event::Resized:
    auto& resized = *event.getResized(); // or event.getResized().value() if you want to doubly check for safety
    ...
    break;
case sf::Event::MouseMove:
    auto& mouseMove = *event.getMouseMove();
    ...
    break;
}
```

This means that you don't have to check every other potential event type before finding the actually active event. It's no less type safe but lets users write code more similar to what they're already doing.

**Comment by ChrisThrasher** [comment]
None of these options are hard to implement so I can have something ready within a day or two of us reaching consensus. Don't worry at all about implementation. It's design and consensus that are the hard parts.

**Comment by Bromeon** [comment]
> `std::variant` is the obvious pick for how we _implement_ `sf::Event`. It perfectly captures what is actually going on under the hood. I think it's a given that any rewrite of `sf::Event` will use it in some capacity.

Just for completeness, as long as we don't need constructors/destructors, we _could_ theoretically keep using `union` internally and use an enum (public or not) as a discriminant. Might add a small compile-time benefit (also for not exposing the header); apart from that there are probably not many advantages.


> Maybe we include an enumeration that points to the active type so you can still jump straight to the block that extracts the active element. I just thought of this on the spot but wanted to put it out there.

I was thinking about that too, but is it really needed? I don't think checking half a dozen events linearly will be a performance issue.

And without separate enum, the API becomes quite a bit simpler. With approach 5), there is already a mapping from method to type, and this would add a third symbol (the constant) that the user needs to keep track of.

Also, with `if/else` there will be only one way to do things: people don't wonder "should I use `if` or `switch`", which I see as better API design.

**Comment by ChrisThrasher** [comment]
> I don't think checking half a dozen events linearly will be a performance issue.

I'm mostly motivated by developer ergonomics and increased familiarity with how SFML 2 handles events. I'm trying to get ahead of whatever complaints or frustrations users may have. We've changed a lot of APIs but no API we've changed is as core to the experience as `sf::Event`.

**Comment by Bromeon** [comment]
Fair point. In my (last) edit, I however showed that this has the risk of triggering the UB again, because the user may rely on a certain type after checking the enumerator:
```cpp
switch (event.type) {
   case sf::Event::MouseWheelScrolled): 
      use(*event.mouseWheel()); // BAM UB
      break;
}
```

This is a problem that is completely out of the way with `if`/`else` only, because there's no way someone can know the type without checking whether the optional is populated.

**Comment by ChrisThrasher** [comment]
Some more spitballing, but is this possible?

```cpp
switch (event.type) {
   case sf::Event::MouseWheelScrolled: 
      use(*get<sf::Event::MouseWheelScrolled>());
      break;
}
```

Use the enum as a non-type template parameter that will return the correct type. Under the hood this might be implemented with a bunch of `if constexpr` blocks but I'm not positive about that. This eliminate all the named functions so that there is just `get<T>` taking us back to option 4 but with a slight twist on it.

**Comment by Bromeon** [comment]
Yes, but... why? 😀 

The other approach is shorter and easier to read, safer, works without repetition, requires fewer API symbols (no enum), and most importantly leaves a single way to do things. So if I read other SFML code, I immediately understand what it's doing and it's not 50/50 based on the convention used.

All that's speaking for `switch` at this point is that people have been used to it before. But is that alone worth the downsides?

**Comment by ChrisThrasher** [comment]
`switch` statements do a great job expressing how amongst many option, only one is active. Big long if/chains don't express that as well. `if/else if` chains are often just switch statements (or some higher level pattern matching) in disguise. I suppose that's something I value more than you do.

**Comment by ChrisThrasher** [comment]
```cpp
if (auto* resized = std::get_if<sf::Event::ResizedEvent>(event)) {
  // ...
} else if (auto* joystickButton = std::get_if<JoystickButtonEvent>(event)) {
  // ...
} else if (auto* mouseWheelScroll = std::get_if<MouseWheelScrollEvent>(event)) {
  // ...
}
```
I wanted to put this out there since `std::get_if` hasn't come up yet. This is already possible with a `std::variant` by itself. If we want users to write `if`/`else if` chains then we can achieve that without writing a custom class.

**Comment by Bromeon** [comment]
> `switch` statements do a great job expressing how amongst many option, only one is active. Big `if`/`else if` chains don't express that as well. `if`/`else if` chains are often just switch statements (or some higher level pattern matching) in disguise. I suppose that's something I value more than you do. I'd rather we continue to allow for higher level, more expressive control flow constructs rather than force users to exclusively use simple conditionals.

I see, thanks for elaboration! I would agree if `switch` did actual pattern matching, but it's still the stupid integer lookup from 1985. Unfortunately this leaves a lot of manual mapping to the user (enum -> type), and there are known pitfalls like `break` etc. So I'm not sure if it's "higher level" than `if/else` -- a chain of `else if` also makes clear that only one branch can be taken.

It's maybe a more fundamental question, whether we want to provide redundant APIs to accomodate for different styles, or simply choose one option which we find the best/safest/simplest even if it doesn't make everyone happy.

---



> I wanted to put this out there since `std::get_if` hasn't come up in conversation yet. This is already possible with a `std::variant` by itself.

But above you wrote "Raw `std::variant` isn't a good fit for SFML's event API", and I agree. Exposing the `std::variant` has several disadvantages, as outlined in my initial post. It's also ergonomically worse than approach 5) in my opinion (see arguments there).

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/pull/2766

I implemented my best idea for a new API. Check it out above. I think it has a lot of great properties and I'm happy with how it turned out.
