### ISSUE TITLE
Add a function to change the mouse cursor

### ISSUE THREAD

**Issue by LaurentGomila** [SFML/SFML#269]
```cpp
enum Cursor
{
    None,
    Arrow,
    Link,
    ...
};

class Window
{
    void setMouseCursor(Cursor cursor);
    void setMouseCursor(const Uint8* pixels, unsigned int width, unsigned int height);
}
```

`setCursor(None)` would replace the current `setMouseCursorVisible(false)` (so this new feature won't add overhead to the API).

Users have already provided implementations for this function on the forum and wiki.

**Comment by mantognini** [comment]
Since most of the discussion is happening in #827, I'm marking this issue as superseded.
