### ISSUE TITLE
Fix MinGW CI failures

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2700]
## Subject of the issue

Some recent changes to GitHub Actions CI images resulted in Ninja being removed from the Windows images. Explanation [here](https://github.com/actions/runner-images/issues/8343#issuecomment-1727810519). There is [a PR to add it back](https://github.com/actions/runner-images/issues/8348) but I don't expect it will get merged. In the meantime that means we need to use Choco to install Ninja. This is easy enough so I went ahead and wrote that up [here](https://github.com/SFML/SFML/commit/ab18e1ac10881836f38cf5e2f8a986bea5171a64).

_However..._

This reveals a new issue. The Windows image is also now shipping MinGW 12 instead of 11. This upgrade is causing [some linker errors](https://github.com/SFML/SFML/actions/runs/6255239241/job/16984226836?pr=2699#step:10:101) which I fear are caused by ABI incompatibilities between our MinGW binaries and MinGW 12. However if this were the case I'd expect users would have caught this sooner given how many users are using MinGW 12 and 13. I'm not sure what else could be causing this. More investigation is required. Is this actually an issue with WinLibs? [This forums post](https://en.sfml-dev.org/forums/index.php?topic=28647.0) is one of the first results when I search for this linker errors.

**Comment by eXpl0it3r** [comment]
The C library dependencies (specifically frretype) have been built against MSVCRT and now fail if you use a UCRT compiler

Potential solutions:

- Download a compatible MSVCRT MinGW version on the GitHub Actions runner
- Build UCRT compatible frretype binaries and check them in
- Remove the freetype binaries and build freetype on the fly

**Comment by ChrisThrasher** [comment]
Is either UCRT or MSVCRT dramatically more popular than the other?

**Comment by eXpl0it3r** [comment]
See also #2710

**Comment by eXpl0it3r** [comment]
> Is either UCRT or MSVCRT dramatically more popular than the other?

Not that I know of. UCRT MinGW is however more something new coming from the WinLibs project. The "old builders" all used MSVCRT.

> If we can detect which runtime is being used at configuration time, we can dynamically pick the right MinGW libs. Any idea if that's feasible?

I guess that should somehow be possible, but I rather move ahead with removing binaries, than adding more binaries.

**Comment by ChrisThrasher** [comment]
https://github.com/actions/runner-images/discussions/8372

Here's a related discussion to follow

**Comment by ChrisThrasher** [comment]
We’ve figured out a solution to this
