### ISSUE TITLE
Individual view and projection transforms for View

### ISSUE THREAD

**Issue by junglie85** [SFML/SFML#2701]
There are cases where I'd like to be able to get the individual view and projection components of the `View` and not just the whole view projection.

I tried writing the orthographic projection and view transforms myself, but the view is always wrong. Taking an inverse of the projection and multiplying it by the original transform it looks like the SFML transform has some extra information in the `tx` and `ty` positions.

Is providing individual view and projection transforms something you're able to support or provide suggestions on how to achieve if not?

**Comment by junglie85** [comment]
> it looks like the SFML transform has some extra information in the tx and ty positions.

No. I was wrong here. I had in fact incorrectly calculated the "camera" view transform. If I multiply the orthographic projection matrix by the inverse of this correctly calculated view matrix, I get the same results as I'd get with the original `View` transform. Still, I think providing these extra transforms could benefit other user's of SFML.

I guess if you did want to adopt this, you'd similarly split the final transform into the two components and potentially cache all 3?

I currently only have this working in a Rust project. When I get opportunity, I'll port it to C++ and share the code / PR.

**Comment by eXpl0it3r** [comment]
Can you provide an example of what you're trying to so, as I don't fully understand it

And also provide some use cases, so we can judge how broadly that feature can be applied to?

**Comment by ChrisThrasher** [comment]
@junglie85 Can you provide some more insight on how such a feature would be used?

**Comment by eXpl0it3r** [comment]
Closing this, as no additional insights has been provided.
