### ISSUE TITLE
Release 2.6.1

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2702]
## Subject of the issue

The 2.6.x has collect a good number of fixes since 2.6.0 was released this summer. Most of those fixes came from the initial wave of users who were packaging and using 2.6.0. Bug reports have died down so I think we're in a good position to release 2.6.1 so we can get these fixes out to users in a punctual manner.

[Here are the diffs from 2.6.0](https://github.com/SFML/SFML/compare/2.6.0...2.6.x). I've already written the changelog as well. The remaining work is just the typical release cycle work of creating binaries and updating the website which should not entail any changes to the docs since this patch release does not touch the API.

@eXpl0it3r @binary1248 @Bromeon thoughts?

---

Looking forward I expect we'll have a 2.6.2 release sometime in 2024 for whatever remaining issues are found in the next few months.

---

## Checklist

- [x] Update SFML version
    - [x] In [CMake](https://github.com/SFML/SFML/blob/master/CMakeLists.txt#L55)
    - [x] In the [config header](https://github.com/SFML/SFML/blob/master/include/SFML/Config.hpp#L30)
    - [x] In the [find_package example](https://github.com/SFML/SFML/blob/master/cmake/SFMLConfig.cmake.in#L17)
    - [x] In the [info.plist](https://github.com/SFML/SFML/blob/master/examples/assets/info.plist#L20)
- [x] Update the changelog
    - [x] In the [repository](https://github.com/SFML/SFML/blob/master/changelog.md)
    - [x] On the [website](https://github.com/SFML/SFML-Website/blob/master/changelog.php)
- [x] Update the website
    - [x] Update the documentation
        - [x] Create a new [doxygen script](https://github.com/SFML/SFML-Website/tree/master/documentation/priv)
        - [x] Generate new HTML documentation
        - [x] Apply the [CSS overrides](https://github.com/SFML/SFML-Website/tree/master/documentation/priv/to_override)
        - [x] Adjust the [documentation links](https://github.com/SFML/SFML-Website/blob/master/learn.php)
        - [x] Update the latest version ([EN](https://github.com/SFML/SFML-Website/blob/master/documentation/header.php) / [FR](https://github.com/SFML/SFML-Website/blob/master/documentation/header-fr.php))
    - [x] Update the tutorials
        - [x] Duplicate the existing tutorial folder and rename for the new version
        - [x] Adjust the [tutorial links](https://github.com/SFML/SFML-Website/blob/master/learn.php)
        - [x] Update the latest version ([EN](https://github.com/SFML/SFML-Website/blob/master/tutorials/header.php) / [FR](https://github.com/SFML/SFML-Website/blob/master/tutorials/header-fr.php))
        - [x] Write new tutorials?!
    - [x] Update the downloads
        - [x] Upload the new binaries
        - [x] Duplicate the existing download folder and rename for the new version
        - [x] Add or remove new or old compilers on the new [download page](https://github.com/SFML/SFML-Website/tree/master/download/sfml)
        - [x] Adjust the file sizes on the new download page
        - [x] Update the old version pages ([EN](https://github.com/SFML/SFML-Website/blob/master/download/sfml/old-versions.php) / [FR](https://github.com/SFML/SFML-Website/blob/master/download/sfml/old-versions-fr.php))
    - [x] Adjust [rewrite rules](https://github.com/SFML/SFML-Website/blob/master/.htaccess) to point to the latest version
- [ ] GitHub Updates
    - [x] [Tag the version](https://github.com/SFML/SFML/tags) in git
    - [x] Create a new [GitHub release](https://github.com/SFML/SFML/releases)
    - [x] Close the open project
    - [ ] Close the open milestone
- [ ] General Updates
    - [ ] Contact package maintainers as soon as a new tag is created
    - [ ] Create a new [forum thread](https://en.sfml-dev.org/forums/index.php?topic=24667.0)
    - [ ] Update the existing [forum thread](https://en.sfml-dev.org/forums/index.php?topic=76.15)
    - [ ] Tweet about the new version
    - [ ] Post about the new version on Reddit (r/sfml & r/cpp)
    - [ ] Update Discord channel description
    - [ ] Update IRC channel description (boxbox & freenode)
    - [ ] Update Slack channel description (cpplang)

## PRs
- Code: #2748
- Website: https://github.com/SFML/SFML-Website/pull/170

**Comment by IovlevYuliy** [comment]
Hi! Is it possible to include `constexpr` version of `sf::Color` (see Color.inl) to release 2.6.1. We hoped it would be released in 2.6, but not :) I guess it's really helpful for many users, cause colors are often defined in compile time. I will be really pleased if you include these changes too in following release.

**Comment by eXpl0it3r** [comment]
In short, no we won't be including it.

For one `constexpr` is not a C++03 feature and SFML 2.x sticks to C++03. Additionally, patch releases (2.6.x) are primarily for fixes and no new feature will be added through that.

`master` is targeting SFML 3 and you're free to use it already, even if the API isn't 100% set in stone (see also [here](https://github.com/SFML/SFML#state-of-development)).

PS: We haven't hit two years (Dec 18, 2021) yet on the constexpr PR, so "several years" isn't exactly true 😉
