### ISSUE TITLE
Generated documentation contains some HTML errors

### ISSUE THREAD

**Issue by jcowgill** [SFML/SFML#2812]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

I noticed a few issues with the doxygen headers / footers. Most can be seen by putting the documentation index page into the W3C validator. You can also see them with the live 2.6.1 documentation: https://validator.w3.org/check?uri=https%3A%2F%2Fwww.sfml-dev.org%2Fdocumentation%2F2.6.1%2Findex.php&charset=%28detect+automatically%29&doctype=Inline&group=0

---

header.html.in:
```html
        <meta http-equiv="Content-Type" content="text/html;"/>
        <meta charset="utf-8"/>
```

Three problems here:
* `meta charset` is a HTML5 thing. It's not valid in XHTML.
* Using both of these elements together is illegal in HTML5 in any case.
* If you don't specify a `charset` in your `Content-Type` then the default is ASCII and not UTF-8 like you want.

---

footer.html:
```html
        </div>
```

There's an unmatched `</div>` on line 1 of the footer.

---

footer.html:
```html
                SFML is licensed under the terms and conditions of the <a href="https://www.sfml-dev.org/license.php">zlib/png license</a>.<br>
```

The `<br>` is not valid XHTML.

### Your Environment

- OS / distro / window manager: Debian unstable
- SFML version: master (but also affects 2.6.1)
- Compiler / toolchain: GCC 13
- Special compiler / CMake flags: `-DSFML_BUILD_DOC=1`

### Steps to reproduce

1. Build SFML with documentation
2. Run the index page through https://validator.w3.org/

### Expected behavior

No errors

### Actual behavior

Generates errors

**Comment by eXpl0it3r** [comment]
Turns out that doxygen can only generate XHTML, so I've fixed the few issues in #2986. One I couldn't fix was there's a `placeholder` attribute on the search box, that XHTML doesn't recognize.

Let me know if that's okay for you.
