### ISSUE TITLE
Doxygen contains empty / useless "Namespaces" and "Files" pages

### ISSUE THREAD

**Issue by jcowgill** [SFML/SFML#2813]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

This page is empty and should probably contain something since SFML does have some namespaces: https://www.sfml-dev.org/documentation/2.6.1/namespaces.php

---

This files page (https://www.sfml-dev.org/documentation/2.6.1/files.php) has some issues which make it useless:
* Most of the files on that page don't link anywhere making it just a list of files (as opposed to telling you what is in each file).
* There is a rogue `doc/mainpage.hpp` file in the list which shouldn't be there.

### Your Environment

- OS / distro / window manager: Debian unstable
- SFML version: master (but also affects 2.6.1)
- Compiler / toolchain: GCC 13
- Special compiler / CMake flags: `-DSFML_BUILD_DOC=1`

### Steps to reproduce

1. Build the docs
2. Look at the "Namespaces" and "Files" tabs

### Expected behavior

These should either:
* Contain something useful
* Be disabled so they don't appear at all

### Actual behavior

Those pages are not useful

**Comment by eXpl0it3r** [comment]
What version of Doxygen are you using?

**Comment by jcowgill** [comment]
Doxygen 1.9.8

**Comment by eXpl0it3r** [comment]
Fixed with #2986

Let me know if this works for you
