### ISSUE TITLE
WebGL Support

### ISSUE THREAD

**Issue by Gabriel-Debono-Tanti** [SFML/SFML#2871]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### Describe your feature request here

A way to build to WebGL.

### Use Cases

When a Game Dev. would enter a game jam and could make a webgl build to support all platforms.

**Comment by ChrisThrasher** [comment]
For technical reasons it's not feasible to support WebGL as a target in SFML 2 or even in the upcoming SFML 3. If you'd like to participate in existing conversations about changing our rendering backend (and thus potentially supporting WebGL) then see https://github.com/SFML/SFML/issues/2423.
