### ISSUE TITLE
`sf::Keyboard::getDescription` returns "Unknown" for F13+ keys on Win32

### ISSUE THREAD

**Issue by pierr3** [SFML/SFML#2872]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

When calling `sf::Keyboard::getDescription` on Scancode `sf::Keyboard::Scan::F13`, and other higher function keys, the function returns "Unknown" on Win32. 

Multiple users reported this problem in my implementation, but only on Win32.

### Your Environment

- OS / distro / window manager: Win32
- SFML version: 2.6.1
- Compiler / toolchain: msbuild + vcpkg
- Special compiler / CMake flags: none

### Steps to reproduce

1. No specific steps needed aside from the code below
```cpp
#include <SFML/Graphics.hpp>
#include <SFML/Window/Event.hpp>
#include <SFML/Window/Keyboard.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode({1280, 720}), "Minimal, complete and verifiable example");
    window.setFramerateLimit(60);

    while (window.isOpen())
    {
        for (sf::Event event; window.pollEvent(event);)
        {
            if (event.type == sf::Event::Closed)
                window.close();

            if (event.type == sf::Event::KeyPressed) {
                std::cout << sf::Keyboard::getDescription(sf::Keyboard::Scancode::F13).toAnsiString() << std::endl;
            }

        }

        window.clear();
        window.display();
    }
}
```

### Expected behavior

Returns a proper key description, such as "F13" or "Function key 13".

### Actual behavior

Returns "Unknown"

**Comment by binary1248** [comment]
So this is the mapping of scan codes `GetKeyNameText` dumps on my system:
```
0x1 -> Esc
0x2 -> 1
0x3 -> 2
0x4 -> 3
0x5 -> 4
0x6 -> 5
0x7 -> 6
0x8 -> 7
0x9 -> 8
0xa -> 9
0xb -> 0
0xc -> -
0xd -> =
0xe -> Backspace
0xf -> Tab
0x10 -> Q
0x11 -> W
0x12 -> E
0x13 -> R
0x14 -> T
0x15 -> Y
0x16 -> U
0x17 -> I
0x18 -> O
0x19 -> P
0x1a -> [
0x1b -> ]
0x1c -> Enter
0x1d -> Ctrl
0x1e -> A
0x1f -> S
0x20 -> D
0x21 -> F
0x22 -> G
0x23 -> H
0x24 -> J
0x25 -> K
0x26 -> L
0x27 -> ;
0x28 -> '
0x29 -> `
0x2a -> Shift
0x2b -> \
0x2c -> Z
0x2d -> X
0x2e -> C
0x2f -> V
0x30 -> B
0x31 -> N
0x32 -> M
0x33 -> ,
0x34 -> .
0x35 -> /
0x36 -> Right Shift
0x37 -> Num *
0x38 -> Alt
0x39 -> Space
0x3a -> Caps Lock
0x3b -> F1
0x3c -> F2
0x3d -> F3
0x3e -> F4
0x3f -> F5
0x40 -> F6
0x41 -> F7
0x42 -> F8
0x43 -> F9
0x44 -> F10
0x45 -> Pause
0x46 -> Scroll Lock
0x47 -> Num 7
0x48 -> Num 8
0x49 -> Num 9
0x4a -> Num -
0x4b -> Num 4
0x4c -> Num 5
0x4d -> Num 6
0x4e -> Num +
0x4f -> Num 1
0x50 -> Num 2
0x51 -> Num 3
0x52 -> Num 0
0x53 -> Num Del
0x54 -> Sys Req
0x56 -> \
0x57 -> F11
0x58 -> F12
0x7c -> F13
0x7d -> F14
0x7e -> F15
0x7f -> F16
0x80 -> F17
0x81 -> F18
0x82 -> F19
0x83 -> F20
0x84 -> F21
0x85 -> F22
0x86 -> F23
0x87 -> F24
```

0x7c to 0x87 just happen to be the VK_F13 to VK_F24 values.

There are 2 possibilities... Either the Windows developers screwed up and unintentionally mixed up scan codes and virtual key codes, or for some reason this was deliberate but undocumented. Either way, it is highly unlikely this will be changed/fixed any time soon on the Windows end, so we would have to remap 0x64-0x76 to 0x7c-0x87 before sending them to `GetKeyNameText`.

**Comment by binary1248** [comment]
Should be fixed with #2873.

**Comment by ChrisThrasher** [comment]
Just fixed this in v3 (`master` branch)`. I think we'll patch this in v2 as well at a later time.

**Comment by pierr3** [comment]
Thank you for the quick fix!
