### ISSUE TITLE
choco package

### ISSUE THREAD

**Issue by ParsaAslaniYC** [SFML/SFML#2876]
### Prerequisite Checklist

- [x] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### Describe your feature request here

Hi. i have a windows device, and i noticed there is no choco package. 

### Use Cases

easy install on windows

### API Example

```bash
choco install libsfml
```

**Comment by ChrisThrasher** [comment]
If you would like choco to distribute SFML then you need to take that up with the choco project.

**Comment by eXpl0it3r** [comment]
Also note that Chocolatey isn't really made for installing libraries. You will have better luck with vcpkg or conan

**Comment by ParsaAslaniYC** [comment]
But i have installed many lib's with choco
