### ISSUE TITLE
Android CI jobs have broken

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#2878]
### Describe your issue here

https://github.com/SFML/SFML/actions/runs/7521531922/job/20472479779

The Android CI jobs are failing on the latest `master`.

**Comment by ChrisThrasher** [comment]
@texus Do you mind taking a look at this? The code failing first appeared in https://github.com/SFML/SFML/issues/2878. Thank you!

**Comment by eXpl0it3r** [comment]
Might be related to: https://github.com/actions/runner-images/issues/8952
