### ISSUE TITLE
Add a CMake guide for static linking the library in MacOS/Linux

### ISSUE THREAD

**Issue by lazarovziv** [SFML/SFML#2900]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### Describe your feature request here

I'm looking to link the sfml-audio/graphics/network/system/window libraries statically to my C++ project and I'm working on a Unix machine, which in you website there's a guide for doing it only for Visual Studio.

### Use Cases

When wanting to create an executable for both macOS and Linux, just recompile the program on the relevant OS and you're good to go!

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/cmake-sfml-project

This guide already covers how to statically link.
