### ISSUE TITLE
`sf::VideoMode::getDesktopMode()` returning the monitor resolution on macOS

### ISSUE THREAD

**Issue by alihakankurt** [SFML/SFML#2906]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

My monitor resolution is 3420x2224 and my screen resolution is set to 1720x1112. The `sf::VideoMode::getDesktopMode()` is returning the correct screen resolution on Windows but it's returning the monitor resolution on macOS (in my case 3420x2224). I think it's related to the `scaleOutXY` function in the [cf_sf_conversion.mm](https://github.com/SFML/SFML/blob/master/src/SFML/Window/macOS/cg_sf_conversion.mm#L73) file because the `CGDisplayModeGetWidth()` and `CGDisplayModeGetWidth()` functions returning the correct screen resolution values.

### Your Environment

- OS / distro / window manager: macOS Ventura 13.5.1
- SFML version: 3.0.0
- Compiler / toolchain: Apple clang version 15..0.0 (clang-1500.1.0.2.5)
- Special compiler / CMake flags:

### Steps to reproduce

1. 
2. 

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    const sf::VideoMode desktop = sf::VideoMode::getDesktopMode();
    const unsigned int width = desktop.size.x / 2;
    const unsigned int height = desktop.size.y / 2;

    // The windows goes out of screen because of wrong screen resolution.
    sf::RenderWindow window(sf::VideoMode({width, height}), "Minimal, complete and verifiable example");
    window.setFramerateLimit(60);

    while (window.isOpen())
    {
        for (sf::Event event; window.pollEvent(event);)
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.display();
    }
}
```

### Expected behavior

The `sf::VideoMode::getDesktopMode()` should have return the screen resolution which is set by user.

### Actual behavior

The `sf::VideoMode::getDesktopMode()` returned the monitor resolution independently from screen resolution.

**Comment by ChrisThrasher** [comment]
Have you read #2300 yet?

**Comment by alihakankurt** [comment]
I checked the current issues to prevent duplication. I saw that issue and I don't think it's related to the my problem. The `sf::VideoMode::getFullscreenModes()` also returning empty and causing segfault but my problem is inconsistency between Windows and macOS platforms. `sf:: VideoMode::getDesktopMode()` returning the user set screen resolution on Windows, but on macOS it's returning the monitor resolution (or the full screen resolution). I as described above, when I remove the `scaleOutXY` function from source code, it's returning the correct values of my custom screen resolution.

**Comment by alihakankurt** [comment]
I tried creating a window with different display sizes using the `sf::VideoMode::getDesktopMode()` function. It seems to be returning the display size correctly and independent of the monitor now. The problem is solved for me, you can close the issue.
