### ISSUE TITLE
Install prefix not honored

### ISSUE THREAD

**Issue by mgrojo** [SFML/SFML#2913]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

I tried to install as a regular user but a system path was tried to be written.

### Your Environment

- OS / distro / window manager: Ubuntu 22.04.4 LTS / Xwayland
- SFML version: b71e8c1dfc52788f8e5953c8ba349d6700fcfe41
- Compiler / toolchain: GCC
- Special compiler / CMake flags:

### Steps to reproduce

`cmake --install . --prefix $HOME/local`

### Expected behavior

Everything is installed under `$HOME/local` with regular user permissions.

### Actual behavior

```
-- Install configuration: "Release"
-- Installing: /home/mgr/local/lib/libcsfml-system.so.3.0.0
-- Installing: /home/mgr/local/lib/libcsfml-system.so.3.0
-- Installing: /home/mgr/local/lib/libcsfml-system.so
-- Installing: /home/mgr/local/lib/libcsfml-window.so.3.0.0
-- Installing: /home/mgr/local/lib/libcsfml-window.so.3.0
-- Installing: /home/mgr/local/lib/libcsfml-window.so
-- Installing: /home/mgr/local/lib/libcsfml-network.so.3.0.0
-- Installing: /home/mgr/local/lib/libcsfml-network.so.3.0
-- Installing: /home/mgr/local/lib/libcsfml-network.so
-- Installing: /home/mgr/local/lib/libcsfml-graphics.so.3.0.0
-- Installing: /home/mgr/local/lib/libcsfml-graphics.so.3.0
-- Installing: /home/mgr/local/lib/libcsfml-graphics.so
-- Installing: /home/mgr/local/lib/libcsfml-audio.so.3.0.0
-- Installing: /home/mgr/local/lib/libcsfml-audio.so.3.0
-- Installing: /home/mgr/local/lib/libcsfml-audio.so
CMake Error at cmake_install.cmake:59 (file):
  file cannot create directory: /usr/local//pkgconfig.  Maybe need
  administrative privileges.
```

**Comment by ChrisThrasher** [comment]
Did you mean to file this bug under the CSFML repository?

**Comment by mgrojo** [comment]
Oops, yes.

Can I simply close this and copy it to CSFML?

**Comment by ChrisThrasher** [comment]
Please reopen this on the CSFML repo
