### ISSUE TITLE
MacOS static release 

### ISSUE THREAD

**Issue by humbertodias** [SFML/SFML#2921]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### Describe your feature request here

Please, add static libraries on macOS release
```sh
mkdir build && cd build
cmake -DBUILD_SHARED_LIBS=OFF ..
make
ls lib
lib/libsfml-audio-s.a
lib/libsfml-graphics-s.a
lib/libsfml-network-s.a
lib/libsfml-system-s.a
lib/libsfml-window-s.a
```

### Use Cases

I was trying to release a [game](https://github.com/vmbatlle/super-mario-kart/pull/63) that uses sfml library and unfortunately using brew only the shared version was available.
So, I tried to find a static compiled version for Mac OS and didn't find.
Therefore, that's the reason of this feature

### API Example

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode({1280, 720}), "Minimal, complete and verifiable example");
    window.setFramerateLimit(60);

    while (window.isOpen())
    {
        for (sf::Event event; window.pollEvent(event);)
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.display();
    }
}
```

**Comment by ChrisThrasher** [comment]
Whether or not we distribute shared macOS libraries is a matter outside of this repo. SFML can be built as static libraries as you have shown. If you would like to use static libraries, you can use the libraries you already built. You can also configure Conan and Vcpkg to provide static libraries. You can also use the [CMake project template](https://github.com/SFML/cmake-sfml-project) we provide which makes it very easy to build SFML (in any configuration want, including static libs) alongside your application. There are number of options that are much superior to us compiling static libraries and giving them to you.
