### ISSUE TITLE
Cannot disable SFML installation targets when installing a game which includes SFML with fetch content

### ISSUE THREAD

**Issue by K20shores** [SFML/SFML#2928]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

I opened a [related issue in the cmake template repository](https://github.com/SFML/cmake-sfml-project/issues/39), but the actual issue is with the SFML cmake files. The installation targets cannot be turned off. When SFML is included with `fetch_content` and you install an application or package it with cpack, the SFML include, lib, and share directories are automaticaly included.

A fix would be to add some cmake variable which can disable all installation targets. Is that desired or am I barking up the wrong tree?

### Your Environment

- OS / distro / window manager: macos
- SFML version: 2.6.x
- Compiler / toolchain: gcc/clang
- Special compiler / CMake flags:

### Steps to reproduce

1. Clone the [cmake template repository](https://github.com/SFML/cmake-sfml-project]
2. Build (`cmake -DCMAKE_INSTALL_PREFIX=install`)
3. `make install`
4. Observe the SFML libraries, headers, and share folder also being installed

### Expected behavior

SFML libraries are not automatically installed when included with fetch content and can be enabled or disabled

### Actual behavior

SFML libraries are automatically installed when included with fetch content and cannot be enabled or disabled

**Comment by eXpl0it3r** [comment]
@ChrisThrasher I know you aren't a fan of the install target/don't generally use it, but it's an issue for those using it with fetch_content.  
Have you ever seen any guidelines on dealing with install targets?

**Comment by K20shores** [comment]
@eXpl0it3r I was able to exclude things from SFML

```
  FetchContent_Declare(sfml
      GIT_REPOSITORY https://github.com/SFML/SFML.git
      GIT_TAG        2.6.1
  )

  set(CPACK_SOURCE_IGNORE_FILES ${sfml_SOURCE_DIR})
  # FetchContent_MakeAvailable(sfml)
  if(NOT sfml_POPULATED)
    FetchContent_Populate(sfml)
    add_subdirectory(${sfml_SOURCE_DIR} ${sfml_BINARY_DIR} EXCLUDE_FROM_ALL)
  endif()
```

Both `CPACK_SOURCE_IGNORE_FILES` and `EXCLUDE_FROM_ALL` seem to be required

**Comment by JonnyPtn** [comment]
Yes, that's the correct fix, as proposed for the cmake template here: https://github.com/SFML/cmake-sfml-project/pull/28

**Comment by eXpl0it3r** [comment]
I'm closing this, as there's a way to work around it on the consumer end and with OpenAL gone, we have one less issue to worry about.

Feel free to add ideas if you think you know, how we can handle this better on the library side.
