### ISSUE TITLE
sfml window example crashes due to acess violation on joystick driver ezfrd64.dll

### ISSUE THREAD

**Issue by sca255** [SFML/SFML#2955]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

i have a generic joystick with a driver containing EZFRD64.dll so the exe crashes due to that
and in the stack trace it causes access violation 
here is the details:
Unhandled exception at 0x0000000010003654 (EZFRD64.dll) in craft++.exe: 0xC0000005: Access violation reading location 0x000000003B5C0090.

### Your Environment

-windows 64 bit
- SFML version: 2.6.1 64 bit
- visual studio 2022 /vc17
- 

### Steps to reproduce

#include <SFML/Window.hpp>

int main()
{
    sf::Window window(sf::VideoMode(800, 600), "My window");

    // run the program as long as the window is open
    while (window.isOpen())
    {
        // check all the window's events that were triggered since the last iteration of the loop
        sf::Event event;
        while (window.pollEvent(event))
        {
            // "close requested" event: we close the window
            if (event.type == sf::Event::Closed)
                window.close();
        }
    }

    return 0;
}

### Expected behavior

the exe should run and not crash

### Actual behavior

the exe crashes after 5 seconds i cannot move or close it in that time

**Comment by eXpl0it3r** [comment]
Sounds like a broken driver. If you do a web search for "EZFRD64.dll", you'll get a lot of similar results.

One of the "solutions" I saw is to remove the specific DLL from `C:\Windows\USB_Vibration\**\EZFRD64.dll`.  
Some say that this disables the vibration functionality though (note that SFML doesn't support rumble).

I'm closing this, as it doesn't seem like something we can "fix" in SFML.

**Comment by sca255** [comment]
oh ok
