### ISSUE TITLE
Store angles internally as radians

### ISSUE THREAD

**Issue by L0laapk3** [SFML/SFML#2976]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### Describe your feature request here

It has been mildly bothering me that angles are internally stored as degrees instead of radians.

It makes more sense to store them internally in radians, since [thats what hardware is optimized for](https://www.felixcloutier.com/x86/fsin). Rather than [having to convert them to radians all the time](https://github.com/SFML/SFML/blob/2386653bd3df5639b9ae537e671d7c9557a774c1/src/SFML/System/Vector2.cpp#L65), only to [have to convert them back immediately after](https://github.com/SFML/SFML/blob/2386653bd3df5639b9ae537e671d7c9557a774c1/src/SFML/Graphics/Transform.cpp#L40).

Especially now that in 3.0 angles are unit-aware with `sf::Angle`, I don't see any reason to use degrees anymore.

Its a fairly trivial change and I'd be happy to PR it myself, but I suspect this is the kind of thing that needs to be discussed first ;)

### Use Cases

`transform.rotate(vector.angle())`

**Comment by vittorioromeo** [comment]
I've done the work so we can discuss pros/cons:
https://github.com/SFML/SFML/pull/2978

**Comment by ChrisThrasher** [comment]
I'm open to this idea if it means fewer lossy conversions between degrees and radians. The fact that the standard library exclusively uses radians compels me to prefer radians. I can't imagine users noticing or caring what underlying representation we choose.

**Comment by kimci86** [comment]
> I can't imagine users noticing or caring what underlying representation we choose.

Well, no need to imagine, this issue is a proof :smile:

On a more serious note, I agree that this is a good idea.
