### ISSUE TITLE
`operator*` overload in sf::Vector2<T> and sf::Vector3<T> template class

### ISSUE THREAD

**Issue by alberto-cardini** [SFML/SFML#2993]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### `operator*` overload in sf::Vector2<T> and sf::Vector3<T> template class
Now is available only the Vector and scalar product. Would be nice to also implement dot product between same dimensions vectors. 

### Use Cases

It can be useful to do calculations between vector without needing to access the single components. It is often used to do vector calculations in physic evaluations. 
So it would be faster for the programmer to implement calculations with dot product and would also be less verbose and more pragmatic.  

### API Example

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode({1280, 720}), "Minimal, complete and verifiable example");
    window.setFramerateLimit(60);
    sf::Vector2f A(10,-10);
    sf::Vector2f B(-10,10);
    sf::Vector2f C = A * B;
    // instead of doing C = sf::Vector2f(A.x * B.x, A.y * B.y);
    while (window.isOpen())
    {
        while (const auto event = window.pollEvent())
        {
            if (event.is<sf::Event::Closed>())
                window.close();
        }

        window.clear();
        window.display();
    }
}
```

**Comment by Bambo-Borris** [comment]
Pretty sure I've seen this discussion before and the usual issues of the intent of `*` for vectors not making sense when written. I think this is a ill-fitting use of the `operator *`. Component-wise multiplication is something the new extension methods already cover for SFML and it's much more clear at a glance what `vec.cwiseMul(otherVec)` means, whereas `vec * otherVec` does not convey the meaning well.

**Comment by eXpl0it3r** [comment]
As @Bambo-Borris mentioned, `*` can have double meanings for vectors, which is why we've implemented both function as separate methods and refrained from using the `operator*`.
