### ISSUE TITLE
iOS reports gyroscope rates as deg/s while Android reports radians/s

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#3001]
iOS:

https://github.com/SFML/SFML/blob/3acc332de06f732331b7e4f989315ab2d5928f99/src/SFML/Window/iOS/SensorImpl.mm#L147-L152

Android:

https://github.com/SFML/SFML/blob/3acc332de06f732331b7e4f989315ab2d5928f99/src/SFML/Window/Android/SensorImpl.cpp#L180-L185

[The docs for `ASENSOR_TYPE_GYROSCOPE`](https://developer.android.com/ndk/reference/group/sensor#group___sensor_1gga8628933cde20921c453a6d2607bdad62a80e9827f6c3ded009f354dc7078a2c68) specify that it reports redians per second, not degrees per second.

**Comment by ChrisThrasher** [comment]
This should be fixed by #2978 by having both iOS and Android report radians and radians per second.

**Comment by eXpl0it3r** [comment]
Fixed with #2978
