### ISSUE TITLE
Add clock speed utility

### ISSUE THREAD

**Issue by jakubbaldyga** [SFML/SFML#3012]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### Describe your feature request here

I believe it wasn't mentioned before. It would be great if clock had its speed and you could change that. Now when there are enhanced shaders in sfml for me such a change would be great.

### Use Cases

In my game i use global clock for most of mechanics from animations to some time locks it would be great if player when dashing or performing some attacks could slow down time. Setting clock speed would be super handy.

### API Example

sf::Clock clock;
clock.start(); //at this point speed is 1

clock.setSpeed(2.f); //double speed
clock.setSpeed(0.5f); //half the speed, slow motion

clock.stop(); //stop

clock.start(); //still speed 0.5f
clock.setSpeed(0.f); //literally same as stop but stop 'remembers' last speed.

**Comment by ChrisThrasher** [comment]
I see the use case you’re describing but I don’t think this is an API I’d be interested in adding.

**Comment by vittorioromeo** [comment]
I agree with Chris, I think this sort of feature is better suited to your own thin wrapper around `sf::Clock`.

I would also recommend using in-game ticks to calculate cooldowns and animation timing rather than system clock in order to achieve deterministic and easily reproducible gameplay (good for networking and replays).
