### ISSUE TITLE
SFML Event Intermediate classes are not fully featured Events.

### ISSUE THREAD

**Issue by L0laapk3** [SFML/SFML#3023]
This issue is meant as a discussion starting point.

Currently, the Event API makes some attempts to introduce a class structure into the events. There are for example already `TouchChanged`, `MouseButtonChanged` event classes exposed.

However, these are not treated the same way as other events, and are as a result of that not very convenient to use. I would like to see this change.

Ideally, I would like the API to be able to do something like this:  
(Listed in comments are limitations of the current API as to why this is not possible right now in a neat way.)
```cpp
void main() {
  sf::Event baseEvent = window.pollEvent();
  // Problem 1: event.getIf<parentClass>() is not possible, you have to exhaustively try getIf on all the event types.
  // Problem 2: There are not enough event parent classes: `MouseButtonChanged` exists, `MousePosition` doesn't.
  if (auto mouseEvent = baseEvent.getIf<sf::Event::MousePosition>()) {
	auto* myWorldBlock = myWorld.getBlockAtLocation(mouseEvent.position);
	if (myWorldBlock)
		if (myWorldBlock->handleEvent(mouseEvent))
		  return true;
    
	// handle other events
  }
}

// Problem 3: Cannot be explicit about only accepting MousePosition event types
bool myWorldBlock::handleEvent(const sf::Event::MousePosition& event) {
	// Problem 4: `event.getIf()` cannot be called on the sub event classes
	if (auto& scrollEvent = event.getIf<sf::Event::MouseWheelScrolled>()) {
		// handle event
		return true;
	}
	// handle other mouse events
	return false;
}
```

To achieve this, I propose the following Event changes:
1. Add more Event parent class groups such as `Event::Mouse`, `Event::Joystick`, `Event::MousePosition`.
2. All Events inherit some common base class which provides `.is()`, `.getIf()`.

**Comment by vittorioromeo** [comment]
My understanding is that the types `KeyChanged`, `MouseButtonChanged', `JoystickButtonChanged`, `JoystickChanged`, and `TouchChanged` are just implementation details to avoid repetition when writing the event fields. Is that true, @ChrisThrasher? If so, we can hide them under `priv` or (gasp) use a macro to avoid the repetition.

**Comment by ChrisThrasher** [comment]
They’re meant to be used and are not something I want to hide.

**Comment by vittorioromeo** [comment]
> They’re meant to be used and are not something I want to hide.

How can they be used?

**Comment by ChrisThrasher** [comment]
https://github.com/search?q=repo%3ASFML%2FSFML+KeyChanged&type=code

**Comment by ChrisThrasher** [comment]
> // Problem 2: There are not enough event parent classes: `MouseButtonChanged` exists, `MousePosition` doesn't.

What about `sf::Event::MouseMoved`?

**Comment by vittorioromeo** [comment]
> https://github.com/search?q=repo%3ASFML%2FSFML+KeyChanged&type=code
> 
> https://github.com/SFML/imgui-sfml/blob/7758bfd06326af08dc919198c13f9f0e64e70b1a/imgui-SFML.cpp#L317-L333

I'm not convinced these uses are worthwhile supporting. They can be handled without relying on these "intermediate" classes that do cause confusion as shown by this issue:

```cpp
//
//
// BEFORE
sf::Event::KeyChanged keyChanged;
keyChanged.code     = kb;
keyChanged.scancode = sf::Keyboard::Scan::Unknown; // TODO: not implemented
keyChanged.alt      = altDown();
keyChanged.control  = controlDown();
keyChanged.shift    = shiftDown();
keyChanged.system   = systemDown();

if (inputEvent.value)
    event = sf::Event::KeyPressed{keyChanged};
else
    event = sf::Event::KeyReleased{keyChanged};

//
//
// AFTER
auto makeEvent = [](auto e)
{
    e.code     = kb;
    e.scancode = sf::Keyboard::Scan::Unknown; // TODO: not implemented
    e.alt      = altDown();
    e.control  = controlDown();
    e.shift    = shiftDown();
    e.system   = systemDown();
    return e;
};

if (inputEvent.value)
    event = makeEvent(sf::Event::KeyPressed{});
else
    event = makeEvent(sf::Event::KeyReleased{});
```

```cpp
//
//
// BEFORE
const auto handleKeyChanged = [&io](const sf::Event::KeyChanged& keyChanged, bool down) {
    // ...
};
if (const auto* keyPressed = event.getIf<sf::Event::KeyPressed>()) {
    handleKeyChanged(*keyPressed, true);
} else if (const auto* keyReleased = event.getIf<sf::Event::KeyReleased>()) {
    handleKeyChanged(*keyReleased, false);
}

//
//
// AFTER
const auto handleKeyChanged = [&io](const auto& keyChanged, bool down) {
    // ...
};
if (const auto* keyPressed = event.getIf<sf::Event::KeyPressed>()) {
    handleKeyChanged(*keyPressed, true);
} else if (const auto* keyReleased = event.getIf<sf::Event::KeyReleased>()) {
    handleKeyChanged(*keyReleased, false);
}
```

Since users are not meant to use `getIf` or eventually visitation with these intermediate events, and since all uses you've shown are pretty much SFML implementation details, I think it would be best to hide them as implementation details or get rid of them.

**Comment by L0laapk3** [comment]
> > // Problem 2: There are not enough event parent classes: `MouseButtonChanged` exists, `MousePosition` doesn't.
> 
> What about `sf::Event::MouseMoved`?

The point of my example is to be able to easily select all the events that have a shared concept of "position", resolve that position to an object in the gameworld if there is any, and forward the event to that object. So arguably it should even be `Event::Position` which includes both mouse and touch events.

I think that case is the strongest use case for a better Event class hierarchy, a similar style example could be created for the joystick events which all have a shared "joystickId" concept, where you send the event to different handlers based on the joystickId.

**Comment by vittorioromeo** [comment]
> point of my example is to be able to easily select all the events that have a shared concept of "position", resolve that position to an object in the gameworld if there is any, and forward the event to that object. So arguably it should even be `Event::Position` which includes both mouse and touch events.

```cpp
template <typename T>
[[nodiscard]] bool handlePositionalEvent(const T* event)
{
    if(event == nullptr) { return false; }

    auto* myWorldBlock = myWorld.getBlockAtLocation(event->position);
    // ...use `myWorldBlock`...

    return true;
}

int main()
{
    while (sf::Event baseEvent = window.pollEvent())
    {
        if (handlePositionalEvent(baseEvent.getIf<sf::Event::MousePosition>()) ||
            handlePositionalEvent(baseEvent.getIf<sf::Event::MouseWheelScrolled>() ||
            handlePositionalEvent(baseEvent.getIf<sf::Event::MouseButtonChanged>())
        {   
            // ...positional event handled!
        }
        
        // ...handle other events...
    }
}
```

**Comment by vittorioromeo** [comment]
@L0laapk3's use case with #3015:

```cpp
template <typename T>
[[nodiscard]] bool handlePositionalEvent(const T& event)
{
    auto* myWorldBlock = myWorld.getBlockAtLocation(event.position);
    // ...use `myWorldBlock`...

    return true;
}

int main()
{
    pollEvents(window, 
        [&](sf::Event::MousePosition e)      { handlePositionalEvent(e); },
        [&](sf::Event::MouseWheelScrolled e) { handlePositionalEvent(e); },
        [&](sf::Event::MouseButtonChanged e) { handlePositionalEvent(e); },
        // ...handle other events...
    );
}
```

**Comment by vittorioromeo** [comment]
@L0laapk3's use case with #3015 and concepts:

```cpp
template <typename T>
[[nodiscard]] bool handlePositionalEvent(const T& event)
{
    auto* myWorldBlock = myWorld.getBlockAtLocation(event.position);
    // ...use `myWorldBlock`...

    return true;
}

int main()
{
    pollEvents(window, 
        [&](OneOf<sf::Event::MousePosition, sf::Event::MouseWheelScrolled, sf::Event::MouseButtonChanged> auto e)      
        { 
            handlePositionalEvent(e); 
        },
        // ...handle other events...
    );
}
```

**Comment by L0laapk3** [comment]
> No need for any hierarchy.
> 
> ```c++
>  if (handlePositionalEvent(event.getIf<sf::Event::MousePosition>()) ||
>    handlePositionalEvent(event.getIf<sf::Event::MouseWheelScrolled>() ||
>    handlePositionalEvent(event.getIf<sf::Event::MouseButtonChanged>())
> ```

This is exactly what I don't want to do, list all the possible event types that have the same shared concept.

Plus, `getIf<sf::Event::MouseButtonChanged>()` doesn't even work right now, that is part of this issue. You'd need to list each of those options out as well.

I'd much rather have a single parent type for all events that share a concept (for example position). This has the following advantages:
1. The code is much cleaner
2. By using inheritance, this also guarantees that the data member of the shared concept is on the same location, which means a single function is able to work with the shared concept, rather than requiring a list of template functions.

**Comment by ChrisThrasher** [comment]
For starters I'll say I'm not interested in expanding the inheritance hierarchy. I don't think that's the right way forward.

I'm wiling to hear out proposals for APIs like `event.getIf<sf::Event::KeyChanged>()` if anyone knows a reasonable way to implement that. I currently can't picture how we'd implement that.

**Comment by vittorioromeo** [comment]
> > No need for any hierarchy.
> > ```c++
> >  if (handlePositionalEvent(event.getIf<sf::Event::MousePosition>()) ||
> >    handlePositionalEvent(event.getIf<sf::Event::MouseWheelScrolled>() ||
> >    handlePositionalEvent(event.getIf<sf::Event::MouseButtonChanged>())
> > ```
> 
> This is exactly what I don't want to do, list all the possible event types that have the same shared concept.

I don't think it's a big deal -- we're not representing events as a class hierarchy but as a sum type, so they are all different event types. The fact that some of them share some data is an implementation detail.

> Plus, `getIf<sf::Event::MouseButtonChanged>()` doesn't even work right now, that is part of this issue. You'd need to list each of those options out as well.

You are right, I apologize. You would have to use both `MouseButtonPressed` and `MouseButtonReleased`.

> I'd much rather have a single parent type for all events that share a concept (for example position). This has the following advantages:
> 
> 1. The code is much cleaner

I'm not sure I agree on this one -- we lose "exhaustiveness checking": to ensure that we're handling all event types we need to look at the class hierarchy and manually figure out if we're covering everything. It is also a design that's incompatible with visitation.

> 2. By using inheritance, this also guarantees that the data member of the shared concept is on the same location, which means a single function is able to work with the shared concept, rather than requiring a list of template functions.

You don't really need a list of large template functions. If all you care about is the `position` of a mouse event... just pass the position!

```cpp
[[nodiscard]] void handlePositionalEvent(const sf::Vector2f& position)
{
    auto* myWorldBlock = myWorld.getBlockAtLocation(position);
    // ...use `myWorldBlock`...
}

int main()
{
    while (sf::Event event = window.pollEvent())
    {
             if (auto* e = event.getIf<sf::Event::MousePosition>())       { handlePositionalEvent(e->position); } 
        else if (auto* e = event.getIf<sf::Event::MouseWheelScrolled>())  { handlePositionalEvent(e->position); }
        else if (auto* e = event.getIf<sf::Event::MouseButtonPressed>())  { handlePositionalEvent(e->position); }
        else if (auto* e = event.getIf<sf::Event::MouseButtonReleased>()) { handlePositionalEvent(e->position); }
        
        // ...handle other events...
    }
}
```

Of course using a template would reduce repetition here:

```cpp
int main()
{
    auto handlePositionalEvents = []<typename... Ts>(const sf::Event& event)
    {
        return ((event.is<Ts>() && handlePositionalEvent(event.getIf<Ts>()->position)) || ...);
    };

    while (sf::Event event = window.pollEvent())
    {
        if (handlePositionalEvents<sf::Event::MousePosition, 
                                   sf::Event::MouseWheelScrolled,
                                   sf::Event::MouseButtonPressed,
                                   sf::Event::MouseButtonReleased>()) { /* ... */ }

        // ...handle other events...
    }
}
```

But then again I'm not convinced that you want to handle all this events in the same way -- you probably have some common shared behavior (i.e. the `handlePositionalEvent` function in my example), but then you want to do something specific to the scroll wheel, or button presses, etc...

**Comment by L0laapk3** [comment]
> For starters I'll say I'm not interested in expanding the inheritance hierarchy. I don't think that's the right way forward.
> 
> I'm wiling to hear out proposals for APIs like event.getIf<sf::Event::KeyChanged>() if anyone knows a reasonable way to implement that. I currently can't picture how we'd implement that.

I have some ideas to implement this but I don't think it is worth it for just the `changed` events, I think it is necessary to at least unduplicate shared concept members `position`, `joystickId` for it to be useful.

> The fact that some of them share some data is an implementation detail.

This is not true right now (Event::fooChanged) and IMO this is a good thing. (Thats what I'm wanting to expand)

> we lose "exhaustiveness checking"

Its unclear to me what you mean with this in relation to sf::Event, can you give an example?

> You don't really need a list of large template functions. If all you care about is the position of a mouse event... just pass the position!

If you unroll the part you needed the templates for before yourself, then sure you do not need the template function anymore

> Of course using a template would reduce repetition here

What would really reduce repetition here is not insisting on duplicating the same members into multiple events and instead using inheritance :D .

> But then again I'm not convinced that you want to handle all this events in the same way -- you probably have some common shared behavior (i.e. the handlePositionalEvent function in my example), but then you want to do something specific to the scroll wheel, or button presses, etc...

You are correct that there is some shared behavior based on the shared members, followed by some specific behavior based on the actual event.

The key for what makes this useful if that you have many different options for handling the specific behavior, and the shared behavior selects which option applies.

For example, imagine you have a 2D topdown minecraft-like world, with a bunch of block types implemented as virtual classes. It is nice to then be able to create a virtual function in the block classes that handles the specific event behavior, and be able to declare those functions in a way that it is clear that it only makes sense for events that have the `position` field. It is also nice that the upper level world event handler can keep the block resolve function concise without having to resort to enumerating all mouse event types which it has nothing to do with.
