### ISSUE TITLE
Adopt clang-tidy's `readability-else-after-return` check

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#3024]
https://clang.llvm.org/extra/clang-tidy/checks/readability/else-after-return.html

We currently disable `readability-else-after-return` which is a wonderful check that finds easy ways to improve readability, reduce indentation, and reduce line count. It's an all around win to enforce this check and transform SFML to adhere to it. Lots of new code written already adheres to style since the benefits of guard clauses are well established.

clang-tidy offers an automatically fixer for this check so actually writing the PR will be as easy as letting clang-tidy rewrite the codebase.

**Comment by ChrisThrasher** [comment]
@vittorioromeo and I have discussed this in past PRs and we both prefer this style. I'm happy to write the commit in case we want to look at how the code actually changes. That may help us understand this check and what exactly it will change about SFML.

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/compare/master...ChrisThrasher:SFML:else-after-return

<img width="263" alt="Screenshot 2024-05-19 at 11 41 01 AM" src="https://github.com/SFML/SFML/assets/39244355/7a1adc74-5ca2-4a93-abe4-95f081936b98">

Here's most of what this change will look like. This only took a few minutes of running clang-tidy locally to get this far. If we agree on this I won't rebase this branch but rather just do it all again on the current state of `master`.

**Comment by eXpl0it3r** [comment]
Looks good to me, although I prefer an extra empty line between the statements, e.g.:

```cpp
if (bla)
    return true;

return false;
```

**Comment by ChrisThrasher** [comment]
> although I prefer an extra empty line between the statements, e.g.:

Happy to make these tweaks when I get to an actual PR
