### ISSUE TITLE
Support moving `sf::Music`s

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#3044]
### Describe your feature request here

PRs like #3021 require move operations so that the objects can be moved into and out of `std::optional`s. `sf::Music` needs to support move operations before we can remove its default constructor and switch to a factory function approach for constructing it.

I briefly looked into how we might achieve this but it wasn't obvious to me. We need to make sure when moving a music, the sound being played does not stop.

**Comment by vittorioromeo** [comment]
PImpl `sf::Music`?

**Comment by ChrisThrasher** [comment]
> PImpl `sf::Music`?

I'd prefer a solution that doesn't require PIMPL since I find it pretty annoying have to hide everything behind a pointer indirection but it certainly would work. My desire to finish the `std::optional`-ification of SFML 3 is greater than my annoyance with using PIMPL in one more place.

**Comment by vittorioromeo** [comment]
Will be fixed by #3075.

**Comment by ChrisThrasher** [comment]
Closed by #3075
