### ISSUE TITLE
Windows GCC 13.2 compilation failed

### ISSUE THREAD

**Issue by Nathan-M-code** [SFML/SFML#3054]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

Compilation failed during linking

### Your Environment

- OS / distro / window manager: Windows 64bits
- SFML version: 2.6.1
- Compiler / toolchain: gcc 13.2 seh posix urct
- Special compiler / CMake flags: Release

### Steps to reproduce

```ps
$repoUrl = "https://github.com/SFML/SFML"
$gitTag = "2.6.1"


# Clone the repository at the specified tag
git clone -b $gitTag $repoUrl

# Change the working directory to external_deps/SFML
cd SFML
md build
cd build
$SFML_build = $PWD

# Execute the cmake command
cmake -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$installPath" ..

# Build the project
cmake --build . --target all

# Install the project
cmake --install .
```

### Expected behavior

Compilation success

### Actual behavior

[ 15%] Built target sfml-system
[ 17%] Built target sfml-main
[ 42%] Built target sfml-window
[ 53%] Built target sfml-network
[ 54%] Linking CXX shared library ..\..\..\lib\sfml-graphics-2.dll
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .../external_deps/SFML/extlibs/libs-mingw/x64/libfreetype.a(sfnt.c.obj):sfnt.c:(.text+0x5614): undefined reference to `_setjmp'
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: .../external_deps/SFML/extlibs/libs-mingw/x64/libfreetype.a(smooth.c.obj):smooth.c:(.text+0x77a): undefined reference to `_setjmp'
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [src\SFML\Graphics\CMakeFiles\sfml-graphics.dir\build.make:602: lib/sfml-graphics-2.dll] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:307: src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/all] Error 2
mingw32-make: *** [Makefile:155: all] Error 2

**Comment by Nathan-M-code** [comment]
UCRT doesnt work, I needed to switch to MSVCRT version of gcc.
If it is written somewhere my bad I didn't see it,
else it is something good to know on the tuto [compile-with-cmake](https://www.sfml-dev.org/tutorials/2.6/compile-with-cmake.php)

**Comment by eXpl0it3r** [comment]
Start with SFML 2.6.2, we'll be issuing an error when trying to use a UCRT version, see #2821

But given the prevalence of this issue, we may need to just go and recompile freetype 😄
