### ISSUE TITLE
`sf::Texture` move semantics implementation inconsistencies

### ISSUE THREAD

**Issue by vittorioromeo** [SFML/SFML#3077]
I noticed that `sf::Texture`'s move operations do not exchange `m_pixelsFlipped` nor `m_hasMipmap`, is this intended or an oversight?

One more inconsistency is that the move operations exchange `m_cacheId` with `0`, but `swap` does this:

```cpp
void Texture::swap(Texture& right) noexcept
{
    std::swap(m_size, right.m_size);
    // ... 
    m_cacheId       = TextureImpl::getUniqueId();
    right.m_cacheId = TextureImpl::getUniqueId();
}
```

Should `m_cacheId` be always reset to a unique id even as a consequence of a move?

**Comment by vittorioromeo** [comment]
@binary1248: what is the reason that `swap` does not simply swap the cache IDs, instead generating two new ones? Are our move operations incorrect in setting the moved-from texture's cache ID to `0`? See #3077 for context.

**Comment by vittorioromeo** [comment]
Some previous discussion here: https://github.com/SFML/SFML/pull/2479#pullrequestreview-1363542042

I find it hard to understand. If moving cache IDs works, then swapping should as well...

**Comment by binary1248** [comment]
#3078 was merged, closing this.
