### ISSUE TITLE
Ensure that all `std::optional` factory functions print errors to `sf::err()` in case of failure

### ISSUE THREAD

**Issue by vittorioromeo** [SFML/SFML#3081]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### Describe your feature request here

As `std::optional` does not carry any additional error information with it, and as we decided to keep the API simple and not use a in-house version of `std::expected`, we should ensure that errors are propagated through the `sf::err()` stream.

There are a few places where errors are not being printed out:

- `sf::InputSoundFile::openFromFile`
- `sf::InputSoundFile::openFromMemory`
- `sf::InputSoundFile::openFromStream`
- `sf::Music::tryOpenFromFile`
- `sf::OutputSoundFile::openFromFile`
- `sf::SoundBuffer::loadFromFile`
- `sf::SoundBuffer::loadFromMemory`
- `sf::SoundBuffer::loadFromStream`
- `sf::SoundBuffer::initialize`
- `sf::Texture::loadFromFile`
- `sf::Texture::loadFromMemory`
- `sf::Texture::loadFromStream`
- `sf::Texture::loadFromImage`
- `sf::IpAddress::resolve` (arguable, it's not really loading a resource)
- `sf::IpAddress::getLocalAddress`
- `sf::IpAddress::getGlobalAddress`
- `sf::Cursor::loadFromPixels`
- `sf::Cursor::loadFromSystem`

### Use Cases

Giving users feedback on why resource loading failed.

### API Example

N/A

**Comment by vittorioromeo** [comment]
I am working on this.

**Comment by ChrisThrasher** [comment]
Is everyone on the same page that eventually we'd like to replace many uses of `sf::err()` with a string-like error type inside a `std::expected` return value? That was part of my rationale when advocating for `std::optional` return values in SFML 3. I want to make sure we're united on how to move forward with error messages in future major versions.

**Comment by vittorioromeo** [comment]
> Is everyone on the same page that eventually we'd like to replace many uses of `sf::err()` with a string-like error type inside a `std::expected` return value? That was part of my rationale when advocating for `std::optional` return values in SFML 3. I want to make sure we're united on how to move forward with error messages in future major versions.

I was under the impression that using something like `std::expected` was considered and discussed in https://github.com/SFML/SFML/issues/2139, but we ended up favouring the simpler `std::optional` solution, at least for SFML 3.x.

**Comment by ChrisThrasher** [comment]
#2139 has much to say about why we chose `std::optional` for v3 but my question is asking about v4 and beyond. I personally feel very strongly in favor of using `std::expected` (and thus C++23) in v4. This particular issue is somewhat dependent on us agreeing that using `std::expected` and thus removing many `sf::err` logs is what we want to do in a future version.

**Comment by vittorioromeo** [comment]
> This particular issue is somewhat dependent on us agreeing that using `std::expected` and thus removing many `sf::err` logs is what we want to do in a future version.

I think that at least for SFML 3.x is worth being consistent with our error messages and provide as much context as possible to our users. Ensuring that all our bases are covered will also make it easier to convert those `err()` calls to `std::expected` logs in a future version.
