### ISSUE TITLE
Use backticks to distinguish code from prose in Doxygen documentation

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#3123]
In a number of recent issues we've made a point to update the Doxygen documentation to use backticks around things like `std::null opt` or references to other SFML APIs to ensure that C++ constructors are differentiated from prose. I'm opening this issue to make a note to ourselves that we ought to audit the codebase to find more places where this pattern can be employed.

Here's a before and after to illustrate how this change improves the readability of the docs. The effect is subtle but useful and requires minimum changes to our code. Note how the style of `std::nullopt` has changed.

<img width="961" alt="Screenshot 2024-06-23 at 9 52 51 AM" src="https://github.com/SFML/SFML/assets/39244355/f1d7dcbe-98dc-4090-8d59-d7057af71b7f">

<img width="962" alt="Screenshot 2024-06-23 at 9 52 29 AM" src="https://github.com/SFML/SFML/assets/39244355/1312cca2-5fa2-4fe5-9ccb-327ad404dc7b">

**Comment by ChrisThrasher** [comment]
In particular this needs to happen in the documentation for public APIs. I'm much less concerned about the cleanliness/hygiene/uniformity of private APIs. We don't even run Doxygen on those private APIs.

**Comment by eXpl0it3r** [comment]
One open question is/was whether we should backtick-ify the SFML types as well. As such this issue is kept open.

**Comment by ChrisThrasher** [comment]
I started looking into whether we do this for SFML types and realized it will be a pretty big PR to make such a change. We can do it but there are a _lot_ of places where our docs refer to other SFML types. I do think the monospaced symbol name looks better though.
