### ISSUE TITLE
catch rvalue overloads with const rvalues instead of non-const rvalues

### ISSUE THREAD

**Issue by ZXShady** [SFML/SFML#3125]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### Describe your feature request here

in Graphics/Sprite.hpp there is deleted overloads for rvalue textures
```cpp
Sprite(Texture&& texture, const IntRect& rectangle) = delete;
```

now this covers majority of rvalues but there is an issue in highly templated code const-rvalues can be made and it will bind to a const-lvalue or the user accidently tried to move a const object. 

The standard library already does this with `ref`,`cref` with `as_const`.

to fix this make the signature like this
```cpp
Sprite(const Texture&& texture,const IntRect& rect) = delete;
```

### Use Cases

Notifies users who accidently moved a `const` variable

**Comment by ChrisThrasher** [comment]
See #3126

**Comment by ZXShady** [comment]
Oh sorry I did not see this issue.

also offtopic but I gave a reason for passing sf::Vector2 by value. in my previous issue sorry for late reply.

**Comment by ChrisThrasher** [comment]
> Oh sorry I did not see this issue.

What do you mean? I opened this PR ~5 minutes after your issue because it was a really easy fix. This was a good issue to open!

**Comment by ZXShady** [comment]
Oh okay I thought I had duplicated an issue.

sorry for being offtopic but I gave an example for why passing by value would improve performance.

https://github.com/SFML/SFML/issues/3047

**Comment by ChrisThrasher** [comment]
> Oh okay I thought I had duplicated an issue.

No worries. Just check the timestamps. 

> sorry for being offtopic but I gave an example for why passing by value would improve performance.

Please don't plug unrelated issues on GitHub. If you would like to get the team's attention about another issue then please join our Discord server where you speak with us.

**Comment by ZXShady** [comment]
okay thank you very much.

**Comment by eXpl0it3r** [comment]
Thank you for bringing this to our attention! 🙂
