### ISSUE TITLE
Consider adding rvalue overload for sf::String::operator+ to allow move semantics

### ISSUE THREAD

**Issue by ZXShady** [SFML/SFML#3133]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### Describe your feature request here

I am sorry if I am posting too many issues.

The current implementation of `sf::String::operator+` is 

```cpp
String operator+(const String& left, const String& right)
{
    String string = left;
    string += right;
    return string;
}
```

this has issues with performance. it does not utilize ~~rvo nor~~ move semantics 
~~change the function into this which is a very simple fix but it increases performance by alot since less copies.~~
adding another overload that takes an rvalue- sf::String would decrease copying by concatening expressions
```cpp
String&& operator+(String&& a,const String& b) {


   return std::move(a += b);

}
```

`a + b + c + d` // used to be 3 copies now 0 moves and 1 copy
will reduce the amount of copies by much another benefit 

[try on godbolt](https://godbolt.org/#z:OYLghAFBqRAWIAuAnApqgNASxBAxgLYCGA1qgILLADOIA5ALQAiAwgLLkDSAogPoBCAVQCSAGSa8AKgE0ACtwCkAZiYAlVABsA6lkRwmqAEbCAdgDMA9nQx4LBAA5YNqZKKIngAVyLBUwgCYgeAoATPyh/Dae1Ih2APKeiPaJAGJOqCZEBKggxFgmGGbptLCo/roWyAEgIYXp1Up1zpnZIBb2LkSxyNQAdHj29higdNZY1KZ4Gp7%2BZfQADGPUbET5AMoWnsh4OXQAjEtxHSYL1hruwNWjAJQYEGUVVYEALE1%2BgQCsby05eSb9g2G9CWk2ms0CdEW2GWqxMGy2O3oB2hRwypww5w8Vzot3u5W61S%2BRWc1QAbN8sjl2KRUKJxog%2BogAB6IIGjaGgmZzSFLFbrTbbXZQ8aok48jEXbG4h4EwIMPZvaoAdgprXZIymRGo1AA1LYTDFUEz7MheDFkPlgDqFErwvNyHg4ERkHqLAbEDqAFQ683KO3kZKGDRYPAgBT2nWR13uo0m6OG42m82W/BOl36mLe83XHUgH0oCDZ622m1McPkKPxxCxl1ERIWHWGVDAfIQHMZj02/g6tCILYmfPIP3FssRqMdms6uuxHUZfxtqvF7vThu6Lu%2BpVlpTdgDucHSOognt0Oa71rCETX25HPdQfeQA6v3dL5Zf29f9oniarNbNKEtg57NaKjniEbAAJ6DpaoQhH65YAG4WFg/g6mYJh7G2cH2ohyGoSYISYe%2B9ogiYUxchCyLjHycICoi%2ByHMcSJnJKgTBBeYTXLc4zUmQsjIBYABWqB4Ig6ICSAComKgO5pCSgQABy3Bo9AfNYYpQhY9CSGgqDnkoyKiTyuIILYszcPilTYLgxIZJSIA8bS9KMiyhRuogax4EQzgSa8lgmIggjUKgshMmJIBfJioCEDSGBBc4IlYG6uBziwFjTAQJwKnOdJSQAcp4BBNsgEkYPYFjULoiUmKl6WZaV5WVW6OWoPlhUuCVcXCYgVVrIgzqIDVBV1Z1CVur1/XNa1RUdX1yADWlQ0zRN%2BQtQV017Lc1C0bs0VkLwBD5FgBAFbwaAAI6eFgaDzgAatwqhrMIcS5TqSi9B81wfgG/FCSJEB/L0Rq6XdD1PS9ey9PMOqiOQuUAOKCOQcPcGsOosAAGujn32uWRD%2BP4vBA3giREEGqD/bCOoAwM9g6u0nTdH0NPY%2BQOIYipanoppDl0jEzmsoZizGUEFhmRZyBWRANk/G0HTIF0lRM4CfnuZ53l7L5bmBcFoXiuJtSRUEEQRLFmhdVVyUmP4g0ZT5GDZStU3tSE5JlRV3VujbmWvG7jUmJNa3O%2BSI0e3Cs3zbVdshz14cB21xUu7F4de1HseO4HCekpt230K%2BIRKPkZGzMBLB4DE5QWMoig4/a%2BQerY9jgSwNjtOB5AYAQFjwagzed937ciZZ/jdFh5DluangiTqaxduWlZrAuZ6D0O7HhNu5cgCAyQMhAMEL59IQhJ976bnPUYAH770uOrD5UxsXuviCBFviTULvh%2BX5hh/H%2BEp9jpGC8OzT1CFna%2BDcm73zXvwDeL8d573wG6GIwCXYHyPnBP%2BFYowLxni7EBp5bRUy7j3SBfoYHbzfvAnBpI8EwR/i%2Bf%2ByDSR0zlgrIcKgEHukYfg7s4Cx6r1IU/Te5D34hHpvLEe7CgFUNQT/Xs/YvR6HGOg0cmCAEgOYQzO%2B7CqF4Ovn3CgJDH7P2ETBMRrDlBMAgDolBtC/RyIfAo/c1BlFnzUS7DR4i74P0sVImhBD7EDk9Io5xJ8VFvn9F9VGZjuieg4UgqhU4W6cISYYbhrjp56mAkwKco9Kx4HPGvbJhhclRgCXqUe9Cx72iiSwkeYQrEgPUUQJJ8T1GpKXOk1G%2BSLH5i6CGXgnkYjKBYNY6hShuAQCID/HUAB6GZ%2BZn76PSd07xjYSmRjKcEIiY8MHlhqZole/A4kegSc03x7j2mzwYV0rJOTtl5IKT04p9zSl3nkVsiJGC2bKToKpDA6lrCaWiYrAEQxBZs3gCLMWjxJbSzstTZWbkPJeRyBrVy/ltYhTCq8Q2bFwhhFNvFUOltrYLVtiqB2eUM4gCUCqX2ocU50oaqHOO01aWEvNmNZOZKTgqmjly5aVL440r5dyyOorBWrWFbS7OCJdihALqRMEulhllyfolKuX0jTVgcXXV0jdm68I7kQ3uRCB7dAwLfNhET7QTynjPEs1zF4EOXoY6BgjYEUMPvvWxoT0mf24TfOp%2BKoFkNfiIgNvrf4qPnscrhYDW4sDdWGuB3q43SKjZU2NozA36KTfwoxQjw2UMaTY7%2BLjrnqOBWwnxiCTm6KXq3PhIaBHGOLYfatFj000PLduMpQSnEVtUYwjx5jtGltAWefRzbjaFs9SIzt47cFlrQX2t5DiB1KL9ZW9xnbvHdpsf49dgTglDvCZE0dMSD1MLOXWkdqTR77M8Ychpy6b0tPrRcuh1TL1eKOec99AHGzfqqeQO1Jy%2BoMg6Qwy%2BkG35pIYZWFNXqQhrEkOQSQODV3%2BkrEhj1Jo65mBEUwbgKRIwsEkHEVQeZQgfH8AoD4LATAwRsN0EDuGoxkItP5IjMFcNMEo9R88dGGNMZY1a9jHGFlCO44gXjh8WBxFkNINGgmaMhBE4x5jh8W4GskxxrjhGRFsDiHdVTVH1OabEzpvN%2BncOGZ4yIxTymdTkDWI9Sz9GtMsd4XZvDxjZPybAqZ7grn3PCE86J7TtRp12cqee2u/kqawmdThrBcHekMmHNaa5iTDA2Etes2Z8yIg6nGDqPQukmxDIYXMr06S6ueFInYbISWiA6mDFJCrDZqxIN0HTRIOXh1zNRiqkC7XSuGAKZk0r9Hrx1Z0HoHs8EvKeF0kQ5AGgLB40bKgGrw2Zmjdue170U3vT5O9HN7sdW1gpDYKIV8uya6syUhzf5TEMCaQRWC04wsib1gljgSZVBqCyHcJoNYcALA7jFMiWwDgnB9LdGDqSGhIfQ9h9YeHjhnDFWABrBU2P0jIFynZdkRPccJHclDmH6IiaUBoMCe2TJhK9XKGKawKtkXq01hioKWK9YlVxZAjEWBDAlDbJ9%2BwodaCMDiEoHUDBy4WLxREEIGlu7IAtLMCXtxkBNe6tkSQFg0q66TuzlHEOaeY4wCgdAJUdzy3sExV7vzObik0nQbgLPibdB1EyeSpIGCkmeDqYAeB8ka16EBCA%2BaQ0YB1NpdAekNrWHBZxDAJAJLzHmOzOgzxrAEGz7ngFn2me0EaOn24muKpJWeEAA%3D%3D%3D)

### Use Cases

Strings are a huge bottle-neck in a lot of code. I have heard that string operations in facebook alone represent 2% so this utilize move semantics since this project uses now C++17 will increase performance in many programs which used sf::String and this string become closer to std::string

**Comment by eXpl0it3r** [comment]
Why is RVO not being triggered in the first code snippet? We're creating a temporary, for which C++17 should guarantee RVO.

I don't exactly see how the code is different, expect that the initial copy is explicit in the first snippet. 🤔

> I am sorry if I am posting too many issues.

No, that's more than welcome! 😊  
As long as you can accept having some issues potentially closed.

**Comment by ZXShady** [comment]
Standard says: `when a temporary class object that has not been bound to a reference (12.2) would be copied/moved to a class object with the same cv-unqualified type, the copy/move operation can be omitted by constructing the temporary object directly into the target of the omitted copy/move` 

it says it must not bind to a reference.


also you can try the godbolt link to see for yourself.

**Comment by ZXShady** [comment]
@eXpl0it3r 

I am sorry I think I am not focused this is all wrong lol. I am so wrong and the draft I linked was wrong it does not allow function parameters.

there is no elisions done here in the godbolt link except one the gain is just with the calling of move constructor instead of copy constructor 🤦 

I should get some sleep before posting an issue with wrong title.

the best most optimized would be to define 2 overloads

```cpp
String operator+(String&& a,const String& b) {
    String c = std::move(a);
    c += b;
    return c;
}


String operator+(const String& a,const String& b) {
    String c = a;
    c += b;
    return c;
}

```

again sorry for the wrong title...
