### ISSUE TITLE
Joystick axes mapping broken on Linux

### ISSUE THREAD

**Issue by AlexAUT** [SFML/SFML#3166]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

All physical joystick axes map to the same SFML Axis (X) on Linux.

### Your Environment

- OS / distro / window manager: Linux/Arch
- SFML version: master
- Compiler / toolchain: GCC/Clang

### Steps to reproduce

Run the joystick example under Linux.

### Expected behavior

"Correct" mappings not all to the same.

### Actual behavior

All physical axes map to the same SFML axes.

**Comment by Bambo-Borris** [comment]
@AlexAUT what joystick device were you using to test the sample?

**Comment by AlexAUT** [comment]
Xbox Series X controller via USB and Bluetooth. See the pull request which fixes the issue for me.

**Comment by Bambo-Borris** [comment]
@AlexAUT I'll give a go of the example on Linux, I have the same device available. I'd be surprised if this is the case since the blame says that region of code has been unchanged for 11 years! (Stranger things have happened though)

**Comment by AlexAUT** [comment]
Yes the change to `std::array` caused it because `ioctl` will cast it to a pointer internally which results in the wrong address. Luckily the array is filled with zeros so the address is always `0` which is handled by `ioctl`.

Maybe all calls to ioctl should be checked for errors to avoid similar bugs in the future?

**Comment by Bambo-Borris** [comment]
Yeah potentially, I left a comment on the PR having just tested the before/after. Definitely worth double checking the other uses 👍🏾

**Comment by ChrisThrasher** [comment]
Oops my bad. Never would have guessed switching to a `std::array` would result in that line of code still compiling. Thanks for tracking this down! We ought to audit other uses of this function and other C functions with variadic arguments to see if similar issues exist.

**Comment by eXpl0it3r** [comment]
Fixed with #3167
