### ISSUE TITLE
Memory Leak with sf::RenderWindow on Closing Window

### ISSUE THREAD

**Issue by iLoveJohnFish** [SFML/SFML#3178]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

After starting and stopping 1000 instances of another sf::RenderWindow from my editor, it seems that the sf::RenderWindow isn't properly cleaning up after itself and leaving a few KB's of data over everytime it runs and shuts down.

### Your Environment

- OS / distro / window manager: Windows 10 Latest update
- SFML version: 2.6.1
- Compiler / toolchain: MSVC 143 + CMake 3.30 + Conan2

### Steps to reproduce

1. Run the code with a memory profiler and observe the total memory usage rise for some reason

```cpp
sf::RenderWindow* pm_CurrentWindow = nullptr;
sf::View* pm_View = nullptr;

static void RunGameInstance()
{
    //////////////////////////////////////////////
    // Setup Window and Camera
    //////////////////////////////////////////////

    if (pm_CurrentWindow || pm_View)
    {
        LogManager::RenderingLogger().Warn("RenderingManager already has a valid window or camera2D currently active", "RenderingManager");
    }

    // Create an SFML window and "camera"
    pm_CurrentWindow = new sf::RenderWindow(sf::VideoMode(800, 600), "Peach Game", sf::Style::Default);
    pm_View = new sf::View();

    // Initialize the view to the size of the window
    pm_View->setSize(pm_CurrentWindow->getSize().x, pm_CurrentWindow->getSize().y);
    pm_View->setCenter(pm_CurrentWindow->getSize().x / 2, pm_CurrentWindow->getSize().y / 2);

    pm_CurrentWindow->setView(*pm_View);

    if (!pm_CurrentWindow->isOpen())
    {
        throw runtime_error("Failed to create window.");
    }

    //////////////////////////////////////////////
    // Rendering Loop
    //////////////////////////////////////////////

    bool fp_IsStressTest = true;
    // Main loop that continues until the window is closed
    while (pm_CurrentWindow->isOpen())
    {
        // Process events
        sf::Event event;

        while (pm_CurrentWindow->pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
            {
                pm_CurrentWindow->close();
            }
        }

        // Clear the screen with a dark blue color
        pm_CurrentWindow->clear(sf::Color(0, 0, 139));

        // Update the window
        pm_CurrentWindow->display();

        if (fp_IsStressTest) //used to stop rendering loop after one cycle for testing
        {
            break;
        }
    }

    //////////////////////////////////////////////
    // Shutdown and Cleanup
    //////////////////////////////////////////////
    
    if (pm_View)
    {
        delete pm_View;
        pm_View = nullptr;
    }
    if (pm_CurrentWindow)
    {
        pm_CurrentWindow->clear();
        pm_CurrentWindow->close();

        delete pm_CurrentWindow;
        pm_CurrentWindow = nullptr;
    }
}

/////////////////////////////////////////////////////////////
// Run the actual test starting up and shutting down the windown
/////////////////////////////////////////////////////////////

static void StessTest(int numIterations, int delayMs)
{
    for (int i = 0; i < numIterations; ++i)
    {
        cout << "Iteration: " << i + 1 << endl;

        // Start the game instance in a thread
        thread gameThread(RunGameInstance);

        // Allow the thread some time to start and initialize resources
        this_thread::sleep_for(chrono::milliseconds(delayMs));

        // Wait for the thread to finish execution
        gameThread.join();

        // Allow some time for resources to be fully released
        this_thread::sleep_for(chrono::milliseconds(delayMs));
    }
}

//////////////////////////////////////////////
// MAIN FUNCTION
//////////////////////////////////////////////

int main(int argc, char* argv[])
{
    try 
    {
        StessTest(1000, 50);
    }
    catch (const exception& ex) 
    {
        cerr << "An error occurred: " << ex.what() << endl;
        return EXIT_FAILURE;
    }

    sf::RenderWindow* f_MemoryCheckWindow = new sf::RenderWindow(sf::VideoMode(800, 600), "Peach Game", sf::Style::Default);

    while (f_MemoryCheckWindow->isOpen())
    {
        // Process events
        sf::Event event;

        while (f_MemoryCheckWindow->pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
            {
                f_MemoryCheckWindow->close();
            }
        }

        // Clear the screen with a dark blue color
        f_MemoryCheckWindow->clear(sf::Color(0, 0, 139));

        // Update the window
        f_MemoryCheckWindow->display();

    }

    delete f_MemoryCheckWindow;
    f_MemoryCheckWindow = nullptr;

    return EXIT_SUCCESS;
}

```

### Expected behavior

sf::RenderWindow should clean up all resources related to it when close() is called as the documentation expresses from my understanding.

### Actual behavior

the running memory of the application increases a wopping 10 MB over the span of 1000 window instance startups and teardowns
![sfml report 1](https://github.com/user-attachments/assets/59c6ad4c-b249-473a-b86f-a39ae8956a2e)
![sfml report 2](https://github.com/user-attachments/assets/44caa54e-032b-4755-bc57-88235edcf38e)

**Comment by ChrisThrasher** [comment]
Can you still observe the memory leak when you replace all uses of `new` and `delete` with `std::unique_ptr`?

**Comment by iLoveJohnFish** [comment]
i'll try that out now

**Comment by ZXShady** [comment]
```cpp
pm_CurrentWindow = new sf::RenderWindow(sf::VideoMode(800, 600), "Peach Game", sf::Style::Default);
    pm_View = new sf::View();

```

this has an issue already if the first new succeeds but the second new fails the delete of the first is not called.


```cpp
    if (!pm_CurrentWindow->isOpen())
    {
        throw runtime_error("Failed to create window.");
    }

```

if this fails you won't call the delete too




try this again but with unique_ptr's.

**Comment by iLoveJohnFish** [comment]
Im observing similiar behaviour with this code:

```cpp
unique_ptr<sf::RenderWindow> pm_CurrentWindow = nullptr;
unique_ptr<sf::View> pm_View = nullptr;

static void RunGameInstance()
{
    //////////////////////////////////////////////
    // Setup Window and Camera
    //////////////////////////////////////////////

    if (pm_CurrentWindow || pm_View)
    {
        LogManager::RenderingLogger().Warn("RenderingManager already has a valid window or camera2D currently active", "RenderingManager");
    }

    // Create an SFML window and "camera"
    pm_CurrentWindow = make_unique<sf::RenderWindow>(sf::VideoMode(800, 600), "Peach Game", sf::Style::Default);
    pm_View = make_unique<sf::View>();

    // Initialize the view to the size of the window
    pm_View->setSize(pm_CurrentWindow->getSize().x, pm_CurrentWindow->getSize().y);
    pm_View->setCenter(pm_CurrentWindow->getSize().x / 2, pm_CurrentWindow->getSize().y / 2);

    pm_CurrentWindow->setView(*pm_View);

    if (!pm_CurrentWindow->isOpen())
    {
        throw runtime_error("Failed to create window.");
    }

    //////////////////////////////////////////////
    // Rendering Loop
    //////////////////////////////////////////////

    bool fp_IsStressTest = true;
    // Main loop that continues until the window is closed
    while (pm_CurrentWindow->isOpen())
    {
        // Process events
        sf::Event event;

        while (pm_CurrentWindow->pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
            {
                pm_CurrentWindow->close();
            }
        }

        // Clear the screen with a dark blue color
        pm_CurrentWindow->clear(sf::Color(0, 0, 139));

        // Update the window
        pm_CurrentWindow->display();

        if (fp_IsStressTest) //used to stop rendering loop after one cycle for testing
        {
            break;
        }
    }

    //////////////////////////////////////////////
    // Shutdown and Cleanup
    //////////////////////////////////////////////
    
    if (pm_View)
    {
        pm_View.reset(nullptr);
    }
    if (pm_CurrentWindow)
    {
        pm_CurrentWindow->clear();
        pm_CurrentWindow->close();

        pm_CurrentWindow.reset(nullptr);
    }
}

/////////////////////////////////////////////////////////////
// Run the actual test starting up and shutting down the windown
/////////////////////////////////////////////////////////////

static void StessTest(int numIterations, int delayMs)
{
    for (int i = 0; i < numIterations; ++i)
    {
        cout << "Iteration: " << i + 1 << endl;

        // Start the game instance in a thread
        thread gameThread(RunGameInstance);

        // Allow the thread some time to start and initialize resources
        this_thread::sleep_for(chrono::milliseconds(delayMs));

        // Wait for the thread to finish execution
        gameThread.join();

        // Allow some time for resources to be fully released
        this_thread::sleep_for(chrono::milliseconds(delayMs));
    }
}

//////////////////////////////////////////////
// MAIN FUNCTION 
//////////////////////////////////////////////

int main(int argc, char* argv[])
{
    try 
    {
        StessTest(1000, 50);
    }
    catch (const exception& ex) 
    {
        cerr << "An error occurred: " << ex.what() << endl;
        return EXIT_FAILURE;
    }

    unique_ptr<sf::RenderWindow> f_MemoryCheckWindow = make_unique<sf::RenderWindow>(sf::VideoMode(800, 600), "Peach Game", sf::Style::Default);

    while (f_MemoryCheckWindow->isOpen())
    {
        // Process events
        sf::Event event;

        while (f_MemoryCheckWindow->pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
            {
                f_MemoryCheckWindow->close();
            }
        }

        // Clear the screen with a dark blue color
        f_MemoryCheckWindow->clear(sf::Color(0, 0, 139));

        // Update the window
        f_MemoryCheckWindow->display();

    }

    f_MemoryCheckWindow.reset(nullptr);

    return EXIT_SUCCESS;
}

```

![sfml report test 2 (1)](https://github.com/user-attachments/assets/a270ec51-ef0f-472d-9877-2bd760ec587e)
![sfml report test 2 (2)](https://github.com/user-attachments/assets/fcf48985-ad5d-44f8-976f-37a47753109c)

I have also noticed this behaviour on both of my systems(Laptop and Desktop, however they are both running AMD + Nvidia RTX Cards)

**Comment by ChrisThrasher** [comment]
If you let the program run for that same ~4 minute duration do you observe a change in memory use or does it stay perfectly constant the whole time?

**Comment by iLoveJohnFish** [comment]
it has stayed constant from what i've seen over a 10 minute run, but I don't mind testing it again if it helps.

**Comment by Bambo-Borris** [comment]
It'd be more helpful here if you used the heap profiler in VS to give us some extra information on what objects aren't being freed (if any). There's also known cases such as leaky graphics drivers which get reported as memory leaks in SFML somewhat frequently. Also, there's no justifiable reason to heap allocate the `sf::View` instance, it's lightweight and perfectly fine to stack allocate instead

**Comment by iLoveJohnFish** [comment]
oh okay I'll try using the heap profiler.

I was thinking hardware may be playing a role here since the two systems i tested it on have similiar hardware.

I initially stack allocated sf::View on my tests, however I started heap allocating it to explicitly eliminate it as a reason for the  possible memory leak.

**Comment by ChrisThrasher** [comment]
I think you have it backwards. Leaks aren’t possible with stack allocations so stack allocate as much as you can.

**Comment by iLoveJohnFish** [comment]
Oh yeah I know the data will be thrown out once it leaves whatever scope it's in if stack allocated.

I just thought might as well do this to make absolute sure it wasn't anything funky.

**Comment by iLoveJohnFish** [comment]
Okay so I finished my calc assignment, and while I was doing it I kept the last window open the entire time:

![sfml long stack test (1)](https://github.com/user-attachments/assets/781ab64d-cb71-4f80-ac8e-9519a93dd716)
![sfml long stack test (2)](https://github.com/user-attachments/assets/ff1cb8e9-ad99-433a-907a-a5abaacc2f1b)
![sfml long stack test (3)](https://github.com/user-attachments/assets/765a5269-07b6-4feb-b77e-7c58c998244b)

Seems like the memory stablizies after window creation and teardown has stopped.

I'll try running more tests, including using the heap profiler as recommended. Have you guys seen anything interesting on your end?

**Comment by iLoveJohnFish** [comment]
oh okay so I ran more tests and didn't really get much better results, HOWEVER I did find this reddit post from like half a year ago:

https://www.reddit.com/r/vulkan/comments/18ph4jc/memory_leaks_inside_nvidia_driver/

This might be the issue, if someone could test this on a red card then we could be certain (if you guys are even able to reproduce this weird memory issue).

**Comment by Bambo-Borris** [comment]
> Okay so I ran more tests and didn't really get much better results, HOWEVER I did find this reddit post from like half a year ago:
> 
> https://www.reddit.com/r/vulkan/comments/18ph4jc/memory_leaks_inside_nvidia_driver/
> 
> This might be the issue, if someone could test this on a red card then we could be certain (if you guys are even able to reproduce this weird memory issue).

We've seen so many reports of leaks associated with graphics objects and they all trace back to leaky driver, or objects cleaned up at exit and essentially none of them can be solved within SFML. I'd say even if an AMD user tests this we're unlikely to find anything new. I would say look over similar forum posts and existing GitHub issues on this repository mentioning memory leaks within SFML and see if any of them can alleviate your concerns here.

**Comment by iLoveJohnFish** [comment]
ahhhhh it's just nice to know where the memory is coming from when i profile. Before I was panicking because I thought I was cleaning up after myself properly, and maybe I was just missing something WHICH SUCKED.

So I really appreciate you taking your time to address my concerns, and especially for pointing me towards followup resources!

Thank you for all the help, and sorry if I wasted any of your time. I can run my debug tools with peace of mind now!
