### ISSUE TITLE
Consolidate Vector2's function names

### ISSUE THREAD

**Issue by eXpl0it3r** [SFML/SFML#3183]
When adding more capabilities to `sf::Vector2<T>` in #1979, the naming of the functions wasn't really part of the discussion.  
While heading for a feature / API freeze, I want to bring this up for discussion.

To me it's important that function names are consistent and speaking, even to the point of being maybe more verbose than strictly necessary.  
As such I currently see three functions that could potentially have a better naming:
- `lengthSq`
- `cwiseMul`
- `cwiseDiv`

In "violation" are `Sq`, `cwise`, `Mul`, and `Div` for me.  
`Sq`, `Mul`, and `Div` could easily be expanded to their full meaning (`Squared`, `Multiply`, `Divide`).  
For `cwise`, I'm unsure if there's a better term than `componentWiseX`. I also find it the least speaking function name, unless you just know what `cwise` stands for.

What are your thoughts on this?

**Comment by Bambo-Borris** [comment]
I agree with the point here for cwiseDiv and cwiseMul, their naming is inconsistent with how SFML names methods in general and also it's not very obvious what the methods do from the name. I'm not so worried about lengthSq, but it could also be considered inconsistently named. I don't have any alternative names in mind yet, but I do think there's some value in reconsidering the naming here.

**Comment by vittorioromeo** [comment]
I think that: 
- `sq` should be extended to `squared`.
- `cwise` needs to be extended to `componentWise` or changed. 
- `mul` and `div` are easily understandable and extending them would be too verbose.

My picks would be:
- `squaredLength`
- `componentWiseMul`
- `componentWiseDiv`

Other ideas (for completeness):
- `lengthSquared`
- `lengthSquare`
- `componentWiseMultiply`
- `componentWiseDivide`
- `perComponentMul`
- `perComponentDiv`
- https://en.wikipedia.org/wiki/Hadamard_product_(matrices)
- `hadamardMul` *(likely too obscure)*
- `hadamardDiv`
- `elementWiseMul` *("element" seems acceptable and shorter)*
- `elementWiseDiv`
- `pointwiseMul` *(I've seen this used before, but rarely)*
- `pointwiseDiv`

**Comment by ChrisThrasher** [comment]
> My picks would be:
> 
> * `squaredLength`
> * `componentWiseMul`
> * `componentWiseDiv`

These are my picks as well.

**Comment by Bambo-Borris** [comment]
Agree with Thrasher/Vee, gives some improved clarity of the naming.
