### ISSUE TITLE
Rename sf::Sound::getLoop and sf::SoundSource::getLoop to isLooping

### ISSUE THREAD

**Issue by ZXShady** [SFML/SFML#3184]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### Describe your feature request here

they both return `bool` and every function in sfml that returns a bool is named `isX` not `getX` so this is inconsistent with the rest of naming scheme and should be renamed to `isLooping`

### Use Cases

Consistency with the rest of the naming convention in the API

**Comment by ChrisThrasher** [comment]
I think I'm cool with this. Would be good to also change `setLoop` to `setLooping`. What do you think @eXpl0it3r?

**Comment by eXpl0it3r** [comment]
Fixed with #3187
