### ISSUE TITLE
setUniformArray with vector crash when buffer is empty even when size is 0

### ISSUE THREAD

**Issue by seigward12** [SFML/SFML#3185]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

![image](https://github.com/user-attachments/assets/915e31a4-3ba2-4123-a8d4-3a0835071f73)
I have this crash and error when using setUniformArray on a shader with a sf::Glsl::Vec2 type.
it happens when the pointer I pass is empty, so it would be normal to have an read access violation, but I still gave the size 0, so it should not be accessing data in my array

### Your Environment

- OS / distro / window manager: Windows
- SFML version: 2.6.1
- Compiler / toolchain: Cmake, MSVC 2019
- Special compiler / CMake flags: SFML linked statically

### Steps to reproduce

```cpp
#include <SFML/Graphics.hpp>
#include <vector>

int main() {
	sf::RectangleShape shape;
	sf::RenderWindow window(sf::VideoMode(800, 600), "My window");
	sf::Shader shader;
	shader.loadFromFile("test.frag", sf::Shader::Type::Fragment);
	sf::RenderStates state(&shader);

	std::vector<sf::Glsl::Vec2> uniformArray;
	shader.setUniformArray("testUniform", uniformArray.data(), 0);

	while (window.isOpen()) {
		sf::Event event;
		while (window.pollEvent(event)) {
			if (event.type == sf::Event::Closed)
				window.close();
		}

		window.clear();
		window.draw(shape, state);
		window.display();
	}

	return 0;
}
```

### Expected behavior

the function should verify that the given size is greater than 0 before accessing data in my array

### Actual behavior

the function just acces the element 0 of they array before doing any check.

**Comment by Bambo-Borris** [comment]
Yeah I would expect an assert to be thrown by SFML under this scenario rather than try access anything within the container. I think the resolution should be an assert checking that the container isn't empty, therefore anyone passing empty would be warned of that. Essentially, and empty container isn't a valid case here. Users should pass a container with data or not call `setUniformArray` at all.

**Comment by ChrisThrasher** [comment]
https://en.cppreference.com/w/cpp/container/vector/data

> If [size()](https://en.cppreference.com/w/cpp/container/vector/size) is ​0​, data() may or may not return a null pointer.

The value of `std::vector::data` is not well defined when the vector is empty so keep that in mind. Setting that aside, what is the use case for providing zero-length arrays as arguments?

**Comment by seigward12** [comment]
For example, if I give to the shader some objects positions found inside a space query, but that no objects are found, a vector of size 0 will be constructed and the loop that fill positions into the vector will not be executed. Of course my fix was to check myself that I was not giving a size 0 vector, but when my program crashed it took time for me to understand that the function was trying to access the first element of the data.

**Comment by ChrisThrasher** [comment]
https://github.com/SFML/SFML/pull/3186

**Comment by kimci86** [comment]
Was someone able to reproduce the issue? I don't see where the vector subscript out of range comes from.

**Comment by seigward12** [comment]
I think it may already been resolved, since I was using 2.6.1.
I just saw the fix of @ChrisThrasher and saw that the function was doing `&contiguous[0]` in 2.6.1, but `contiguous.data()` now.

**Comment by kimci86** [comment]
Oh right, it makes sense. Then we could fix it on 2.6.x branch, master branch is fine already.

**Comment by ChrisThrasher** [comment]
@seigward12 Will you please test #3186 to confirm whether or not it fixes your issue? Thanks!

**Comment by seigward12** [comment]
@ChrisThrasher I tested it and there is no more crash, also tested on current developpement branch and it was fixed
