### ISSUE TITLE
Descriptive Networking error messages

### ISSUE THREAD

**Issue by mohcine-otmane** [SFML/SFML#3210]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### Describe your feature request here

It would very helpful to make SFML networking error more descriptive like ASIO

### Use Cases

Networking

### API Example

#include <SFML/Network.hpp>
#include <iostream>

int main() {
    // ----- The client -----

    // Create a socket
    sf::TcpSocket socket;

    // Connect to the server on localhost (127.0.0.1) at port 53000
    if (socket.connect("127.0.0.1", 53000) != sf::Socket::Done) {
        std::cout << "Failed to connect to server." << std::endl;
        return -1;
    }
    std::cout << "Connected to the server." << std::endl;

    // Send a message to the server
    std::string message = "Hi, I am a client";
    if (socket.send(message.c_str(), message.size() + 1) != sf::Socket::Done) {
        std::cout << "Failed to send message to server." << std::endl;
        return -1;
    }
    std::cout << "Message sent to the server: " << message << std::endl;

    // Receive the reply from the server
    char buffer[1024];
    std::size_t received = 0;
    if (socket.receive(buffer, sizeof(buffer), received) != sf::Socket::Done) {
        std::cout << "Failed to receive message from server." << std::endl;
        return -1;
    }
    std::cout << "The server said: " << buffer << std::endl;

    return 0;
}

**Comment by eXpl0it3r** [comment]
If you want to discuss ideas, please join the [forum or Discord](https://www.sfml-dev.org/community.php). It's not productive to spam the issue tracker with all your ideas and AI generated code examples.

And if you do think, you have a valuable point, please spend some time, actually providing the necessary information.

SFML isn't ASIO, so you need to be more specific what kind of error messages you're missing or you'd like to see. Chances are, you might just not understanding how to use SFML.

**Comment by ChrisThrasher** [comment]
Please provide an explicit example of what you want the error messages to look like
