### ISSUE TITLE
Migration Guide Enhancements

### ISSUE THREAD

**Issue by eXpl0it3r** [SFML/SFML#3228]
With the release candidate on the horizon and people starting to migrate code bases over to SFML 3, we might notice issues people run into with the current version of the migration guide.

This issue should collect these points centrally, so changes can be derived from it.

- [x] The audio API changes, mostly related to the new ChannelMap, aren't mentioned in the guide - yes, they're a new feature, but it also breaks existing code. https://github.com/SFML/SFML/pull/3349
- [x] "in favor of `sf::View::operator=`" might not be clear, that it means the assignment of a new `sf::View` instance https://github.com/SFML/SFML/pull/3297
- [x] The "Removal of Default Constructors" section could use an example on how the existing code should be changed (init at construction or using `std::optional`) https://github.com/SFML/SFML/pull/3297
- [x] The "Fixed Width" entry might need to be higher up, as it's among the first compiler errors people will likely run into https://github.com/SFML/SFML/pull/3297
- [x] The streaming behavior for audio changed
- [x] NonCopyable header (and others?) were deleted https://github.com/SFML/SFML/pull/3297
- [x] `KeyPresssed` -> `KeyPressed`
- [x] Removal of the one deprecated `RenderTexture::create` overload (already mentioned in deprecated APIs table)
- [x] Mention conversion of classes to names spaces for `sf::Keyboard`, `sf::Mouse`, `sf::Joystick`, `sf::Touch` https://github.com/SFML/SFML/pull/3297
- [x] Mention removal of [`setProcessingInterval`](https://www.sfml-dev.org/documentation/2.6.1/classsf_1_1SoundStream.php#a3a38d317279163f3766da2e538fbde93), and also update the code comment still referencing it #3315 
- [x] Mention minimum compiler requirements
- [x] Explicitly state that `left`, `top`, `width`, `height` of `sf::Rect` have been replaced https://github.com/SFML/SFML/pull/3323

**Comment by Lorenzooone** [comment]
[setProcessingInterval](https://www.sfml-dev.org/documentation/2.6.1/classsf_1_1SoundStream.php#a3a38d317279163f3766da2e538fbde93) doesn't exist anymore in SFML 3.0, but this is not detailed in the migration.md. This can lead to users wasting time searching for an alternative.
There is also a comment still referencing it in the source, iirc.

**Comment by ZXShady** [comment]
the guide doesn't mention that `sf::Keyboard`,`sf::Mouse`,`sf::Joystick`,`sf::Touch` are now namespaces instead of classes with all static members.


so old code like this which shortens a name.
```cpp
using sfTch = sf::Touch;
sfTch::something();
```

will now have to be

```cpp
namespace sfTch = sf::Touch;
sfTch::something();
```

**Comment by ChrisThrasher** [comment]
> the guide doesn't mention that `sf::Keyboard`,`sf::Mouse`,`sf::Joystick`,`sf::Touch` are now namespaces instead of classes with all static members.

Fixed in #3297

**Comment by Lorenzooone** [comment]
Maybe it should be explicitly stated that the sf::Rect public attributes left, top, width and height don't exist anymore.

I am saying to explicitly state it so someone going to the migration.md file can quickly find the problem.

**Comment by eXpl0it3r** [comment]
It seems to me, that we've included all the things that have been reported, as such I'll close this issue.

Maybe once people start using it, we'll notice stuff that could be done better.

**Comment by eXpl0it3r** [comment]
- [ ] Mention using `#include <optional>`
- [ ] Be more explicit with the `sf::Rect` field changes
- [ ] Consider providing more info for Visual Studio on how to enable C++17
