### ISSUE TITLE
SFML 3.0.0-rc.1 fails to compile on clang-tidy error.

### ISSUE THREAD

**Issue by m00se-3** [SFML/SFML#3262]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

I have a project for checking out the 3.0.0-rc.1 pre-release. I encountered a clang-tidy error that the team should probably be aware of. 

"error: prefer 'std::numbers::pi_v<float>' to this literal, differs by '8.74e-08' [modernize-use-std-numbers,-warnings-as-errors]"

Obviously this is not a huge deal, but I'm not sure how to workaround this without modifying source code. I'm using CPM for package management.

### Your Environment

- OS / distro / window manager: Windows 10
- SFML version: 3.0.0-rc.1
- Compiler / toolchain: LLVM 18.1.8
- Special compiler / CMake flags: None

### Steps to reproduce

1. 
2. 

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode({1280, 720}), "Minimal, complete and verifiable example");
    window.setFramerateLimit(60);

    while (window.isOpen())
    {
        while (const std::optional event = window.pollEvent())
        {
            if (event->is<sf::Event::Closed>())
                window.close();
        }

        window.clear();
        window.display();
    }
}
```

### Expected behavior

Successful compilation.

### Actual behavior

"error: prefer 'std::numbers::pi_v<float>' to this literal, differs by '8.74e-08' [modernize-use-std-numbers,-warnings-as-errors]"

**Comment by ChrisThrasher** [comment]
If you configure with the `dev` CMake preset then this problem will go away. It occurs because you're compiling SFML in C++20 mode (which is valid) but then also analyzing SFML in C++20 mode which causes clang-tidy to emit warnings about not using C++20 features.

**Comment by ZXShady** [comment]
Didn't test it but clang tidy shouldn't warn about it unless you are compiling in C++20 where these constants are available mode but SFML is a C++17 library also I think with 3rd party headers you should use `-isystem/include/to/sfml` instead of `-Iinclude/to/sfml` suppress warnings from third party headers.

also preferably post the file with the issue. but if I had to guess it is in Angle.hpp.

**Comment by m00se-3** [comment]
Thanks for the reply. It's a little embarrassing how the answer was right in front of my face. Live and learn, I guess.
