### ISSUE TITLE
This framework alive? i think this framework is dead

### ISSUE THREAD

**Issue by CoolRash7** [SFML/SFML#3285]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I understand [SFML's scope](https://www.sfml-dev.org/contribute.php#general-considerations) and believe the feature fits it

### Describe your feature request here

I write game on this SFML framework. and i dont found particles and i broke my project. And i dont sure that only PC export - it very nice. This framework now alive and developers make games in 2024 on SFML?

### Use Cases

9090900090909uoipoipu

### API Example

```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode({1280, 720}), "Minimal, complete and verifiable example");
    window.setFramerateLimit(60);

    while (window.isOpen())
    {
        while (const std::optional event = window.pollEvent())
        {
            if (event->is<sf::Event::Closed>())
                window.close();
        }

        window.clear();
        window.display();
    }
}
```
f

**Comment by ChrisThrasher** [comment]
This library is still being maintained. Go look at the commit history.
