### ISSUE TITLE
Possible bug in sf::Image::LoadFromFile

### ISSUE THREAD

**Issue by r-moeritz** [SFML/SFML#33]
On my machine (VC10 x64) `sf::Image::LoadFromFile` always returns false, but `sf::Image::LoadFromMemory` works. See [gist 943141](https://gist.github.com/943141) for code which exhibits this behaviour on my machine.
.

**Comment by latoto** [comment]
Hello I use Windows 7. LoadFromFile only worked once, then I stop.
Do not load any type of image, or * .png or * .jpg.
I tried reaciendo the project from scratch, but rather only loads the font file * .ttf and * .ogg file that are in the same directory.
I tried to load different images of these 2 types png and jpg, I even tried to run the same project from a VirtualBox with Windows 10 with the same result.
I have seen many people and nInternet has been the same. I set the working directory path absolutely, so I got to load the font and sound, but the pictures ... no way.
You can help? Thank you so much!
My mail: tonitoranzo@gmail.com
Greetings from Madrid-Spain!

**Comment by zsbzsb** [comment]
@latoto Please open a thread on the forums, you will get help there and be sure to include your SFML version and compiler info. Commenting on a ~4 year old issue won't get you help.

**Comment by latoto** [comment]
Sorry, I did not know he was doing wrong.
I'll watch what you tell me to see if I can find.
My English is very bad.
Thank you! A greeting!
Translated with Google
