### ISSUE TITLE
Complete transition from `std::uint32_t` to `char32_t` for UTF-32 characters

### ISSUE THREAD

**Issue by ChrisThrasher** [SFML/SFML#3324]
In https://github.com/SFML/SFML/pull/2480 we started using C++11's `char32_t` keyword to represent UTF-32 characters. This aligns with how `std::u32string` is a specialization of `std::basic_string<T>` with `char32_t`. The `sf::String` interface was changed to use `char32_T` as well. 

However, there are many places where we still use `std::uint32_t` to represent UTF-32 characters both in the public API and the private implementation.

`sf::Event::TextEntered` still uses `std::uint32_t`
https://github.com/SFML/SFML/blob/d78cec0236d066275b63b65de069ca64d734034b/include/SFML/Window/Event.hpp#L86-L89

Many `sf::Utf` functions are using `std::uint32_t`
https://github.com/SFML/SFML/blob/d78cec0236d066275b63b65de069ca64d734034b/include/SFML/System/Utf.hpp#L72-L73

This branch shows a number internal uses of `std::uint32_t` and there are even more that I haven't yet changed.
https://github.com/SFML/SFML/compare/master...char32_t

This is an API inconsistency that ought to be rectified. The problem is, with [SFML 3's release imminent](https://github.com/SFML/SFML/issues/3314), I'm unsure if it's worth trying to finalize this work and merge it. It represents a rather small risk but the library is also in a very risk-averse phase right before our biggest release ever.

A smaller and safer change would be to simply change `TextEntered` to use `char32_t` and nothing else. This means our events are consistent with `sf::String`. I'm unsure about changing `sf::Utf` nor changing internal uses of `std::uint32_t` to `char32_t`. That is a larger and riskier change. I'm no expert in string conversion so I can't be confident I'd make that refactor without introducing a subtle regression.

---

Expanding the scope of this issue, I believe there may also be places we're using `std::uint16_t` for UTF-16 characters which ought to be replaced with C++11's `char16_t` keyword. I have not looked into this yet but I believe it's another minor inconsistency or imperfection worth fixing at some point.

**Comment by eXpl0it3r** [comment]
Personally, I think it's more important to align the API now and live with a potential bug that can be rectified in a patch version, than to leave a inconsistent API, that can't be fixed until SFML 4 or essentially requires API deprecation before we even finished SFML 3.

Some conversion "tests" could be written to compare (the most basic) before and after scenarios.

**Comment by ChrisThrasher** [comment]
> Some conversion "tests" could be written to compare (the most basic) before and after scenarios.

We have no direct tests for `sf::Utf`. We indirectly test that code through the `sf::String` tests but I bet a lot of codepaths are uncovered or undercovered. This is partly why I see the risk in this change. We don't have good tests to check our work. We do need to write those tests but they're going to be pretty tricky and nobody is going to write them besides me if we're being realistic. Maybe one day I'll do that.

If you're willing to accept this risk due to the last-minute nature of the change and the lack of unit tests, then I suppose I can move forward with it and try to get a PR up soon.
