### ISSUE TITLE
WglContext:: SelectBestPixelFormat initialization issue.

### ISSUE THREAD

**Issue by fenggy** [SFML/SFML#3335]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

Firstly, I am not sure if this is a bug. The description is as follows:

I found during debugging that in selectBestPixelFormat, the ChoosePixelFormat logic is triggered because SF_GLAD-WGL-ARB_pixel-format defaults to false,

After the initialization of the OpenGL extension is completed, SF_GLAD-WGL-ARB_pixel_format becomes true, which means that wglHookePixelFormatARB is supported, but due to the check mechanism of selectBestPixelFormat, wglHookePixelFormatARB is not executed. Resulting in BestFormat not being optimal,

The development environment is window11, vs2022, and sfml is version V3. x.

May I ask if the design is like this, or is it a bug in version 3.0?
#2616 It should be an initialization issue, but this is not

### Your Environment

- OS / distro / window manager: windows
- SFML version: 3.x
- Compiler / toolchain: vs2022
- Special compiler / CMake flags:

### Steps to reproduce

```cpp
int WglContext::selectBestPixelFormat(HDC deviceContext, unsigned int bitsPerPixel, const ContextSettings& settings, bool pbuffer)
{
    static std::mutex                         cacheMutex;
    static std::vector<PixelFormatCacheEntry> pixelFormatCache;

    // Check if we have already previously found a pixel format for
    // the current inputs and return it if one has been previously found
    {
        const std::lock_guard lock(cacheMutex);

        for (const auto& entry : pixelFormatCache)
        {
            if (bitsPerPixel == entry.bitsPerPixel && settings.depthBits == entry.depthBits &&
                settings.stencilBits == entry.stencilBits && settings.antiAliasingLevel == entry.antiAliasingLevel &&
                pbuffer == entry.pbuffer)
                return entry.bestFormat;
        }
    }

    ensureInit();

    // Find a suitable pixel format -- first try with wglChoosePixelFormatARB
    int bestFormat = 0;
    if (SF_GLAD_WGL_ARB_pixel_format)
    {}
}
```

### Expected behavior

Should OpenGL extensions be initialized first?

### Actual behavior

SF_GLAD-WGL-ARB_pixel-format defaults to false.

**Comment by eXpl0it3r** [comment]
Did you run into any actual issue or was this just something you saw while stepping through SFML code?

The first OpenGL context to be created is supposed to be non-optional. It is then used to load all the extensions.
See also: https://www.khronos.org/opengl/wiki/Creating_an_OpenGL_Context_(WGL)#Create_a_False_Context

So while, you might indeed observe that for the first context, once you use SFML, you should have a context with the correct pixel format set.

**Comment by fenggy** [comment]
> Did you run into any actual issue or was this just something you saw while stepping through SFML code?
> 
> The first OpenGL context to be created is supposed to be non-optional. It is then used to load all the extensions. See also: https://www.khronos.org/opengl/wiki/Creating_an_OpenGL_Context_(WGL)#Create_a_False_Context
> 
> So while, you might indeed observe that for the first context, once you use SFML, you should have a context with the correct pixel format set.

Yes, I haven't encountered any problems yet. I just learned about the excellent design of the engine. I thought the optimal context environment would be created by default, so I debugged and traced the code, but found that it's not like that. That's why I raised this question because I found this comment in the code.

// Find a pixel format with ChoosePixelFormat, if wglChoosePixelFormatARB is not supported
// ChoosePixelFormat doesn't support pbuffers
`  if ((bestFormat == 0) && !pbuffer)
    {.......
    }`
Why can't buffering function be included during initialization? Is this my question?

OpenGL is too low-level and complex, but SFML encapsulation is excellent, which is also the reason for learning it.

**Comment by fenggy** [comment]
A new issue has been discovered. The following code can only obtain one drawing result, and calling object movement, rotation, scaling, etc. does not work. The new version (3.0) feature has not been implemented yet? or  usage error?  the same code is normal in 2.6.1.
`       
        RenderWindow window1(VideoMode(Vector2u(800, 600)), "code window");

	CircleShape shape(50.f);

	// set the shape color to green
	shape.setFillColor(Color(255, 0, 50));

	while (window1.isOpen())
	{
		// Process events
		while (const std::optional event = window1.pollEvent())
		{
			// Window closed or escape key pressed: exit
			if (event->is<Event::Closed>() ||
				(event->is<Event::KeyPressed>() &&
					event->getIf<Event::KeyPressed>()->code == Keyboard::Key::Escape))
			{
				window1.close();
			}
		}
		window1.clear(Color::Black);
		shape.move(Vector2f(3.f, 0.f));
		window1.draw(shape);		
		window1.display();
		
	}
	return 0;`

**Comment by fenggy** [comment]
`
#include <SFML/Graphics.hpp>

int main()
{
	sf::RenderWindow window(sf::VideoMode(600, 400), "SFML works!");
	sf::CircleShape shape(50.f);
	sf::RectangleShape re(sf::Vector2f(100, 50));
	shape.setFillColor(sf::Color::Green);
	shape.setOrigin(25, 25);
	re.setFillColor(sf::Color::Red);
	re.setOrigin(50, 25);
	re.setPosition(100, 50);


	while (window.isOpen())
	{
		sf::Event event;
		while (window.pollEvent(event))
		{
			if (event.type == sf::Event::Closed)
				window.close();
		}

		window.clear();
		re.rotate(0.1f);
		shape.rotate(0.1f);
		window.draw(shape);
		window.draw(re);
		window.display();
	}

	return 0;
}
`
The above code is normal in 2.6.1

**Comment by fenggy** [comment]
> A new issue has been discovered. The following code can only obtain one drawing result, and calling object movement, rotation, scaling, etc. does not work. The new version (3.0) feature has not been implemented yet? or usage error? the same code is normal in 2.6.1. ` RenderWindow window1(VideoMode(Vector2u(800, 600)), "code window");
> 
> ```
> CircleShape shape(50.f);
> 
> // set the shape color to green
> shape.setFillColor(Color(255, 0, 50));
> 
> while (window1.isOpen())
> {
> 	// Process events
> 	while (const std::optional event = window1.pollEvent())
> 	{
> 		// Window closed or escape key pressed: exit
> 		if (event->is<Event::Closed>() ||
> 			(event->is<Event::KeyPressed>() &&
> 				event->getIf<Event::KeyPressed>()->code == Keyboard::Key::Escape))
> 		{
> 			window1.close();
> 		}
> 	}
> 	window1.clear(Color::Black);
> 	shape.move(Vector2f(3.f, 0.f));
> 	window1.draw(shape);		
> 	window1.display();
> 	
> }
> return 0;`
> ```


If the movement step is greater than or equal to 5, you can see that the object quickly moves away from the screen, while if it is less than 5, the window does not respond.

**Comment by fenggy** [comment]
> A new issue has been discovered. The following code can only obtain one drawing result, and calling object movement, rotation, scaling, etc. does not work. The new version (3.0) feature has not been implemented yet? or usage error? the same code is normal in 2.6.1. ` RenderWindow window1(VideoMode(Vector2u(800, 600)), "code window");
> 
> ```
> CircleShape shape(50.f);
> 
> // set the shape color to green
> shape.setFillColor(Color(255, 0, 50));
> 
> while (window1.isOpen())
> {
> 	// Process events
> 	while (const std::optional event = window1.pollEvent())
> 	{
> 		// Window closed or escape key pressed: exit
> 		if (event->is<Event::Closed>() ||
> 			(event->is<Event::KeyPressed>() &&
> 				event->getIf<Event::KeyPressed>()->code == Keyboard::Key::Escape))
> 		{
> 			window1.close();
> 		}
> 	}
> 	window1.clear(Color::Black);
> 	shape.move(Vector2f(3.f, 0.f));
> 	window1.draw(shape);		
> 	window1.display();
> 	
> }
> return 0;`
> ```

shape.move(Vector2f(5.f, 0.f)); 

If the movement step is greater than or equal to 5, you can see that the object quickly moves away from the screen, while if it is less than 5, the window does not respond.
