### ISSUE TITLE
I have error in new update 3.0.0

### ISSUE THREAD

**Issue by J3Omar** [SFML/SFML#3356]
### Prerequisite Checklist

- [X] I searched for [existing issues](https://github.com/search?q=repo%3ASFML%2FSFML&type=issues) to prevent duplicates
- [X] I searched for [existing discussions on the forum](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fen.sfml-dev.org) to prevent duplicates
- [X] I am here to report an issue and not to just ask a question or look for help (use the [forum](https://en.sfml-dev.org/forums/index.php#c3) or [Discord](https://discord.gg/nr4X7Fh) instead)

### Describe your issue here

I have mingw64 version 14.2.0 . I update SFML today from 2.6.2 to 3.0.0 and I find error when I run a program I execute by this code `g++ main.cpp -o main.exe -lsfml-audio -lsfml-system` no error happened when execute the file I doing sound program the error is 

```
main.exe - Entry Point Not Found The procedure entry point

_ZNKSt25_codecvt_utf8_utf16_baselwE10do_unshiftER9_MbstatetPcS

3_RS3_could not be located in the dynamic link library

C:\msys64\mingw64\bin\sfml-system-3.dll.
" and "main.exe - Entry Point Not Found

The procedure entry point

_ZNKSt25_codecvt_utf8_utf16_baselwE10do_unshiftER9_MbstatetPcS

3_RS3_could not be located in the dynamic link library

C:\msys64\mingw64\bin\sfml-audio-3.dll.
```

I try back to the last version and the program run successfuly the error exist only in new version

### Your Environment

Windows
3.0.0
Compiler
mingw64 14.2.0

**Comment by eXpl0it3r** [comment]
Are you using the compiler that's linked on the download page?

**Comment by J3Omar** [comment]
> Are you using the compiler that's linked on the download page?

yes occur error and is not compile

**Comment by J3Omar** [comment]
> Are you using the compiler that's linked on the download page?

It worked after delete folder msys64

**Comment by ChrisThrasher** [comment]
> > Are you using the compiler that's linked on the download page?
> 
> It worked after delete folder msys64

Closing this issue since it sounds like you resolved your own error.
