### ISSUE TITLE
Anti-aliasing broken - or rather, mechanism for picking the best visual is

### ISSUE THREAD

**Issue by svenstaro** [SFML/SFML#35]
As per [this thread](http://www.sfml-dev.org/forum/viewtopic.php?p=30712#30712) the GlxContext::CreateContext function, while apparently able to pick the best visual for other given properties such as resolution and bit-depth, doesn't seem to honor the multisampling setting even on system that have those visuals available.

In fact, from hacking the code a little it seems to effectively always pick the first one (of glxinfo). Perhaps this function should be improved so that systems whose first visual doesn't support multisampling can also benefit from multisampling.

**Comment by konstin** [comment]
I'm still facing this problem both with SFML 2.2 under Ubuntu 14.04 with proprietary nvidia drivers. This is code I use:
```
    sf::ContextSettings settings;
    settings.antialiasingLevel = 8;
    sf::RenderWindow window(sf::VideoMode(width, height), "title", sf::Style::Default, settings);
    std::cout << window.getSettings().antialiasingLevel << std::endl;
```
The last line only prints `0`.

In the package sources of Ubuntu 14.04 there is only version 2.1, so I compiled SFML from source, but the there was still no antialiasing. My graphics card definitely supports antialiasing. Here is my [glxinfo](https://gist.github.com/konstin/110c4f6dd7f3e22493a6).

**Comment by Bromeon** [comment]
@konstin Have you used the latest GitHub version (**not** SFML 2.2)? There have been some recent changes to context handling. Do you see the error message in the console?

**Comment by konstin** [comment]
With latest git I see these messages:
```
Warning: The created OpenGL context does not fully meet the settings that were requested
Requested: version = 2.1 ; depth bits = 0 ; stencil bits = 0 ; AA level = 8 ; core = false ; debug = false
Created: version = 4.5 ; depth bits = 0 ; stencil bits = 0 ; AA level = 0 ; core = false ; debug = false
```

And btw my program doesn't work anymore because there seems to be an issue with the mouse coordinates

**Comment by binary1248** [comment]
What is the output of `glxinfo`?

**Comment by konstin** [comment]
https://gist.github.com/konstin/110c4f6dd7f3e22493a6

**Comment by binary1248** [comment]
@konstin can you test #862?

The tree is at https://github.com/LaurentGomila/SFML/tree/bugfix/pixel_format_evaluation

**Comment by konstin** [comment]
With #862 the programm crashes on startup with the following message, both with and without antialiasing enabled:
```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  78 (X_CreateColormap)
  Serial number of failed request:  20
  Current serial number in output stream:  23
```
I can't get a stacktrace because the programm exits immediatly after printing the message.

**Comment by minirop** [comment]
@konstin add a breakpoint on exit and/or abort (not sure which one). that should do the trick.

**Comment by konstin** [comment]
Thanks, setting breakpoints on two syscalls (exit and exit_group) gave me a stacktrace:
```
(gdb) bt
#0  0x00007ffff6c291c9 in __GI__exit (status=status@entry=1) at ../sysdeps/unix/sysv/linux/_exit.c:32
#1  0x00007ffff6ba266b in __run_exit_handlers (status=1, listp=<optimized out>, run_list_atexit=run_list_atexit@entry=true) at exit.c:97
#2  0x00007ffff6ba26f5 in __GI_exit (status=<optimized out>) at exit.c:104
#3  0x00007ffff60186b8 in _XDefaultError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#4  0x00007ffff60187ed in _XError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007ffff60157e7 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#6  0x00007ffff6015895 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007ffff60161d5 in _XEventsQueued () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007ffff6018f25 in _XGetRequest () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007ffff5ffdd42 in _XGetWindowAttributes () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#10 0x00007ffff5ffdf31 in XGetWindowAttributes () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#11 0x00007ffff7981c09 in sf::priv::GlxContext::createContext(sf::priv::GlxContext*, unsigned int, sf::ContextSettings const&) () from /usr/local/lib/libsfml-window.so.2.2
#12 0x00007ffff79825c5 in sf::priv::GlxContext::GlxContext(sf::priv::GlxContext*) () from /usr/local/lib/libsfml-window.so.2.2
#13 0x00007ffff796eed1 in sf::priv::GlContext::globalInit() () from /usr/local/lib/libsfml-window.so.2.2
#14 0x00007ffff796fa47 in sf::GlResource::GlResource() () from /usr/local/lib/libsfml-window.so.2.2
#15 0x00007ffff79718ae in sf::Window::Window() () from /usr/local/lib/libsfml-window.so.2.2
#16 0x00007ffff7bc1e39 in sf::RenderWindow::RenderWindow(sf::VideoMode, sf::String const&, unsigned int, sf::ContextSettings const&) () from /usr/local/lib/libsfml-graphics.so.2.2
#17 0x00000000004030da in main () at Aufgabe2.cpp:90
```

**Comment by binary1248** [comment]
@konstin can you try again now? I updated the branch.
