### ISSUE TITLE
Send WM hint to float windows under Linux

### ISSUE THREAD

**Issue by ghost** [SFML/SFML#368]
Most SFML applications are intended to be viewed at a fixed size, and when a tiling window manager tries to tile an SFML window, it rarely gives a desired result.

After doing a bit of research, it appears that running `xprop` and clicking on any floating window will always yeld:
`_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL`

Additionally, it may make sense to set "SFML" and "sfml" classes to SFML windows so that (if ever needed), SFML windows can be matched and treated differently at the WM level.

**Comment by surafel911** [comment]
If you guys are curious, I've been researching this issue myself. I found out that adding the atom _NET_WM_STATE_MODAL seems to do the trick, at least in i3.
