### ISSUE TITLE
Add support for Geometry Shader

### ISSUE THREAD

**Issue by Mrowqa** [SFML/SFML#428]
It could be done like sf::RenderStates. You can keep method for one type of shader and write second method for all three types - if you don't want one of types you can simply pass empty string/stream (add sf::EmptyStream?). If one of shader's type won't be supported - you can simply fail loadFromXXX method - programmer should check which shaders are available before using them.

For checking which shaders are available you can simply modify existing method:
static bool isAvailable (Type shaderType);
Not bad idea is make it with binary flags.

**Comment by eXpl0it3r** [comment]
Merged in 146f63874a2a215eb0776d11da45b68871fa02ce
