### ISSUE TITLE
Leaving full-screen on Linux deactivates second monitor

### ISSUE THREAD

**Issue by Oberon00** [SFML/SFML#436]
When leaving full-screen (either by closing the window or calling `create()` with a non-full-screen mode), the resolution of the primary monitor is correctly restored but the second one is left deactivated, even after logging out and in again. I have to manually reactivate it in System Settings -> Display and Monitors. (Relative) screen positions are also lost.

This minimal program is enough to (always) reproduce the bug on my Kubuntu 13.04 system with two monitors (notebook monitor and external one set as primary) and SFML commit 6c1899d0f70e4dc845d7f482b22c9d79f7cd4f2f (aka 2.1):

``` c++
#include <SFML/Window/Window.hpp>

int main()
{
    sf::Window w(sf::VideoMode(800, 600), "My window", sf::Style::Fullscreen);
}
```

The issue also appears when leaving the full-screen mode with `Window::create()`.

(As a side note, the window is also created in the top-left corner of the primary screen instead of the center.)
#### Additional system information

ATI Mobility Radeon 5650 with open source drivers.
Output of `X -version`:

```
X.Org X Server 1.13.3
Release Date: 2013-03-07
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-37-generic x86_64 Ubuntu
Current Operating System: Linux cn-0-u 3.8.0-27-generic #40-Ubuntu SMP Tue Jul 9 00:17:05 UTC 2013 x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-3.8.0-27-generic root=UUID=(left out) ro quiet splash vt.handoff=7
Build Date: 17 April 2013  10:43:13PM
xorg-server 2:1.13.3-0ubuntu6 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.28.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
```

I'm not an experienced Linux user but if you give me pointers, I would be happy to provide you with more relevant information.

**Comment by G-Octav** [comment]
I can confirm this bug with the latest version of SFML. I'm running Linux Mint Cinnamon 17.2 and basically if my fullscreen window crashes, the second monitor gets turned off completely and the resolution on my first one is reduced to a minimum. It's a very localized bug but you should still re-open the issue

**Comment by eXpl0it3r** [comment]
> if my fullscreen window crashes

So it only happens when it crashes?

**Comment by G-Octav** [comment]
In my case yes, only when the window crashes. In my case the crash was the icon if that helps but I'm sure that's unrelated.

**Comment by eXpl0it3r** [comment]
I'm still a bit confused.

What happens if your fullscreen application closes normally?

What happens if your fullscreen application crashes?

What Window Manager do you use?

Is your SFML version 2.3.1?

**Comment by G-Octav** [comment]
> What happens if your fullscreen application closes normally?

If the game has no crashes, then it simply starts and behaves normally, covering one whole monitor in fullscreen state. If I close it after that, nothing happens to my monitors

> What happens if your fullscreen application crashes?

One display gets disabled, the other one has its resolution lowered to around 800x600

> What Window Manager do you use?

MATE 1.10

> Is your SFML version 2.3.1?

Yes, installed from the official repository

**Comment by binary1248** [comment]
So... SFML is supposed to do something after it crashes?
