### ISSUE TITLE
isKeyPressed is broken on OSX Mavericks

### ISSUE THREAD

**Issue by davidkiger** [SFML/SFML#505]
After a few builds, and with no source changes, isKeyPressed no longer works for any application built with SFML until a system reboot. Digging through the build, something is going wrong in

**/src/SFML/Window/OSX/HIDInputManager.mm**,

specifically in

**bool HIDInputManager::isPressed(IOHIDElements& elements)**.

The lines:

```
        IOHIDDeviceRef device = IOHIDElementGetDevice(*it);
        IOHIDDeviceGetValue(device, *it, &value);

        if (!value) {

            // This means some kind of error / disconnection so we remove this
            // element from our buttons

            CFRelease(*it);
            it = elements.erase(it);

        } else if ...
```

are the root of the problem, as _value_ is invalid and each device get removed from the list.

This may exist on more than Mavericks, but that's all I have to test. You can see more details in this thread: http://en.sfml-dev.org/forums/index.php?topic=13802.0

**Comment by shazow** [comment]
FWIW I'm running into this on Mac OS X 10.9.5 (13F34) when compiling https://github.com/miki151/keeperrl with sfml 2.1 installed via brew.

Relevant chunk:

```
Crashed Thread:  4  com.apple.audio.IOThread.client

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: EXC_I386_GPFLT

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_platform.dylib      	0x00007fff89b58b29 _platform_memmove$VARIANT$Unknown + 41
1   libsfml-window.2.dylib        	0x000000010e781cf2 sf::priv::HIDInputManager::isKeyPressed(sf::Keyboard::Key) + 164
2   keeper                        	0x000000010ccdb0b2 WindowView::mapLeftClickFun(Vec2) + 258 (window_view.cpp:172)
```

Pasted the full crash report here: http://pastebin.com/raw.php?i=HEmeFgzw

Let me know if I can do anything to help debug this further. :)

**Comment by shazow** [comment]
I built it against the latest HEAD of SFML and it's working fine now. Yay.
