### ISSUE TITLE
Android Screen rotation crash

### ISSUE THREAD

**Issue by mrpantalon** [SFML/SFML#531]
Hi,
When the smartphone is rotated, the app crash came with backtrace : http://pastebin.com/DepbhSvE

My code is the code of android samples.
Lib compiled with NDK rev 9c and android gcc 4.8 + stlport

**Comment by eXpl0it3r** [comment]
Removed milestone due to missing progress.

**Comment by mantognini** [comment]
Is this still a bug or was it fixed a long time ago and the issue was forgotten? (Probably @MarioLiebisch knows?)

**Comment by MarioLiebisch** [comment]
It's an edge case. This more or less only is an issue if you don't try to handle rotation inside SFML (same with #644). Proper documentation can "fix" this (as commented above).
