### ISSUE TITLE
Include Unit Tests

### ISSUE THREAD

**Issue by Jebbs** [SFML/SFML#623]
I feel that it would be beneficial to include unit tests in the library. This would be useful for catching bugs for various changes, as well as just being a good idea for a library like this.

Wondering what the devs think.

**Comment by zackthehuman** [comment]
@binary1248 What is the proper process for contributing this effort? I would like to write tests, so do I need to fork your fork in order to do this?

**Comment by TankOs** [comment]
@zackthehuman Using that branch is at least a good idea. As far as I know, @Bromeon is already writing tests, so at least some coordination is required.

**Comment by zackthehuman** [comment]
It looks like the tests were merged into the master branch in this repository, so I will fork from here and send a PR if I can. @TankOs

**Comment by eXpl0it3r** [comment]
We finally (!) have a foundation for unit tests merged with #1475! 🎉 
Let's hope we can rapidly grow the testing library. 🙂
