### ISSUE TITLE
[Android] Expose the ANativeActivity to the user

### ISSUE THREAD

**Issue by AlexAUT** [SFML/SFML#680]
At the moment it's impossible to get the ANativeActivity (except with a awful hack). But the user need it to load assets, call JNI function, access the savedstates...

Maybe the getSystemHandle() should return a struct containing a pointer to the ANativeActivity and the ANativeWindow.

**Comment by eXpl0it3r** [comment]
Removed milestone due to missing progress.

**Comment by MarioLiebisch** [comment]
Essentially got this ready, just missing updated documentation (waiting on #961) and some testing.

**Comment by eXpl0it3r** [comment]
Added in 9f6f02f988e2378b13e969129fcf31825c8f190f
