### ISSUE TITLE
error while loading shared libraries: libsfml-window.so.2.2.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ghost** [SFML/SFML#752]
commit fc850ed99fc3e52e16c7d9d1bf71daf92cbe5f76
cmake .
make
sudo make install

```
//
#include <SFML/Window.hpp>

int main()
{
    sf::Window window(sf::VideoMode(800, 600), "My window");

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }
    }
}
//
```

built with:
g++ -I/usr/local/include -L/usr/local/lib -lsfml-window main.cpp

compiles cleanly however when run linker throws the following error:
error while loading shared libraries: libsfml-window.so.2.2.0: cannot open shared object file: No such file or directory

seems to be related to this https://bugs.archlinux.org/task/43122 bug from python-sfml

let me know if you'd like any more information

**Comment by abodelot** [comment]
@binary1248 I just ran into this issue after a fresh SFML 2.2 install and was clueless. Running `ldconfig` solved the issue, thank you.

**Comment by cbalen** [comment]
I had the same issue but I've always used a different method to solve the problem so the user never has to worry about using ldconfig or setting their LD_LIBRARY_PATH. This CMake page discusses the issue (http://www.cmake.org/Wiki/CMake_RPATH_handling) and I've found that if you follow their recommendation by adding the code below in between lines 16-18 of your SFML-2.2/CMakeLists.txt file then you don't have this problem. I'm using OpenSUSE 13.1, and after adding this code it seems to have been resolved and I can now run the examples/window executable.

CMake Code:
SET(CMAKE_SKIP_BUILD_RPATH  FALSE)
SET(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE) 
SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

LIST(FIND CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES "${CMAKE_INSTALL_PREFIX}/lib" isSystemDir)
IF("${isSystemDir}" STREQUAL "-1")
   SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
ENDIF("${isSystemDir}" STREQUAL "-1")
