### ISSUE TITLE
Support cmake config file packages

### ISSUE THREAD

**Issue by SrTobi** [SFML/SFML#758]
It would be very nice, if SFML would support the [config file packages](http://www.cmake.org/cmake/help/v3.0/manual/cmake-packages.7.html#config-file-packages) on top of the normal FindSFML.cmake procedure. So we could use SFML like this:

``` cmake
find_package(sfml COMPONENTS system window graphics REQUIERD)
add_executable(sfml-prog ${SOURCE})

# "sfml::" is a namespace
target_link_libraries(sfml::system sfml::window sfml::graphics)
```

[Here is the forum thread](http://en.sfml-dev.org/forums/index.php?topic=17060.0)

**Comment by eXpl0it3r** [comment]
Superseded by #1335
