### ISSUE TITLE
Minimizing and changing the keyboard layout triggers an unhandled event

### ISSUE THREAD

**Issue by kimci86** [SFML/SFML#879]
I'm using Ubuntu 14.04 and SFML 2.3 (commit 80214d1)
When I minimize a window, I get this message:
```
X Extensions:
	Generic Event Extension - First event: 0
	SHAPE - First event: 64
	MIT-SHM - First event: 65
	XInputExtension - First event: 66
	XTEST - First event: 0
	BIG-REQUESTS - First event: 0
	SYNC - First event: 83
	XKEYBOARD - First event: 85
	XC-MISC - First event: 0
	SECURITY - First event: 86
	XFIXES - First event: 87
	RENDER - First event: 0
	RANDR - First event: 89
	XINERAMA - First event: 0
	Composite - First event: 0
	DAMAGE - First event: 91
	MIT-SCREEN-SAVER - First event: 92
	DOUBLE-BUFFER - First event: 0
	RECORD - First event: 0
	DPMS - First event: 0
	Present - First event: 0
	DRI3 - First event: 0
	X-Resource - First event: 0
	XVideo - First event: 93
	XFree86-VidModeExtension - First event: 0
	XFree86-DGA - First event: 95
	DRI2 - First event: 102
	GLX - First event: 104
	SGI-GLX - First event: 104
Unhandled event type: 64
Report this to the SFML maintainers if possible
```

Minimal example code to reproduce it:
```c++
#include <SFML/Window.hpp>

int main()
{
    sf::Window window(sf::VideoMode(800, 600), "My window");
    while(window.isOpen())
    {
        sf::Event event;
        while(window.pollEvent(event))
            if(event.type == sf::Event::Closed)
                window.close();
        sf::sleep(sf::milliseconds(20));
    }
    return 0;
}
```

**Comment by binary1248** [comment]
Are you using a compositor or have any window manager effects enabled?

**Comment by kimci86** [comment]
I am using the default Ubuntu setup. Disabling animations in CompizConfig Settings Manager did not change anything.

**Comment by zwookie** [comment]
Also on Ubuntu 14.04 using 80214d1 version of SFML and I get the same error. I noticed it only shows up once even if I bring the window back up and repeatedly minimize it again. Here's my log:

`X Extensions:
        XINERAMA - First event: 0
        Generic Event Extension - First event: 0
        SHAPE - First event: 64
        MIT-SHM - First event: 65
        XInputExtension - First event: 66
        XTEST - First event: 0
        BIG-REQUESTS - First event: 0
        SYNC - First event: 83
        XKEYBOARD - First event: 85
        XC-MISC - First event: 0
        SECURITY - First event: 86
        XFIXES - First event: 87
        RENDER - First event: 0
        RANDR - First event: 89
        XINERAMA - First event: 0
        Composite - First event: 0
        DAMAGE - First event: 91
        MIT-SCREEN-SAVER - First event: 92
        DOUBLE-BUFFER - First event: 0
        RECORD - First event: 0
        DPMS - First event: 0
        Present - First event: 0
        DRI3 - First event: 0
        X-Resource - First event: 0
        XVideo - First event: 93
        XVideo-MotionCompensation - First event: 0
        XFree86-VidModeExtension - First event: 0
        XFree86-DGA - First event: 95
        DRI2 - First event: 102
        GLX - First event: 104
        SGI-GLX - First event: 104
        ATIFGLRXDRI - First event: 0
        ATIFGLEXTENSION - First event: 0
        glesx - First event: 0
        AMDXVOPL - First event: 0
        AMDXVBA - First event: 0
Unhandled event type: 64
Report this to the SFML maintainers if possible`

**Comment by binary1248** [comment]
> I noticed it only shows up once even if I bring the window back up and repeatedly minimize it again.

This is by design so that the same warning doesn't spam your output.

I can reproduce the issue in Ubuntu 14.04 and 14.10. It seems to be coming from compiz since it doesn't happen in any desktop environment besides Unity. Since many Ubuntu users will probably be using Unity which relies on compiz, I guess this warrants a whitelist.

**Comment by binary1248** [comment]
Try out https://github.com/SFML/SFML/tree/bugfix/shape_event.

**Comment by kimci86** [comment]
This fixes the problem. No message is showing up now. :+1:

**Comment by zwookie** [comment]
Also tested shape_event branch and the error message is gone.

**Comment by kimci86** [comment]
I noticed another warning message. As it may not deserve a new github issue, I add a comment here.

Using Ubuntu 14.04 and SFML 2.3, after some keyboard input in a window, changing the keyboard layout (qwerty/azerty) gives the following warning:
```
X Extensions:
	Generic Event Extension - First event: 0
	SHAPE - First event: 64
	MIT-SHM - First event: 65
	XInputExtension - First event: 66
	XTEST - First event: 0
	BIG-REQUESTS - First event: 0
	SYNC - First event: 83
	XKEYBOARD - First event: 85
	XC-MISC - First event: 0
	SECURITY - First event: 86
	XFIXES - First event: 87
	RENDER - First event: 0
	RANDR - First event: 89
	XINERAMA - First event: 0
	Composite - First event: 0
	DAMAGE - First event: 91
	MIT-SCREEN-SAVER - First event: 92
	DOUBLE-BUFFER - First event: 0
	RECORD - First event: 0
	DPMS - First event: 0
	Present - First event: 0
	DRI3 - First event: 0
	X-Resource - First event: 0
	XVideo - First event: 93
	XFree86-VidModeExtension - First event: 0
	XFree86-DGA - First event: 95
	DRI2 - First event: 102
	GLX - First event: 104
	SGI-GLX - First event: 104
Unhandled event type: 85
Report this to the SFML maintainers if possible
```

**Comment by binary1248** [comment]
The question now is, should SFML handle keyboard layout changes while an application is running?

@SFML/sfml

**Comment by eXpl0it3r** [comment]
What does "handle" really mean?

**Comment by MarioLiebisch** [comment]
I think binary talks about the switch for character mapping (if any). For example, QWERTZ vs. QWERTY. How should `sf::Key::Z` and `sf::Key::Y` react to this (if at all). To be honest, I'm not really sure how/if these change behavior right now nor whether they should (ignoring `sf::Event::TextEntered`).

**Comment by binary1248** [comment]
"Behave properly". The current implementation caches the keyboard layout so it doesn't have to query an external library every time a keyboard event arrives like it did in the previous Xlib implementation. Xlib took care of the remapping for us, but since we do the translation ourselves now, we will have to take care of mapping changes. It isn't _that_ hard to do, in fact I already know how it would be done. The question is, is it worth writing code that handles a layout switch mid-application? I don't think this happens very often, and even less so when people are playing games.

**Comment by minirop** [comment]
The only reason I can think of changing the layout while playing, is for poorly handled games. (I have a AZERTY keyboard, so I'm playing a game using WASD and I have to select a QWERTY layout so I can play with ZQSD)

**Comment by TankOs** [comment]
@binary1248 It's one less error source, at least.

**Comment by eXpl0it3r** [comment]
Superseded by #883
