### ISSUE TITLE
Make SFML to support Vulkan API

### ISSUE THREAD

**Issue by cocof35** [SFML/SFML#899]

**Comment by MarioLiebisch** [comment]
Is there [more than a feature page already](https://www.khronos.org/vulkan)? I have yet to see header files or even a working implementation.

Till then this really is nothing to worry about or plan for. One of the next stepping stones will get working non-legacy OpenGL calls working for all platforms. After that there might be thoughts on Vulkan, but as long as there isn't even something finished to start working with, this is pretty much invalid.

Also: Leaving descriptions blank is bad as well. Why not explain a bit more? You might have noticed Vulkan's current state.

**Comment by acterhd** [comment]
Make please Vulkan!

**Comment by acterhd** [comment]
Vulkan is out 16 Febrary.

**Comment by Bromeon** [comment]
Please discuss anything related to Vulkan here: http://en.sfml-dev.org/forums/index.php?topic=19822
