### ISSUE TITLE
[2.3] Mac OS X Xcode App template unable to copy framework

### ISSUE THREAD

**Issue by 8F5FA1581B223693008DC26C** [SFML/SFML#905]
# Context
*System:* Mac OS X 10.10.3
*SFML version:* SFML-2.3-osx-clang-universal
*Downloaded today (2015-06-05) from:* http://www.sfml-dev.org/files/SFML-2.3-osx-clang-universal.tar.gz
*After applying the procedure for the __Frameworks__ described in:* http://www.sfml-dev.org/tutorials/2.3/start-osx.php

*Error:* `ditto: can't get real path for source '/Users/m/Prog/Projects/SFML/git/packaging/tmp//install//Library/Frameworks/sfml-system.framework'
couldn't copy /Users/m/Prog/Projects/SFML/git/packaging/tmp//install//Library/Frameworks/sfml-system.framework to /Users/8F5FA1581B223693008DC26C/Library/Developer/Xcode/DerivedData/My_First_SFML_App-fiwggsvwdnxwwqdfobspmbhcngfi/Build/Products/Debug/My First SFML App.app/Contents/Frameworks//sfml-system.framework`

# Correction
## Patch command:
`curl -fsSl https://gist.githubusercontent.com/mantognini/307d63352c136e47b34d/raw/996aa52d60c0e171a435d6b3802abaf1214d572c/template.patch | patch '/Library/Developer/Xcode/Templates/SFML/SFML App.xctemplate/TemplateInfo.plist'`
## Manual patch:
1. Edit `/Library/Developer/Xcode/Templates/SFML/SFML\ App.xctemplate/TemplateInfo.plist`
2. Replace the following lines (149-150):
  * `CMAKE_INSTALL_FRAMEWORK_PREFIX="/Users/m/Prog/Projects/SFML/git/packaging/tmp//install//Library/Frameworks"`
  * `CMAKE_INSTALL_LIB_PREFIX="/Users/m/Prog/Projects/SFML/git/packaging/tmp/install/usr/local/lib"`
* by the following:
  * `CMAKE_INSTALL_FRAMEWORK_PREFIX="/Library/Frameworks"`
  * `CMAKE_INSTALL_LIB_PREFIX="/usr/local/lib"`
3. Test and enjoy!

**Comment by mantognini** [comment]
Yes, this is a known issue. See [here](http://en.sfml-dev.org/forums/index.php?topic=18126.msg130379#msg130379) for an automatic patch.

**Comment by 8F5FA1581B223693008DC26C** [comment]
Sorry for the inconvenience, I should have also searched in the forum.
I updated my previous comment with your patch command from the forum.

**Comment by eXpl0it3r** [comment]
The archive on the download page has been updated. @mantognini

**Comment by mantognini** [comment]
Thanks. :)

**Comment by austinmw** [comment]
Hi, I tried both the patch command and the manual edit and I still get the error.

**Comment by mantognini** [comment]
As you can see above, the package has been updated and you should not suffer from the issue.

**Comment by austinmw** [comment]
But I do still have the issue.. is it because I'm using 2.3 instead of 2.3.1? There is no 2.3.1 on the downloads page for Mac yet.

**Comment by mantognini** [comment]
No, it is not related to a specific version, it was merely a packaging issue. The archive you can download was fixed, and if by any chance it wasn't, you can still apply the patch. If you have a specific issue, please open a thread on the forum and describe precisely the error you're encountering.
