### ISSUE TITLE
'â', 'ê', 'ô', … characters aren't detected by TextEntered event.

### ISSUE THREAD

**Issue by CBenoit** [SFML/SFML#908]
Hi,
I got an issue with SFML 2.3 (latest version from github).  Characters based on the '^' dead key aren't recognized (example : 'â', 'ê' and 'ô') by the TextEntered event on my system. I use Linux Mint 17 with Cinnamon (and of course, with X).

Here's a minimal code which reproduces the issue on my system :
```C++
#include <iostream>

#include <SFML/Window.hpp>

int main()
{
    bool running = true;

    sf::Window window(sf::VideoMode(800, 600), "My window"); 
    window.setFramerateLimit(60);

    while (running)
    {
        // Process events...
        sf::Event event;
        while (window.pollEvent(event))
        {
            switch (event.type)
            {
                case sf::Event::Closed:
                    running = false;
                    break;
                case sf::Event::TextEntered:
                    std::cout << event.text.unicode << std::endl;
                    break;
                default:
                    break;
            }
        }

        window.display();
    }
    
    if (window.isOpen())
        window.close();

    return 0;
}
```
Moreover, I got the following message twice :
```
X Extensions:
	Generic Event Extension - First event: 0
	SHAPE - First event: 64
	MIT-SHM - First event: 65
	XInputExtension - First event: 66
	XTEST - First event: 0
	BIG-REQUESTS - First event: 0
	SYNC - First event: 83
	XKEYBOARD - First event: 85
	XC-MISC - First event: 0
	SECURITY - First event: 86
	XFIXES - First event: 87
	RENDER - First event: 0
	RANDR - First event: 89
	XINERAMA - First event: 0
	Composite - First event: 0
	DAMAGE - First event: 91
	MIT-SCREEN-SAVER - First event: 92
	DOUBLE-BUFFER - First event: 0
	RECORD - First event: 0
	DPMS - First event: 0
	Present - First event: 0
	DRI3 - First event: 0
	X-Resource - First event: 0
	XVideo - First event: 93
	XFree86-VidModeExtension - First event: 0
	XFree86-DGA - First event: 95
	DRI2 - First event: 102
	GLX - First event: 104
	SGI-GLX - First event: 104
Unhandled event type: 85
Report this to the SFML maintainers if possible
```
However, I don't really know how exactly I got that…

Thanks.

**Comment by binary1248** [comment]
Try out the [2.3.x branch](https://github.com/SFML/SFML/tree/2.3.x). X keyboard issues similar to what is happening in your case have been fixed there.

**Comment by Lomadriel** [comment]
I use ArchLinux 4.0.5-1-ARCH, Cinnamon 2.6.7
I try SFML 2.3.X branch but it doesn't seem to work however I haven't any messages like @CBenoit. Characters based on the '^' dead key aren't printed.

**Comment by CBenoit** [comment]
@binary1248 : I tried out the 2.3.x branch. Same result as @Lomadriel.

**Comment by binary1248** [comment]
Try out the [bugfix/xlib_events](https://github.com/SFML/SFML/tree/bugfix/xlib_events) branch.

**Comment by CBenoit** [comment]
Characters based on the '^', '`' and '´' dead keys are now properly recognized on my system!
However, '¯' produce 'e' instead of 'ē', 'u' instead of 'ū', … using '~' and '¸' I'm able to produce 'ç', 'õ' and 'ā' only (when ȩ, ũ, ĩ, ẽ exists as well).

**Comment by binary1248** [comment]
Are you sure those missing glyphs can be displayed on your terminal? And do those key combinations work in other applications? If they do, which applications are they?

**Comment by CBenoit** [comment]
I'm sure they can be displayed because I put them in my code to test before checking if I was able to actually type it.
I'm lucky : in term of application, as a French guy, '^', '`', '´' and 'ç' are enough for me.
This is just about other people who may need it in some other countries.

**Comment by binary1248** [comment]
OK... It seems that the X input method that SFML and many other multimedia libraries use does not properly support many dead-key combinations. This is not an SFML bug, but a "bug" in the X input method implementation if their developers would even categorize it as such. They will probably just classify it as a shortcoming that was never fully implemented.

The problem you are having only arises when you try to use key combinations. If you use a keyboard that supports single keystroke input of those characters, SFML detects and outputs them correctly. You can test this yourself by switching to the Latvian keyboard layout and pressing the 'ē' key combination (AltGr + E) or the 'ū' key combination (AltGr + U), they will both work.

For most users typing in their native language or using a native keyboard layout, this shouldn't be too big of a problem. In the future, when SFML has clipboard support, another possibility would be for the user to copy in a glyph from a character map application.

**Comment by CBenoit** [comment]
I see. So, if this is no longer an SFML issue, feel free to close it and thank you for your help!

**Comment by binary1248** [comment]
Like I said, SFML can only support what X input method supports, and that is combine characters up to unicode codepoint U+00FF ('ÿ'), so technically half of this issue can be fixed in SFML. I'll keep this issue open until the associated PR can get merged.

**Comment by binary1248** [comment]
Closing this now as this has been partially fixed and can't be fully fixed in SFML.
