### ISSUE TITLE
aiff not supported in osx

### ISSUE THREAD

**Issue by cayuse** [SFML/SFML#914]
command line app compiled in OS X gives 'format not supported' error for aiff files.
```c++
#include <SFML/Audio.hpp>
int main()  {
    sf::Music mTheme1;
    if (!mTheme1.openFromFile("test1.aiff"))
        return -1;
    mTheme1.play();

    while (mTheme1.getStatus() == sf:: SoundSource::Playing){
    }
return 0;
 }
```

compiled with:
g++ -c main.cpp

linked with:
g++ main.o -o sfml-app -framework sfml-system -framework sfml-audio

error given:
Failed to open sound file "test1.aiff" (format not supported)

The test1.aiff file is known to be good and plays under linux, as well as with other apps on the OS X machine itself.

**Comment by LaurentGomila** [comment]
> command line app compiled in OS X gives 'format not supported' error for aiff files.

So you reported it as a bug instead of trusting the error message and checking that this format was indeed not supported by SFML? ...

**Comment by cayuse** [comment]
from the SFML Documentation: http://www.sfml-dev.org/documentation/2.0/classsf_1_1Music.php

Here is a complete list of all the supported audio formats: ogg, wav, flac, aiff, au, raw, paf, svx, nist, voc, ircam, w64, mat4, mat5 pvf, htk, sds, avr, sd2, caf, wve, mpc2k, rf64.

**Comment by MarioLiebisch** [comment]
You're looking at the wrong (outdated) version. That's for **2.0**, while the latest version is **2.3**. Due to Libsndfile being dropped, the supported formats changed.

[The new list of supported formats can be found here.](http://www.sfml-dev.org/documentation/2.3/classsf_1_1InputSoundFile.php#af68e54bc9bfac19554c84601156fe93f)

It could need more formats, but the lack for AIFF is not a real bug right now (more like a missing feature).

**Comment by cayuse** [comment]
MarioLiebisch,

OK thanks for your reply.  Most likely i ended up with 2.0 on the linux machine and 2.3 on the osx box and just couldn't figure out why it worked on one and not the other.  I did look around quite a bit and even asked on the IRC # before submitting. I did not find the updated documentation.

FWIW SFML is easily one of the best documented frameworks I've ever attempted to work with.
