### ISSUE TITLE
pkg-config should be enabled in windows too

### ISSUE THREAD

**Issue by aullidolunar** [SFML/SFML#919]
I think it should be a good idea that pkg-config is also supported in windows for sfml, this will help cmake pickup the install include and lib directories, or other pkg-config based utilities

**Comment by Bromeon** [comment]
As outlined in the [contribution guidelines](http://www.sfml-dev.org/contribute.php), please use the forum for discussion prior to opening an issue. Issues are reserved for confirmed tasks.
