### ISSUE TITLE
VSync always on

### ISSUE THREAD

**Issue by ToufiPF** [SFML/SFML#920]
Hello,
It seems VSync is always on, even if I use : setVerticalSyncEnabled(false).
I know it because my graphic card don't support it.
![vsync](https://cloud.githubusercontent.com/assets/13187080/8512137/d370cc64-2335-11e5-9987-ab1bca813a3d.PNG)
I use GCC 4.7.1 and SFML 2.3.

Here is my code :

#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(200, 200), "SFML works !");
    sf::CircleShape shape(100.f);
    shape.setFillColor(sf::Color::Yellow);

    window.setVerticalSyncEnabled(false);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.waitEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.draw(shape);
        window.display();
    }

    return 0;
}

Thanks for watching ^_^

**Comment by victorlevasseur** [comment]
The warning shown in the console tells that OpenGL is not even rendered by your graphic card but by software as you didn't install the drivers for your graphic card.

**Comment by LaurentGomila** [comment]
Please use the forum for help requests. This tracker is only for confirmed issues and features.

http://www.sfml-dev.org/issues.php
