### ISSUE TITLE
Clean way to disconnect sf::Music from stream.

### ISSUE THREAD

**Issue by daid** [SFML/SFML#924]
I've been using sf::Music with custom FileStreams up from SFML-2.1

Now with SFML-2.3.1 I suddenly have a new issue. Before, I relied on the unspecified behavior that when you called sf::Music::stop(), the file stream is no longer accessed. And thus, I could destroy the underlying sf::InputStream just fine.

While all is fine during runtime (minor tweak needed to keep the old stream alive while the new stream is opened). During shutdown of my program I run into the problem that the resource system is destroyed before the sound system.

Right now, I'm doing a:
```
sf::music::openFromMemory("", 0);
```
On the music entities before I start shutting down all systems of the program. But it's quite a bit of a hack.
(Due to the fact that I'm using static objects, of which the construction and destruction order is not guaranteed)

**Comment by binary1248** [comment]
The issue tracker is for confirmed issues only. Discussions about changes or usage of the API should take place on the forum. Thank you.

**Comment by daid** [comment]
Small tip in that case:
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by binary1248** [comment]
https://github.com/SFML/SFML
Scroll all the way to the bottom of the page.

GitHub might support parsing a CONTRIBUTING file if one exists, but providing information in the readme located at the root of the repository is a more general approach that works regardless of where the project is hosted.
