### ISSUE TITLE
Errors in Parallels VM

### ISSUE THREAD

**Issue by austinmw** [SFML/SFML#927]
Hi, there is a compatibility issue with SFML and Parallels Tools. I'm hoping someone may better understand it and provide a workaround. On a fresh install of Xubuntu VM I get SFML working, and then after installing Parallels Tools I run the same sfml app and get the error:

X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  1 (X_CreateWindow)
  Serial number of failed request:  74
  Current serial number in output stream:  75

Any ideas on what the issue is or how I can patch it?

**Comment by LaurentGomila** [comment]
To avoid splitting answers, please reply in the forum thread: http://en.sfml-dev.org/forums/index.php?topic=18600.0

This tracker is rather for confirmed issues and features, as described in the issues guideline.
