### ISSUE TITLE
Inability to save files with .jpeg extension

### ISSUE THREAD

**Issue by kikiotsuka** [SFML/SFML#929]
.jpeg and .jpg file extensions are interchangeable, yet SFML does not seem to support saving .jpeg extensions. Noteworthy in this code segment https://github.com/SFML/SFML/blob/master/src/SFML/Graphics/ImageLoader.cpp#L253 SFML doesn't check for a .jpeg extension. I would like to propose a minor bugfix for simply allowing files with a .jpeg extension to be saved in the exact same manner as a .jpg

**Comment by MarioLiebisch** [comment]
Good catch. Although the whole "extension detection" as-is is quite a bit naive. For example, `test.coolpng` or even `some_png` would still be interpreted as a PNG image since it's longer than 3 characters and ends with `png`. But this is obviously wrong. Going to create a patch, thanks anyway. :)

**Comment by kikiotsuka** [comment]
Thanks, I decided to change my implementation and repropose it

**Comment by TankOs** [comment]
I think we should really search for '.' from the end, extract the extension and then check, @MarioLiebisch. This bug might be a good opportunity to change it. @kikiotsuka thanks for reporting!

**Comment by kikiotsuka** [comment]
@TankOs do you mind giving me another shot? I tried it again here https://github.com/kikiotsuka/SFML/pull/3

**Comment by kikiotsuka** [comment]
@TankOs do you mind giving me another shot? I redid that section of the code here https://github.com/kikiotsuka/SFML/pull/1

**Comment by Bromeon** [comment]
Next time, please read the [contribution guidelines](http://www.sfml-dev.org/contribute.php) first. This helps us organize things better -- it's not necessary to have 3 open issues/PRs for the same thing. Thanks.

Let's continue the discussion in #931, otherwise it gets confusing ;)
I'll close this so we have one issue/PR per task.
