### ISSUE TITLE
Why does SFML provide FindSFML.cmake instead of SFMLConfig.cmake?

### ISSUE THREAD

**Issue by danijar** [SFML/SFML#937]
The CMake way to make libraries available to other CMake projects is to [install a configure file](http://www.cmake.org/cmake/help/v3.2/manual/cmake-packages.7.html#creating-packages). This would be named either `SFMLConfig.cmake` or `sfml-config.cmake` and be installed to `<install-prefix>/lib/cmake/sfml-2.3.1/`.

This file is similar to a find script, but can be much simpler since its created at installation time and thus already knows where SFML is installed to. This script will be used automatically instead of the find script when another project looks for SFML via `find_package()`.

It seems to me that installing a find script is an accidental misuse but there might be a reason I don't see. Is this intentional and if not, can be fix this? An example of how this can look like is the [Assimp configure file](https://github.com/assimp/assimp/blob/master/assimp-config.cmake.in).

**Comment by LaurentGomila** [comment]
Config files are indeed better. Don't hesitate to submit a PR :stuck_out_tongue:

**Comment by TankOs** [comment]
Is it correct that such files would only be available if the user compiled and installed SFML himself? If so, that would be difficult for binary releases, especially when the install prefix can be anything.

**Comment by LaurentGomila** [comment]
No, look at the very first lines of the example he gave:

```
get_filename_component(_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_PREFIX "${_PREFIX}" PATH)
get_filename_component(_PREFIX "${_PREFIX}" PATH)
get_filename_component(ASSIMP_ROOT_DIR "${_PREFIX}" PATH)
```

The script extracts the current directory and then works only with relative paths.

**Comment by TankOs** [comment]
I see, that's fair enough then.

**Comment by susnux** [comment]
> It seems to me that installing a find script is an accidental misuse but there might be a reason I don't see.

I found out that they are only used if they are installed in /prefix/share/cmake/Modules/.
Normally cmake uses only FindXY delivered with it (path above) or delivered with the project which uses the XY-library.

So config files are really a good idea (but please install in /prefix/share/XYZ, cmake looks also there and /lib or /usr/lib should not contain config files. The FHS says: "/usr/lib includes object files, libraries, and internal binaries.")

**Comment by danijar** [comment]
Supporting binary releases requires some additional work indeed, since you have to find the third-party dependencies again on the new machine. But we already have the find scripts, so it's basically just calling those through [`find_package()`][1]. To locate the SFML binaries we could use [`find_library()`][2] which should handle the correct name prefixes and file extensions.

[1]: http://www.cmake.org/cmake/help/v3.2/command/find_package.html
[2]: http://www.cmake.org/cmake/help/v3.2/command/find_library.html

**Comment by danijar** [comment]
@LaurentGomila By the way, do you understand why Assimp use the line `get_filename_component(_PREFIX "${_PREFIX}" PATH)` twice? I'm playing around with config files a bit and maybe I can find the time to write one for SFML in the next days.

**Comment by eXpl0it3r** [comment]
Superseded by #1335
