### ISSUE TITLE
SFML Window focus grab bug on Windows.

### ISSUE THREAD

**Issue by edbird** [SFML/SFML#949]
Breif explanation of the bug I have found:

On LINUX:

When a SFML app runs and a SFML Window OPENS a "GAINED FOCUS" EVENT is generated.

On WINDOWS:

When an SFML app runs and a SFML Window OPENS NO "GAINED FOCUS" EVENT IS GENERATED.

Why is this a bug?

If you have a flag which keeps track of whether your window has focus or not, then this flag will NOT be initialized correctly on WINDOWS platform, as NO GAINED FOCUS event is generated when the app runs.

FIX: Either set your flag to TRUE by default when the program runs. (NOT IDEAL: What if you run your app and then open another window before it actually has time to start up! Your flag will be set to TRUE when it should be set to FALSE. [based on assumption that no LOST FOCUS event is generated?])

I believe in SFML later versions there is a "hasFocus()" method which checks if the window has focus? But this difference in behaviour depending on OS still is not ideal, however it is not a serious bug.

Hope that is enough info - tried to keep this short.

**Comment by eXpl0it3r** [comment]
Please follow the [contribution guidelines](http://www.sfml-dev.org/contribute.php) in reporting issues, we like to keep the tracker for confirmed issues only.

As for the "bug", it's not really up to SFML. SFML reports the events that the OS generates. If they act differently on different OS there's nothing that we can do. Plus as you've noticed yourself we've added a `hasFocus()` function exactly for such situations.
