### ISSUE TITLE
[Android] Touch not working on some device

### ISSUE THREAD

**Issue by r-e-d** [SFML/SFML#953]
On my tablet (Sony Xperia Z4), AInputEvent_getSource returns 20482 (AINPUT_SOURCE_TOUCHSCREEN & AINPUT_SOURCE_STYLUS) instead of only AINPUT_SOURCE_TOUCHSCREEN for touch events. I don't know if this is expected or if it's a bug in the android of my device.

One solution if to change the check in processMotionEvent and processPointerEvent to device & AINPUT_SOURCE_TOUCHSCREEN.

Also these functions will forward an uninitialized event if the type is neither AINPUT_SOURCE_MOUSE nor AINPUT_SOURCE_TOUCHSCREEN.

**Comment by MarioLiebisch** [comment]
Hm, have to check this. How do you input stuff? Your finger or indeed some stylus?

**Comment by r-e-d** [comment]
I only use finger. I don't have a stylus :)

**Comment by MarioLiebisch** [comment]
Could you try that branch? Still not 100% sure what's the reason for this, considering all examples I've found use exact comparison as well.

**Comment by r-e-d** [comment]
This fix the problem, thanks.

It may be a bug in my device because I think it makes no sense to return an event with both touch and stylus set. But this patch prevent the problem and should not affect other android device.

**Comment by MarioLiebisch** [comment]
Okay, great. And yeah, while I'm not 100% happy with this fix, it's definitely something we could keep just to be sure for now.
