### ISSUE TITLE
LoadFromFile not load images "* .png" and not * .jpg. Unable to open file

### ISSUE THREAD

**Issue by latoto** [SFML/SFML#957]
Hello I use Windows 7. LoadFromFile only worked once, then I stop.
Do not load any type of image, or * .png or * .jpg.
I tried reaciendo the project from scratch, but rather only loads the font file * .ttf and * .ogg file that are in the same directory.
I tried to load different images of these 2 types png and jpg, I even tried to run the same project from a VirtualBox with Windows 10 with the same result.
I have seen many people and nInternet has been the same. I set the working directory path absolutely, so I got to load the font and sound, but the pictures ... no way.
My version is SFML2:
SFML 2.3.1
GCC 4.7.1 TDM (SJLJ) - 32-bit

Running on Windows 7 and Windows 10

The ide I use is Code Blocks.
CodeBlocks installation is new.
Installation S.O. Windows 10 is new.
There is a tutorial that shows how to load an image file exported Gimp "* .c"
allowing for the inclusion and upload an image to the bottom of the window?
I found a similar one to the icon but I could not use it with a background image.
Thank you
My mail: tonitoranzo@gmail.com
Greetings from Madrid-Spain!
Translated with Google

You can help? Thank you so much!
My mail: tonitoranzo@gmail.com
Greetings from Madrid-Spain!

**Comment by zsbzsb** [comment]
Just to be clear, the forums are [here](http://en.sfml-dev.org/forums/index.php). This here on github is the tracker and is for confirmed issues/features only.

**Comment by latoto** [comment]
Excuse me
Thank you for your kindness. A greeting!

Translated with Google.

Translated with Google.

**Comment by TankOs** [comment]
Closed until resolved, thanks for reporting anyway. ;)

**Comment by MarioLiebisch** [comment]
Removed your email to save you from potential spam.

Would also be helpful if you could attach the images failing to load to your forum post.
