### ISSUE TITLE
Added a eclipse android.

### ISSUE THREAD

**Issue by 1aam2am1** [SFML/SFML#959]
Added a eclipse android tutorial of build example.

**Comment by MarioLiebisch** [comment]
Is this supposed to be a pull request? Or a feature request? I'm not really sure what to do with this "issue". I'm closing this, feel free to edit and reopen it, once clarified.

**Comment by Bromeon** [comment]
Please use the forum for feature requests and general discussions.
See also [contribution guidelines](http://www.sfml-dev.org/contribute.php).
