### ISSUE TITLE
Switching from SFML 2.3 to SFML 2.3.1

### ISSUE THREAD

**Issue by sysint64** [SFML/SFML#960]
I use SMFL in my project, I use C++ 14 standard and manually build with clang++ with flags "-std=c++14 -stdlib=libc++". Everything works well in SFML 2.3, but in SFML 2.3.1 there are problems with events: mouse moving, scrolling and so on are not working.

**Comment by MarioLiebisch** [comment]
[Post on the forums](http://en.sfml-dev.org/forums/). Make sure to include as many details and/or code snippets as possible. A short example to reproduce and showcase the issue would be helpful.

Edit and reopen this issue in case there's indeed some issue within SFML.
