### ISSUE TITLE
SFML 2.3.2

### ISSUE THREAD

**Issue by Krakowski** [SFML/SFML#964]
If I set setPlayingOffset() over more than 50% of .flac file, music restarts playing.

For example: music.setPlayingOffset(sf::seconds(200); (music duration is equal 300 seconds). This causes playing music from the beginning.

If I open .ogg file, everything works well- I can set every value which is less than music.getDuration();

What is the problem?

**Comment by zsbzsb** [comment]
Please open a thread on the forums and include a complete and minimal example. Be sure to include an audio file that shows the problem and information about your copy of SFML. We try to keep the tracker for confirmed issues/features.

**Comment by eXpl0it3r** [comment]
As @zsbzsb said and as it's stated in the [contribution guidelines](http://www.sfml-dev.org/contribute.php), it would be great if you could open a thread on the [official forum](http://en.sfml-dev.org/forums/) about this issue.
