### ISSUE TITLE
numpad keys return sf::Key::Unknown

### ISSUE THREAD

**Issue by pubby** [SFML/SFML#967]
When I press the numpad number keys, the returned code is sf::Key::Unknown, rather than sf::Key::NumpadFoo. Num-lock has no effect on this.

I'm on Arch Linux and using SFML. 2.3.1-2. I am using a nonstandard keyboard layout (Colemak), but I'm not sure if that matters.

**Comment by binary1248** [comment]
This was already fixed in #910. Try using SFML 2.3.2.
