### ISSUE TITLE
Rpath issues with examples

### ISSUE THREAD

**Issue by mantognini** [SFML/SFML#971]
When running `make install`, warnings such as this one will be emitted for all SFML example on OS X.

> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: for architecture x86_64 object: //usr/local/share/SFML/examples/cocoa/cocoa.app/Contents/MacOS/cocoa malformed object (inconsistent sizeofcmds field in mach header)

For all examples but cocoa this is no huge issue -- the programs can be launched from the command line as usual if SFML is installed on the system.

However, Finder will refuse to launch cocoa.app with this error message:

> “cocoa.app” is damaged and can’t be opened. You should move it to the Trash.

But if run from the command line (`./cocoa.app/Contents/MacOS/cocoa`) it works.

The issue seems to come from an incompatibility with rpath... I don't have time to properly investigate right now so here are a few pointers for motivated people (or me, probably).

 * Tested with cmake 3.3.1 and 2.8.12.2, no difference
 * [[cmake-developers] "Inconsistent sizeofcmds" on Mac](https://www.mail-archive.com/cmake-developers@cmake.org/msg14319.html): a bug in `install_name_tool` maybe? (very recent: 17/09/15)
 * [[CMake] Installation corrupts library on OS X](http://public.kitware.com/pipermail/cmake/2014-October/058859.html): multiple rpaths conflicting with each others?
 * Print rpath of a binary: `otool -l cocoa.app/Contents/MacOS/cocoa | grep -A2 -B1 LC_RPATH`
 * Rpath before installing:
```
m@mbp ~/P/P/S/g/b/1/c/dylibs> otool -l examples/cocoa/cocoa.app/Contents/MacOS/cocoa  | grep -A2 -B1 LC_RPATH
Load command 25
          cmd LC_RPATH
      cmdsize 80
         path /Users/m/Prog/Projects/SFML/git/builds/10.7/clang/dylibs/lib (offset 12)
--
--
Load command 26
          cmd LC_RPATH
      cmdsize 80
         path /Users/m/Prog/Projects/SFML/git/SFML/extlibs/libs-osx/Frameworks (offset 12)
```
 * Rpath after installing:
```
m@mbp /u/l/s/S/e/cocoa> otool -l cocoa.app/Contents/MacOS/cocoa   | grep -A2 -B1 LC_RPATH
Load command 25
          cmd LC_RPATH
      cmdsize 80
         path /Users/m/Prog/Projects/SFML/git/SFML/extlibs/libs-osx/Frameworks (offset 12)
```

So something is definitely wrong with rpaths....

**Comment by eXpl0it3r** [comment]
Do you know a solution to this, @mantognini?

**Comment by mantognini** [comment]
No, but I plan on working on this one soon(-ish). The first thing is to make sure it still happens (maybe cmake or install_name_tool have fixed this since then)...

In any case, this is very specific to the Cocoa example we have here -- understand: this can be solved later as well without a big impact.

**Comment by mantognini** [comment]
Actually, I can't reproduce this anymore... 😄 

Maybe it was fixed in a recent version of cmake (I now have 3.5.2) or it was due to universal builds (that are no longer officially supported by SFML). I don't know. In any case, I'm closing this.

**Comment by eXpl0it3r** [comment]
I removed the mileston, so we don't get confused whether there has been work done to it for 2.4.
