### ISSUE TITLE
isKeyPressed never true in OSX Yosemite 10.10.4 (14E46)

### ISSUE THREAD

**Issue by worldspawn** [SFML/SFML#985]
Hello,

i've just been trying out a SFML tutorial and was trying out keyboard interactivity. As far as I can tell isKeyPressed just never works. 

This works fine
``` cpp
if (sf::Mouse::isButtonPressed(sf::Mouse::Left))
        {
            rectangle.move(1, 0);
        }
```

The below if statement bodies never run:

``` cpp
if (sf::Keyboard::isKeyPressed(sf::Keyboard::D))
        {
            // left key is pressed: move our character
            rectangle.move(1, 0);
        }
        
        if (sf::Keyboard::isKeyPressed(sf::Keyboard::Right))
        {
            // left key is pressed: move our character
            rectangle.move(0, 1);
        }
```

http://hastebin.com/bipefotovo.avrasm

I've installed SFML from the website yesterday. `SFML-2.3.2-osx-clang-universal.tar.gz`

**Comment by Bromeon** [comment]
Please have a look at the [contribution guidelines](http://www.sfml-dev.org/contribute.php) (the link appears when opening an issue). For help requests and unconfirmed issues, the preferred platform should be the forum.

Are you sure that it never works at all, and it's [not one of the other issues](https://github.com/SFML/SFML/search?utf8=%E2%9C%93&q=iskeypressed&type=Issues)? Can you provide a minimal complete example?

**Comment by mantognini** [comment]
Cannot reproduce with master version.

If you're still having an issue, stop by the forum for help.
