### ISSUE TITLE
sfml link error when at 64bit ubuntu

### ISSUE THREAD

**Issue by zhengjiezxxy** [SFML/SFML#992]
I build the newest libsfml* from github. And then I tried to compile the following example from the tutorial:

#include "SFML/Graphics.hpp"
int main()
{
    sf::RenderWindow window(sf::VideoMode(200, 200), "SFML works!");
    sf::CircleShape shape(100.f,(unsigned int)1);
    shape.setFillColor(sf::Color::Green);

    while (window.isOpen())
    {
        sf::Event event;
        while (window.pollEvent(event))
        {
            if (event.type == sf::Event::Closed)
                window.close();
        }

        window.clear();
        window.draw(shape);
        window.display();
    }

    return 0;
}

The error is like these:
test.o: In function `main':
test.cpp:(.text+0xd0): undefined reference to `sf::CircleShape::CircleShape(float, unsigned long)'
test.o: In function `sf::CircleShape::~CircleShape()':
test.cpp:(.text._ZN2sf11CircleShapeD2Ev[_ZN2sf11CircleShapeD5Ev]+0x47): undefined reference to `operator delete(void*, unsigned long)'
test.o: In function `sf::CircleShape::~CircleShape()':
test.cpp:(.text._ZN2sf11CircleShapeD0Ev[_ZN2sf11CircleShapeD5Ev]+0x25): undefined reference to `operator delete(void*, unsigned long)'
/usr/bin/ld: link errors found, deleting executable `sfml-app'

But in libsfml-graphics.so there is only 
sf::CircleShape::CircleShape(float, unsigned int).

And in CircleShape.hpp, the function prototype is 
"/usr/local/include/SFML/Graphics/CircleShape.hpp" 3
    explicit CircleShape(float radius = 0, std::size_t pointCount = 30);

My OS is ubuntu64 bit, so as far as I know, size_t is unsigned long, but why after I compile libsfml,
it's unsigned int in the libsfml-graphics.so

**Comment by eXpl0it3r** [comment]
Please use the forum for compiler/linker issues. As mentioned in the [Contribution Guidelines](pip install -r requirements.txt) this tracker is for confirmed bugs and features only.
