### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by mantognini** [SFML/SFML#993]
In order to fix a few typos at once, here is a list of known typos:

 - [x] [`BlendMultipy`](https://github.com/SFML/SFML/blob/e80bf0ba92b2993a2811cdf117396da46f4a406c/include/SFML/Graphics/BlendMode.hpp#L204) should read `BlendMultiply`
 - [x] [Then, ~~every~~ objects drawn in this render target will be](https://github.com/SFML/SFML/blob/master/include/SFML/Graphics/View.hpp#L309)

**Comment by binary1248** [comment]
Bump. How do we proceed with this?

**Comment by eXpl0it3r** [comment]
The idea was to collect all the typos and then merge near the end.

**Comment by eXpl0it3r** [comment]
See also: https://github.com/SFML/SFML-Website/pull/62

**Comment by mantognini** [comment]
Superseded by #1098.
