### ISSUE TITLE
Irregular circle(polygon-like) rendered in linux.

### ISSUE THREAD

**Issue by kirtangajjar** [SFML/SFML#994]
I just ran the example code from getting started page, and here is the circle that i got -

![screenshot from 2015-10-22 20 21 31](https://cloud.githubusercontent.com/assets/8456197/10668612/b830cc54-78fa-11e5-8118-dbab992742e2.png)

One question - why is it looking more like a polygon and less like a circle? What can i do to make it look more like a  circle?

**Comment by eXpl0it3r** [comment]
Please follow the [contribution guidelines](http://www.sfml-dev.org/contribute.php), which you have been linked to when opening this issue, and post such questions on the forum. We like to keep this tracker for confirmed bugs and features only.

You may find [the documentation](http://www.sfml-dev.org/documentation/2.3.2/classsf_1_1CircleShape.php#aaebe705e7180cd55588eb19488af3af1) an interesting read regarding your questions.
