### ISSUE TITLE
sf::Event::TextEntered fired when escape is pressed

### ISSUE THREAD

**Issue by Potato42** [SFML/SFML#996]
When you press the escape key, it is treated as a `TextEntered` event.  Since the escape key is normally not used to enter text, I would consider this a bug.

To reproduce: run the following program and press escape.  "TextEntered event fired!" will be printed to stdout.

    #include <iostream>
    #include <SFML/Graphics.hpp>

    int main(void) {
        sf::RenderWindow window(sf::VideoMode(640, 480), "TextEntered problem");
        while(window.isOpen()) {
            sf::Event event;
            while(window.pollEvent(event)) {
                if(event.type == sf::Event::Closed) window.close();
                else if(event.type == sf::Event::TextEntered) {
                    std::cout << "TextEntered event fired!" << std::endl;
                }
            }
        }
    }

**Comment by LaurentGomila** [comment]
TextEntered events are *never* a bug, since SFML doesn't add any logic on top of what the OS decides to send. "Text" may be misleading, since this event is triggered for anything that is defined in the Unicode standard -- and escape is.
